#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Hand-crafted home UI dictionary patches — literary quality per localization guide."""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).with_name("powerball_home_dict_patches.json")

# fmt: off
PATCHES: dict[str, dict[str, str]] = {
"3": {
    "home_counter_lotteries": "Loteries suivies",
    "home_counter_draws": "Derniers tirages",
    "home_counter_jackpots": "Jackpots US cumulés",
    "home_counter_refresh": "Actualisation des données",
    "home_how_subtitle": "Comment ça marche",
    "home_how_title": "Comment ça marche",
    "home_how_lead": "De la comparaison des jackpots à la vérification de vos numéros — quatre étapes simples.",
    "home_how_step1_title": "Fixez un budget",
    "home_how_step1_text": "La loterie est un divertissement — considérez les tickets comme partie de votre budget loisirs, pas un investissement.",
    "home_how_step2_title": "Choisissez votre loterie",
    "home_how_step2_text": "Comparez les jackpots en direct pour PowerBall, Mega Millions, EuroMillions et les tirages régionaux dans le carrousel ci-dessus.",
    "home_how_step3_title": "Choisissez vos numéros",
    "home_how_step3_text": "Utilisez la sélection rapide ou choisissez vos numéros. Vérifiez les calendriers de tirage avant de jouer chez un opérateur officiel.",
    "home_how_step4_title": "Vérifiez les résultats",
    "home_how_step4_text": "Après le tirage, comparez vos numéros avec les derniers résultats sur cette page ou vérifiez votre ticket auprès de l'opérateur officiel.",
    "home_why_subtitle": "Pourquoi PowerBall Jackpot",
    "home_why_title": "Votre hub de résultats loto",
    "home_why_lead": "Jackpots, tirages récents et outils numériques — tout ce dont vous avez besoin avant de visiter un opérateur officiel.",
    "home_why_1_title": "Jackpots et résultats en direct",
    "home_why_1_text": "Jackpots estimés, derniers numéros tirés et calendriers des principales loteries US et EU en un seul endroit.",
    "home_why_2_title": "Vérifiez vos numéros",
    "home_why_2_text": "Comparez vos choix avec le dernier tirage publié grâce au vérificateur intégré.",
    "home_why_3_title": "Cinq jeux majeurs",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto et Lotto America — règles et sélecteurs intégrés.",
    "home_why_4_title": "Jeu responsable",
    "home_why_4_text": "Guides indépendants et liens vers les opérateurs officiels — jouez pour le plaisir, fixez un budget, connaissez les probabilités.",
    "home_hero_img_alt": "— jackpots de loterie",
    "home_slider_estimated_prize": "Jackpot estimé :",
    "home_picker_title": "Choisissez vos numéros chanceux",
    "home_picker_lead": "Choisissez vos numéros pour le prochain tirage — changez de loterie pour comparer jackpots et calendriers.",
    "home_select_lottery": "Choisir une loterie",
    "home_results_title": "Résultats récents de loterie",
    "home_results_lead": "Derniers numéros gagnants et gains marquants des grands tirages — mis à jour après chaque résultat publié.",
    "home_view_all": "Tout voir",
    "home_results_amount": "Montant :",
    "home_results_draw_date": "Tirage effectué le :",
    "home_checker_title": "Vérifier mes numéros",
    "home_checker_lead": "Comparez vos numéros avec le dernier tirage publié.",
    "home_checker_submit": "Vérifier les numéros",
    "home_picker_line_hint_before": "Billet",
    "home_picker_line_hint_after": "sur %1 — appuyez sur une ligne à droite pour en modifier une autre",
    "home_picker_pick_main": "Choisissez %1 numéros",
    "home_picker_pick_bonus": "Choisir le bonus",
    "home_picker_quick_pick": "Sélection rapide",
    "home_picker_clear_all": "Tout effacer",
    "home_ticket_select_number": "Numéros sélectionnés",
    "home_ticket_price": "Prix du ticket",
    "home_ticket_price_lines_zero": "(0 lignes × %1)",
    "home_ticket_price_pending": "(%1 ligne(s) en attente de %2 × %3)",
    "home_ticket_price_one": "(1 ligne × %1)",
    "home_ticket_price_lines": "(%1 lignes × %2)",
    "home_ticket_buy": "Acheter le ticket",
    "home_payment_methods": "Modes de paiement acceptés :",
    "home_ticket_line_title": "Ligne du ticket %1",
    "home_checker_aria_main": "Numéro principal",
    "home_checker_aria_bonus": "Numéro bonus",
    "home_checker_err_all": "Saisissez tous les numéros.",
    "home_checker_err_invalid": "Numéro invalide.",
    "home_checker_err_range": "Le numéro %1 est hors limites (%2–%3).",
    "home_checker_err_unique": "Les numéros principaux doivent être uniques.",
    "home_checker_no_draw_loaded": "Les numéros du dernier tirage ne sont pas encore chargés.",
    "home_checker_latest_draw": "Dernier tirage (%1) : %2",
    "home_checker_latest_draw_no_date": "Dernier tirage : %1",
    "home_checker_no_draw_data": "Pas de données de tirage pour cette loterie. Réessayez après la prochaine synchronisation.",
    "home_checker_draw_on": " — tirage %1",
    "home_checker_no_matches": "Aucune correspondance avec les numéros gagnants.",
    "home_checker_matched_main": "Vous avez %1 numéro(s) principal(aux) correct(s)",
    "home_checker_matched_bonus": " et %2 numéro(s) bonus correct(s)",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Numéros du jackpot — vérifiez auprès de l'opérateur officiel.",
    "home_checker_all_main_hint": " Tous les numéros principaux correspondent — vérifiez auprès de l'opérateur officiel.",
    "home_checker_winning_label": "Gagnants : %1",
    "home_picker_stage_complete": "Ligne complète — ajoutez une autre ligne ou achetez un ticket.",
    "home_picker_main_set": "Numéros principaux définis (%1/%2). Choisissez %3 ci-dessous (%4/%5) — boule rouge dans le panneau ticket.",
    "home_picker_selected_main": "%1 sur %2 numéros principaux sélectionnés.",
    "home_picker_bonus_fallback": "numéros bonus",
},
"4": {
    "home_counter_lotteries": "Verfolgte Lotterien",
    "home_counter_draws": "Neueste Ziehungen",
    "home_counter_jackpots": "Kombinierte US-Jackpots",
    "home_counter_refresh": "Datenaktualisierung",
    "home_how_subtitle": "So funktioniert's",
    "home_how_title": "So funktioniert's",
    "home_how_lead": "Vom Jackpot-Vergleich bis zur Zahlenprüfung — vier einfache Schritte.",
    "home_how_step1_title": "Budget festlegen",
    "home_how_step1_text": "Lotterie ist Unterhaltung — sehen Sie Lose als Teil Ihres Freizeitbudgets, nicht als Investition.",
    "home_how_step2_title": "Lotterie wählen",
    "home_how_step2_text": "Vergleichen Sie Live-Jackpots für PowerBall, Mega Millions, EuroMillions und regionale Ziehungen im Karussell oben.",
    "home_how_step3_title": "Zahlen wählen",
    "home_how_step3_text": "Nutzen Sie Quick Pick oder wählen Sie Zahlen im Picker. Prüfen Sie die Ziehungstermine, bevor Sie beim offiziellen Anbieter spielen.",
    "home_how_step4_title": "Ergebnisse prüfen",
    "home_how_step4_text": "Vergleichen Sie nach der Ziehung Ihre Zahlen mit den neuesten Ergebnissen auf dieser Seite oder prüfen Sie Ihr Los beim offiziellen Anbieter.",
    "home_why_subtitle": "Warum PowerBall Jackpot",
    "home_why_title": "Ihr Lotto-Ergebnis-Hub",
    "home_why_lead": "Jackpots, aktuelle Ziehungen und Zahlen-Tools — alles, was Sie brauchen, bevor Sie einen offiziellen Anbieter besuchen.",
    "home_why_1_title": "Live-Jackpots & Ergebnisse",
    "home_why_1_text": "Geschätzte Jackpots, neueste Gewinnzahlen und Termine großer US- und EU-Lotterien an einem Ort.",
    "home_why_2_title": "Zahlen prüfen",
    "home_why_2_text": "Vergleichen Sie Ihre Tipps mit der zuletzt veröffentlichten Ziehung über den integrierten Zahlen-Checker.",
    "home_why_3_title": "Fünf große Spiele",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto und Lotto America — Regeln und Picker eingebaut.",
    "home_why_4_title": "Verantwortungsvolles Spielen",
    "home_why_4_text": "Unabhängige Guides und Links zu offiziellen Anbietern — spielen Sie zum Spaß, setzen Sie ein Budget, kennen Sie die Chancen.",
    "home_hero_img_alt": "— Lotto-Jackpots",
    "home_slider_estimated_prize": "Geschätzter Gewinn :",
    "home_picker_title": "Glückszahlen wählen",
    "home_picker_lead": "Wählen Sie Ihre Zahlen für die nächste Ziehung — wechseln Sie die Lotterie, um Jackpots und Termine zu vergleichen.",
    "home_select_lottery": "Lotterie wählen",
    "home_results_title": "Aktuelle Lottoergebnisse",
    "home_results_lead": "Neueste Gewinnzahlen und Gewinn-Highlights großer Ziehungen — aktualisiert nach jedem veröffentlichten Ergebnis.",
    "home_view_all": "Alle anzeigen",
    "home_results_amount": "Betrag :",
    "home_results_draw_date": "Ziehung am :",
    "home_checker_title": "Meine Zahlen prüfen",
    "home_checker_lead": "Vergleichen Sie Ihre Zahlen mit der zuletzt veröffentlichten Ziehung.",
    "home_checker_submit": "Zahlen prüfen",
    "home_picker_line_hint_before": "Los",
    "home_picker_line_hint_after": "von %1 — tippen Sie rechts auf eine Zeile, um eine andere zu bearbeiten",
    "home_picker_pick_main": "%1 Zahlen wählen",
    "home_picker_pick_bonus": "Bonus wählen",
    "home_picker_quick_pick": "Quick Pick",
    "home_picker_clear_all": "Alles löschen",
    "home_ticket_select_number": "Gewählte Zahlen",
    "home_ticket_price": "Ticketpreis",
    "home_ticket_price_lines_zero": "(0 Zeilen × %1)",
    "home_ticket_price_pending": "(%1 Zeile(n) warten auf %2 × %3)",
    "home_ticket_price_one": "(1 Zeile × %1)",
    "home_ticket_price_lines": "(%1 Zeilen × %2)",
    "home_ticket_buy": "Ticket kaufen",
    "home_payment_methods": "Akzeptierte Zahlungsmethoden :",
    "home_ticket_line_title": "Ticketzeile %1",
    "home_checker_aria_main": "Hauptzahl",
    "home_checker_aria_bonus": "Bonuszahl",
    "home_checker_err_all": "Geben Sie alle Zahlen ein.",
    "home_checker_err_invalid": "Ungültige Zahl.",
    "home_checker_err_range": "Zahl %1 liegt außerhalb des Bereichs (%2–%3).",
    "home_checker_err_unique": "Hauptzahlen müssen eindeutig sein.",
    "home_checker_no_draw_loaded": "Gewinnzahlen der letzten Ziehung noch nicht geladen.",
    "home_checker_latest_draw": "Letzte Ziehung (%1): %2",
    "home_checker_latest_draw_no_date": "Letzte Ziehung: %1",
    "home_checker_no_draw_data": "Keine Ziehungsdaten für diese Lotterie. Versuchen Sie es nach der nächsten Synchronisierung erneut.",
    "home_checker_draw_on": " — Ziehung %1",
    "home_checker_no_matches": "Keine Übereinstimmung mit den Gewinnzahlen.",
    "home_checker_matched_main": "Sie haben %1 Hauptzahl(en) richtig",
    "home_checker_matched_bonus": " und %2 Bonuszahl(en) richtig",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Jackpot-Zahlen — beim offiziellen Anbieter verifizieren.",
    "home_checker_all_main_hint": " Alle Hauptzahlen stimmen — beim offiziellen Anbieter verifizieren.",
    "home_checker_winning_label": "Gewinnzahlen: %1",
    "home_picker_stage_complete": "Zeile vollständig — weitere Zeile hinzufügen oder Ticket kaufen.",
    "home_picker_main_set": "Hauptzahlen gesetzt (%1/%2). Wählen Sie %3 unten (%4/%5) — rote Kugel im Ticket-Panel.",
    "home_picker_selected_main": "%1 von %2 Hauptzahlen ausgewählt.",
    "home_picker_bonus_fallback": "Bonuszahlen",
},
"6": {
    "home_counter_lotteries": "Loterías seguidas",
    "home_counter_draws": "Últimos sorteos",
    "home_counter_jackpots": "Jackpots de EE. UU. combinados",
    "home_counter_refresh": "Actualización de datos",
    "home_how_subtitle": "Cómo funciona",
    "home_how_title": "Cómo funciona",
    "home_how_lead": "Desde comparar jackpots hasta comprobar tus números — cuatro pasos sencillos.",
    "home_how_step1_title": "Fija un presupuesto",
    "home_how_step1_text": "La lotería es entretenimiento — trata los boletos como parte de tu presupuesto de ocio, no como inversión.",
    "home_how_step2_title": "Elige tu lotería",
    "home_how_step2_text": "Compara jackpots en vivo de PowerBall, Mega Millions, EuroMillions y sorteos regionales en el carrusel de arriba.",
    "home_how_step3_title": "Elige tus números",
    "home_how_step3_text": "Usa la selección rápida o elige números en el selector. Consulta los calendarios de sorteo antes de jugar con un operador oficial.",
    "home_how_step4_title": "Comprueba resultados",
    "home_how_step4_text": "Tras el sorteo, compara tus números con los últimos resultados en esta página o verifica tu boleto con el operador oficial.",
    "home_why_subtitle": "Por qué PowerBall Jackpot",
    "home_why_title": "Tu hub de resultados de lotería",
    "home_why_lead": "Jackpots, sorteos recientes y herramientas de números — todo lo que necesitas antes de visitar un operador oficial.",
    "home_why_1_title": "Jackpots y resultados en vivo",
    "home_why_1_text": "Jackpots estimados, últimos números ganadores y calendarios de las principales loterías de EE. UU. y la UE en un solo lugar.",
    "home_why_2_title": "Comprueba tus números",
    "home_why_2_text": "Compara tus elecciones con el último sorteo publicado usando el verificador integrado.",
    "home_why_3_title": "Cinco juegos principales",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto y Lotto America — reglas y selectores integrados.",
    "home_why_4_title": "Juego responsable",
    "home_why_4_text": "Guías independientes y enlaces a operadores oficiales — juega por diversión, fija un presupuesto, conoce las probabilidades.",
    "home_hero_img_alt": "— jackpots de lotería",
    "home_slider_estimated_prize": "Premio estimado :",
    "home_picker_title": "Elige tus números de la suerte",
    "home_picker_lead": "Elige tus números para el próximo sorteo — cambia de lotería para comparar jackpots y calendarios.",
    "home_select_lottery": "Seleccionar lotería",
    "home_results_title": "Resultados recientes de lotería",
    "home_results_lead": "Últimos números ganadores y premios destacados de grandes sorteos — actualizado tras cada resultado publicado.",
    "home_view_all": "Ver todo",
    "home_results_amount": "Importe :",
    "home_results_draw_date": "Sorteo realizado el :",
    "home_checker_title": "Comprobar mis números",
    "home_checker_lead": "Compara tus números con el último sorteo publicado.",
    "home_checker_submit": "Comprobar números",
    "home_picker_line_hint_before": "Boleto",
    "home_picker_line_hint_after": "de %1 — toca una fila a la derecha para editar otra línea",
    "home_picker_pick_main": "Elige %1 números",
    "home_picker_pick_bonus": "Elegir bonus",
    "home_picker_quick_pick": "Selección rápida",
    "home_picker_clear_all": "Borrar todo",
    "home_ticket_select_number": "Números elegidos",
    "home_ticket_price": "Precio del boleto",
    "home_ticket_price_lines_zero": "(0 líneas × %1)",
    "home_ticket_price_pending": "(%1 línea(s) esperando %2 × %3)",
    "home_ticket_price_one": "(1 línea × %1)",
    "home_ticket_price_lines": "(%1 líneas × %2)",
    "home_ticket_buy": "Comprar boleto",
    "home_payment_methods": "Métodos de pago aceptados :",
    "home_ticket_line_title": "Línea del boleto %1",
    "home_checker_aria_main": "Número principal",
    "home_checker_aria_bonus": "Número bonus",
    "home_checker_err_all": "Introduce todos los números.",
    "home_checker_err_invalid": "Número no válido.",
    "home_checker_err_range": "El número %1 está fuera de rango (%2–%3).",
    "home_checker_err_unique": "Los números principales deben ser únicos.",
    "home_checker_no_draw_loaded": "Los números del último sorteo aún no están cargados.",
    "home_checker_latest_draw": "Último sorteo (%1): %2",
    "home_checker_latest_draw_no_date": "Último sorteo: %1",
    "home_checker_no_draw_data": "No hay datos de sorteo para esta lotería. Inténtalo tras la próxima sincronización.",
    "home_checker_draw_on": " — sorteo %1",
    "home_checker_no_matches": "Sin coincidencias con los números ganadores.",
    "home_checker_matched_main": "Acertaste %1 número(s) principal(es)",
    "home_checker_matched_bonus": " y %2 número(s) bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Números del jackpot — verifica con el operador oficial.",
    "home_checker_all_main_hint": " Todos los números principales coinciden — verifica con el operador oficial.",
    "home_checker_winning_label": "Ganadores: %1",
    "home_picker_stage_complete": "Línea completa — añade otra línea o compra un boleto.",
    "home_picker_main_set": "Números principales listos (%1/%2). Elige %3 abajo (%4/%5) — bola roja en el panel del boleto.",
    "home_picker_selected_main": "%1 de %2 números principales seleccionados.",
    "home_picker_bonus_fallback": "números bonus",
},
"8": {
    "home_counter_lotteries": "Lotarias acompanhadas",
    "home_counter_draws": "Últimos sorteios",
    "home_counter_jackpots": "Jackpots dos EUA combinados",
    "home_counter_refresh": "Atualização de dados",
    "home_how_subtitle": "Como funciona",
    "home_how_title": "Como funciona",
    "home_how_lead": "Da comparação de jackpots à verificação dos seus números — quatro passos simples.",
    "home_how_step1_title": "Defina um orçamento",
    "home_how_step1_text": "A lotaria é entretenimento — trate os bilhetes como parte do seu orçamento de lazer, não como investimento.",
    "home_how_step2_title": "Escolha a lotaria",
    "home_how_step2_text": "Compare jackpots em direto de PowerBall, Mega Millions, EuroMillions e sorteios regionais no carrossel acima.",
    "home_how_step3_title": "Escolha os números",
    "home_how_step3_text": "Use a seleção rápida ou escolha números no seletor. Confira os calendários de sorteio antes de jogar com um operador oficial.",
    "home_how_step4_title": "Verifique resultados",
    "home_how_step4_text": "Após o sorteio, compare os seus números com os últimos resultados nesta página ou verifique o bilhete com o operador oficial.",
    "home_why_subtitle": "Porquê PowerBall Jackpot",
    "home_why_title": "O seu hub de resultados de lotaria",
    "home_why_lead": "Jackpots, sorteios recentes e ferramentas de números — tudo o que precisa antes de visitar um operador oficial.",
    "home_why_1_title": "Jackpots e resultados em direto",
    "home_why_1_text": "Jackpots estimados, últimos números sorteados e calendários das principais lotarias dos EUA e da UE num só lugar.",
    "home_why_2_title": "Verifique os seus números",
    "home_why_2_text": "Compare as suas escolhas com o último sorteio publicado através do verificador integrado.",
    "home_why_3_title": "Cinco jogos principais",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto e Lotto America — regras e seletores integrados.",
    "home_why_4_title": "Jogo responsável",
    "home_why_4_text": "Guias independentes e ligações a operadores oficiais — jogue por diversão, defina um orçamento, conheça as probabilidades.",
    "home_hero_img_alt": "— jackpots de lotaria",
    "home_slider_estimated_prize": "Prémio estimado :",
    "home_picker_title": "Escolha os seus números da sorte",
    "home_picker_lead": "Escolha os números para o próximo sorteio — mude de lotaria para comparar jackpots e calendários.",
    "home_select_lottery": "Selecionar lotaria",
    "home_results_title": "Resultados recentes de lotaria",
    "home_results_lead": "Últimos números vencedores e destaques de prémios dos grandes sorteios — atualizado após cada resultado publicado.",
    "home_view_all": "Ver tudo",
    "home_results_amount": "Montante :",
    "home_results_draw_date": "Sorteio realizado em :",
    "home_checker_title": "Verificar os meus números",
    "home_checker_lead": "Compare os seus números com o último sorteio publicado.",
    "home_checker_submit": "Verificar números",
    "home_picker_line_hint_before": "Bilhete",
    "home_picker_line_hint_after": "de %1 — toque numa linha à direita para editar outra",
    "home_picker_pick_main": "Escolha %1 números",
    "home_picker_pick_bonus": "Escolher bonus",
    "home_picker_quick_pick": "Seleção rápida",
    "home_picker_clear_all": "Limpar tudo",
    "home_ticket_select_number": "Números selecionados",
    "home_ticket_price": "Preço do bilhete",
    "home_ticket_price_lines_zero": "(0 linhas × %1)",
    "home_ticket_price_pending": "(%1 linha(s) à espera de %2 × %3)",
    "home_ticket_price_one": "(1 linha × %1)",
    "home_ticket_price_lines": "(%1 linhas × %2)",
    "home_ticket_buy": "Comprar bilhete",
    "home_payment_methods": "Métodos de pagamento aceites :",
    "home_ticket_line_title": "Linha do bilhete %1",
    "home_checker_aria_main": "Número principal",
    "home_checker_aria_bonus": "Número bonus",
    "home_checker_err_all": "Introduza todos os números.",
    "home_checker_err_invalid": "Número inválido.",
    "home_checker_err_range": "O número %1 está fora do intervalo (%2–%3).",
    "home_checker_err_unique": "Os números principais devem ser únicos.",
    "home_checker_no_draw_loaded": "Os números do último sorteio ainda não foram carregados.",
    "home_checker_latest_draw": "Último sorteio (%1): %2",
    "home_checker_latest_draw_no_date": "Último sorteio: %1",
    "home_checker_no_draw_data": "Sem dados de sorteio para esta lotaria. Tente novamente após a próxima sincronização.",
    "home_checker_draw_on": " — sorteio %1",
    "home_checker_no_matches": "Sem correspondências com os números vencedores.",
    "home_checker_matched_main": "Acertou em %1 número(s) principal(is)",
    "home_checker_matched_bonus": " e %2 número(s) bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Números do jackpot — confirme com o operador oficial.",
    "home_checker_all_main_hint": " Todos os números principais coincidem — confirme com o operador oficial.",
    "home_checker_winning_label": "Vencedores: %1",
    "home_picker_stage_complete": "Linha completa — adicione outra linha ou compre um bilhete.",
    "home_picker_main_set": "Números principais definidos (%1/%2). Escolha %3 abaixo (%4/%5) — bola vermelha no painel do bilhete.",
    "home_picker_selected_main": "%1 de %2 números principais selecionados.",
    "home_picker_bonus_fallback": "números bonus",
},
"14": {
    "home_counter_lotteries": "Lotterie monitorate",
    "home_counter_draws": "Ultimi estrazioni",
    "home_counter_jackpots": "Jackpot USA combinati",
    "home_counter_refresh": "Aggiornamento dati",
    "home_how_subtitle": "Come funziona",
    "home_how_title": "Come funziona",
    "home_how_lead": "Dal confronto dei jackpot al controllo dei numeri — quattro passaggi semplici.",
    "home_how_step1_title": "Stabilisci un budget",
    "home_how_step1_text": "La lotteria è intrattenimento — considera i biglietti parte del budget svago, non un investimento.",
    "home_how_step2_title": "Scegli la lotteria",
    "home_how_step2_text": "Confronta i jackpot live di PowerBall, Mega Millions, EuroMillions e le estrazioni regionali nel carosello sopra.",
    "home_how_step3_title": "Scegli i numeri",
    "home_how_step3_text": "Usa la selezione rapida o scegli i numeri nel selettore. Controlla i calendari delle estrazioni prima di giocare con un operatore ufficiale.",
    "home_how_step4_title": "Controlla i risultati",
    "home_how_step4_text": "Dopo l'estrazione, confronta i tuoi numeri con gli ultimi risultati su questa pagina o verifica il biglietto con l'operatore ufficiale.",
    "home_why_subtitle": "Perché PowerBall Jackpot",
    "home_why_title": "Il tuo hub dei risultati lotto",
    "home_why_lead": "Jackpot, estrazioni recenti e strumenti numerici — tutto ciò che ti serve prima di visitare un operatore ufficiale.",
    "home_why_1_title": "Jackpot e risultati live",
    "home_why_1_text": "Jackpot stimati, ultimi numeri estratti e calendari delle principali lotterie USA e UE in un unico posto.",
    "home_why_2_title": "Controlla i tuoi numeri",
    "home_why_2_text": "Confronta le tue scelte con l'ultima estrazione pubblicata tramite il verificatore integrato.",
    "home_why_3_title": "Cinque giochi principali",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto e Lotto America — regole e selettori integrati.",
    "home_why_4_title": "Gioco responsabile",
    "home_why_4_text": "Guide indipendenti e link agli operatori ufficiali — gioca per divertimento, imposta un budget, conosci le probabilità.",
    "home_hero_img_alt": "— jackpot della lotteria",
    "home_slider_estimated_prize": "Premio stimato :",
    "home_picker_title": "Scegli i numeri fortunati",
    "home_picker_lead": "Scegli i numeri per la prossima estrazione — cambia lotteria per confrontare jackpot e calendari.",
    "home_select_lottery": "Seleziona lotteria",
    "home_results_title": "Risultati recenti della lotteria",
    "home_results_lead": "Ultimi numeri vincenti e vincite principali delle grandi estrazioni — aggiornato dopo ogni risultato pubblicato.",
    "home_view_all": "Vedi tutto",
    "home_results_amount": "Importo :",
    "home_results_draw_date": "Estrazione effettuata il :",
    "home_checker_title": "Controlla i miei numeri",
    "home_checker_lead": "Confronta i tuoi numeri con l'ultima estrazione pubblicata.",
    "home_checker_submit": "Controlla numeri",
    "home_picker_line_hint_before": "Biglietto",
    "home_picker_line_hint_after": "di %1 — tocca una riga a destra per modificarne un'altra",
    "home_picker_pick_main": "Scegli %1 numeri",
    "home_picker_pick_bonus": "Scegli bonus",
    "home_picker_quick_pick": "Selezione rapida",
    "home_picker_clear_all": "Cancella tutto",
    "home_ticket_select_number": "Numeri selezionati",
    "home_ticket_price": "Prezzo del biglietto",
    "home_ticket_price_lines_zero": "(0 righe × %1)",
    "home_ticket_price_pending": "(%1 riga/he in attesa di %2 × %3)",
    "home_ticket_price_one": "(1 riga × %1)",
    "home_ticket_price_lines": "(%1 righe × %2)",
    "home_ticket_buy": "Acquista biglietto",
    "home_payment_methods": "Metodi di pagamento accettati :",
    "home_ticket_line_title": "Riga del biglietto %1",
    "home_checker_aria_main": "Numero principale",
    "home_checker_aria_bonus": "Numero bonus",
    "home_checker_err_all": "Inserisci tutti i numeri.",
    "home_checker_err_invalid": "Numero non valido.",
    "home_checker_err_range": "Il numero %1 è fuori intervallo (%2–%3).",
    "home_checker_err_unique": "I numeri principali devono essere univoci.",
    "home_checker_no_draw_loaded": "I numeri dell'ultima estrazione non sono ancora caricati.",
    "home_checker_latest_draw": "Ultima estrazione (%1): %2",
    "home_checker_latest_draw_no_date": "Ultima estrazione: %1",
    "home_checker_no_draw_data": "Nessun dato di estrazione per questa lotteria. Riprova dopo la prossima sincronizzazione.",
    "home_checker_draw_on": " — estrazione %1",
    "home_checker_no_matches": "Nessuna corrispondenza con i numeri vincenti.",
    "home_checker_matched_main": "Hai indovinato %1 numero/i principale/i",
    "home_checker_matched_bonus": " e %2 numero/i bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Numeri del jackpot — verifica con l'operatore ufficiale.",
    "home_checker_all_main_hint": " Tutti i numeri principali coincidono — verifica con l'operatore ufficiale.",
    "home_checker_winning_label": "Vincenti: %1",
    "home_picker_stage_complete": "Riga completa — aggiungi un'altra riga o acquista un biglietto.",
    "home_picker_main_set": "Numeri principali impostati (%1/%2). Scegli %3 sotto (%4/%5) — pallina rossa nel pannello biglietto.",
    "home_picker_selected_main": "%1 di %2 numeri principali selezionati.",
    "home_picker_bonus_fallback": "numeri bonus",
},
"15": {
    "home_counter_lotteries": "Gevolgde loterijen",
    "home_counter_draws": "Laatste trekkingen",
    "home_counter_jackpots": "Gecombineerde VS-jackpots",
    "home_counter_refresh": "Dataverversing",
    "home_how_subtitle": "Hoe het werkt",
    "home_how_title": "Hoe het werkt",
    "home_how_lead": "Van jackpots vergelijken tot je nummers controleren — vier eenvoudige stappen.",
    "home_how_step1_title": "Stel een budget vast",
    "home_how_step1_text": "Loterij is entertainment — zie loten als onderdeel van je uitgaven voor plezier, niet als investering.",
    "home_how_step2_title": "Kies je loterij",
    "home_how_step2_text": "Vergelijk live jackpots voor PowerBall, Mega Millions, EuroMillions en regionale trekkingen in de carrousel hierboven.",
    "home_how_step3_title": "Kies je nummers",
    "home_how_step3_text": "Gebruik quick pick of kies nummers in de kiezer. Controleer trekkingsschema's voordat je bij een officiële aanbieder speelt.",
    "home_how_step4_title": "Controleer resultaten",
    "home_how_step4_text": "Vergelijk na de trekking je nummers met de nieuwste resultaten op deze pagina of verifieer je lot bij de officiële aanbieder.",
    "home_why_subtitle": "Waarom PowerBall Jackpot",
    "home_why_title": "Jouw loterijresultaten-hub",
    "home_why_lead": "Jackpots, recente trekkingen en nummertools — alles wat je nodig hebt voordat je een officiële aanbieder bezoekt.",
    "home_why_1_title": "Live jackpots & resultaten",
    "home_why_1_text": "Geschatte jackpots, nieuwste getrokken nummers en schema's van grote VS- en EU-loterijen op één plek.",
    "home_why_2_title": "Controleer je nummers",
    "home_why_2_text": "Vergelijk je keuzes met de laatst gepubliceerde trekking via de ingebouwde nummerchecker.",
    "home_why_3_title": "Vijf grote spellen",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto en Lotto America — regels en kiezers ingebouwd.",
    "home_why_4_title": "Verantwoord spelen",
    "home_why_4_text": "Onafhankelijke gidsen en links naar officiële aanbieders — speel voor de fun, stel een budget vast, ken de kansen.",
    "home_hero_img_alt": "— loterijjackpots",
    "home_slider_estimated_prize": "Geschatte prijs :",
    "home_picker_title": "Kies je geluksnummers",
    "home_picker_lead": "Kies je nummers voor de volgende trekking — wissel van loterij om jackpots en schema's te vergelijken.",
    "home_select_lottery": "Loterij kiezen",
    "home_results_title": "Recente loterijresultaten",
    "home_results_lead": "Nieuwste winnende nummers en opvallende uitbetalingen van grote trekkingen — bijgewerkt na elk gepubliceerd resultaat.",
    "home_view_all": "Alles bekijken",
    "home_results_amount": "Bedrag :",
    "home_results_draw_date": "Trekking op :",
    "home_checker_title": "Mijn nummers controleren",
    "home_checker_lead": "Vergelijk je nummers met de laatst gepubliceerde trekking.",
    "home_checker_submit": "Nummers controleren",
    "home_picker_line_hint_before": "Lot",
    "home_picker_line_hint_after": "van %1 — tik rechts op een rij om een andere te bewerken",
    "home_picker_pick_main": "Kies %1 nummers",
    "home_picker_pick_bonus": "Bonus kiezen",
    "home_picker_quick_pick": "Snelle keuze",
    "home_picker_clear_all": "Alles wissen",
    "home_ticket_select_number": "Gekozen nummers",
    "home_ticket_price": "Lotprijs",
    "home_ticket_price_lines_zero": "(0 rijen × %1)",
    "home_ticket_price_pending": "(%1 rij(en) wachten op %2 × %3)",
    "home_ticket_price_one": "(1 rij × %1)",
    "home_ticket_price_lines": "(%1 rijen × %2)",
    "home_ticket_buy": "Lot kopen",
    "home_payment_methods": "Geaccepteerde betaalmethoden :",
    "home_ticket_line_title": "Lotrij %1",
    "home_checker_aria_main": "Hoofdnummer",
    "home_checker_aria_bonus": "Bonusnummer",
    "home_checker_err_all": "Voer alle nummers in.",
    "home_checker_err_invalid": "Ongeldig nummer.",
    "home_checker_err_range": "Nummer %1 valt buiten het bereik (%2–%3).",
    "home_checker_err_unique": "Hoofdnummers moeten uniek zijn.",
    "home_checker_no_draw_loaded": "Nummers van de laatste trekking zijn nog niet geladen.",
    "home_checker_latest_draw": "Laatste trekking (%1): %2",
    "home_checker_latest_draw_no_date": "Laatste trekking: %1",
    "home_checker_no_draw_data": "Geen trekkinggegevens voor deze loterij. Probeer het opnieuw na de volgende synchronisatie.",
    "home_checker_draw_on": " — trekking %1",
    "home_checker_no_matches": "Geen overeenkomst met de winnende nummers.",
    "home_checker_matched_main": "Je hebt %1 hoofdnummer(s) goed",
    "home_checker_matched_bonus": " en %2 bonusnummer(s) goed",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Jackpotnummers — verifieer bij de officiële aanbieder.",
    "home_checker_all_main_hint": " Alle hoofdnummers komen overeen — verifieer bij de officiële aanbieder.",
    "home_checker_winning_label": "Winnend: %1",
    "home_picker_stage_complete": "Rij compleet — voeg een rij toe of koop een lot.",
    "home_picker_main_set": "Hoofdnummers ingesteld (%1/%2). Kies %3 hieronder (%4/%5) — rode bal in het lotpaneel.",
    "home_picker_selected_main": "%1 van %2 hoofdnummers geselecteerd.",
    "home_picker_bonus_fallback": "bonusnummers",
},
"16": {
    "home_counter_lotteries": "Śledzone loterie",
    "home_counter_draws": "Ostatnie losowania",
    "home_counter_jackpots": "Łączne jackpoty USA",
    "home_counter_refresh": "Odświeżanie danych",
    "home_how_subtitle": "Jak to działa",
    "home_how_title": "Jak to działa",
    "home_how_lead": "Od porównania jackpotów po sprawdzenie numerów — cztery proste kroki.",
    "home_how_step1_title": "Ustal budżet",
    "home_how_step1_text": "Loteria to rozrywka — traktuj kupony jako część budżetu na przyjemności, nie inwestycję.",
    "home_how_step2_title": "Wybierz loterię",
    "home_how_step2_text": "Porównaj na żywo jackpoty PowerBall, Mega Millions, EuroMillions i losowań regionalnych w karuzeli powyżej.",
    "home_how_step3_title": "Wybierz numery",
    "home_how_step3_text": "Użyj szybkiego wyboru lub wybierz numery w selektorze. Sprawdź terminy losowań przed grą u oficjalnego operatora.",
    "home_how_step4_title": "Sprawdź wyniki",
    "home_how_step4_text": "Po losowaniu porównaj numery z najnowszymi wynikami na tej stronie lub zweryfikuj kupon u oficjalnego operatora.",
    "home_why_subtitle": "Dlaczego PowerBall Jackpot",
    "home_why_title": "Twój hub wyników loterii",
    "home_why_lead": "Jackpoty, ostatnie losowania i narzędzia numeryczne — wszystko, czego potrzebujesz przed wizytą u oficjalnego operatora.",
    "home_why_1_title": "Jackpoty i wyniki na żywo",
    "home_why_1_text": "Szacowane jackpoty, ostatnie wylosowane numery i harmonogramy głównych loterii USA i UE w jednym miejscu.",
    "home_why_2_title": "Sprawdź swoje numery",
    "home_why_2_text": "Porównaj swoje typy z ostatnio opublikowanym losowaniem za pomocą wbudowanego sprawdzacza.",
    "home_why_3_title": "Pięć głównych gier",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto i Lotto America — zasady i selektory wbudowane.",
    "home_why_4_title": "Odpowiedzialna gra",
    "home_why_4_text": "Niezależne poradniki i linki do oficjalnych operatorów — graj dla przyjemności, ustal budżet, znaj swoje szanse.",
    "home_hero_img_alt": "— jackpoty loterii",
    "home_slider_estimated_prize": "Szacowana wygrana :",
    "home_picker_title": "Wybierz szczęśliwe numery",
    "home_picker_lead": "Wybierz numery na następne losowanie — przełącz loterię, by porównać jackpoty i terminy.",
    "home_select_lottery": "Wybierz loterię",
    "home_results_title": "Ostatnie wyniki loterii",
    "home_results_lead": "Najnowsze zwycięskie numery i wyróżnione wygrane z głównych losowań — aktualizowane po każdym opublikowanym wyniku.",
    "home_view_all": "Zobacz wszystko",
    "home_results_amount": "Kwota :",
    "home_results_draw_date": "Losowanie odbyło się :",
    "home_checker_title": "Sprawdź moje numery",
    "home_checker_lead": "Porównaj swoje numery z ostatnio opublikowanym losowaniem.",
    "home_checker_submit": "Sprawdź numery",
    "home_picker_line_hint_before": "Kupon",
    "home_picker_line_hint_after": "z %1 — dotknij wiersza po prawej, by edytować inny",
    "home_picker_pick_main": "Wybierz %1 liczb",
    "home_picker_pick_bonus": "Wybierz bonus",
    "home_picker_quick_pick": "Szybki wybór",
    "home_picker_clear_all": "Wyczyść wszystko",
    "home_ticket_select_number": "Wybrane numery",
    "home_ticket_price": "Cena kuponu",
    "home_ticket_price_lines_zero": "(0 linii × %1)",
    "home_ticket_price_pending": "(%1 linia/linie czeka na %2 × %3)",
    "home_ticket_price_one": "(1 linia × %1)",
    "home_ticket_price_lines": "(%1 linii × %2)",
    "home_ticket_buy": "Kup kupon",
    "home_payment_methods": "Akceptowane metody płatności :",
    "home_ticket_line_title": "Linia kuponu %1",
    "home_checker_aria_main": "Liczba główna",
    "home_checker_aria_bonus": "Liczba bonusowa",
    "home_checker_err_all": "Wprowadź wszystkie numery.",
    "home_checker_err_invalid": "Nieprawidłowa liczba.",
    "home_checker_err_range": "Liczba %1 jest poza zakresem (%2–%3).",
    "home_checker_err_unique": "Liczby główne muszą być unikalne.",
    "home_checker_no_draw_loaded": "Numery ostatniego losowania nie zostały jeszcze załadowane.",
    "home_checker_latest_draw": "Ostatnie losowanie (%1): %2",
    "home_checker_latest_draw_no_date": "Ostatnie losowanie: %1",
    "home_checker_no_draw_data": "Brak danych losowania dla tej loterii. Spróbuj ponownie po następnej synchronizacji.",
    "home_checker_draw_on": " — losowanie %1",
    "home_checker_no_matches": "Brak zgodności ze zwycięskimi numerami.",
    "home_checker_matched_main": "Trafiono %1 liczbę/liczb głównych",
    "home_checker_matched_bonus": " i %2 liczbę/liczb bonusowych",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Numery jackpota — zweryfikuj u oficjalnego operatora.",
    "home_checker_all_main_hint": " Wszystkie liczby główne się zgadzają — zweryfikuj u oficjalnego operatora.",
    "home_checker_winning_label": "Zwycięskie: %1",
    "home_picker_stage_complete": "Linia uzupełniona — dodaj kolejną lub kup kupon.",
    "home_picker_main_set": "Liczby główne ustawione (%1/%2). Wybierz %3 poniżej (%4/%5) — czerwona kula w panelu kuponu.",
    "home_picker_selected_main": "Wybrano %1 z %2 liczb głównych.",
    "home_picker_bonus_fallback": "liczby bonusowe",
},
"19": {
    "home_counter_lotteries": "Lotterii urmărite",
    "home_counter_draws": "Ultimele extrageri",
    "home_counter_jackpots": "Jackpoturi SUA combinate",
    "home_counter_refresh": "Actualizare date",
    "home_how_subtitle": "Cum funcționează",
    "home_how_title": "Cum funcționează",
    "home_how_lead": "De la compararea jackpoturilor la verificarea numerelor — patru pași simpli.",
    "home_how_step1_title": "Stabilește un buget",
    "home_how_step1_text": "Loteria este divertisment — tratează biletele ca parte din bugetul de relaxare, nu ca investiție.",
    "home_how_step2_title": "Alege loteria",
    "home_how_step2_text": "Compară jackpoturile live pentru PowerBall, Mega Millions, EuroMillions și extragerile regionale în caruselul de mai sus.",
    "home_how_step3_title": "Alege numerele",
    "home_how_step3_text": "Folosește selecția rapidă sau alege numere în selector. Verifică calendarul extragerilor înainte de a juca la un operator oficial.",
    "home_how_step4_title": "Verifică rezultatele",
    "home_how_step4_text": "După extragere, compară numerele cu cele mai recente rezultate pe această pagină sau verifică biletul la operatorul oficial.",
    "home_why_subtitle": "De ce PowerBall Jackpot",
    "home_why_title": "Hub-ul tău de rezultate loto",
    "home_why_lead": "Jackpoturi, extrageri recente și instrumente pentru numere — tot ce ai nevoie înainte să vizitezi un operator oficial.",
    "home_why_1_title": "Jackpoturi și rezultate live",
    "home_why_1_text": "Jackpoturi estimate, ultimele numere extrase și programele principalelor loterii din SUA și UE într-un singur loc.",
    "home_why_2_title": "Verifică numerele",
    "home_why_2_text": "Compară alegerile tale cu ultima extragere publicată folosind verificatorul integrat.",
    "home_why_3_title": "Cinci jocuri majore",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto și Lotto America — reguli și selectoare integrate.",
    "home_why_4_title": "Joc responsabil",
    "home_why_4_text": "Ghiduri independente și linkuri către operatori oficiali — joacă pentru distracție, stabilește un buget, cunoaște șansele.",
    "home_hero_img_alt": "— jackpoturi de loterie",
    "home_slider_estimated_prize": "Premiu estimat :",
    "home_picker_title": "Alege numerele norocoase",
    "home_picker_lead": "Alege numerele pentru următoarea extragere — schimbă loteria pentru a compara jackpoturi și programe.",
    "home_select_lottery": "Selectează loteria",
    "home_results_title": "Rezultate recente la loterie",
    "home_results_lead": "Ultimele numere câștigătoare și câștiguri notabile din extrageri majore — actualizat după fiecare rezultat publicat.",
    "home_view_all": "Vezi tot",
    "home_results_amount": "Sumă :",
    "home_results_draw_date": "Extragerea a avut loc pe :",
    "home_checker_title": "Verifică numerele mele",
    "home_checker_lead": "Compară numerele tale cu ultima extragere publicată.",
    "home_checker_submit": "Verifică numerele",
    "home_picker_line_hint_before": "Bilet",
    "home_picker_line_hint_after": "din %1 — atinge un rând din dreapta pentru a edita altul",
    "home_picker_pick_main": "Alege %1 numere",
    "home_picker_pick_bonus": "Alege bonus",
    "home_picker_quick_pick": "Selecție rapidă",
    "home_picker_clear_all": "Șterge tot",
    "home_ticket_select_number": "Numere selectate",
    "home_ticket_price": "Preț bilet",
    "home_ticket_price_lines_zero": "(0 linii × %1)",
    "home_ticket_price_pending": "(%1 linie/linii în așteptarea %2 × %3)",
    "home_ticket_price_one": "(1 linie × %1)",
    "home_ticket_price_lines": "(%1 linii × %2)",
    "home_ticket_buy": "Cumpără bilet",
    "home_payment_methods": "Metode de plată acceptate :",
    "home_ticket_line_title": "Linia biletului %1",
    "home_checker_aria_main": "Număr principal",
    "home_checker_aria_bonus": "Număr bonus",
    "home_checker_err_all": "Introdu toate numerele.",
    "home_checker_err_invalid": "Număr invalid.",
    "home_checker_err_range": "Numărul %1 este în afara intervalului (%2–%3).",
    "home_checker_err_unique": "Numerele principale trebuie să fie unice.",
    "home_checker_no_draw_loaded": "Numerele ultimei extrageri nu sunt încă încărcate.",
    "home_checker_latest_draw": "Ultima extragere (%1): %2",
    "home_checker_latest_draw_no_date": "Ultima extragere: %1",
    "home_checker_no_draw_data": "Nu există date de extragere pentru această loterie. Încearcă din nou după următoarea sincronizare.",
    "home_checker_draw_on": " — extragere %1",
    "home_checker_no_matches": "Nicio potrivire cu numerele câștigătoare.",
    "home_checker_matched_main": "Ai nimerit %1 număr/e principal/e",
    "home_checker_matched_bonus": " și %2 număr/e bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Numere de jackpot — verifică la operatorul oficial.",
    "home_checker_all_main_hint": " Toate numerele principale coincid — verifică la operatorul oficial.",
    "home_checker_winning_label": "Câștigătoare: %1",
    "home_picker_stage_complete": "Linie completă — adaugă altă linie sau cumpără un bilet.",
    "home_picker_main_set": "Numere principale setate (%1/%2). Alege %3 mai jos (%4/%5) — bilă roșie în panoul biletului.",
    "home_picker_selected_main": "%1 din %2 numere principale selectate.",
    "home_picker_bonus_fallback": "numere bonus",
},
"9": {
    "home_counter_lotteries": "Отслеживаемые лотереи",
    "home_counter_draws": "Последние тиражи",
    "home_counter_jackpots": "Суммарные джекпоты США",
    "home_counter_refresh": "Обновление данных",
    "home_how_subtitle": "Как это работает",
    "home_how_title": "Как это работает",
    "home_how_lead": "От сравнения джекпотов до проверки номеров — четыре простых шага.",
    "home_how_step1_title": "Определите бюджет",
    "home_how_step1_text": "Лотерея — это развлечение: относитесь к билетам как к части бюджета на отдых, а не как к инвестиции.",
    "home_how_step2_title": "Выберите лотерею",
    "home_how_step2_text": "Сравните актуальные джекпоты PowerBall, Mega Millions, EuroMillions и региональных тиражей в карусели выше.",
    "home_how_step3_title": "Выберите номера",
    "home_how_step3_text": "Используйте быстрый выбор или отметьте номера в селекторе. Проверьте расписание тиражей перед игрой у официального оператора.",
    "home_how_step4_title": "Проверьте результаты",
    "home_how_step4_text": "После тиража сравните номера с последними результатами на этой странице или проверьте билет у официального оператора.",
    "home_why_subtitle": "Почему PowerBall Jackpot",
    "home_why_title": "Ваш хаб результатов лотереи",
    "home_why_lead": "Джекпоты, свежие тиражи и инструменты для номеров — всё необходимое перед визитом к официальному оператору.",
    "home_why_1_title": "Джекпоты и результаты в реальном времени",
    "home_why_1_text": "Оценочные джекпоты, последние выигрышные номера и расписание крупных лотерей США и ЕС в одном месте.",
    "home_why_2_title": "Проверьте свои номера",
    "home_why_2_text": "Сравните выбранные номера с последним опубликованным тиражом через встроенный проверщик.",
    "home_why_3_title": "Пять крупных игр",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto и Lotto America — правила и селекторы уже на месте.",
    "home_why_4_title": "Ответственная игра",
    "home_why_4_text": "Независимые гайды и ссылки на официальных операторов — играйте ради удовольствия, задайте бюджет, знайте шансы.",
    "home_hero_img_alt": "— джекпоты лотереи",
    "home_slider_estimated_prize": "Оценочный приз :",
    "home_picker_title": "Выберите счастливые номера",
    "home_picker_lead": "Выберите номера на следующий тираж — переключайте лотереи, чтобы сравнить джекпоты и расписание.",
    "home_select_lottery": "Выбрать лотерею",
    "home_results_title": "Последние результаты лотереи",
    "home_results_lead": "Свежие выигрышные номера и крупные выплаты — обновляется после каждого опубликованного тиража.",
    "home_view_all": "Смотреть все",
    "home_results_amount": "Сумма :",
    "home_results_draw_date": "Тираж состоялся :",
    "home_checker_title": "Проверить мои номера",
    "home_checker_lead": "Сравните свои номера с последним опубликованным тиражом.",
    "home_checker_submit": "Проверить номера",
    "home_picker_line_hint_before": "Билет",
    "home_picker_line_hint_after": "из %1 — нажмите на строку справа, чтобы редактировать другую",
    "home_picker_pick_main": "Выберите %1 номеров",
    "home_picker_pick_bonus": "Выбрать бонус",
    "home_picker_quick_pick": "Быстрый выбор",
    "home_picker_clear_all": "Очистить всё",
    "home_ticket_select_number": "Выбранные номера",
    "home_ticket_price": "Цена билета",
    "home_ticket_price_lines_zero": "(0 строк × %1)",
    "home_ticket_price_pending": "(%1 строк(а) ждут %2 × %3)",
    "home_ticket_price_one": "(1 строка × %1)",
    "home_ticket_price_lines": "(%1 строк × %2)",
    "home_ticket_buy": "Купить билет",
    "home_payment_methods": "Принимаемые способы оплаты :",
    "home_ticket_line_title": "Строка билета %1",
    "home_checker_aria_main": "Основной номер",
    "home_checker_aria_bonus": "Бонусный номер",
    "home_checker_err_all": "Введите все номера.",
    "home_checker_err_invalid": "Некорректный номер.",
    "home_checker_err_range": "Номер %1 вне диапазона (%2–%3).",
    "home_checker_err_unique": "Основные номера должны быть уникальными.",
    "home_checker_no_draw_loaded": "Номера последнего тиража ещё не загружены.",
    "home_checker_latest_draw": "Последний тираж (%1): %2",
    "home_checker_latest_draw_no_date": "Последний тираж: %1",
    "home_checker_no_draw_data": "Нет данных тиража для этой лотереи. Попробуйте после следующей синхронизации.",
    "home_checker_draw_on": " — тираж %1",
    "home_checker_no_matches": "Совпадений с выигрышными номерами нет.",
    "home_checker_matched_main": "Совпало основных номеров: %1",
    "home_checker_matched_bonus": " и бонусных: %2",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Номера джекпота — подтвердите у официального оператора.",
    "home_checker_all_main_hint": " Все основные номера совпали — подтвердите у официального оператора.",
    "home_checker_winning_label": "Выигрышные: %1",
    "home_picker_stage_complete": "Строка заполнена — добавьте ещё одну или купите билет.",
    "home_picker_main_set": "Основные номера выбраны (%1/%2). Укажите %3 ниже (%4/%5) — красный шар в панели билета.",
    "home_picker_selected_main": "Выбрано %1 из %2 основных номеров.",
    "home_picker_bonus_fallback": "бонусные номера",
},
"18": {
    "home_counter_lotteries": "Відстежувані лотереї",
    "home_counter_draws": "Останні тиражі",
    "home_counter_jackpots": "Сумарні джекпоти США",
    "home_counter_refresh": "Оновлення даних",
    "home_how_subtitle": "Як це працює",
    "home_how_title": "Як це працює",
    "home_how_lead": "Від порівняння джекпотів до перевірки номерів — чотири прості кроки.",
    "home_how_step1_title": "Визначте бюджет",
    "home_how_step1_text": "Лотерея — це розвага: ставтеся до квитків як до частини бюджету на відпочинок, а не як до інвестиції.",
    "home_how_step2_title": "Оберіть лотерею",
    "home_how_step2_text": "Порівняйте актуальні джекпоти PowerBall, Mega Millions, EuroMillions і регіональних тиражів у каруселі вище.",
    "home_how_step3_title": "Оберіть номери",
    "home_how_step3_text": "Скористайтеся швидким вибором або позначте номери в селекторі. Перевірте розклад тиражів перед грою в офіційного оператора.",
    "home_how_step4_title": "Перевірте результати",
    "home_how_step4_text": "Після тиражу порівняйте номери з останніми результатами на цій сторінці або перевірте квиток у офіційного оператора.",
    "home_why_subtitle": "Чому PowerBall Jackpot",
    "home_why_title": "Ваш хаб результатів лотереї",
    "home_why_lead": "Джекпоти, свіжі тиражі та інструменти для номерів — усе необхідне перед візитом до офіційного оператора.",
    "home_why_1_title": "Джекпоти та результати наживо",
    "home_why_1_text": "Орієнтовні джекпоти, останні виграшні номери та розклад великих лотерей США і ЄС в одному місці.",
    "home_why_2_title": "Перевірте свої номери",
    "home_why_2_text": "Порівняйте обрані номери з останнім опублікованим тиражем через вбудований перевірник.",
    "home_why_3_title": "П'ять великих ігор",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto та Lotto America — правила й селектори вже на місці.",
    "home_why_4_title": "Відповідальна гра",
    "home_why_4_text": "Незалежні гайди та посилання на офіційних операторів — грайте заради задоволення, задайте бюджет, знайте шанси.",
    "home_hero_img_alt": "— джекпоти лотереї",
    "home_slider_estimated_prize": "Орієнтовний приз :",
    "home_picker_title": "Оберіть щасливі номери",
    "home_picker_lead": "Оберіть номери на наступний тираж — перемикайте лотереї, щоб порівняти джекпоти та розклад.",
    "home_select_lottery": "Обрати лотерею",
    "home_results_title": "Останні результати лотереї",
    "home_results_lead": "Свіжі виграшні номери та ключові виплати — оновлюється після кожного опублікованого тиражу.",
    "home_view_all": "Дивитися все",
    "home_results_amount": "Сума :",
    "home_results_draw_date": "Тираж відбувся :",
    "home_checker_title": "Перевірити мої номери",
    "home_checker_lead": "Порівняйте свої номери з останнім опублікованим тиражем.",
    "home_checker_submit": "Перевірити номери",
    "home_picker_line_hint_before": "Квиток",
    "home_picker_line_hint_after": "з %1 — натисніть рядок праворуч, щоб редагувати інший",
    "home_picker_pick_main": "Оберіть %1 номерів",
    "home_picker_pick_bonus": "Обрати бонус",
    "home_picker_quick_pick": "Швидкий вибір",
    "home_picker_clear_all": "Очистити все",
    "home_ticket_select_number": "Обрані номери",
    "home_ticket_price": "Ціна квитка",
    "home_ticket_price_lines_zero": "(0 рядків × %1)",
    "home_ticket_price_pending": "(%1 рядок(и) чекають на %2 × %3)",
    "home_ticket_price_one": "(1 рядок × %1)",
    "home_ticket_price_lines": "(%1 рядків × %2)",
    "home_ticket_buy": "Купити квиток",
    "home_payment_methods": "Прийняті способи оплати :",
    "home_ticket_line_title": "Рядок квитка %1",
    "home_checker_aria_main": "Основний номер",
    "home_checker_aria_bonus": "Бонусний номер",
    "home_checker_err_all": "Введіть усі номери.",
    "home_checker_err_invalid": "Некоректний номер.",
    "home_checker_err_range": "Номер %1 поза діапазоном (%2–%3).",
    "home_checker_err_unique": "Основні номери мають бути унікальними.",
    "home_checker_no_draw_loaded": "Номери останнього тиражу ще не завантажені.",
    "home_checker_latest_draw": "Останній тираж (%1): %2",
    "home_checker_latest_draw_no_date": "Останній тираж: %1",
    "home_checker_no_draw_data": "Немає даних тиражу для цієї лотереї. Спробуйте після наступної синхронізації.",
    "home_checker_draw_on": " — тираж %1",
    "home_checker_no_matches": "Збігів із виграшними номерами немає.",
    "home_checker_matched_main": "Збіглося основних номерів: %1",
    "home_checker_matched_bonus": " і бонусних: %2",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Номери джекпоту — підтвердіть у офіційного оператора.",
    "home_checker_all_main_hint": " Усі основні номери збіглися — підтвердіть у офіційного оператора.",
    "home_checker_winning_label": "Виграшні: %1",
    "home_picker_stage_complete": "Рядок заповнено — додайте ще один або купіть квиток.",
    "home_picker_main_set": "Основні номери обрано (%1/%2). Вкажіть %3 нижче (%4/%5) — червона куля в панелі квитка.",
    "home_picker_selected_main": "Обрано %1 з %2 основних номерів.",
    "home_picker_bonus_fallback": "бонусні номери",
},
"7": {
    "home_counter_lotteries": "ट्रैक की गई लॉटरी",
    "home_counter_draws": "नवीनतम ड्रॉ",
    "home_counter_jackpots": "संयुक्त US जैकपॉट",
    "home_counter_refresh": "डेटा रिफ्रेश",
    "home_how_subtitle": "यह कैसे काम करता है",
    "home_how_title": "यह कैसे काम करता है",
    "home_how_lead": "जैकपॉट की तुलना से अपने नंबरों की जाँच तक — चार सरल चरण।",
    "home_how_step1_title": "बजट तय करें",
    "home_how_step1_text": "लॉटरी मनोरंजन है — टिकट को निवेश नहीं, अपने मनोरंजन बजट का हिस्सा समझें।",
    "home_how_step2_title": "लॉटरी चुनें",
    "home_how_step2_text": "ऊपर के कैरousel में PowerBall, Mega Millions, EuroMillions और क्षेत्रीय ड्रॉ के लाइव जैकपॉट की तुलना करें।",
    "home_how_step3_title": "नंबर चुनें",
    "home_how_step3_text": "क्विक पिक का उपयोग करें या पिकर में नंबर चुनें। आधिकारिक ऑपरेटर पर खेलने से पहले ड्रॉ शेड्यूल देखें।",
    "home_how_step4_title": "परिणाम जाँचें",
    "home_how_step4_text": "ड्रॉ के बाद इस पेज पर नवीनतम परिणामों से अपने नंबरों की तुलना करें या आधिकारिक ऑपरेटर से टिकट सत्यापित करें।",
    "home_why_subtitle": "PowerBall Jackpot क्यों",
    "home_why_title": "आपका लॉटरी परिणाम हब",
    "home_why_lead": "जैकपॉट, हाल के ड्रॉ और नंबर टूल — आधिकारिक ऑपरेटर पर जाने से पहले जो कुछ चाहिए।",
    "home_why_1_title": "लाइव जैकपॉट और परिणाम",
    "home_why_1_text": "अनुमानित जैकपॉट, नवीनतम विजेता नंबर और प्रमुख US/EU लॉटरी शेड्यूल एक ही जगह।",
    "home_why_2_title": "अपने नंबर जाँचें",
    "home_why_2_text": "पेज पर बिल्ट-इन चेकर से अपने चुने हुए नंबरों की तुलना अंतिम प्रकाशित ड्रॉ से करें।",
    "home_why_3_title": "पाँच प्रमुख गेम",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto और Lotto America — नियम और पिकर बिल्ट-इन।",
    "home_why_4_title": "जिम्मेदार खेल",
    "home_why_4_text": "स्वतंत्र गाइड और आधिकारिक ऑपरेटर लिंक — मज़े के लिए खेलें, बजट तय करें, संभावनाएँ जानें।",
    "home_hero_img_alt": "— लॉटरी जैकपॉट",
    "home_slider_estimated_prize": "अनुमानित पुरस्कार :",
    "home_picker_title": "भाग्यशाली नंबर चुनें",
    "home_picker_lead": "अगले ड्रॉ के लिए नंबर चुनें — जैकपॉट और शेड्यूल तुलना के लिए लॉटरी बदलें।",
    "home_select_lottery": "लॉटरी चुनें",
    "home_results_title": "हाल के लॉटरी परिणाम",
    "home_results_lead": "नवीनतम विजेता नंबर और प्रमुख ड्रॉ की झलक — हर प्रकाशित परिणाम के बाद अपडेट।",
    "home_view_all": "सभी देखें",
    "home_results_amount": "राशि :",
    "home_results_draw_date": "ड्रॉ की तारीख :",
    "home_checker_title": "मेरे नंबर जाँचें",
    "home_checker_lead": "अपने नंबरों की तुलना अंतिम प्रकाशित ड्रॉ से करें।",
    "home_checker_submit": "नंबर जाँचें",
    "home_picker_line_hint_before": "टिकट",
    "home_picker_line_hint_after": "%1 में से — दूसरी लाइन संपादित करने के लिए दाईं ओर की पंक्ति पर टैप करें",
    "home_picker_pick_main": "%1 नंबर चुनें",
    "home_picker_pick_bonus": "बोनस चुनें",
    "home_picker_quick_pick": "क्विक पिक",
    "home_picker_clear_all": "सब साफ़ करें",
    "home_ticket_select_number": "चुने गए नंबर",
    "home_ticket_price": "टिकट की कीमत",
    "home_ticket_price_lines_zero": "(0 लाइन × %1)",
    "home_ticket_price_pending": "(%1 लाइन %2 का इंतज़ार × %3)",
    "home_ticket_price_one": "(1 लाइन × %1)",
    "home_ticket_price_lines": "(%1 लाइन × %2)",
    "home_ticket_buy": "टिकट खरीदें",
    "home_payment_methods": "स्वीकृत भुगतान विधियाँ :",
    "home_ticket_line_title": "टिकट लाइन %1",
    "home_checker_aria_main": "मुख्य नंबर",
    "home_checker_aria_bonus": "बोनस नंबर",
    "home_checker_err_all": "सभी नंबर दर्ज करें।",
    "home_checker_err_invalid": "अमान्य नंबर।",
    "home_checker_err_range": "नंबर %1 सीमा (%2–%3) से बाहर है।",
    "home_checker_err_unique": "मुख्य नंबर अद्वितीय होने चाहिए।",
    "home_checker_no_draw_loaded": "अंतिम ड्रॉ के नंबर अभी लोड नहीं हुए।",
    "home_checker_latest_draw": "अंतिम ड्रॉ (%1): %2",
    "home_checker_latest_draw_no_date": "अंतिम ड्रॉ: %1",
    "home_checker_no_draw_data": "इस लॉटरी के लिए ड्रॉ डेटा नहीं। अगले सिंक के बाद पुनः प्रयास करें।",
    "home_checker_draw_on": " — ड्रॉ %1",
    "home_checker_no_matches": "विजेता नंबरों से कोई मेल नहीं।",
    "home_checker_matched_main": "आपके %1 मुख्य नंबर मेल खाते हैं",
    "home_checker_matched_bonus": " और %2 बोनस नंबर",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " जैकपॉट नंबर — आधिकारिक ऑपरेटर से सत्यापित करें।",
    "home_checker_all_main_hint": " सभी मुख्य नंबर मेल खाते हैं — आधिकारिक ऑपरेटर से सत्यापित करें।",
    "home_checker_winning_label": "विजेता: %1",
    "home_picker_stage_complete": "लाइन पूर्ण — एक और लाइन जोड़ें या टिकट खरीदें।",
    "home_picker_main_set": "मुख्य नंबर सेट (%1/%2). नीचे %3 चुनें (%4/%5) — टिकट पैनल में लाल गेंद।",
    "home_picker_selected_main": "%2 में से %1 मुख्य नंबर चुने।",
    "home_picker_bonus_fallback": "बोनस नंबर",
},
"11": {
    "home_counter_lotteries": "اليانصيب المتتبعة",
    "home_counter_draws": "أحدث السحوبات",
    "home_counter_jackpots": "مجموع الجوائز الأمريكية",
    "home_counter_refresh": "تحديث البيانات",
    "home_how_subtitle": "كيف يعمل",
    "home_how_title": "كيف يعمل",
    "home_how_lead": "من مقارنة الجوائز إلى التحقق من أرقامك — أربع خطوات بسيطة.",
    "home_how_step1_title": "حدّد ميزانية",
    "home_how_step1_text": "اليانصيب ترفيه — تعامل مع التذاكر كجزء من ميزانية المتعة، لا كاستثمار.",
    "home_how_step2_title": "اختر اليانصيب",
    "home_how_step2_text": "قارن الجوائز المباشرة لـ PowerBall وMega Millions وEuroMillions والسحوبات الإقليمية في الشريط أعلاه.",
    "home_how_step3_title": "اختر أرقامك",
    "home_how_step3_text": "استخدم الاختيار السريع أو حدّد الأرقام في المُنتقي. راجع جداول السحب قبل اللعب لدى مشغّل رسمي.",
    "home_how_step4_title": "تحقق من النتائج",
    "home_how_step4_text": "بعد السحب، قارن أرقامك مع أحدث النتائج في هذه الصفحة أو تحقق من تذكرتك لدى المشغّل الرسمي.",
    "home_why_subtitle": "لماذا PowerBall Jackpot",
    "home_why_title": "مركز نتائج اليانصيب",
    "home_why_lead": "الجوائز والسحوبات الأخيرة وأدوات الأرقام — كل ما تحتاجه قبل زيارة مشغّل رسمي.",
    "home_why_1_title": "جوائز ونتائج مباشرة",
    "home_why_1_text": "جوائز تقديرية وأحدث الأرقام الفائزة وجداول أهم اليانصيب الأمريكية والأوروبية في مكان واحد.",
    "home_why_2_title": "تحقق من أرقامك",
    "home_why_2_text": "قارن اختياراتك مع آخر سحب منشور عبر أداة التحقق المدمجة.",
    "home_why_3_title": "خمس ألعاب رئيسية",
    "home_why_3_text": "PowerBall وMega Millions وEuroMillions وFlorida Lotto وLotto America — قواعد ومُنتقيات مدمجة.",
    "home_why_4_title": "لعب مسؤول",
    "home_why_4_text": "أدلة مستقلة وروابط للمشغّلين الرسميين — العب للمتعة، حدّد ميزانية، واعرف الاحتمالات.",
    "home_hero_img_alt": "— جوائز اليانصيب",
    "home_slider_estimated_prize": "الجائزة التقديرية :",
    "home_picker_title": "اختر أرقام الحظ",
    "home_picker_lead": "اختر أرقامك للسحب القادم — بدّل اليانصيب لمقارنة الجوائز والجداول.",
    "home_select_lottery": "اختر اليانصيب",
    "home_results_title": "نتائج اليانصيب الأخيرة",
    "home_results_lead": "أحدث الأرقام الفائزة وأبرز المكاسب — يُحدَّث بعد كل نتيجة منشورة.",
    "home_view_all": "عرض الكل",
    "home_results_amount": "المبلغ :",
    "home_results_draw_date": "أُجري السحب في :",
    "home_checker_title": "تحقق من أرقامي",
    "home_checker_lead": "قارن أرقامك مع آخر سحب منشور.",
    "home_checker_submit": "تحقق من الأرقام",
    "home_picker_line_hint_before": "تذكرة",
    "home_picker_line_hint_after": "من %1 — اضغط صفاً على اليمين لتحرير صف آخر",
    "home_picker_pick_main": "اختر %1 أرقام",
    "home_picker_pick_bonus": "اختر bonus",
    "home_picker_quick_pick": "اختيار سريع",
    "home_picker_clear_all": "مسح الكل",
    "home_ticket_select_number": "الأرقام المختارة",
    "home_ticket_price": "سعر التذكرة",
    "home_ticket_price_lines_zero": "(0 صفوف × %1)",
    "home_ticket_price_pending": "(%1 صف(وف) بانتظار %2 × %3)",
    "home_ticket_price_one": "(صف واحد × %1)",
    "home_ticket_price_lines": "(%1 صفوف × %2)",
    "home_ticket_buy": "شراء تذكرة",
    "home_payment_methods": "طرق الدفع المقبولة :",
    "home_ticket_line_title": "صف التذكرة %1",
    "home_checker_aria_main": "رقم رئيسي",
    "home_checker_aria_bonus": "رقم إضافي",
    "home_checker_err_all": "أدخل جميع الأرقام.",
    "home_checker_err_invalid": "رقم غير صالح.",
    "home_checker_err_range": "الرقم %1 خارج النطاق (%2–%3).",
    "home_checker_err_unique": "يجب أن تكون الأرقام الرئيسية فريدة.",
    "home_checker_no_draw_loaded": "أرقام آخر سحب غير محمّلة بعد.",
    "home_checker_latest_draw": "آخر سحب (%1): %2",
    "home_checker_latest_draw_no_date": "آخر سحب: %1",
    "home_checker_no_draw_data": "لا توجد بيانات سحب لهذا اليانصيب. حاول بعد المزامنة التالية.",
    "home_checker_draw_on": " — سحب %1",
    "home_checker_no_matches": "لا تطابق مع الأرقام الفائزة.",
    "home_checker_matched_main": "طابقت %1 رقماً/أرقاماً رئيسية",
    "home_checker_matched_bonus": " و%2 رقماً/أرقام bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " أرقام الجائزة — تحقق لدى المشغّل الرسمي.",
    "home_checker_all_main_hint": " جميع الأرقام الرئيسية متطابقة — تحقق لدى المشغّل الرسمي.",
    "home_checker_winning_label": "الفائزة: %1",
    "home_picker_stage_complete": "الصف مكتمل — أضف صفاً آخر أو اشترِ تذكرة.",
    "home_picker_main_set": "الأرقام الرئيسية جاهزة (%1/%2). اختر %3 أدناه (%4/%5) — الكرة الحمراء في لوحة التذكرة.",
    "home_picker_selected_main": "تم اختيار %1 من %2 أرقام رئيسية.",
    "home_picker_bonus_fallback": "أرقام إضافية",
},
"12": {
    "home_counter_lotteries": "İzlənən lotereyalar",
    "home_counter_draws": "Son tirajlar",
    "home_counter_jackpots": "ABŞ cekpotlarının cəmi",
    "home_counter_refresh": "Məlumat yenilənməsi",
    "home_how_subtitle": "Necə işləyir",
    "home_how_title": "Necə işləyir",
    "home_how_lead": "Cekpotların müqayisəsindən nömrələrin yoxlanmasına qədər — dörd sadə addım.",
    "home_how_step1_title": "Büdcə müəyyən edin",
    "home_how_step1_text": "Lotereya əyləncədir — biletləri investisiya deyil, əyləncə büdcəsinin hissəsi kimi qəbul edin.",
    "home_how_step2_title": "Lotereya seçin",
    "home_how_step2_text": "Yuxarıdakı karuseldə PowerBall, Mega Millions, EuroMillions və regional tirajların canlı cekpotlarını müqayisə edin.",
    "home_how_step3_title": "Nömrələri seçin",
    "home_how_step3_text": "Sürətli seçimdən istifadə edin və ya seçicidə nömrələri işarələyin. Rəsmi operatorda oynamazdan əvvəl tiraj cədvəlini yoxlayın.",
    "home_how_step4_title": "Nəticələri yoxlayın",
    "home_how_step4_text": "Tirajdan sonra nömrələri bu səhifədəki son nəticələrlə müqayisə edin və ya bileti rəsmi operatorda yoxlayın.",
    "home_why_subtitle": "Niyə PowerBall Jackpot",
    "home_why_title": "Lotereya nəticələri mərkəziniz",
    "home_why_lead": "Cekpotlar, son tirajlar və nömrə alətləri — rəsmi operatora getməzdən əvvəl lazım olan hər şey.",
    "home_why_1_title": "Canlı cekpotlar və nəticələr",
    "home_why_1_text": "Təxmini cekpotlar, son qalib nömrələr və əsas ABŞ/Aİ lotereyalarının cədvəli bir yerdə.",
    "home_why_2_title": "Nömrələrinizi yoxlayın",
    "home_why_2_text": "Seçimlərinizi səhifədəki yoxlayıcı ilə son dərc olunmuş tirajla müqayisə edin.",
    "home_why_3_title": "Beş əsas oyun",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto və Lotto America — qaydalar və seçicilər daxildir.",
    "home_why_4_title": "Məsuliyyətli oyun",
    "home_why_4_text": "Müstəqil bələdçilər və rəsmi operator linkləri — əyləncə üçün oynayın, büdcə qoyun, ehtimalları bilin.",
    "home_hero_img_alt": "— lotereya cekpotları",
    "home_slider_estimated_prize": "Təxmini mükafat :",
    "home_picker_title": "Bəxtli nömrələri seçin",
    "home_picker_lead": "Növbəti tiraj üçün nömrələri seçin — cekpot və cədvəli müqayisə etmək üçün lotereyanı dəyişin.",
    "home_select_lottery": "Lotereya seçin",
    "home_results_title": "Son lotereya nəticələri",
    "home_results_lead": "Son qalib nömrələr və əsas uduşlar — hər dərc olunmuş nəticədən sonra yenilənir.",
    "home_view_all": "Hamısına bax",
    "home_results_amount": "Məbləğ :",
    "home_results_draw_date": "Tiraj tarixi :",
    "home_checker_title": "Nömrələrimi yoxla",
    "home_checker_lead": "Nömrələrinizi son dərc olunmuş tirajla müqayisə edin.",
    "home_checker_submit": "Nömrələri yoxla",
    "home_picker_line_hint_before": "Bilet",
    "home_picker_line_hint_after": "%1-dən — başqa sətri redaktə etmək üçün sağdakı sətirə toxunun",
    "home_picker_pick_main": "%1 nömrə seçin",
    "home_picker_pick_bonus": "Bonus seçin",
    "home_picker_quick_pick": "Sürətli seçim",
    "home_picker_clear_all": "Hamısını sil",
    "home_ticket_select_number": "Seçilmiş nömrələr",
    "home_ticket_price": "Bilet qiyməti",
    "home_ticket_price_lines_zero": "(0 sətir × %1)",
    "home_ticket_price_pending": "(%1 sətir %2 gözləyir × %3)",
    "home_ticket_price_one": "(1 sətir × %1)",
    "home_ticket_price_lines": "(%1 sətir × %2)",
    "home_ticket_buy": "Bilet al",
    "home_payment_methods": "Qəbul olunan ödəniş üsulları :",
    "home_ticket_line_title": "Bilet sətri %1",
    "home_checker_aria_main": "Əsas nömrə",
    "home_checker_aria_bonus": "Bonus nömrə",
    "home_checker_err_all": "Bütün nömrələri daxil edin.",
    "home_checker_err_invalid": "Yanlış nömrə.",
    "home_checker_err_range": "%1 nömrəsi diapazondan kənardadır (%2–%3).",
    "home_checker_err_unique": "Əsas nömrələr unikal olmalıdır.",
    "home_checker_no_draw_loaded": "Son tiraj nömrələri hələ yüklənməyib.",
    "home_checker_latest_draw": "Son tiraj (%1): %2",
    "home_checker_latest_draw_no_date": "Son tiraj: %1",
    "home_checker_no_draw_data": "Bu lotereya üçün tiraj məlumatı yoxdur. Növbəti sinxronizasiyadan sonra yenidən cəhd edin.",
    "home_checker_draw_on": " — tiraj %1",
    "home_checker_no_matches": "Qalib nömrələrlə uyğunluq yoxdur.",
    "home_checker_matched_main": "%1 əsas nömrə uyğun gəldi",
    "home_checker_matched_bonus": " və %2 bonus nömrə",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Cekpot nömrələri — rəsmi operatorda təsdiqləyin.",
    "home_checker_all_main_hint": " Bütün əsas nömrələr uyğundur — rəsmi operatorda təsdiqləyin.",
    "home_checker_winning_label": "Qalib: %1",
    "home_picker_stage_complete": "Sətir tamamlandı — başqa sətir əlavə edin və ya bilet alın.",
    "home_picker_main_set": "Əsas nömrələr hazırdır (%1/%2). Aşağıda %3 seçin (%4/%5) — biletdə qırmızı top.",
    "home_picker_selected_main": "%2 əsas nömrədən %1-i seçildi.",
    "home_picker_bonus_fallback": "bonus nömrələr",
},
"13": {
    "home_counter_lotteries": "ট্র্যাক করা লটারি",
    "home_counter_draws": "সর্বশেষ ড্র",
    "home_counter_jackpots": "যুক্ত US জ্যাকপট",
    "home_counter_refresh": "ডেটা রিফ্রেশ",
    "home_how_subtitle": "কীভাবে কাজ করে",
    "home_how_title": "কীভাবে কাজ করে",
    "home_how_lead": "জ্যাকপট তুলনা থেকে নম্বর যাচাই — চারটি সহজ ধাপ।",
    "home_how_step1_title": "বাজেট নির্ধারণ করুন",
    "home_how_step1_text": "লটারি বিনোদন — টিকিটকে বিনvestment নয়, আনন্দের বাজেটের অংশ হিসেবে দেখুন।",
    "home_how_step2_title": "লটারি বেছে নিন",
    "home_how_step2_text": "উপরের ক্যারousel-এ PowerBall, Mega Millions, EuroMillions ও আঞ্চলিক ড্র-এর লাইভ জ্যাকপট তুলনা করুন।",
    "home_how_step3_title": "নম্বর বেছে নিন",
    "home_how_step3_text": "কুইক পিক ব্যবহার করুন বা পিকারে নম্বর চয়ন করুন। অফিসিয়াল অপারেটরে খেলার আগে ড্র শিড्यूল দেখুন।",
    "home_how_step4_title": "ফলাফল যাচাই করুন",
    "home_how_step4_text": "ড্র-এর পর এই পেজে সর্বশেষ ফলাফলের সঙ্গে নম্বর মিলান বা অফিসিয়াল অপারেটরে টিকিট যাচাই করুন।",
    "home_why_subtitle": "কেন PowerBall Jackpot",
    "home_why_title": "আপনার লটারি ফলাফল হাব",
    "home_why_lead": "জ্যাকপট, সাম্প্রতিক ড্র ও নম্বর টুল — অফিসিয়াল অপারেটরে যাওয়ার আগে যা দরকার।",
    "home_why_1_title": "লাইভ জ্যাকপট ও ফলাফল",
    "home_why_1_text": "আনুমানিক জ্যাকপট, সর্বশেষ বিজয়ী নম্বর ও প্রধান US/EU লটারির শিড्यूল এক জায়গায়।",
    "home_why_2_title": "নম্বর যাচাই করুন",
    "home_why_2_text": "পেজের বিল্ট-ইন চেকার দিয়ে শেষ প্রকাশিত ড্র-এর সঙ্গে আপনার পছন্দ মিলান।",
    "home_why_3_title": "পাঁচটি প্রধান গেম",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto ও Lotto America — নিয়ম ও পিকার অন্তর্ভুক্ত।",
    "home_why_4_title": "দায়িত্বশীল খেলা",
    "home_why_4_text": "স্বাধীন গাইড ও অফিসিয়াল অপারেটর লিংক — মজার জন্য খেলুন, বাজেট ঠিক করুন, সম্ভাবনা জানুন।",
    "home_hero_img_alt": "— লটারি জ্যাকপট",
    "home_slider_estimated_prize": "আনুমানিক পুরস্কার :",
    "home_picker_title": "ভাগ্যবান নম্বর বেছে নিন",
    "home_picker_lead": "পরবর্তী ড্র-এর জন্য নম্বর বেছে নিন — জ্যাকপট ও শিড्यूল তুলনায় লটারি বদলান।",
    "home_select_lottery": "লটারি নির্বাচন",
    "home_results_title": "সাম্প্রতিক লটারি ফলাফল",
    "home_results_lead": "সর্বশেষ বিজয়ী নম্বর ও বড় ড্র-এর হাইলাইট — প্রতিটি প্রকাশিত ফলাফলের পর আপডেট।",
    "home_view_all": "সব দেখুন",
    "home_results_amount": "পরিমাণ :",
    "home_results_draw_date": "ড্র হয়েছিল :",
    "home_checker_title": "আমার নম্বর যাচাই",
    "home_checker_lead": "শেষ প্রকাশিত ড্র-এর সঙ্গে নম্বর মিলান।",
    "home_checker_submit": "নম্বর যাচাই",
    "home_picker_line_hint_before": "টিকিট",
    "home_picker_line_hint_after": "%1-এর মধ্যে — অন্য লাইন সম্পাদনায় ডানে সারিতে ট্যাপ করুন",
    "home_picker_pick_main": "%1টি নম্বর বেছে নিন",
    "home_picker_pick_bonus": "বোনাস বেছে নিন",
    "home_picker_quick_pick": "কুইক পিক",
    "home_picker_clear_all": "সব মুছুন",
    "home_ticket_select_number": "নির্বাচিত নম্বর",
    "home_ticket_price": "টিকিটের দাম",
    "home_ticket_price_lines_zero": "(0 লাইন × %1)",
    "home_ticket_price_pending": "(%1 লাইন %2-এর জন্য অপেক্ষা × %3)",
    "home_ticket_price_one": "(1 লাইন × %1)",
    "home_ticket_price_lines": "(%1 লাইন × %2)",
    "home_ticket_buy": "টিকিট কিনুন",
    "home_payment_methods": "গ্রহণযোগ্য পেমেন্ট পদ্ধতি :",
    "home_ticket_line_title": "টিকিট লাইন %1",
    "home_checker_aria_main": "মূল নম্বর",
    "home_checker_aria_bonus": "বোনাস নম্বর",
    "home_checker_err_all": "সব নম্বর লিখুন।",
    "home_checker_err_invalid": "অবৈধ নম্বর।",
    "home_checker_err_range": "নম্বর %1 সীমার বাইরে (%2–%3)।",
    "home_checker_err_unique": "মূল নম্বরগুলো অনন্য হতে হবে।",
    "home_checker_no_draw_loaded": "সর্বশেষ ড্র-এর নম্বর এখনো লোড হয়নি।",
    "home_checker_latest_draw": "সর্বশেষ ড্র (%1): %2",
    "home_checker_latest_draw_no_date": "সর্বশেষ ড্র: %1",
    "home_checker_no_draw_data": "এই লটারির জন্য ড্র ডেটা নেই। পরবর্তী সিঙ্কের পর আবার চেষ্টা করুন।",
    "home_checker_draw_on": " — ড্র %1",
    "home_checker_no_matches": "বিজয়ী নম্বরের সঙ্গে মিল নেই।",
    "home_checker_matched_main": "আপনার %1টি মূল নম্বর মিলেছে",
    "home_checker_matched_bonus": " এবং %2টি বোনাস নম্বর",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " জ্যাকপট নম্বর — অফিসিয়াল অপারেটরে যাচাই করুন।",
    "home_checker_all_main_hint": " সব মূল নম্বর মিলেছে — অফিসিয়াল অপারেটরে যাচাই করুন।",
    "home_checker_winning_label": "বিজয়ী: %1",
    "home_picker_stage_complete": "লাইন সম্পূর্ণ — আরেকটি লাইন যোগ করুন বা টিকিট কিনুন।",
    "home_picker_main_set": "মূল নম্বর সেট (%1/%2). নিচে %3 বেছে নিন (%4/%5) — টিকিট প্যানেলে লাল বল।",
    "home_picker_selected_main": "%2টি মূল নম্বরের মধ্যে %1টি নির্বাচিত।",
    "home_picker_bonus_fallback": "বোনাস নম্বর",
},
"17": {
    "home_counter_lotteries": "Xổ số đang theo dõi",
    "home_counter_draws": "Kỳ quay mới nhất",
    "home_counter_jackpots": "Tổng jackpot Mỹ",
    "home_counter_refresh": "Làm mới dữ liệu",
    "home_how_subtitle": "Cách hoạt động",
    "home_how_title": "Cách hoạt động",
    "home_how_lead": "Từ so sánh jackpot đến kiểm tra số — bốn bước đơn giản.",
    "home_how_step1_title": "Đặt ngân sách",
    "home_how_step1_text": "Xổ số là giải trí — coi vé là phần ngân sách vui chơi, không phải đầu tư.",
    "home_how_step2_title": "Chọn xổ số",
    "home_how_step2_text": "So sánh jackpot trực tiếp của PowerBall, Mega Millions, EuroMillions và các kỳ quay khu vực ở carousel phía trên.",
    "home_how_step3_title": "Chọn số",
    "home_how_step3_text": "Dùng chọn nhanh hoặc chọn số trong bộ chọn. Xem lịch quay trước khi chơi với nhà vận hành chính thức.",
    "home_how_step4_title": "Kiểm tra kết quả",
    "home_how_step4_text": "Sau khi quay, so sánh số với kết quả mới nhất trên trang này hoặc xác minh vé với nhà vận hành chính thức.",
    "home_why_subtitle": "Vì sao PowerBall Jackpot",
    "home_why_title": "Trung tâm kết quả xổ số của bạn",
    "home_why_lead": "Jackpot, kỳ quay gần đây và công cụ số — mọi thứ bạn cần trước khi đến nhà vận hành chính thức.",
    "home_why_1_title": "Jackpot và kết quả trực tiếp",
    "home_why_1_text": "Jackpot ước tính, số trúng mới nhất và lịch các xổ số lớn Mỹ/EU tại một nơi.",
    "home_why_2_title": "Kiểm tra số của bạn",
    "home_why_2_text": "So sánh lựa chọn với kỳ quay mới công bố qua công cụ kiểm tra trên trang.",
    "home_why_3_title": "Năm trò chơi lớn",
    "home_why_3_text": "PowerBall, Mega Millions, EuroMillions, Florida Lotto và Lotto America — quy tắc và bộ chọn tích hợp.",
    "home_why_4_title": "Chơi có trách nhiệm",
    "home_why_4_text": "Hướng dẫn độc lập và liên kết nhà vận hành chính thức — chơi vì niềm vui, đặt ngân sách, biết xác suất.",
    "home_hero_img_alt": "— jackpot xổ số",
    "home_slider_estimated_prize": "Giải ước tính :",
    "home_picker_title": "Chọn số may mắn",
    "home_picker_lead": "Chọn số cho kỳ quay tiếp theo — đổi xổ số để so sánh jackpot và lịch.",
    "home_select_lottery": "Chọn xổ số",
    "home_results_title": "Kết quả xổ số gần đây",
    "home_results_lead": "Số trúng mới nhất và điểm nổi bật từ các kỳ quay lớn — cập nhật sau mỗi kết quả công bố.",
    "home_view_all": "Xem tất cả",
    "home_results_amount": "Số tiền :",
    "home_results_draw_date": "Kỳ quay diễn ra :",
    "home_checker_title": "Kiểm tra số của tôi",
    "home_checker_lead": "So sánh số của bạn với kỳ quay mới công bố.",
    "home_checker_submit": "Kiểm tra số",
    "home_picker_line_hint_before": "Vé",
    "home_picker_line_hint_after": "trên %1 — chạm hàng bên phải để sửa hàng khác",
    "home_picker_pick_main": "Chọn %1 số",
    "home_picker_pick_bonus": "Chọn bonus",
    "home_picker_quick_pick": "Chọn nhanh",
    "home_picker_clear_all": "Xóa tất cả",
    "home_ticket_select_number": "Số đã chọn",
    "home_ticket_price": "Giá vé",
    "home_ticket_price_lines_zero": "(0 dòng × %1)",
    "home_ticket_price_pending": "(%1 dòng đang chờ %2 × %3)",
    "home_ticket_price_one": "(1 dòng × %1)",
    "home_ticket_price_lines": "(%1 dòng × %2)",
    "home_ticket_buy": "Mua vé",
    "home_payment_methods": "Phương thức thanh toán chấp nhận :",
    "home_ticket_line_title": "Dòng vé %1",
    "home_checker_aria_main": "Số chính",
    "home_checker_aria_bonus": "Số bonus",
    "home_checker_err_all": "Nhập đủ tất cả số.",
    "home_checker_err_invalid": "Số không hợp lệ.",
    "home_checker_err_range": "Số %1 ngoài phạm vi (%2–%3).",
    "home_checker_err_unique": "Các số chính phải khác nhau.",
    "home_checker_no_draw_loaded": "Số kỳ quay mới nhất chưa được tải.",
    "home_checker_latest_draw": "Kỳ quay mới nhất (%1): %2",
    "home_checker_latest_draw_no_date": "Kỳ quay mới nhất: %1",
    "home_checker_no_draw_data": "Không có dữ liệu quay cho xổ số này. Thử lại sau lần đồng bộ tiếp theo.",
    "home_checker_draw_on": " — kỳ quay %1",
    "home_checker_no_matches": "Không trùng với số trúng.",
    "home_checker_matched_main": "Bạn trùng %1 số chính",
    "home_checker_matched_bonus": " và %2 số bonus",
    "home_checker_matched_end": ".",
    "home_checker_jackpot_hint": " Số jackpot — xác minh với nhà vận hành chính thức.",
    "home_checker_all_main_hint": " Tất cả số chính trùng — xác minh với nhà vận hành chính thức.",
    "home_checker_winning_label": "Trúng: %1",
    "home_picker_stage_complete": "Dòng đã đủ — thêm dòng khác hoặc mua vé.",
    "home_picker_main_set": "Đã chọn số chính (%1/%2). Chọn %3 bên dưới (%4/%5) — bóng đỏ trên bảng vé.",
    "home_picker_selected_main": "Đã chọn %1 trên %2 số chính.",
    "home_picker_bonus_fallback": "số bonus",
},
}
# fmt: on

def main() -> None:
    OUT.write_text(json.dumps(PATCHES, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} — locales: {sorted(PATCHES.keys())}, keys per locale: {len(next(iter(PATCHES.values())))}")


if __name__ == "__main__":
    main()
