# -*- coding: utf-8 -*-
"""Native-quality overrides for casino_articles#25 — FR, DE, ES, RU."""

FR = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "À propos de Jack-Pot",
    "img_hero_alt": "Lobby du casino en ligne Jack-Pot et aperçu de Chicken Road",
    "about_paras": [
        "Jack-Pot est une plateforme en ligne où jeux de casino et paris sportifs sont accessibles avec un seul compte. Le site propose des sections claires : casino, live, sport, promos, paiements, tournois et cashback. Pour l'utilisateur, il est facile de savoir où aller. La plateforme reste assez simple. Le casino est divisé en catégories. Vous pouvez aussi utiliser les sections principales si vous savez déjà ce que vous voulez jouer.",
        "Chicken Road convient bien à Jack-Pot, car c'est exactement le type de jeu qui a besoin d'un accès rapide. Personne ne veut fouiller un immense lobby pour trouver un jeu arcade rapide. Vous l'ouvrez, réglez la mise, choisissez le niveau de risque et le tour commence. Pour Chicken Road, l'avantage principal de Jack-Pot est le chemin direct vers le jeu : lobby rapide, barre de recherche, accès mobile et mise en page qui ne gêne pas. C'est suffisant pour un jeu basé sur des tours courts et des décisions rapides.",
        "Jack-Pot propose aussi des bonus et des promos. Avant de jouer, consultez la section promotion. N'activez rien sans lire les conditions. Les bonus peuvent être limités dans le temps ou par des règles.",
    ],
    "h2_where": "Où trouver Chicken Road sur Jack-Pot",
    "where_paras": [
        "Chicken Road est facile à trouver sur Jack-Pot si vous savez où chercher. Ouvrez la section casino et allez dans Slots ou Crash Games. La plupart des jeux arcade rapides se trouvent généralement dans ces catégories.",
        "Le moyen le plus rapide est la recherche. Tapez Chicken Road dans la barre de recherche, attendez que la bannière du jeu apparaisse et ouvrez-la. Le jeu devrait se lancer dans une fenêtre séparée.",
        "Vous pouvez aussi chercher par fournisseur. Entrez InOut et Jack-Pot devrait afficher les jeux de ce studio. Cela aide si vous voulez trouver non seulement Chicken Road, mais aussi d'autres titres InOut.",
        "Parfois le jeu apparaît aussi dans Crash Games, où les plateformes placent souvent les jeux instantanés, les crash games et les titres qui ne rentrent pas dans les catégories de slots classiques.",
    ],
    "short_path_title": "Le chemin le plus court est simple :",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": [
        "Si le jeu n'apparaît pas par son nom, essayez de chercher InOut à la place.",
    ],
    "h2_play": "Comment jouer à Chicken Road sur Jack-Pot",
    "play_paras": [
        "Chicken Road sur Jack-Pot est facile à lancer. Si vous débutez, commencez avec Easy. Cela laisse plus de marge pour comprendre le jeu. Medium est déjà plus vif. Hard et Hardcore conviennent mieux aux joueurs qui savent à quelle vitesse une balance peut disparaître dans ce type de jeu. Avant d'appuyer sur Play, revérifiez la mise. Surtout sur téléphone. Un tap trop rapide peut lancer le tour avec le mauvais montant.",
        "Le bouton principal est Cash Out. Appuyez quand le multiplicateur actuel vous convient et que vous voulez vous arrêter. Si vous attendez trop longtemps et que le tour tourne mal, la mise est perdue.",
        "S'il s'agit du Chicken Road original d'InOut Games, les règles de base restent les mêmes sur Jack-Pot que sur d'autres plateformes : avancer, faire monter le multiplicateur, Cash Out avant de perdre le tour.",
    ],
    "h2_demo": "Démo et jeu en argent réel sur Jack-Pot",
    "demo_paras": [
        "La démo Chicken Road est disponible sur Jack-Pot, et c'est par là que je commencerais. Pas parce que la démo apprend à gagner — elle ne le fait pas. Mais elle permet de voir le jeu sans pression.",
        "En mode démo, vous jouez avec un solde virtuel. Vous pouvez changer la difficulté, tester différentes mises, faire avancer la poule sur la route et essayer de Cash Out à différents moments. Si le tour se passe mal, votre argent réel n'est pas touché. Le mode argent réel se ressent différemment. Le jeu peut avoir la même apparence, les mêmes boutons et le multiplicateur monte de la même façon. Mais dès que votre propre solde est en jeu, chaque pas pèse plus lourd.",
        "En démo, les gens jouent souvent beaucoup plus librement. Le solde est virtuel, donc tester des modes plus durs ou aller un peu plus loin ne fait pas vraiment mal.",
        "Avec de l'argent réel, le même geste change tout. Même bouton, même multiplicateur, même route — mais la mise est la vôtre. Certains Cash Out trop tôt par peur de perdre. D'autres vont trop loin pour récupérer le tour précédent. C'est là que la pression commence. Utilisez donc la démo sur Jack-Pot d'abord. Apprenez le jeu là. Le jeu en argent réel n'a de sens que quand vous comprenez la mécanique et acceptez le risque.",
    ],
    "h2_mobile": "Chicken Road sur mobile via Jack-Pot",
    "mobile_paras": [
        "Chicken Road fonctionne bien sur téléphone. Ouvrez Jack-Pot, trouvez le jeu, réglez la mise et lancez le tour sans interface lourde. Sur mobile, la mise en page se resserre. Le champ de mise, Play et Cash Out restent faciles d'accès, ce qui compte dans ce jeu. Vous ne voulez pas chercher le bouton de sortie quand le multiplicateur bouge déjà.",
        "Les tours sont courts, donc le mobile convient bien. Une session normale ne prend que quelques taps. Ouvrez le tour, avancez la poule, surveillez le multiplicateur et partez quand la prochaine étape commence à paraître trop risquée.",
        "La vitesse dépend surtout de l'appareil et de la connexion. Un téléphone récent avec une connexion stable sera plus fluide. Un vieux navigateur ou un signal faible peut ralentir l'écran. Et comme l'affichage est petit, vérifiez toujours la mise avant Play — un tap imprudent suffit pour lancer avec le mauvais montant. Jouez via le navigateur. Évitez les APK aléatoires de sites inconnus, surtout ceux qui promettent des prédicteurs, des hacks ou une version « spéciale » de Chicken Road.",
    ],
    "h2_final": "Conclusion",
    "final_paras": [
        "Chicken Road convient bien à Jack-Pot car le jeu n'a pas besoin d'une configuration compliquée. Ouvrez le casino, trouvez le titre, choisissez le mode, réglez la mise et le tour commence. Pour ce type de jeu rapide, c'est exactement ce qu'on veut.",
        "L'attrait principal est simple : tours courts, boutons clairs, multiplicateur qui monte et choix constant — prendre le résultat actuel ou risquer un pas de plus. Facile à comprendre, mais le jeu peut vite vous accrocher.",
        "Jack-Pot offre à Chicken Road un endroit propre pour jouer, surtout depuis le mobile. La recherche fonctionne, le lobby n'est pas trop lourd et le mode démo est utile pour tester la mécanique d'abord.",
        "Chicken Road n'est pas un outil pour gagner de l'argent. C'est un jeu de casino avec un vrai risque. Utilisez la démo avant l'argent réel, fixez des limites, ne courez pas après les pertes et traitez chaque tour comme du divertissement, pas comme un revenu.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Qu'est-ce que Jack-Pot ?", "Jack-Pot est une plateforme de casino en ligne et de paris sportifs. Vous pouvez jouer aux slots, au live casino, aux jeux instantanés, aux crash games et aux paris sportifs."],
        ["Jack-Pot est-il réservé au casino ?", "Non. Le casino n'est qu'une partie de la plateforme."],
        ["L'inscription est-elle rapide ?", "L'inscription prend moins d'une minute. Ensuite, le site peut proposer un choix de bonus ou ouvrir la fenêtre de dépôt."],
        ["Jack-Pot propose-t-il des bonus ?", "Oui, mais consultez le site officiel pour voir les bonus actuellement disponibles."],
        ["Puis-je trouver Chicken Road sur Jack-Pot ?", "Oui, si Chicken Road est disponible dans le lobby Jack-Pot. Cherchez d'abord par le nom du jeu. Si rien n'apparaît, essayez le fournisseur : InOut."],
        ["Jack-Pot fonctionne-t-il sur mobile ?", "Oui, Jack-Pot s'ouvre sur mobile via le navigateur. Lobby casino, bookmaker, caisse et compte sont utilisables depuis un téléphone. La vitesse dépend de l'appareil et de la connexion. Un signal faible ou un vieux navigateur peut ralentir certains jeux."],
        ["Jack-Pot est-il sûr ?", "Oui, mais assurez-vous d'être sur le vrai domaine Jack-Pot. Les copies frauduleuses peuvent ressembler de très près au site original."],
        ["Quelle licence Jack-Pot possède-t-il ?", "D'après les informations que nous avons consultées, Jack-Pot opère avec une licence offshore d'Anjouan. C'est une licence légale, souvent utilisée par les marques de casino plus récentes. Ce n'est toutefois pas le même niveau de protection que des régulateurs plus stricts. La réputation, l'historique des paiements et la qualité du support comptent donc beaucoup."],
        ["Jack-Pot demandera-t-il des documents ?", "Très probablement avant un retrait, oui. Envoyez les documents uniquement via le site officiel Jack-Pot."],
        ["Les retraits sont-ils instantanés ?", "Pas toujours. Les petits retraits peuvent être plus rapides. Les gros paiements peuvent prendre plus de temps à cause de la vérification, des limites du prestataire ou de contrôles manuels."],
        ["Jouer sur Jack-Pot est-il risqué ?", "Oui. Slots, crash games, live casino et paris sportifs comportent tous un risque. Vous pouvez perdre de l'argent. Utilisez des limites, ne courez pas après les pertes et ne traitez pas Jack-Pot comme un moyen de gagner. C'est du divertissement de jeu, pas un revenu."],
    ],
}

DE = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Über Jack-Pot",
    "img_hero_alt": "Jack-Pot Online-Casino-Lobby und Chicken-Road-Überblick",
    "about_paras": [
        "Jack-Pot ist eine Online-Plattform, auf der Casino-Spiele und Sportwetten mit einem Konto verfügbar sind. Die Seite hat klare Bereiche: Casino, Live, Sport, Promos, Zahlungen, Turniere und Cashback. Für Nutzer ist es leicht, den richtigen Weg zu finden. Die Plattform wirkt einfach genug. Das Casino ist in Kategorien unterteilt. Sie können auch die Hauptbereiche nutzen, wenn Sie schon wissen, was Sie spielen möchten.",
        "Chicken Road passt gut zu Jack-Pot, weil es genau die Art Spiel ist, die schnellen Zugang braucht. Niemand will durch ein riesiges Lobby-Menü wühlen, nur um ein schnelles Arcade-Spiel zu finden. Sie öffnen es, setzen den Einsatz, wählen das Risikoniveau und die Runde startet. Für Chicken Road ist der Hauptvorteil von Jack-Pot der klare Weg zum Spiel: schnelles Lobby, Suchleiste, mobiler Zugang und ein Layout, das nicht im Weg steht. Das reicht für ein Spiel mit kurzen Runden und schnellen Entscheidungen.",
        "Jack-Pot hat auch Boni und Promos. Schauen Sie vor dem Spielen in den Promotionsbereich. Aktivieren Sie nichts blind. Boni können zeitlich oder durch Regeln begrenzt sein.",
    ],
    "h2_where": "Wo Sie Chicken Road auf Jack-Pot finden",
    "where_paras": [
        "Chicken Road ist auf Jack-Pot leicht zu finden, wenn Sie wissen, wo Sie suchen müssen. Öffnen Sie den Casino-Bereich und gehen Sie zu Slots oder Crash Games. Die meisten schnellen Arcade-Spiele liegen meist in diesen Kategorien.",
        "Am schnellsten geht es über die Suche. Tippen Sie Chicken Road in die Suchleiste, warten Sie auf das Spielbanner und öffnen Sie es. Das Spiel sollte in einem separaten Fenster starten.",
        "Sie können auch nach Anbieter suchen. Geben Sie InOut ein und Jack-Pot zeigt Spiele dieses Studios. Das hilft, wenn Sie nicht nur Chicken Road, sondern auch andere InOut-Titel finden möchten.",
        "Manchmal erscheint das Spiel auch unter Crash Games, wo Plattformen oft Instant Games, Crash Games und Titel platzieren, die nicht in klassische Slot-Kategorien passen.",
    ],
    "short_path_title": "Der kurze Weg ist einfach:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": [
        "Wenn das Spiel nicht unter dem Namen erscheint, suchen Sie stattdessen nach InOut.",
    ],
    "h2_play": "Wie man Chicken Road auf Jack-Pot spielt",
    "play_paras": [
        "Chicken Road auf Jack-Pot ist leicht zu starten. Wenn Sie neu sind, beginnen Sie mit Easy. Das gibt mehr Raum, das Spiel zu verstehen. Medium fühlt sich schon schärfer an. Hard und Hardcore sind besser für Spieler, die wissen, wie schnell ein Guthaben in diesem Spieltyp verschwinden kann. Bevor Sie Play drücken, prüfen Sie den Einsatz noch einmal. Besonders am Handy. Ein hastiger Tap kann die Runde mit dem falschen Betrag starten.",
        "Der Hauptbutton ist Cash Out. Drücken Sie ihn, wenn der aktuelle Multiplikator reicht und Sie stoppen wollen. Warten Sie zu lange und die Runde läuft schief, ist der Einsatz weg.",
        "Wenn es das originale Chicken Road von InOut Games ist, bleiben die Grundregeln auf Jack-Pot wie auf anderen Plattformen: vorwärts gehen, Multiplikator wachsen lassen, Cash Out bevor die Runde verloren geht.",
    ],
    "h2_demo": "Demo und Echtgeld-Spiel auf Jack-Pot",
    "demo_paras": [
        "Die Chicken-Road-Demo ist auf Jack-Pot verfügbar, und dort würde ich anfangen. Nicht weil die Demo zeigt, wie man gewinnt — das tut sie nicht. Aber sie lässt Sie das Spiel ohne Druck sehen.",
        "Im Demo-Modus spielen Sie mit virtuellem Guthaben. Sie können die Schwierigkeit wechseln, verschiedene Einsätze testen, das Huhn auf der Straße bewegen und Cash Out an verschiedenen Punkten versuchen. Geht die Runde schief, passiert nichts mit Ihrem echten Geld. Echtgeld fühlt sich anders an. Das Spiel sieht gleich aus, die Buttons sind gleich und der Multiplikator wächst gleich. Aber sobald Ihr eigenes Guthaben im Spiel ist, fühlt sich jeder Schritt schwerer an.",
        "Im Demo-Modus spielen die meisten deutlich lockerer. Das Guthaben ist virtuell, also tut es nicht weh, härtere Modi zu testen oder ein paar Schritte weiter zu gehen.",
        "Mit echtem Geld fühlt sich dieselbe Bewegung anders an. Gleicher Button, gleicher Multiplikator, gleiche Straße — aber der Einsatz ist Ihrer. Manche cashen zu früh aus, weil sie nicht verlieren wollen. Andere gehen zu weit, um die letzte Runde zurückzuholen. Dort beginnt der Druck. Nutzen Sie also zuerst die Demo auf Jack-Pot. Lernen Sie das Spiel dort. Echtgeld macht nur Sinn, wenn Sie die Mechanik verstehen und das Risiko akzeptieren.",
    ],
    "h2_mobile": "Chicken Road mobil über Jack-Pot",
    "mobile_paras": [
        "Chicken Road funktioniert gut am Handy. Öffnen Sie Jack-Pot, finden Sie das Spiel, setzen Sie den Einsatz und starten Sie die Runde ohne schwere Oberfläche. Mobil wird das Layout enger. Einsatzfeld, Play und Cash Out bleiben gut erreichbar — wichtig in diesem Spiel. Sie wollen nicht nach dem Ausstiegsbutton suchen, wenn der Multiplikator schon läuft.",
        "Die Runden sind kurz, also passt Mobil gut. Eine normale Session braucht nur wenige Taps. Runde öffnen, Huhn bewegen, Multiplikator im Blick behalten und gehen, wenn der nächste Schritt zu riskant wirkt.",
        "Die Geschwindigkeit hängt vor allem von Gerät und Verbindung ab. Ein neues Handy mit stabilem Internet fühlt sich flüssiger an. Ein alter Browser oder schwaches Signal kann den Bildschirm träger machen. Und weil das Display klein ist, prüfen Sie immer den Einsatz vor Play — ein unachtsamer Tap reicht, um mit dem falschen Betrag zu starten. Spielen Sie über den Browser. Vermeiden Sie zufällige APKs von unbekannten Seiten, besonders solche mit Predictors, Hacks oder einer „speziellen“ Chicken-Road-Version.",
    ],
    "h2_final": "Fazit",
    "final_paras": [
        "Chicken Road passt gut zu Jack-Pot, weil das Spiel keine komplizierte Einrichtung braucht. Casino öffnen, Titel finden, Modus wählen, Einsatz setzen — die Runde startet. Für diesen schnellen Spieltyp ist das genau richtig.",
        "Der Hauptreiz ist einfach: kurze Runden, klare Buttons, wachsender Multiplikator und die ständige Wahl — aktuelles Ergebnis nehmen oder einen Schritt mehr riskieren. Leicht zu verstehen, aber das Spiel kann schnell ziehen.",
        "Jack-Pot gibt Chicken Road einen sauberen Platz zum Spielen, besonders mobil. Die Suche funktioniert, das Lobby ist nicht zu schwer und der Demo-Modus ist nützlich, um die Mechanik zuerst zu testen.",
        "Chicken Road ist kein Geldverdienst-Tool. Es ist ein Casino-Spiel mit echtem Risiko. Nutzen Sie die Demo vor Echtgeld, setzen Sie Limits, jagen Sie Verlusten nicht nach und behandeln Sie jede Runde als Unterhaltung, nicht als Einkommen.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Was ist Jack-Pot?", "Jack-Pot ist eine Online-Casino- und Sportwetten-Plattform. Sie können Slots, Live Casino, Instant Games, Crash Games und Sportwetten spielen."],
        ["Ist Jack-Pot nur für Casino-Spiele?", "Nein. Casino ist nur ein Teil der Plattform."],
        ["Wie schnell ist die Registrierung?", "Die Registrierung dauert weniger als eine Minute. Danach kann die Seite eine Bonuswahl zeigen oder das Einzahlungsfenster öffnen."],
        ["Bietet Jack-Pot Boni?", "Ja, aber schauen Sie auf der offiziellen Website, welche aktuellen Boni verfügbar sind."],
        ["Finde ich Chicken Road auf Jack-Pot?", "Ja, wenn Chicken Road im Jack-Pot-Spiel-Lobby verfügbar ist. Suchen Sie zuerst nach dem Spielnamen. Wenn nichts erscheint, versuchen Sie den Anbieter: InOut."],
        ["Funktioniert Jack-Pot mobil?", "Ja, Jack-Pot öffnet sich mobil über den Browser. Casino-Lobby, Sportwetten, Kasse und Konto sind vom Handy nutzbar. Die Geschwindigkeit hängt von Gerät und Verbindung ab. Schwaches Signal oder alter Browser kann Spiele langsamer laden."],
        ["Ist Jack-Pot sicher?", "Ja, aber stellen Sie sicher, dass Sie auf der echten Jack-Pot-Domain sind. Gefälschte Casino-Kopien können dem Original sehr ähnlich sehen."],
        ["Welche Lizenz hat Jack-Pot?", "Nach den Informationen, die wir zuvor geprüft haben, operiert Jack-Pot mit einer Offshore-Lizenz aus Anjouan. Das ist eine legale Lizenz, oft von neueren Casino-Marken genutzt. Sie bietet jedoch nicht denselben Spielerschutz wie strengere Regulatoren. Reputation, Zahlungshistorie und Support-Qualität sind hier wichtig."],
        ["Fragt Jack-Pot nach Dokumenten?", "Sehr wahrscheinlich vor einer Auszahlung, ja. Laden Sie Dokumente nur über die offizielle Jack-Pot-Website hoch."],
        ["Sind Auszahlungen sofort?", "Nicht immer. Kleine Auszahlungen können schneller sein. Größere Auszahlungen können länger dauern wegen Verifizierung, Zahlungsanbieter-Limits oder manueller Prüfungen."],
        ["Ist Spielen auf Jack-Pot riskant?", "Ja. Slots, Crash Games, Live Casino und Sportwetten bergen alle Risiko. Sie können Geld verlieren. Nutzen Sie Limits, jagen Sie Verlusten nicht nach und behandeln Sie Jack-Pot nicht als Verdienstmöglichkeit. Es ist Glücksspiel-Unterhaltung, kein Einkommen."],
    ],
}

ES = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Sobre Jack-Pot",
    "img_hero_alt": "Lobby del casino online Jack-Pot y vista general de Chicken Road",
    "about_paras": [
        "Jack-Pot es una plataforma online donde casino y apuestas deportivas están disponibles con una sola cuenta. El sitio tiene secciones claras: casino, live, deportes, promos, pagos, torneos y cashback. Para el usuario es fácil elegir a dónde ir. La plataforma se siente bastante simple. El casino está dividido en categorías. También puedes usar las secciones principales si ya sabes qué quieres jugar.",
        "Chicken Road encaja bien en Jack-Pot porque es exactamente el tipo de juego que necesita acceso rápido. Nadie quiere buscar en un lobby enorme para encontrar un juego arcade veloz. Lo abres, pones la apuesta, eliges el nivel de riesgo y la ronda empieza. Para Chicken Road, la ventaja principal de Jack-Pot es el camino limpio al juego: lobby rápido, barra de búsqueda, acceso móvil y un diseño que no estorba. Eso basta para un juego de rondas cortas y decisiones rápidas.",
        "Jack-Pot también tiene bonos y promos, así que conviene revisar la sección de promociones antes de jugar. No actives nada a ciegas. Los bonos pueden estar limitados por tiempo o por reglas.",
    ],
    "h2_where": "Dónde encontrar Chicken Road en Jack-Pot",
    "where_paras": [
        "Chicken Road es fácil de encontrar en Jack-Pot si sabes dónde mirar. Abre la sección casino y ve a Slots o Crash Games. La mayoría de juegos arcade rápidos suelen estar en estas categorías.",
        "La forma más rápida es la búsqueda. Escribe Chicken Road en la barra, espera a que aparezca el banner del juego y ábrelo. El juego debería lanzarse en una ventana aparte.",
        "También puedes buscar por proveedor. Escribe InOut y Jack-Pot debería mostrar juegos de este estudio. Ayuda si quieres encontrar no solo Chicken Road, sino otros títulos de InOut.",
        "A veces el juego también aparece en Crash Games, donde las plataformas suelen colocar juegos instantáneos, crash games y títulos que no encajan en categorías clásicas de slots.",
    ],
    "short_path_title": "El camino corto es simple:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": [
        "Si el juego no aparece por nombre, prueba buscar InOut en su lugar.",
    ],
    "h2_play": "Cómo jugar Chicken Road en Jack-Pot",
    "play_paras": [
        "Chicken Road en Jack-Pot es fácil de empezar. Si eres nuevo, empieza con Easy. Da más margen para entender el juego. Medium ya se siente más intenso. Hard y Hardcore son mejores para jugadores que saben lo rápido que puede desaparecer el saldo en este tipo de juego. Antes de pulsar Play, revisa la apuesta otra vez. Especialmente en el móvil. Un toque apresurado puede iniciar la ronda con el monto equivocado.",
        "El botón principal es Cash Out. Pulsa cuando el multiplicador actual te baste y quieras parar. Si esperas demasiado y la ronda sale mal, se pierde la apuesta.",
        "Si es el Chicken Road original de InOut Games, las reglas básicas son las mismas en Jack-Pot que en otras plataformas: avanzar, hacer crecer el multiplicador, Cash Out antes de perder la ronda.",
    ],
    "h2_demo": "Demo y juego con dinero real en Jack-Pot",
    "demo_paras": [
        "La demo de Chicken Road está disponible en Jack-Pot, y por ahí empezaría yo. No porque la demo enseñe a ganar — no lo hace. Pero te deja ver el juego sin presión.",
        "En modo demo juegas con saldo virtual. Puedes cambiar la dificultad, probar distintas apuestas, mover el pollo por la carretera y probar Cash Out en distintos puntos. Si la ronda sale mal, no pasa nada con tu dinero real. El modo real se siente distinto. El juego puede verse igual, los botones iguales y el multiplicador crece igual. Pero cuando entra tu propio saldo, cada paso pesa más.",
        "En demo la gente suele jugar mucho más suelto. El saldo es virtual, así que no duele probar modos más duros o ir un poco más lejos.",
        "Con dinero real, el mismo movimiento se siente distinto. Mismo botón, mismo multiplicador, misma carretera — pero la apuesta es tuya. Algunos hacen Cash Out demasiado pronto por miedo a perder. Otros van demasiado lejos para recuperar la ronda anterior. Ahí empieza la presión. Usa primero la demo en Jack-Pot. Aprende el juego ahí. El juego real solo tiene sentido cuando entiendes la mecánica y aceptas el riesgo.",
    ],
    "h2_mobile": "Chicken Road en móvil vía Jack-Pot",
    "mobile_paras": [
        "Chicken Road funciona bien en el teléfono. Abre Jack-Pot, encuentra el juego, pon la apuesta y empieza la ronda sin una interfaz pesada. En móvil el diseño se compacta. El campo de apuesta, Play y Cash Out siguen fáciles de alcanzar, lo cual importa en este juego. No quieres buscar el botón de salida cuando el multiplicador ya se mueve.",
        "Las rondas son cortas, así que el móvil encaja bien. Una sesión normal son solo unos toques. Abre la ronda, mueve el pollo, vigila el multiplicador y sal cuando el siguiente paso empiece a sentirse demasiado arriesgado.",
        "La velocidad depende sobre todo del dispositivo y la conexión. Un móvil nuevo con internet estable se siente más fluido. Un navegador viejo o señal débil puede hacer que la pantalla responda más lento. Y como la pantalla es pequeña, revisa siempre la apuesta antes de Play — un toque descuidado basta para empezar con el monto equivocado. Juega por el navegador. Evita APK aleatorios de sitios desconocidos, sobre todo los que prometen predictores, hacks o una versión «especial» de Chicken Road.",
    ],
    "h2_final": "Conclusión",
    "final_paras": [
        "Chicken Road encaja bien en Jack-Pot porque el juego no necesita una configuración complicada. Abre el casino, encuentra el título, elige el modo, pon la apuesta y la ronda empieza. Para este tipo de juego rápido, eso es justo lo que quieres.",
        "El atractivo principal es simple: rondas cortas, botones claros, multiplicador creciente y la elección constante — tomar el resultado actual o arriesgar un paso más. Fácil de entender, pero el juego puede engancharte rápido.",
        "Jack-Pot da a Chicken Road un lugar limpio para jugar, especialmente desde el móvil. La búsqueda funciona, el lobby no es pesado y el modo demo es útil para probar la mecánica primero.",
        "Chicken Road no es una herramienta para ganar dinero. Es un juego de casino con riesgo real. Usa la demo antes del dinero real, pon límites, no persigas pérdidas y trata cada ronda como entretenimiento, no como ingreso.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["¿Qué es Jack-Pot?", "Jack-Pot es una plataforma de casino online y apuestas deportivas. Puedes jugar slots, live casino, juegos instantáneos, crash games y apuestas deportivas."],
        ["¿Jack-Pot es solo para casino?", "No. El casino es solo una parte de la plataforma."],
        ["¿Qué tan rápido es el registro?", "El registro tarda menos de un minuto. Después el sitio puede mostrar una elección de bono o abrir la ventana de depósito."],
        ["¿Jack-Pot ofrece bonos?", "Sí, pero ve al sitio oficial para ver qué bonos actuales hay para los jugadores."],
        ["¿Puedo encontrar Chicken Road en Jack-Pot?", "Sí, si Chicken Road está disponible en el lobby de Jack-Pot. Busca primero por el nombre del juego. Si no aparece nada, prueba el proveedor: InOut."],
        ["¿Jack-Pot funciona en móvil?", "Sí, Jack-Pot se abre en móvil por el navegador. Lobby de casino, deportes, caja y cuenta son usables desde el teléfono. La velocidad depende del dispositivo y la conexión. Señal débil o navegador viejo puede hacer que algunos juegos carguen más lento."],
        ["¿Es seguro usar Jack-Pot?", "Sí, pero asegúrate de estar en el dominio real de Jack-Pot. Las copias falsas pueden parecerse mucho al sitio original."],
        ["¿Qué licencia tiene Jack-Pot?", "Según la información que revisamos antes, Jack-Pot opera con licencia offshore de Anjouan. Es una licencia legal, a menudo usada por marcas de casino más nuevas. Aun así, no ofrece el mismo nivel de protección que reguladores más estrictos. Por eso importan la reputación, el historial de pagos y la calidad del soporte."],
        ["¿Jack-Pot pedirá documentos?", "Muy probablemente antes del retiro, sí. Sube documentos solo por el sitio oficial de Jack-Pot."],
        ["¿Los retiros son instantáneos?", "No siempre. Retiros pequeños pueden ser más rápidos. Pagos grandes pueden tardar más por verificación, límites del proveedor o revisiones manuales."],
        ["¿Es arriesgado jugar en Jack-Pot?", "Sí. Slots, crash games, live casino y apuestas deportivas implican riesgo. Puedes perder dinero. Usa límites, no persigas pérdidas y no trates Jack-Pot como forma de ganar. Es entretenimiento de juego, no ingreso."],
    ],
}

RU = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "О Jack-Pot",
    "img_hero_alt": "Лобби онлайн-казино Jack-Pot и обзор Chicken Road",
    "about_paras": [
        "Jack-Pot — онлайн-платформа, где казино и ставки на спорт доступны с одного аккаунта. На сайте понятные разделы: casino, live, sport, promos, payments, tournaments и cashback. Пользователю легко выбрать, куда идти. Платформа выглядит достаточно простой. Казино разбито на категории. Можно сразу открыть нужный раздел, если вы уже знаете, во что хотите играть.",
        "Chicken Road хорошо подходит Jack-Pot, потому что это как раз тот тип игры, которому нужен быстрый доступ. Никто не хочет копаться в огромном лобби ради быстрой аркадной игры. Открываете её, ставите ставку, выбираете уровень риска — и раунд начинается. Для Chicken Road главное преимущество Jack-Pot — прямой путь к игре: быстрое лобби, поиск, мобильный доступ и интерфейс, который не мешает. Этого достаточно для игры с короткими раундами и быстрыми решениями.",
        "На Jack-Pot есть бонусы и промо, поэтому перед игрой стоит заглянуть в раздел акций. Не активируйте ничего вслепую. Бонусы могут быть ограничены по времени или правилам.",
    ],
    "h2_where": "Где найти Chicken Road на Jack-Pot",
    "where_paras": [
        "Chicken Road легко найти на Jack-Pot, если знать, куда смотреть. Откройте раздел casino и перейдите в Slots или Crash Games. Большинство быстрых аркадных игр обычно лежат в этих категориях.",
        "Самый быстрый способ — поиск. Введите Chicken Road в строку поиска, дождитесь баннера игры и откройте её. Игра должна запуститься в отдельном окне.",
        "Можно искать по провайдеру. Введите InOut — Jack-Pot покажет игры этой студии. Это помогает найти не только Chicken Road, но и другие тайтлы InOut.",
        "Иногда игра также появляется в Crash Games, куда платформы часто ставят instant games, crash games и тайтлы вне классических слотов.",
    ],
    "short_path_title": "Короткий путь простой:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": [
        "Если игра не появляется по названию, попробуйте поиск по InOut.",
    ],
    "h2_play": "Как играть в Chicken Road на Jack-Pot",
    "play_paras": [
        "Chicken Road на Jack-Pot легко запустить. Если вы новичок, начните с Easy. Так проще понять игру. Medium уже ощущается резче. Hard и Hardcore лучше для тех, кто знает, как быстро может уйти баланс в таких играх. Перед Play ещё раз проверьте ставку. Особенно на телефоне. Один поспешный тап — и раунд стартует с неверной суммой.",
        "Главная кнопка — Cash Out. Нажимайте, когда текущий множитель вас устраивает и вы хотите остановиться. Если ждать слишком долго и раунд пойдёт не так, ставка сгорает.",
        "Если это оригинальный Chicken Road от InOut Games, базовые правила на Jack-Pot те же, что и на других платформах: двигаться вперёд, растить множитель, Cash Out до проигрыша раунда.",
    ],
    "h2_demo": "Демо и игра на реальные деньги на Jack-Pot",
    "demo_paras": [
        "Демо Chicken Road доступно на Jack-Pot, и я бы начал именно с него. Не потому что демо учит выигрывать — нет. Но оно позволяет посмотреть игру без давления.",
        "В демо вы играете на виртуальный баланс. Можно менять сложность, пробовать разные ставки, двигать курицу по дороге и тестировать Cash Out в разных точках. Если раунд прошёл плохо, реальные деньги не пострадают. Режим на деньги ощущается иначе. Игра может выглядеть так же, кнопки те же, множитель растёт так же. Но когда в игре ваш баланс, каждый шаг ощущается тяжелее.",
        "В демо люди обычно играют гораздо свободнее. Баланс виртуальный, поэтому не больно тестировать сложные режимы или идти чуть дальше.",
        "На реальные деньги тот же ход ощущается иначе. Та же кнопка, тот же множитель, та же дорога — но ставка уже ваша. Кто-то делает Cash Out слишком рано из страха проиграть. Кто-то идёт слишком далеко, чтобы отыграть прошлый раунд. Тут и начинается давление. Сначала используйте демо на Jack-Pot. Изучите игру там. Игра на деньги имеет смысл только когда вы понимаете механику и принимаете риск.",
    ],
    "h2_mobile": "Chicken Road на мобильном через Jack-Pot",
    "mobile_paras": [
        "Chicken Road нормально работает на телефоне. Откройте Jack-Pot, найдите игру, поставьте ставку и запускайте раунд без тяжёлого интерфейса. На мобильном вёрстка компактнее. Поле ставки, Play и Cash Out остаются под рукой — в этой игре это важно. Не хочется искать кнопку выхода, когда множитель уже движется.",
        "Раунды короткие, поэтому мобильная игра подходит. Обычная сессия — несколько тапов. Открыли раунд, двигаете курицу, следите за множителем и выходите, когда следующий шаг кажется слишком рискованным.",
        "Скорость в основном зависит от устройства и связи. Свежий телефон со стабильным интернетом будет плавнее. Старый браузер или слабый сигнал могут замедлить экран. А из-за маленького дисплея всегда проверяйте ставку перед Play — одного невнимательного тапа хватит, чтобы стартовать с неверной суммой. Играйте через браузер. Избегайте случайных APK с неизвестных сайтов, особенно с «предикторами», взломами или «особой» версией Chicken Road.",
    ],
    "h2_final": "Итог",
    "final_paras": [
        "Chicken Road хорошо подходит Jack-Pot, потому что игре не нужна сложная настройка. Открыли casino, нашли тайтл, выбрали режим, поставили ставку — раунд начался. Для такого быстрого формата это именно то, что нужно.",
        "Главная привлекательность проста: короткие раунды, понятные кнопки, растущий множитель и постоянный выбор — забрать текущий результат или рискнуть ещё шагом. Понять легко, но игра может быстро затянуть.",
        "Jack-Pot даёт Chicken Road удобное место для игры, особенно с мобильного. Поиск работает, лобби не перегружено, демо полезно, если хотите сначала проверить механику.",
        "Chicken Road — не инструмент заработка. Это казино-игра с реальным риском. Сначала демо, потом деньги; ставьте лимиты, не гонитесь за проигрышами и относитесь к каждому раунду как к развлечению, а не к доходу.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Что такое Jack-Pot?", "Jack-Pot — онлайн-платформа казино и ставок на спорт. Можно играть в слоты, live casino, instant games, crash games и делать спортивные ставки."],
        ["Jack-Pot только для казино?", "Нет. Казино — лишь часть платформы."],
        ["Насколько быстрая регистрация?", "Регистрация занимает меньше минуты. После этого сайт может предложить выбор бонуса или открыть окно депозита."],
        ["Есть ли бонусы на Jack-Pot?", "Да, но смотрите актуальные предложения на официальном сайте."],
        ["Можно ли найти Chicken Road на Jack-Pot?", "Да, если Chicken Road есть в лобби Jack-Pot. Сначала ищите по названию игры. Если ничего нет — попробуйте провайдера InOut."],
        ["Работает ли Jack-Pot на мобильном?", "Да, Jack-Pot открывается в мобильном браузере. Лобби казино, спорт, касса и аккаунт доступны с телефона. Скорость зависит от устройства и связи. Слабый сигнал или старый браузер могут замедлить загрузку игр."],
        ["Безопасен ли Jack-Pot?", "Да, но убедитесь, что вы на настоящем домене Jack-Pot. Поддельные копии казино могут быть очень похожи на оригинал."],
        ["Какая лицензия у Jack-Pot?", "По информации, которую мы ранее проверяли, Jack-Pot работает по офшорной лицензии Anjouan. Это легальная лицензия, часто у новых брендов казино. Но уровень защиты игроков ниже, чем у строгих регуляторов. Поэтому важны репутация, история выплат и качество поддержки."],
        ["Попросит ли Jack-Pot документы?", "Скорее всего да, перед выводом. Загружайте документы только через официальный сайт Jack-Pot."],
        ["Мгновенные ли выводы?", "Не всегда. Мелкие выводы могут быть быстрее. Крупные выплаты дольше из-за верификации, лимитов платёжки или ручных проверок."],
        ["Рискованно ли играть на Jack-Pot?", "Да. Слоты, crash games, live casino и ставки на спорт — всё с риском. Можно потерять деньги. Ставьте лимиты, не гонитесь за проигрышами и не считайте Jack-Pot способом заработка. Это развлечение, а не доход."],
    ],
}

EXPORT = {"fr": FR, "de": DE, "es": ES, "ru": RU}
