# -*- coding: utf-8 -*-
"""Overrides for casino_articles#11 — AR, AZ."""

AR = {
    "h2_intro": "Chicken Road على 1xBet — ما يبحث عنه اللاعبون",
    "img_hero_alt": "عناوين Chicken Road في لوبي كازينo 1xBet",
    "intro_paras": [
        "يبحث اللاعبون عن Chicken Road على 1xBet لأنه أصبح من ألعاب الكازينو السريعة التي يُذكر اسمها في كل مكان. القواعد سهلة: الدجاجة تتقدم، المضاعف يرتفع، ويجب الخروج قبل أن تُكسر الجولة.",
        "هذا هو جاذبية اللعبة. بدون إعداد slot طويل أو شاشة bonus معقدة. تفتح اللعبة وتفهم الضغط فوراً: أخذ النتيجة الحالية أو خطوة إضافية.",
        "Chicken Road يناسب نوع الألعاب التي يبحث عنها كثيرون على 1xBet — إطلاق سريع، جولات قصيرة، وCash Out.",
        "قد تختلف الت availability حسب المنطقة واللوبي.",
        "الخطوة الأولى: تحقق من بحث كازينo 1xBet — اكتب Chicken Road أو InOut.",
    ],
    "h2_about": "عن 1xBet",
    "img_about_alt": "الصفحة الرئيسية للمراهنات والكازينo على 1xBet",
    "about_paras": [
        "1xBet منصة كبيرة للمراهنات والكازينo في حساب واحد.",
        "slots وlive casino وcrash وinstant وeSports — لوبي كامل.",
        "للألعاب السريعة: casino وبحث وفئات في حساب واحد.",
        "Chicken Road يناسب: جولات قصيرة وأزرار بسيطة.",
    ],
    "h2_available": "هل Chicken Road متاح على 1xBet؟",
    "img_search_alt": "نتائج البحث عن Chicken Road على 1xBet",
    "available_paras": [
        "نعم، Chicken Road على 1xBet مع عناوين InOut Games — الأصلي وChicken Road 2.",
        "أسهل طريقة: شريط البحث. Demo متاح أيضاً.",
    ],
    "short_path_title": "المسار القصير:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "التحقق من Chicken Road في لوبي 1xBet",
    "img_filter_alt": "فلتر وبحث مزوّد InOut على 1xBet",
    "lobby_paras": [
        "أنظف طريقة: بحث اللوبي. Chicken Road أو InOut.",
        "إن لم يظهر، جرّب Slots أو Crash Games أو Instant Games.",
    ],
    "quick_check_title": "الفحص السريع:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["لا أمرّر اللوبي كاملاً — البحث أسرع."],
    "h2_play": "كيف تعمل ألعاب Chicken Road على 1xBet",
    "img_play_alt": "Gameplay لـ Chicken Road مع المضاعف وCash Out على 1xBet",
    "play_paras": [
        "على 1xBet ليس عنواناً واحداً: original و2.0 وBonus وGold وVegas وRace.",
        "ابدأ برهان بسيط ثم اختر المخاطرة.",
        "نفس حلقة القرار: الدجاجة تتحرك والمضاعف يرتفع.",
        "الضغط من قرار صغير متكرر.",
        "Cash Out هو الزر الأهم.",
    ],
    "h2_why": "لماذا يناسب Chicken Road لوبي 1xBet",
    "img_versions_alt": "إصدارات مختلفة من Chicken Road في لوبي 1xBet",
    "why_paras": [
        "1xBet لديها slots وcrash وinstant وlive — Chicken Road يناسب طبيعياً.",
        "عدد كبير من الإصدارات ذات الصلة في اللوبي.",
        "السؤال: أي إصدار تفتح أولاً.",
        "Original لفهم التنسيق؛ 2.0 أكثر صقلًا.",
        "على 1xBet يبدو كفئة صغيرة خاصة.",
    ],
    "h2_mobile": "اللعب عبر الجوال على 1xBet",
    "img_mobile_alt": "Chicken Road في تطبيق 1xBet للجوال",
    "mobile_paras": [
        "1xBet مناسب على الجوال — التطبيق أو المتصفح.",
        "جلسات قصيرة وشاشة غير مزدحمة.",
        "انتبه لحقل الرهان.",
        "استخدم التطبيق الرسمي؛ تجنّب APK وpredictors.",
    ],
    "h2_bonuses": "المكافآت والعروض على 1xBet",
    "img_bonus_alt": "قسم مكافآت الكازينo على 1xBet",
    "bonus_paras": [
        "المكافآت من المنصة وليس من اللعبة.",
        "بعضها للslots أو الرياضة فقط؛ بعضها يستبعد crash/instant.",
        "اقرأ الشروط قبل التفعيل.",
        "تحقق من wagering وحدود الرهان.",
    ],
    "h2_safety": "الأمان على 1xBet",
    "safety_paras": [
        "مواقع النسخ قد تبدو حقيقية.",
        "تجنّب تطبيقات predictor.",
        "ترفيه وليس دخلاً.",
    ],
    "h2_final": "الرأي النهائي",
    "final_paras": [
        "1xBet قوية للألعاب السريعة: بحث وجوال وعدة عناوين Chicken Road.",
        "ابدأ بـ Demo وتحقق في لوبيك.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["هل Chicken Road على 1xBet؟", "نعم، في لوبي الكازينo مع InOut."],
        ["كيف أجد Chicken Road؟", "Casino → بحث → Chicken Road."],
        ["البحث بـ InOut؟", "نعم."],
        ["ليس في اللوبي؟", "جرّب InOut؛ قد يكون مخفياً إقليمياً."],
        ["Demo؟", "نعم."],
        ["كيف تعمل؟", "قرارات قصيرة، رهان، مضاعف، Cash Out."],
        ["المكافآت مع crash؟", "ليس دائماً."],
        ["predictors آمنة؟", "لا."],
        ["أي إصدار أولاً؟", "Chicken Road original."],
        ["مختلف في التطبيق؟", "قليلاً — شاشة أضيق."],
    ],
}

AZ = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "1xBet-də Chicken Road — oyunçular nə axtarır",
    "img_hero_alt": "1xBet casino lobisində Chicken Road titulları",
    "intro_paras": [
        "Oyunçular 1xBet-də Chicken Road axtarır, çünki o, hər yerdə danışılan sürətli casino titullarından biridir. Qaydalar sadədir: toyuq irəli gedir, multiplikator artır, raund qırılmazdan çıxmaq lazımdır.",
        "Cazibə budur. Uzun slot setup yoxdur. Oyunu açanda təzyiq dərhal başa düşülür.",
        "Chicken Road 1xBet-də axtarılan oyun tipinə uyğundur — sürətli start, qısa raundlar, Cash Out.",
        "Mövcudluq region və lobidən asılı ola bilər.",
        "İlk addım: 1xBet casino axtarışı — Chicken Road və ya InOut.",
    ],
    "h2_about": "1xBet haqqında",
    "img_about_alt": "1xBet idman mərcləri və casino əsas səhifəsi",
    "about_paras": [
        "1xBet bir hesabda hər şeyi toplayan böyük mərclər və casino platformasıdır.",
        "Slots, live casino, crash, instant, eSports — tam lobby.",
        "Sürətli oyunlar üçün: casino, axtarış, kateqoriyalar eyni hesabda.",
        "Chicken Road uyğundur: qısa raundlar, sadə düymələr.",
    ],
    "h2_available": "Chicken Road 1xBet-də varmı?",
    "img_search_alt": "1xBet-də Chicken Road axtarış nəticələri",
    "available_paras": [
        "Bəli, Chicken Road 1xBet-də InOut Games xətti ilə — original və Chicken Road 2.",
        "Ən asan yol: axtarış paneli. Demo də mövcuddur.",
    ],
    "short_path_title": "Qısa yol:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "1xBet lobisində Chicken Road yoxlanışı",
    "img_filter_alt": "1xBet-də InOut filtr və axtarış",
    "lobby_paras": [
        "Ən təmiz yol: lobby axtarışı. Chicken Road və ya InOut.",
        "Görünmürsə, Slots, Crash Games, Instant Games yoxlayın.",
    ],
    "quick_check_title": "Sürətli yoxlama:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Bütün lobini əllə sürüşdürməzdim — axtarış daha sürətlidir."],
    "h2_play": "1xBet-də Chicken Road oyunları necə işləyir",
    "img_play_alt": "1xBet-də multiplikator və Cash Out ilə Chicken Road gameplay",
    "play_paras": [
        "1xBet-də tək titul deyil: original, 2.0, Bonus, Gold, Vegas, Race.",
        "Sadə mərcdən başlayın, sonra riski seçin.",
        "Eyni qərar döngəsi.",
        "Kiçik təkrarlanan qərardan təzyiq.",
        "Cash Out ən vacib düymədir.",
    ],
    "h2_why": "Niyə Chicken Road 1xBet lobisinə uyğundur",
    "img_versions_alt": "1xBet lobisində müxtəlif Chicken Road versiyaları",
    "why_paras": [
        "1xBet-də artıq slots, crash, instant, live var — Chicken Road təbii uyğun gəlir.",
        "Lobidə çoxlu əlaqəli versiya.",
        "Sual: hansı versiyanı əvvəl açmaq.",
        "Format üçün original; 2.0 daha cilalanmış.",
        "1xBet-də kiçik öz kateqoriyası kimi.",
    ],
    "h2_mobile": "1xBet vasitəsilə mobil oyun",
    "img_mobile_alt": "1xBet mobil tətbiqində Chicken Road",
    "mobile_paras": [
        "1xBet mobil üçün yaxşıdır — app və ya brauzer.",
        "Qısa sessiyalar, yüngül interfeys.",
        "Mərc sahəsinə diqqət.",
        "Rəsmi app; APK və predictor-lərdən çəkinin.",
    ],
    "h2_bonuses": "1xBet-də bonuslar və promolar",
    "img_bonus_alt": "1xBet casino bonus bölməsi",
    "bonus_paras": [
        "Bonuslar platformadan gəlir, oyundan yox.",
        "Bəziləri yalnız slots/idman; bəziləri crash/instant istisna edir.",
        "Aktivləşdirmədən əvvəl şərtləri oxuyun.",
        "Wagering və mərc limitlərini yoxlayın.",
    ],
    "h2_safety": "1xBet-də təhlükəsizlik",
    "safety_paras": [
        "Kopya saytlar inandırıcı ola bilər.",
        "Predictor tətbiqlərindən çəkinin.",
        "Əyləncə, gəlir deyil.",
    ],
    "h2_final": "Yekun fikir",
    "final_paras": [
        "1xBet sürətli casino oyunları üçün güclüdür: axtarış, mobil və bir neçə Chicken Road titulu.",
        "Demo ilə başlayın, öz lobinizdə yoxlayın.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road 1xBet-də varmı?", "Bəli, InOut ilə lobby-də."],
        ["Necə tapım?", "Casino → axtarış → Chicken Road."],
        ["InOut axtarış?", "Bəli."],
        ["Lobby-də yoxdur?", "InOut sınayın."],
        ["Demo?", "Bəli."],
        ["Necə işləyir?", "Qısa qərarlar, mərc, multiplikator, Cash Out."],
        ["Crash üçün bonus?", "Həmişə yox."],
        ["Predictor təhlükəsiz?", "Xeyr."],
        ["Hansı versiya əvvəl?", "Original Chicken Road."],
        ["App-də fərqli?", "Bir az — ekran daha sıx."],
    ],
}

EXPORT = {"ar": AR, "az": AZ}
