# -*- coding: utf-8 -*-
"""Overrides for casino_articles#11 — PT, IT, NL."""

PT = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road na 1xBet — o que os jogadores procuram",
    "img_hero_alt": "Títulos Chicken Road no lobby casino 1xBet",
    "intro_paras": [
        "Os jogadores procuram Chicken Road na 1xBet porque o jogo se tornou um daqueles títulos casino rápidos de que todos falam. As regras são fáceis: a galinha avança, o multiplicador cresce e é preciso sair da ronda antes que quebre.",
        "Esse é todo o apelo. Sem setup longo de slot, sem ecrã de bónus complicado, sem aprender vinte símbolos antes da primeira ronda. Abre o jogo e percebe quase de imediato a pressão: ficar com o resultado atual ou tentar mais um passo.",
        "Chicken Road encaixa no estilo de jogos que muitos procuram na 1xBet — lançamento rápido, rondas curtas, controlos simples e decisões de Cash Out.",
        "Mas a disponibilidade pode depender da região e do lobby casino. Nalgumas contas aparece o Chicken Road original da InOut Games; noutras pode faltar ou surgirem jogos instant/crash similares.",
        "O primeiro passo é simples: verifique a pesquisa casino 1xBet. Escreva Chicken Road ou InOut e veja o que o lobby mostra na sua região.",
    ],
    "h2_about": "Sobre a 1xBet",
    "img_about_alt": "Página inicial de apostas e casino 1xBet",
    "about_paras": [
        "A 1xBet é uma grande plataforma de apostas e casino com tudo numa conta. As apostas desportivas são o que mais conhecem, mas o site também tem uma grande secção casino.",
        "Na plataforma há slots, live casino, crash games, instant games, eSports, desportos virtuais e apostas ao vivo. Já não é só sportsbook — é um lobby completo.",
        "Para jogos rápidos, esta estrutura ajuda. Abre casino, usa pesquisa, vê categorias e muda entre slots, live ou crash sem sair da conta.",
        "Chicken Road ou jogos similares encaixam bem: rondas curtas, botões simples e acesso rápido — o que muitos esperam de instant games.",
    ],
    "h2_available": "Chicken Road está disponível na 1xBet?",
    "img_search_alt": "Resultados de pesquisa Chicken Road na 1xBet",
    "available_paras": [
        "Sim, Chicken Road está na 1xBet, com outros títulos da linha InOut Games. Encontra-se o Chicken Road original e Chicken Road 2. Aqui a situação é melhor que noutras plataformas — a 1xBet mostra a série Chicken Road no lobby.",
        "A forma mais fácil de verificar é a barra de pesquisa. Escreva Chicken Road e espere pelos cartões do jogo. Também pode pesquisar InOut. Importante: o modo Demo também está disponível para testar mecânica e versões antes de jogar a dinheiro real.",
    ],
    "short_path_title": "O caminho curto:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Verificar Chicken Road no lobby 1xBet",
    "img_filter_alt": "Filtro e pesquisa de fornecedor InOut na 1xBet",
    "lobby_paras": [
        "A forma mais limpa de verificar Chicken Road na 1xBet é a pesquisa do lobby, não as categorias. Abra casino e escreva Chicken Road ou InOut.",
        "Se Chicken Road não aparecer na sua conta, verifique Slots, Crash Games, Instant Games ou Other. Lembre-se: lobbies mudam por país, moeda e região.",
    ],
    "quick_check_title": "A verificação rápida é assim:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Não faria scroll manual por todo o lobby — a pesquisa é mais rápida."],
    "h2_play": "Como funcionam os jogos Chicken Road na 1xBet",
    "img_play_alt": "Gameplay Chicken Road com multiplicador e Cash Out na 1xBet",
    "play_paras": [
        "Na 1xBet, Chicken Road não é um só título nos resultados. O lobby pode mostrar várias versões: original, 2.0, Bonus, Gold, Vegas, Race e outros.",
        "Começa com aposta simples. Depois decide o risco. Modos mais seguros avançam mais devagar; agressivos empurram o multiplicador mais.",
        "Após iniciar, repete-se o mesmo ciclo: galinha avança, multiplicador cresce, resultado atual fica mais tentador.",
        "É aqui que nasce a pressão. Tudo gira numa decisão pequena repetida: chega por agora ou mais um passo?",
        "Cash Out é o botão que mais importa. A tempo, a ronda termina com o resultado atual. Tarde demais, a aposta pode desaparecer.",
    ],
    "h2_why": "Porque Chicken Road encaixa no lobby 1xBet",
    "img_versions_alt": "Diferentes versões Chicken Road no lobby 1xBet",
    "why_paras": [
        "A 1xBet é uma plataforma onde jogos rápidos não destoam. Slots, crash, instant, live e desporto já estão lá — Chicken Road encaixa naturalmente.",
        "Destaca-se não só o original, mas quantas versões relacionadas o lobby mostra. Compare 2.0, Gold, Vegas, Race ou Bonus sem mudar de plataforma.",
        "A pergunta real: qual versão abrir primeiro.",
        "O original ajuda a entender o formato. 2.0 parece mais polido. Gold e Vegas são mais temáticos. Race é mais rápido. Bonus para quem quer mais features.",
        "Na 1xBet, Chicken Road parece uma pequena categoria própria.",
    ],
    "h2_mobile": "Jogo mobile via 1xBet",
    "img_mobile_alt": "Chicken Road na app mobile 1xBet",
    "mobile_paras": [
        "A 1xBet funciona bem para este tipo de jogo no telemóvel. Abra casino na app ou browser, pesquise Chicken Road e lance sem percorrer todo o lobby.",
        "No telemóvel faz sentido: sessões curtas, ecrã não sobrecarregado, botões principais perto.",
        "Cuidado com o campo de aposta — um toque rápido pode iniciar com valor errado, sobretudo entre Demo e dinheiro real.",
        "Use a app oficial 1xBet ou browser. Evite APKs aleatórios e apps predictor.",
    ],
    "h2_bonuses": "Bónus e promos na 1xBet",
    "img_bonus_alt": "Secção de bónus e promos casino 1xBet",
    "bonus_paras": [
        "Bónus em torno de Chicken Road na 1xBet vêm da plataforma, não do jogo. As regras são da 1xBet.",
        "O detalhe principal é elegibilidade. Alguns bónus só para slots ou desporto; outros excluem crash e instant games.",
        "Antes de ativar, leia termos. Verifique se crash/instant games contam para wagering.",
        "Veja também efeito no saldo: fundos bloqueados, max cashout ou limite de aposta. Com jogos rápidos é fácil quebrar regras sem notar.",
    ],
    "h2_safety": "Segurança e confiança na 1xBet",
    "safety_paras": [
        "Sites cópia podem parecer convincentes. Depois pedem SMS cedo, APK ou pagamento antes da caixa normal.",
        "Evite apps predictor — Chicken Road não precisa de sinais ou bots.",
        "É entretenimento rápido, não plano de rendimento. Não persiga perdas numa sessão.",
    ],
    "h2_final": "Opinião final",
    "final_paras": [
        "A 1xBet é forte para jogos casino rápidos: pesquisa, categorias, mobile e vários títulos Chicken Road num só sítio.",
        "Comece com Demo para ver que versão gosta. Verifique o jogo no seu lobby e não deixe uma ronda rápida virar sessão longa sem plano.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road está disponível na 1xBet?", "Sim. Aparece no lobby casino com outros jogos InOut — original, 2.0, Gold, Vegas, Race, Bonus e relacionados."],
        ["Como encontro Chicken Road na 1xBet?", "Abra casino e use a pesquisa. Escreva Chicken Road — mais rápido que scroll no lobby."],
        ["Posso pesquisar por InOut?", "Sim. Mostra a lista completa do fornecedor."],
        ["E se Chicken Road não estiver no lobby?", "Verifique ortografia e tente InOut. Pode estar oculto por região ou moeda."],
        ["Posso jogar Demo na 1xBet?", "Sim, Demo disponível para títulos Chicken Road."],
        ["Como funcionam jogos estilo Chicken Road?", "Decisões curtas: aposta, galinha avança, multiplicador cresce, Cash Out a tempo."],
        ["Bónus funcionam com crash games?", "Nem sempre. Verifique wagering antes de ativar."],
        ["Apps predictor são seguras?", "Não — evite predictors, bots e APKs suspeitos."],
        ["Que versão abrir primeiro?", "O Chicken Road original para entender o formato base."],
        ["Chicken Road é diferente na app 1xBet?", "Um pouco — tudo fica mais compacto no ecrã; vá mais devagar antes de Play."],
    ],
}

IT = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road su 1xBet — cosa cercano i giocatori",
    "img_hero_alt": "Titoli Chicken Road nel lobby casino 1xBet",
    "intro_paras": [
        "I giocatori cercano Chicken Road su 1xBet perché è uno di quei titoli casino veloci di cui si parla ovunque. Regole semplici: gallina avanti, moltiplicatore su, uscire prima che il round si rompa.",
        "Tutto l'appeal è lì. Niente setup slot lungo, niente bonus complicato. Apri e capisci subito: prendere il risultato attuale o un passo in più.",
        "Chicken Road encaixa nel tipo di giochi che molti cercano su 1xBet — avvio rapido, round corti, controlli semplici e Cash Out.",
        "La disponibilità può dipendere da regione e lobby. A volte c'è l'originale InOut Games, a volte no o compaiono giochi simili.",
        "Primo passo: cerca nel casino 1xBet. Digita Chicken Road o InOut e guarda cosa mostra il lobby.",
    ],
    "h2_about": "Informazioni su 1xBet",
    "img_about_alt": "Homepage scommesse e casino 1xBet",
    "about_paras": [
        "1xBet è una grande piattaforma scommesse e casino in un account. Conosciuta soprattutto per lo sport, ha anche un ampio casino.",
        "Slot, live casino, crash, instant, eSports, sport virtuali e live betting — un lobby completo.",
        "Per giochi rapidi la struttura aiuta: casino, ricerca, categorie, tutto nello stesso account.",
        "Chicken Road encaixa: round corti, pulsanti semplici, accesso veloce.",
    ],
    "h2_available": "Chicken Road è disponibile su 1xBet?",
    "img_search_alt": "Risultati ricerca Chicken Road su 1xBet",
    "available_paras": [
        "Sì, Chicken Road c'è su 1xBet con altri titoli InOut Games — originale e Chicken Road 2. Meglio che su altre piattaforme: la serie è nel lobby.",
        "Modo più facile: barra di ricerca. Digita Chicken Road o InOut. Anche Demo disponibile per testare meccanica e versioni.",
    ],
    "short_path_title": "Il percorso breve:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Verificare Chicken Road nel lobby 1xBet",
    "img_filter_alt": "Filtro e ricerca provider InOut su 1xBet",
    "lobby_paras": [
        "Il modo più pulito è la ricerca nel lobby, non le categorie. Digita Chicken Road o InOut.",
        "Se non compare, prova Slots, Crash Games, Instant Games. I lobby cambiano per paese e valuta.",
    ],
    "quick_check_title": "Il controllo rapido:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Non scorrere tutto il lobby — la ricerca è più veloce."],
    "h2_play": "Come funzionano i giochi Chicken Road su 1xBet",
    "img_play_alt": "Gameplay Chicken Road con moltiplicatore e Cash Out su 1xBet",
    "play_paras": [
        "Su 1xBet non è un solo titolo: original, 2.0, Bonus, Gold, Vegas, Race e altri.",
        "Inizi con puntata semplice, poi scegli il rischio.",
        "Loop decisionale: gallina avanza, moltiplicatore cresce, risultato più tentatore.",
        "Pressione da una piccola decisione ripetuta: basta ora o un passo ancora?",
        "Cash Out è il pulsante chiave — in tempo chiude il round, troppo tardi perdi la puntata.",
    ],
    "h2_why": "Perché Chicken Road encaixa nel lobby 1xBet",
    "img_versions_alt": "Diverse versioni Chicken Road nel lobby 1xBet",
    "why_paras": [
        "1xBet ha già slot, crash, instant, live e sport — Chicken Road encaixa naturalmente.",
        "Spicca il numero di versioni correlate nel lobby.",
        "Domanda reale: quale versione aprire per prima.",
        "Original per capire il formato; 2.0 più rifinito; Gold/Vegas tematici; Race più dinamico.",
        "Su 1xBet sembra una piccola categoria a sé.",
    ],
    "h2_mobile": "Gioco mobile via 1xBet",
    "img_mobile_alt": "Chicken Road sull'app mobile 1xBet",
    "mobile_paras": [
        "1xBet va bene su mobile — app o browser, cerca Chicken Road e avvia.",
        "Sessioni corte, schermo non sovraccarico, pulsanti vicini.",
        "Controlla la puntata — un tap veloce può sbagliare importo.",
        "App ufficiale o browser; evita APK e predictor.",
    ],
    "h2_bonuses": "Bonus e promo su 1xBet",
    "img_bonus_alt": "Sezione bonus casino 1xBet",
    "bonus_paras": [
        "I bonus vengono dalla piattaforma, non dal gioco.",
        "Alcuni solo slot o sport; altri escludono crash/instant.",
        "Leggi termini e wagering prima di attivare.",
        "Attenzione a fondi bloccati, max cashout e limiti puntata.",
    ],
    "h2_safety": "Sicurezza su 1xBet",
    "safety_paras": [
        "I siti clone imitano colori e layout — poi chiedono SMS o APK.",
        "Evita predictor e bot.",
        "Intrattenimento, non reddito — non inseguire perdite.",
    ],
    "h2_final": "Opinione finale",
    "final_paras": [
        "1xBet è forte per giochi veloci: ricerca, mobile e più titoli Chicken Road insieme.",
        "Inizia con Demo, verifica nel tuo lobby e non prolungare sessioni senza piano.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road è su 1xBet?", "Sì, nel lobby casino con altri InOut — original, 2.0, Gold, Vegas, Race, Bonus."],
        ["Come trovo Chicken Road?", "Casino → ricerca → Chicken Road."],
        ["Posso cercare InOut?", "Sì, mostra l'elenco completo del provider."],
        ["Se non c'è nel lobby?", "Prova InOut; può dipendere da regione/valuta."],
        ["C'è la Demo?", "Sì, per confrontare versioni."],
        ["Come funzionano?", "Decisioni brevi, puntata, moltiplicatore, Cash Out."],
        ["I bonus valgono per crash?", "Non sempre — controlla wagering."],
        ["Predictor sicuri?", "No, evitali."],
        ["Quale versione aprire?", "L'original Chicken Road."],
        ["Diverso nell'app?", "Un po' — schermo più compatto, rallenta prima di Play."],
    ],
}

NL = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road op 1xBet — wat spelers zoeken",
    "img_hero_alt": "Chicken Road-titels in het 1xBet casino-lobby",
    "intro_paras": [
        "Spelers zoeken Chicken Road op 1xBet omdat het een van die snelle casino-titels is waar iedereen over praat. Regels zijn simpel: kip vooruit, multiplier omhoog, weg vóór de ronde breekt.",
        "Dat is de aantrekkingskracht. Geen lang slot-setup, geen ingewikkeld bonusscherm. Je opent het spel en voelt meteen de druk: huidige resultaat nemen of nog een stap.",
        "Chicken Road past bij wat veel spelers op 1xBet zoeken — snelle start, korte rondes, eenvoudige bediening en Cash Out.",
        "Beschikbaarheid kan per regio en lobby verschillen. Soms staat het originele InOut Games erop, soms niet.",
        "Eerste stap: check de 1xBet casino-zoekbalk. Typ Chicken Road of InOut.",
    ],
    "h2_about": "Over 1xBet",
    "img_about_alt": "1xBet sport- en casino-startpagina",
    "about_paras": [
        "1xBet is een groot wed- en casinoplatform in één account. Bekend om sport, maar ook een grote casinosectie.",
        "Slots, live casino, crash, instant, eSports, virtual sports en live betting — een volledig lobby.",
        "Handig voor snelle spellen: zoeken, categorieën, alles in hetzelfde account.",
        "Chicken Road past: korte rondes, simpele knoppen, snelle toegang.",
    ],
    "h2_available": "Is Chicken Road beschikbaar op 1xBet?",
    "img_search_alt": "Zoekresultaten Chicken Road op 1xBet",
    "available_paras": [
        "Ja, Chicken Road staat op 1xBet met andere InOut Games-titels — origineel en Chicken Road 2. Beter dan op sommige platforms: de serie staat in het lobby.",
        "Makkelijkste check: zoekbalk. Typ Chicken Road of InOut. Demo is ook beschikbaar.",
    ],
    "short_path_title": "Het korte pad:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Chicken Road controleren in het 1xBet-lobby",
    "img_filter_alt": "Filter en InOut-zoekopdracht op 1xBet",
    "lobby_paras": [
        "Schoonste manier: lobby-zoeken, niet categorieën. Typ Chicken Road of InOut.",
        "Zie je het niet, probeer Slots, Crash Games, Instant Games. Lobbies verschillen per land en valuta.",
    ],
    "quick_check_title": "Snelle check:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Niet handmatig scrollen — zoeken is sneller."],
    "h2_play": "Hoe Chicken Road-spellen werken op 1xBet",
    "img_play_alt": "Chicken Road gameplay met multiplier en Cash Out op 1xBet",
    "play_paras": [
        "Op 1xBet niet één titel: original, 2.0, Bonus, Gold, Vegas, Race en meer.",
        "Begin met eenvoudige inzet, kies daarna risico.",
        "Zelfde beslissingslus: kip beweegt, multiplier stijgt.",
        "Druk van één kleine herhaalde keuze: genoeg nu of nog een stap?",
        "Cash Out is de belangrijkste knop.",
    ],
    "h2_why": "Waarom Chicken Road past in het 1xBet-lobby",
    "img_versions_alt": "Verschillende Chicken Road-versies in het 1xBet-lobby",
    "why_paras": [
        "1xBet heeft al slots, crash, instant, live en sport — Chicken Road past natuurlijk.",
        "Opvallend: veel gerelateerde versies in één lobby.",
        "Echte vraag: welke versie eerst openen.",
        "Original voor het formaat; 2.0 verfijnder; Gold/Vegas thematischer; Race sneller.",
        "Op 1xBet lijkt het een eigen mini-categorie.",
    ],
    "h2_mobile": "Mobiel spelen via 1xBet",
    "img_mobile_alt": "Chicken Road in de 1xBet mobiele app",
    "mobile_paras": [
        "1xBet werkt goed mobiel — app of browser, zoek Chicken Road en start.",
        "Korte sessies, niet overvol scherm.",
        "Let op inzetveld — snelle tik kan verkeerd bedrag geven.",
        "Officiële app of browser; vermijd APK's en predictors.",
    ],
    "h2_bonuses": "Bonussen en promo's op 1xBet",
    "img_bonus_alt": "1xBet casino-bonussectie",
    "bonus_paras": [
        "Bonussen komen van het platform, niet uit het spel zelf.",
        "Sommige alleen slots of sport; andere sluiten crash/instant uit.",
        "Lees voorwaarden en wagering.",
        "Let op geblokkeerde bonusfondsen en inzetlimieten.",
    ],
    "h2_safety": "Veiligheid op 1xBet",
    "safety_paras": [
        "Kloonsites lijken echt — daarna vreemde SMS of APK.",
        "Vermijd predictors en bots.",
        "Entertainment, geen inkomen — jaag verliezen niet na.",
    ],
    "h2_final": "Eindoordeel",
    "final_paras": [
        "1xBet is sterk voor snelle casino-spellen: zoeken, mobiel en meerdere Chicken Road-titels.",
        "Start met demo, check je eigen lobby, plan je sessie.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Is Chicken Road op 1xBet?", "Ja, in het casino-lobby met andere InOut-titels."],
        ["Hoe vind ik Chicken Road?", "Casino → zoeken → Chicken Road."],
        ["Zoeken op InOut?", "Ja, volledige providerlijst."],
        ["Niet in lobby?", "Probeer InOut; kan regionaal verborgen zijn."],
        ["Demo beschikbaar?", "Ja, voor Chicken Road-titels."],
        ["Hoe werken ze?", "Korte beslissingen, inzet, multiplier, Cash Out."],
        ["Bonussen voor crash?", "Niet altijd — check wagering."],
        ["Predictors veilig?", "Nee, vermijd ze."],
        ["Welke versie eerst?", "Originele Chicken Road."],
        ["Anders in de app?", "Iets compacter scherm — rustig voor Play."],
    ],
}

EXPORT = {"pt": PT, "it": IT, "nl": NL}
