# -*- coding: utf-8 -*-
"""Overrides for casino_articles#25 — PT, IT, NL."""

PT = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Sobre o Jack-Pot",
    "img_hero_alt": "Lobby do casino online Jack-Pot e visão geral do Chicken Road",
    "about_paras": [
        "Jack-Pot é uma plataforma online onde jogos de casino e apostas desportivas estão disponíveis numa só conta. O site tem secções claras: casino, live, desporto, promos, pagamentos, torneios e cashback. Para o utilizador é fácil escolher para onde ir. A plataforma parece simples o suficiente. O casino está dividido em categorias. Também pode usar as secções principais se já souber o que quer jogar.",
        "Chicken Road combina bem com o Jack-Pot porque é exatamente o tipo de jogo que precisa de acesso rápido. Ninguém quer vasculhar um lobby enorme para encontrar um jogo arcade veloz. Abre, define a aposta, escolhe o nível de risco e a ronda começa. Para Chicken Road, a principal vantagem do Jack-Pot é o caminho limpo até ao jogo: lobby rápido, barra de pesquisa, acesso mobile e um layout que não atrapalha. Isso basta para um jogo de rondas curtas e decisões rápidas.",
        "O Jack-Pot também tem bónus e promos, por isso vale a pena ver a secção de promoções antes de jogar. Não ative nada às cegas. Os bónus podem ser limitados no tempo ou por regras.",
    ],
    "h2_where": "Onde encontrar Chicken Road no Jack-Pot",
    "where_paras": [
        "Chicken Road é fácil de encontrar no Jack-Pot se souber onde procurar. Abra a secção casino e vá a Slots ou Crash Games. A maioria dos jogos arcade rápidos costuma estar nestas categorias.",
        "O caminho mais rápido é a pesquisa. Escreva Chicken Road na barra, espere pelo banner do jogo e abra-o. O jogo deve abrir numa janela separada.",
        "Também pode pesquisar por fornecedor. Introduza InOut e o Jack-Pot deve mostrar jogos deste estúdio. Ajuda se quiser encontrar não só Chicken Road, mas outros títulos InOut.",
        "Por vezes o jogo também aparece em Crash Games, onde as plataformas costumam colocar jogos instantâneos, crash games e títulos fora das categorias clássicas de slots.",
    ],
    "short_path_title": "O caminho curto é simples:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Se o jogo não aparecer pelo nome, tente pesquisar InOut."],
    "h2_play": "Como jogar Chicken Road no Jack-Pot",
    "play_paras": [
        "Chicken Road no Jack-Pot é fácil de começar. Se for novo, comece com Easy. Dá mais margem para entender o jogo. Medium já parece mais intenso. Hard e Hardcore são melhores para quem sabe o quão rápido o saldo pode desaparecer neste tipo de jogo. Antes de carregar em Play, confira a aposta outra vez. Especialmente no telemóvel. Um toque apressado pode iniciar a ronda com o valor errado.",
        "O botão principal é Cash Out. Carregue quando o multiplicador atual for suficiente e quiser parar. Se esperar demasiado e a ronda correr mal, a aposta perde-se.",
        "Se for o Chicken Road original da InOut Games, as regras básicas no Jack-Pot são as mesmas que noutras plataformas: avançar, fazer crescer o multiplicador, Cash Out antes de perder a ronda.",
    ],
    "h2_demo": "Demo e jogo a dinheiro real no Jack-Pot",
    "demo_paras": [
        "A demo de Chicken Road está disponível no Jack-Pot, e por aí começaria. Não porque a demo ensine a ganhar — não ensina. Mas permite ver o jogo sem pressão.",
        "No modo demo joga com saldo virtual. Pode mudar a dificuldade, testar apostas diferentes, mover a galinha pela estrada e experimentar Cash Out em pontos distintos. Se a ronda correr mal, o dinheiro real não é afetado. O modo real sente-se diferente. O jogo pode parecer igual, os botões iguais e o multiplicador cresce da mesma forma. Mas quando o seu saldo entra em jogo, cada passo pesa mais.",
        "Em demo as pessoas costumam jogar muito mais soltas. O saldo é virtual, por isso não dói testar modos mais difíceis ou ir um pouco mais longe.",
        "Com dinheiro real, o mesmo movimento sente-se diferente. Mesmo botão, mesmo multiplicador, mesma estrada — mas a aposta é sua. Alguns fazem Cash Out cedo demais por medo de perder. Outros vão longe demais para recuperar a ronda anterior. É aí que a pressão começa. Use primeiro a demo no Jack-Pot. Aprenda o jogo lá. Jogar a dinheiro real só faz sentido quando entende a mecânica e aceita o risco.",
    ],
    "h2_mobile": "Chicken Road no mobile via Jack-Pot",
    "mobile_paras": [
        "Chicken Road funciona bem no telemóvel. Abra o Jack-Pot, encontre o jogo, defina a aposta e comece a ronda sem interface pesada. No mobile o layout fica mais compacto. O campo de aposta, Play e Cash Out continuam fáceis de alcançar, o que importa neste jogo. Não quer procurar o botão de saída quando o multiplicador já se move.",
        "As rondas são curtas, por isso o mobile encaixa bem. Uma sessão normal são só alguns toques. Abra a ronda, mova a galinha, vigie o multiplicador e saia quando o próximo passo começar a parecer arriscado demais.",
        "A velocidade depende sobretudo do dispositivo e da ligação. Um telemóvel recente com internet estável será mais fluido. Um browser antigo ou sinal fraco pode tornar o ecrã mais lento. E como o ecrã é pequeno, confira sempre a aposta antes de Play — um toque descuidado basta para começar com o valor errado. Jogue pelo browser. Evite APKs aleatórios de sites desconhecidos, especialmente os que prometem preditores, hacks ou uma versão «especial» de Chicken Road.",
    ],
    "h2_final": "Conclusão",
    "final_paras": [
        "Chicken Road combina bem com o Jack-Pot porque o jogo não precisa de configuração complicada. Abra o casino, encontre o título, escolha o modo, defina a aposta e a ronda começa. Para este tipo de jogo rápido, é exatamente o que quer.",
        "O apelo principal é simples: rondas curtas, botões claros, multiplicador a crescer e a escolha constante — ficar com o resultado atual ou arriscar mais um passo. Fácil de entender, mas o jogo pode prender rapidamente.",
        "O Jack-Pot dá ao Chicken Road um lugar limpo para jogar, especialmente no mobile. A pesquisa funciona, o lobby não é pesado e o modo demo é útil para testar a mecânica primeiro.",
        "Chicken Road não é ferramenta para ganhar dinheiro. É um jogo de casino com risco real. Use a demo antes do dinheiro real, defina limites, não persiga perdas e trate cada ronda como entretenimento, não como rendimento.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["O que é o Jack-Pot?", "Jack-Pot é uma plataforma de casino online e apostas desportivas. Pode jogar slots, live casino, jogos instantâneos, crash games e apostas desportivas."],
        ["O Jack-Pot é só para casino?", "Não. O casino é apenas uma parte da plataforma."],
        ["O registo é rápido?", "O registo demora menos de um minuto. Depois o site pode mostrar escolha de bónus ou abrir a janela de depósito."],
        ["O Jack-Pot oferece bónus?", "Sim, mas vá ao site oficial para ver os bónus atuais disponíveis."],
        ["Posso encontrar Chicken Road no Jack-Pot?", "Sim, se Chicken Road estiver disponível no lobby do Jack-Pot. Pesquise primeiro pelo nome do jogo. Se nada aparecer, tente o fornecedor InOut."],
        ["O Jack-Pot funciona no mobile?", "Sim, o Jack-Pot abre no mobile pelo browser. Lobby de casino, desporto, caixa e conta são usáveis no telemóvel. A velocidade depende do dispositivo e da ligação. Sinal fraco ou browser antigo pode tornar alguns jogos mais lentos."],
        ["O Jack-Pot é seguro?", "Sim, mas certifique-se de que está no domínio real do Jack-Pot. Cópias falsas podem parecer muito o site original."],
        ["Que licença tem o Jack-Pot?", "Pela informação que revimos antes, o Jack-Pot opera com licença offshore de Anjouan. É uma licença legal, muitas vezes usada por marcas de casino mais novas. Ainda assim, não oferece o mesmo nível de proteção que reguladores mais rigorosos. Por isso importam reputação, histórico de pagamentos e qualidade do suporte."],
        ["O Jack-Pot pedirá documentos?", "Muito provavelmente antes do levantamento, sim. Envie documentos apenas pelo site oficial do Jack-Pot."],
        ["Os levantamentos são instantâneos?", "Nem sempre. Levantamentos pequenos podem ser mais rápidos. Pagamentos maiores podem demorar mais por verificação, limites do provedor ou revisões manuais."],
        ["É arriscado jogar no Jack-Pot?", "Sim. Slots, crash games, live casino e apostas desportivas envolvem risco. Pode perder dinheiro. Use limites, não persiga perdas e não trate o Jack-Pot como forma de ganhar. É entretenimento de jogo, não rendimento."],
    ],
}

IT = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Informazioni su Jack-Pot",
    "img_hero_alt": "Lobby del casino online Jack-Pot e panoramica di Chicken Road",
    "about_paras": [
        "Jack-Pot è una piattaforma online dove giochi da casino e scommesse sportive sono disponibili con un solo account. Il sito ha sezioni chiare: casino, live, sport, promos, pagamenti, tornei e cashback. Per l'utente è facile capire dove andare. La piattaforma sembra abbastanza semplice. Il casino è diviso in categorie. Puoi anche usare le sezioni principali se sai già cosa vuoi giocare.",
        "Chicken Road si adatta bene a Jack-Pot perché è esattamente il tipo di gioco che ha bisogno di accesso rapido. Nessuno vuole scavare in un lobby enorme per trovare un gioco arcade veloce. Lo apri, imposti la puntata, scegli il livello di rischio e il round parte. Per Chicken Road, il vantaggio principale di Jack-Pot è il percorso pulito al gioco: lobby veloce, barra di ricerca, accesso mobile e layout che non disturba. Basta per un gioco basato su round corti e decisioni rapide.",
        "Jack-Pot ha anche bonus e promozioni, quindi conviene controllare la sezione promo prima di giocare. Non attivare nulla alla cieca. I bonus possono essere limitati nel tempo o dalle regole.",
    ],
    "h2_where": "Dove trovare Chicken Road su Jack-Pot",
    "where_paras": [
        "Chicken Road è facile da trovare su Jack-Pot se sai dove guardare. Apri la sezione casino e vai su Slots o Crash Games. La maggior parte dei giochi arcade rapidi si trova di solito in queste categorie.",
        "Il modo più veloce è la ricerca. Digita Chicken Road nella barra, attendi il banner del gioco e aprilo. Il gioco dovrebbe avviarsi in una finestra separata.",
        "Puoi anche cercare per provider. Inserisci InOut e Jack-Pot dovrebbe mostrare i giochi di questo studio. Utile se vuoi trovare non solo Chicken Road, ma altri titoli InOut.",
        "A volte il gioco compare anche in Crash Games, dove le piattaforme spesso mettono instant games, crash games e titoli fuori dalle categorie classiche di slot.",
    ],
    "short_path_title": "Il percorso breve è semplice:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Se il gioco non compare per nome, prova a cercare InOut."],
    "h2_play": "Come giocare a Chicken Road su Jack-Pot",
    "play_paras": [
        "Chicken Road su Jack-Pot è facile da avviare. Se sei nuovo, inizia con Easy. Dà più spazio per capire il gioco. Medium è già più intenso. Hard e Hardcore sono meglio per chi sa quanto velocemente il saldo può sparire in questo tipo di gioco. Prima di premere Play, ricontrolla la puntata. Soprattutto sul telefono. Un tap affrettato può avviare il round con l'importo sbagliato.",
        "Il pulsante principale è Cash Out. Premilo quando il moltiplicatore attuale basta e vuoi fermarti. Se aspetti troppo e il round va male, la puntata si perde.",
        "Se è il Chicken Road originale di InOut Games, le regole base su Jack-Pot restano le stesse delle altre piattaforme: avanzare, far crescere il moltiplicatore, Cash Out prima di perdere il round.",
    ],
    "h2_demo": "Demo e gioco con soldi veri su Jack-Pot",
    "demo_paras": [
        "La demo di Chicken Road è disponibile su Jack-Pot, e da lì inizierei. Non perché la demo insegni a vincere — non lo fa. Ma ti permette di vedere il gioco senza pressione.",
        "In modalità demo giochi con saldo virtuale. Puoi cambiare difficoltà, provare puntate diverse, muovere il pollo sulla strada e testare Cash Out in punti diversi. Se il round va male, i soldi veri non sono toccati. La modalità soldi veri si sente diversa. Il gioco può sembrare uguale, i pulsanti uguali e il moltiplicatore cresce allo stesso modo. Ma quando entra il tuo saldo, ogni passo pesa di più.",
        "In demo la gente di solito gioca molto più libera. Il saldo è virtuale, quindi non fa male provare modalità più difficili o andare un po' oltre.",
        "Con soldi veri, la stessa mossa si sente diversa. Stesso pulsante, stesso moltiplicatore, stessa strada — ma la puntata è tua. Alcuni fanno Cash Out troppo presto per paura di perdere. Altri vanno troppo oltre per recuperare il round precedente. È lì che inizia la pressione. Usa prima la demo su Jack-Pot. Impara il gioco lì. Il gioco con soldi veri ha senso solo quando capisci la meccanica e accetti il rischio.",
    ],
    "h2_mobile": "Chicken Road su mobile via Jack-Pot",
    "mobile_paras": [
        "Chicken Road funziona bene sul telefono. Apri Jack-Pot, trova il gioco, imposta la puntata e avvia il round senza un'interfaccia pesante. Su mobile il layout si stringe. Campo puntata, Play e Cash Out restano facili da raggiungere, cosa importante in questo gioco. Non vuoi cercare il pulsante di uscita quando il moltiplicatore si muove già.",
        "I round sono corti, quindi il mobile si adatta bene. Una sessione normale sono pochi tap. Apri il round, muovi il pollo, tieni d'occhio il moltiplicatore e esci quando il passo successivo inizia a sembrare troppo rischioso.",
        "La velocità dipende soprattutto da dispositivo e connessione. Un telefono recente con internet stabile sarà più fluido. Un browser vecchio o segnale debole può rendere lo schermo più lento. E perché il display è piccolo, controlla sempre la puntata prima di Play — un tap incauto basta per iniziare con l'importo sbagliato. Gioca dal browser. Evita APK casuali da siti sconosciuti, soprattutto quelli che promettono predittori, hack o una versione «speciale» di Chicken Road.",
    ],
    "h2_final": "Conclusione",
    "final_paras": [
        "Chicken Road si adatta bene a Jack-Pot perché il gioco non ha bisogno di una configurazione complicata. Apri il casino, trova il titolo, scegli la modalità, imposta la puntata e il round parte. Per questo tipo di gioco veloce è esattamente ciò che vuoi.",
        "Il fascino principale è semplice: round corti, pulsanti chiari, moltiplicatore che cresce e scelta costante — prendere il risultato attuale o rischiare un passo in più. Facile da capire, ma il gioco può coinvolgerti in fretta.",
        "Jack-Pot offre a Chicken Road un posto pulito per giocare, soprattutto da mobile. La ricerca funziona, il lobby non è troppo pesante e la demo è utile per testare prima la meccanica.",
        "Chicken Road non è uno strumento per fare soldi. È un gioco da casino con rischio reale. Usa la demo prima dei soldi veri, imposta limiti, non inseguire le perdite e tratta ogni round come intrattenimento, non come reddito.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Cos'è Jack-Pot?", "Jack-Pot è una piattaforma di casino online e scommesse sportive. Puoi giocare a slot, live casino, instant games, crash games e scommesse sportive."],
        ["Jack-Pot è solo per il casino?", "No. Il casino è solo una parte della piattaforma."],
        ["Quanto è veloce la registrazione?", "La registrazione richiede meno di un minuto. Poi il sito può mostrare una scelta di bonus o aprire la finestra di deposito."],
        ["Jack-Pot offre bonus?", "Sì, ma vai sul sito ufficiale per vedere i bonus attuali disponibili."],
        ["Posso trovare Chicken Road su Jack-Pot?", "Sì, se Chicken Road è disponibile nel lobby Jack-Pot. Cerca prima per nome del gioco. Se non compare nulla, prova il provider InOut."],
        ["Jack-Pot funziona su mobile?", "Sì, Jack-Pot si apre su mobile dal browser. Lobby casino, sport, cassa e account sono usabili dal telefono. La velocità dipende da dispositivo e connessione. Segnale debole o browser vecchio può rallentare alcuni giochi."],
        ["Jack-Pot è sicuro?", "Sì, ma assicurati di essere sul dominio reale di Jack-Pot. Le copie false possono assomigliare molto al sito originale."],
        ["Che licenza ha Jack-Pot?", "Dalle informazioni che abbiamo rivisto in precedenza, Jack-Pot opera con licenza offshore di Anjouan. È una licenza legale, spesso usata da brand casino più nuovi. Tuttavia non offre lo stesso livello di protezione di regolatori più severi. Contano quindi reputazione, storico pagamenti e qualità del supporto."],
        ["Jack-Pot chiederà documenti?", "Molto probabilmente prima del prelievo, sì. Carica documenti solo tramite il sito ufficiale Jack-Pot."],
        ["I prelievi sono istantanei?", "Non sempre. Prelievi piccoli possono essere più rapidi. Pagamenti grandi possono richiedere più tempo per verifica, limiti del provider o controlli manuali."],
        ["È rischioso giocare su Jack-Pot?", "Sì. Slot, crash games, live casino e scommesse sportive comportano rischio. Puoi perdere soldi. Usa limiti, non inseguire le perdite e non trattare Jack-Pot come modo per guadagnare. È intrattenimento d'azzardo, non reddito."],
    ],
}

NL = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Over Jack-Pot",
    "img_hero_alt": "Jack-Pot online casino-lobby en Chicken Road-overzicht",
    "about_paras": [
        "Jack-Pot is een online platform waar casinospellen en sportweddenschappen beschikbaar zijn met één account. De site heeft duidelijke secties: casino, live, sport, promos, betalingen, toernooien en cashback. Voor de gebruiker is het makkelijk om te kiezen waar je naartoe gaat. Het platform voelt eenvoudig genoeg. Het casino is verdeeld in categorieën. Je kunt ook de hoofdsecties gebruiken als je al weet wat je wilt spelen.",
        "Chicken Road past goed bij Jack-Pot omdat het precies het type spel is dat snelle toegang nodig heeft. Niemand wil door een enorme lobby graven om een snel arcadespel te vinden. Je opent het, zet de inzet, kiest het risiconiveau en de ronde start. Voor Chicken Road is het grootste voordeel van Jack-Pot het duidelijke pad naar het spel: snelle lobby, zoekbalk, mobiele toegang en een layout die niet in de weg zit. Dat is genoeg voor een spel met korte rondes en snelle beslissingen.",
        "Jack-Pot heeft ook bonussen en promo's. Check de promotiesectie voordat je speelt. Activeer niets blind. Bonussen kunnen in tijd of regels beperkt zijn.",
    ],
    "h2_where": "Waar je Chicken Road vindt op Jack-Pot",
    "where_paras": [
        "Chicken Road is makkelijk te vinden op Jack-Pot als je weet waar je moet kijken. Open de casinosectie en ga naar Slots of Crash Games. De meeste snelle arcadespellen staan meestal in deze categorieën.",
        "De snelste manier is zoeken. Typ Chicken Road in de zoekbalk, wacht tot de spelbanner verschijnt en open het. Het spel zou in een apart venster moeten starten.",
        "Je kunt ook op provider zoeken. Voer InOut in en Jack-Pot toont spellen van dit studio. Handig als je niet alleen Chicken Road wilt vinden, maar ook andere InOut-titels.",
        "Soms staat het spel ook in Crash Games, waar platforms vaak instant games, crash games en titels plaatsen die niet in klassieke slotcategorieën passen.",
    ],
    "short_path_title": "Het korte pad is simpel:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Als het spel niet op naam verschijnt, probeer dan InOut te zoeken."],
    "h2_play": "Hoe je Chicken Road speelt op Jack-Pot",
    "play_paras": [
        "Chicken Road op Jack-Pot is makkelijk te starten. Als je nieuw bent, begin met Easy. Dat geeft meer ruimte om het spel te begrijpen. Medium voelt al scherper. Hard en Hardcore zijn beter voor spelers die weten hoe snel een saldo kan verdwijnen in dit type spel. Controleer de inzet nog eens voordat je op Play drukt. Vooral op je telefoon. Eén haastige tik kan de ronde met het verkeerde bedrag starten.",
        "De hoofdknop is Cash Out. Druk wanneer de huidige multiplier genoeg is en je wilt stoppen. Wacht je te lang en de ronde loopt mis, dan is de inzet weg.",
        "Als dit de originele Chicken Road van InOut Games is, blijven de basisregels op Jack-Pot hetzelfde als op andere platforms: vooruit gaan, multiplier laten groeien, Cash Out voordat je de ronde verliest.",
    ],
    "h2_demo": "Demo en echt geld spelen op Jack-Pot",
    "demo_paras": [
        "De Chicken Road-demo is beschikbaar op Jack-Pot, en daar zou ik beginnen. Niet omdat demo leert winnen — dat doet het niet. Maar het laat je het spel zien zonder druk.",
        "In demo speel je met virtueel saldo. Je kunt moeilijkheid wisselen, verschillende inzetten testen, de kip over de weg bewegen en Cash Out op verschillende punten proberen. Gaat de ronde mis, dan gebeurt er niets met je echt geld. Echt geld voelt anders. Het spel kan hetzelfde lijken, de knoppen hetzelfde en de multiplier groeit hetzelfde. Maar zodra je eigen saldo meedoet, voelt elke stap zwaarder.",
        "In demo spelen mensen meestal veel losser. Het saldo is virtueel, dus het doet geen pijn om hardere modi te testen of iets verder te gaan.",
        "Met echt geld voelt dezelfde zet anders. Dezelfde knop, dezelfde multiplier, dezelfde weg — maar de inzet is van jou. Sommigen cashen te vroeg uit uit angst om te verliezen. Anderen gaan te ver om de vorige ronde terug te winnen. Daar begint de druk. Gebruik eerst de demo op Jack-Pot. Leer het spel daar. Echt geld spelen heeft alleen zin als je de mechanica begrijpt en het risico accepteert.",
    ],
    "h2_mobile": "Chicken Road mobiel via Jack-Pot",
    "mobile_paras": [
        "Chicken Road werkt prima op je telefoon. Open Jack-Pot, vind het spel, zet de inzet en start de ronde zonder zware interface. Op mobiel wordt de layout compacter. Inzetveld, Play en Cash Out blijven goed bereikbaar, wat in dit spel belangrijk is. Je wilt niet zoeken naar de uit-knop als de multiplier al beweegt.",
        "De rondes zijn kort, dus mobiel spelen past goed. Een normale sessie is maar een paar tikken. Open de ronde, beweeg de kip, houd de multiplier in de gaten en stop wanneer de volgende stap te riskant aanvoelt.",
        "De snelheid hangt vooral af van je apparaat en verbinding. Een nieuwe telefoon met stabiel internet voelt soepeler. Een oude browser of zwak signaal kan het scherm trager laten reageren. En omdat het display klein is, check altijd de inzet voordat je op Play drukt — één onoplettende tik is genoeg om met het verkeerde bedrag te starten. Speel via de browser. Vermijd willekeurige APK's van onbekende sites, vooral dingen die predictors, hacks of een «speciale» Chicken Road-versie beloven.",
    ],
    "h2_final": "Slot",
    "final_paras": [
        "Chicken Road past goed bij Jack-Pot omdat het spel geen ingewikkelde setup nodig heeft. Open het casino, vind de titel, kies de modus, zet de inzet en de ronde start. Voor dit soort snelle spellen is dat precies wat je wilt.",
        "De hoofdaantrekkingskracht is simpel: korte rondes, duidelijke knoppen, groeiende multiplier en de constante keuze — het huidige resultaat nemen of nog één stap riskeren. Makkelijk te begrijpen, maar het spel kan je snel pakken.",
        "Jack-Pot geeft Chicken Road een schone plek om te spelen, vooral vanaf mobiel. Zoeken werkt, de lobby is niet te zwaar en demo is nuttig als je eerst de mechanica wilt testen.",
        "Chicken Road is geen geldmachine. Het is een casinospel met echt risico. Gebruik demo vóór echt geld, stel limieten in, jaag verliezen niet na en behandel elke ronde als entertainment, niet als inkomen.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Wat is Jack-Pot?", "Jack-Pot is een online casino- en sportweddenschappenplatform. Je kunt slots, live casino, instant games, crash games en sportweddenschappen spelen."],
        ["Is Jack-Pot alleen voor casino?", "Nee. Casino is slechts één deel van het platform."],
        ["Hoe snel is registratie?", "Registratie duurt minder dan een minuut. Daarna kan de site een bonuskeuze tonen of het stortingsvenster openen."],
        ["Biedt Jack-Pot bonussen?", "Ja, maar ga naar de officiële website om te zien welke bonussen nu beschikbaar zijn."],
        ["Kan ik Chicken Road vinden op Jack-Pot?", "Ja, als Chicken Road beschikbaar is in de Jack-Pot-spellobby. Zoek eerst op spelnaam. Als niets verschijnt, probeer de provider InOut."],
        ["Werkt Jack-Pot op mobiel?", "Ja, Jack-Pot opent mobiel via de browser. Casino-lobby, sport, kassa en account zijn bruikbaar vanaf je telefoon. Snelheid hangt af van apparaat en verbinding. Zwak signaal of oude browser kan sommige spellen trager laden."],
        ["Is Jack-Pot veilig?", "Ja, maar zorg dat je op het echte Jack-Pot-domein bent. Nepcasino-kopieën kunnen erg op de originele site lijken."],
        ["Welke licentie heeft Jack-Pot?", "Volgens de informatie die we eerder bekeken, opereert Jack-Pot met een offshore-licentie uit Anjouan. Dat is een legale licentie, vaak gebruikt door nieuwere casinomerken. Het biedt echter niet hetzelfde beschermingsniveau als strengere toezichthouders. Reputatie, betalingsgeschiedenis en supportkwaliteit tellen hier dus zwaar."],
        ["Vraagt Jack-Pot om documenten?", "Waarschijnlijk wel vóór opname. Upload documenten alleen via de officiële Jack-Pot-website."],
        ["Zijn opnames direct?", "Niet altijd. Kleine opnames kunnen sneller zijn. Grotere uitbetalingen kunnen langer duren door verificatie, providerlimieten of handmatige controles."],
        ["Is spelen op Jack-Pot riskant?", "Ja. Slots, crash games, live casino en sportweddenschappen brengen allemaal risico met zich mee. Je kunt geld verliezen. Gebruik limieten, jaag verliezen niet na en behandel Jack-Pot niet als verdienmethode. Het is gokentertainment, geen inkomen."],
    ],
}

EXPORT = {"pt": PT, "it": IT, "nl": NL}
