# -*- coding: utf-8 -*-
"""Overrides for casino_articles#11 — PL, RO, UA."""

PL = {
    "h2_intro": "Chicken Road na 1xBet — czego szukają gracze",
    "img_hero_alt": "Tytuły Chicken Road w lobby kasyna 1xBet",
    "intro_paras": [
        "Gracze szukają Chicken Road na 1xBet, bo gra stała się jednym z tych szybkich tytułów casino, o których mówią wszędzie. Zasady są proste: kurczak idzie do przodu, mnożnik rośnie, trzeba wyjść z rundy, zanim się zepsuje.",
        "Na tym polega cały urok. Bez długiej konfiguracji slota i skomplikowanego bonusu. Otwierasz grę i od razu czujesz presję: wziąć aktualny wynik czy spróbować jeszcze kroku.",
        "Chicken Road pasuje do stylu gier, których wielu szuka na 1xBet — szybki start, krótkie rundy, proste sterowanie i decyzje Cash Out.",
        "Dostępność zależy od regionu i lobby. Czasem widać oryginalny Chicken Road od InOut Games, czasem nie.",
        "Pierwszy krok: sprawdź wyszukiwarkę casino 1xBet. Wpisz Chicken Road lub InOut.",
    ],
    "h2_about": "O 1xBet",
    "img_about_alt": "Strona główna zakładów i kasyna 1xBet",
    "about_paras": [
        "1xBet to duża platforma zakładów i kasyna w jednym koncie. Znana ze sportu, ale ma też duży dział casino.",
        "Są slots, live casino, crash games, instant games, eSports, sporty wirtualne i live betting — pełne lobby.",
        "Dla szybkich gier to wygodne: casino, wyszukiwarka, kategorie w jednym koncie.",
        "Chicken Road pasuje: krótkie rundy, proste przyciski, szybki dostęp.",
    ],
    "h2_available": "Czy Chicken Road jest na 1xBet?",
    "img_search_alt": "Wyniki wyszukiwania Chicken Road na 1xBet",
    "available_paras": [
        "Tak, Chicken Road jest na 1xBet wraz z innymi tytułami InOut Games — oryginał i Chicken Road 2. 1xBet pokazuje serię Chicken Road w lobby.",
        "Najprościej przez wyszukiwarkę: Chicken Road lub InOut. Dostępny też tryb Demo.",
    ],
    "short_path_title": "Krótka ścieżka:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Sprawdzanie Chicken Road w lobby 1xBet",
    "img_filter_alt": "Filtr i wyszukiwanie dostawcy InOut na 1xBet",
    "lobby_paras": [
        "Najczyściej przez wyszukiwarkę lobby, nie kategorie. Wpisz Chicken Road lub InOut.",
        "Jeśli nie widać gry, sprawdź Slots, Crash Games, Instant Games. Lobby zmienia się wg kraju i waluty.",
    ],
    "quick_check_title": "Szybka kontrola:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Nie przewijałbym całego lobby — wyszukiwarka jest szybsza."],
    "h2_play": "Jak działają gry Chicken Road na 1xBet",
    "img_play_alt": "Rozgrywka Chicken Road z mnożnikiem i Cash Out na 1xBet",
    "play_paras": [
        "Na 1xBet to nie jeden tytuł: original, 2.0, Bonus, Gold, Vegas, Race i inne.",
        "Zacznij od prostej stawki, potem wybierz ryzyko.",
        "Ta sama pętla decyzji: kurczak idzie, mnożnik rośnie.",
        "Presja z małej powtarzalnej decyzji: wystarczy teraz czy jeszcze krok?",
        "Cash Out to najważniejszy przycisk.",
    ],
    "h2_why": "Dlaczego Chicken Road pasuje do lobby 1xBet",
    "img_versions_alt": "Różne wersje Chicken Road w lobby 1xBet",
    "why_paras": [
        "1xBet ma slots, crash, instant, live i sport — Chicken Road naturalnie pasuje.",
        "Wyróżnia się liczba powiązanych wersji w lobby.",
        "Pytanie: którą wersję otworzyć najpierw.",
        "Original dla formatu; 2.0 bardziej dopracowany; Gold/Vegas tematyczne; Race szybszy.",
        "Na 1xBet to mała własna kategoria.",
    ],
    "h2_mobile": "Gra mobilna przez 1xBet",
    "img_mobile_alt": "Chicken Road w aplikacji mobilnej 1xBet",
    "mobile_paras": [
        "1xBet sprawdza się na mobile — app lub przeglądarka, wyszukaj Chicken Road i graj.",
        "Krótkie sesje, przejrzysty ekran.",
        "Uważaj na pole stawki — pośpieszny tap może dać złą kwotę.",
        "Oficjalna app lub browser; unikaj APK i predictorów.",
    ],
    "h2_bonuses": "Bonusy i promocje na 1xBet",
    "img_bonus_alt": "Sekcja bonusów kasyna 1xBet",
    "bonus_paras": [
        "Bonusy pochodzą z platformy, nie z samej gry.",
        "Niektóre tylko slots lub sport; inne wykluczają crash/instant.",
        "Czytaj warunki i wagering przed aktywacją.",
        "Sprawdź blokadę środków bonusowych i limity stawki.",
    ],
    "h2_safety": "Bezpieczeństwo na 1xBet",
    "safety_paras": [
        "Klony wyglądają przekonująco — potem dziwne SMS lub APK.",
        "Unikaj predictorów i botów.",
        "To rozrywka, nie dochód — nie gonić strat.",
    ],
    "h2_final": "Podsumowanie",
    "final_paras": [
        "1xBet to dobre miejsce na szybkie gry casino: wyszukiwarka, mobile i kilka tytułów Chicken Road.",
        "Zacznij od demo, sprawdź w swoim lobby i nie przedłużaj sesji bez planu.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Czy Chicken Road jest na 1xBet?", "Tak, w lobby casino z innymi InOut — original, 2.0, Gold, Vegas, Race, Bonus."],
        ["Jak znaleźć Chicken Road?", "Casino → wyszukiwarka → Chicken Road."],
        ["Szukać InOut?", "Tak, pełna lista dostawcy."],
        ["Brak w lobby?", "Spróbuj InOut; może być ukryte regionalnie."],
        ["Czy jest demo?", "Tak, dla tytułów Chicken Road."],
        ["Jak działają?", "Krótkie decyzje, stawka, mnożnik, Cash Out."],
        ["Bonusy na crash?", "Nie zawsze — sprawdź wagering."],
        ["Predictory bezpieczne?", "Nie, unikaj."],
        ["Którą wersję pierwszą?", "Oryginalny Chicken Road."],
        ["Inaczej w app?", "Trochę — wszystko bliżej na ekranie."],
    ],
}

RO = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road pe 1xBet — ce caută jucătorii",
    "img_hero_alt": "Titluri Chicken Road în lobby-ul casino 1xBet",
    "intro_paras": [
        "Jucătorii caută Chicken Road pe 1xBet pentru că jocul a devenit unul dintre titlurile casino rapide despre care se vorbește peste tot. Reguli simple: găina avansează, multiplicatorul crește, trebuie să ieși din rundă înainte să se strice.",
        "Asta e tot farmecul. Fără setup lung de slot. Deschizi jocul și înțelegi presiunea: iei rezultatul actual sau mai faci un pas.",
        "Chicken Road se potrivește stilului de jocuri căutate pe 1xBet — lansare rapidă, runde scurte, Cash Out.",
        "Disponibilitatea depinde de regiune și lobby.",
        "Primul pas: verifică căutarea casino 1xBet — Chicken Road sau InOut.",
    ],
    "h2_about": "Despre 1xBet",
    "img_about_alt": "Pagina principală pariuri și casino 1xBet",
    "about_paras": [
        "1xBet e o platformă mare de pariuri și casino într-un cont. Cunoscută pentru sport, dar are și secțiune casino mare.",
        "Slots, live casino, crash, instant, eSports — lobby complet.",
        "Pentru jocuri rapide: casino, căutare, categorii în același cont.",
        "Chicken Road se potrivește: runde scurte, butoane simple.",
    ],
    "h2_available": "Este Chicken Road disponibil pe 1xBet?",
    "img_search_alt": "Rezultate căutare Chicken Road pe 1xBet",
    "available_paras": [
        "Da, Chicken Road e pe 1xBet cu alte titluri InOut Games — original și Chicken Road 2.",
        "Cel mai ușor: bara de căutare. Și modul Demo e disponibil.",
    ],
    "short_path_title": "Calea scurtă:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Verificarea Chicken Road în lobby 1xBet",
    "img_filter_alt": "Filtru și căutare furnizor InOut pe 1xBet",
    "lobby_paras": [
        "Cel mai curat: căutare în lobby. Chicken Road sau InOut.",
        "Dacă nu apare, încearcă Slots, Crash Games, Instant Games.",
    ],
    "quick_check_title": "Verificarea rapidă:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Nu aș derula manual tot lobby-ul."],
    "h2_play": "Cum funcționează jocurile Chicken Road pe 1xBet",
    "img_play_alt": "Gameplay Chicken Road cu multiplicator și Cash Out pe 1xBet",
    "play_paras": [
        "Pe 1xBet nu e un singur titlu: original, 2.0, Bonus, Gold, Vegas, Race.",
        "Începi cu miză simplă, apoi alegi riscul.",
        "Aceeași buclă de decizie.",
        "Presiune dintr-o decizie mică repetată.",
        "Cash Out e butonul cheie.",
    ],
    "h2_why": "De ce Chicken Road se potrivește lobby-ului 1xBet",
    "img_versions_alt": "Versiuni diferite Chicken Road în lobby 1xBet",
    "why_paras": [
        "1xBet are deja slots, crash, instant, live — Chicken Road se potrivește.",
        "Multe versiuni înrudite în același lobby.",
        "Întrebarea: ce versiune deschizi prima.",
        "Original pentru format; 2.0 mai rafinat; Gold/Vegas tematice.",
        "Pe 1xBet pare o mică categorie proprie.",
    ],
    "h2_mobile": "Joc mobil prin 1xBet",
    "img_mobile_alt": "Chicken Road în app mobil 1xBet",
    "mobile_paras": [
        "1xBet merge bine pe mobil — app sau browser.",
        "Sesiuni scurte, ecran neîncărcat.",
        "Ai grijă la câmpul mizei.",
        "App oficială; evită APK și predictori.",
    ],
    "h2_bonuses": "Bonusuri și promoții pe 1xBet",
    "img_bonus_alt": "Secțiune bonusuri casino 1xBet",
    "bonus_paras": [
        "Bonusurile vin de la platformă.",
        "Unele doar slots/sport; altele exclud crash/instant.",
        "Citește termenii înainte de activare.",
        "Verifică fonduri blocate și limite de miză.",
    ],
    "h2_safety": "Siguranță pe 1xBet",
    "safety_paras": [
        "Site-urile copie pot părea reale.",
        "Evită aplicațiile predictor.",
        "Divertisment, nu venit.",
    ],
    "h2_final": "Părere finală",
    "final_paras": [
        "1xBet e bun pentru jocuri rapide: căutare, mobil, mai multe titluri Chicken Road.",
        "Începe cu demo și verifică în propriul lobby.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road e pe 1xBet?", "Da, în lobby cu alte InOut."],
        ["Cum găsesc Chicken Road?", "Casino → căutare → Chicken Road."],
        ["Pot căuta InOut?", "Da."],
        ["Dacă nu e în lobby?", "Încearcă InOut; poate fi ascuns regional."],
        ["Există demo?", "Da."],
        ["Cum funcționează?", "Decizii scurte, miză, multiplicator, Cash Out."],
        ["Bonusuri pentru crash?", "Nu întotdeauna."],
        ["Predictori sigure?", "Nu."],
        ["Ce versiune prima?", "Chicken Road original."],
        ["Diferit în app?", "Puțin — ecran mai compact."],
    ],
}

UA = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road на 1xBet — що шукають гравці",
    "img_hero_alt": "Тайтли Chicken Road у лобі казино 1xBet",
    "intro_paras": [
        "Гравці шукають Chicken Road на 1xBet, бо гра стала одним із швидких casino-тайтлів, про які говорять скрізь. Правила прості: курка вперед, множник росте, треба вийти до «поломки» раунду.",
        "У цьому весь прикол. Без довгого setup слота. Відкриваєте гру і одразу відчуваєте тиск: забрати результат чи ризикнути кроком.",
        "Chicken Road підходить під стиль ігор на 1xBet — швидкий старт, короткі раунди, Cash Out.",
        "Доступність залежить від регіону та лобі.",
        "Перший крок: пошук casino 1xBet — Chicken Road або InOut.",
    ],
    "h2_about": "Про 1xBet",
    "img_about_alt": "Головна сторінка ставок і казино 1xBet",
    "about_paras": [
        "1xBet — велика платформа ставок і казино в одному акаунті.",
        "Slots, live casino, crash, instant, eSports — повне лобі.",
        "Для швидких ігор зручно: casino, пошук, категорії в одному акаунті.",
        "Chicken Road підходить: короткі раунди, прості кнопки.",
    ],
    "h2_available": "Чи доступний Chicken Road на 1xBet?",
    "img_search_alt": "Результати пошуку Chicken Road на 1xBet",
    "available_paras": [
        "Так, Chicken Road є на 1xBet з іншими тайтлами InOut Games — original і Chicken Road 2.",
        "Найпростіше через пошук. Також доступний Demo.",
    ],
    "short_path_title": "Короткий шлях:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Перевірка Chicken Road у лобі 1xBet",
    "img_filter_alt": "Фільтр і пошук провайдера InOut на 1xBet",
    "lobby_paras": [
        "Найчистіше — пошук у лобі. Chicken Road або InOut.",
        "Якщо не видно — Slots, Crash Games, Instant Games.",
    ],
    "quick_check_title": "Швидка перевірка:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Не гортав би все лобі вручну."],
    "h2_play": "Як працюють ігри Chicken Road на 1xBet",
    "img_play_alt": "Геймплей Chicken Road з множником і Cash Out на 1xBet",
    "play_paras": [
        "На 1xBet не один тайтл: original, 2.0, Bonus, Gold, Vegas, Race.",
        "Почніть із простої ставки, потім оберіть ризик.",
        "Той самий цикл рішень.",
        "Тиск від малого повторюваного рішення.",
        "Cash Out — головна кнопка.",
    ],
    "h2_why": "Чому Chicken Road підходить лобі 1xBet",
    "img_versions_alt": "Різні версії Chicken Road у лобі 1xBet",
    "why_paras": [
        "1xBet уже має slots, crash, instant, live — Chicken Road органічно вписується.",
        "Багато пов’язаних версій в одному лобі.",
        "Питання: яку версію відкрити першою.",
        "Original для формату; 2.0 полірованіший.",
        "На 1xBet це мала власна категорія.",
    ],
    "h2_mobile": "Мобільна гра через 1xBet",
    "img_mobile_alt": "Chicken Road у мобільному застосунку 1xBet",
    "mobile_paras": [
        "1xBet зручний на mobile — app або браузер.",
        "Короткі сесії, не перевантажений екран.",
        "Стежте за полем ставки.",
        "Офіційний app; уникайте APK і predictor.",
    ],
    "h2_bonuses": "Бонуси та промо на 1xBet",
    "img_bonus_alt": "Розділ бонусів казино 1xBet",
    "bonus_paras": [
        "Бонуси від платформи, не від гри.",
        "Деякі лише slots/спорт; інші виключають crash/instant.",
        "Читайте умови перед активацією.",
        "Перевіряйте блокування bonus funds.",
    ],
    "h2_safety": "Безпека на 1xBet",
    "safety_paras": [
        "Копії сайтів можуть виглядати переконливо.",
        "Уникайте predictor-додатків.",
        "Розвага, не дохід.",
    ],
    "h2_final": "Підсумок",
    "final_paras": [
        "1xBet — сильна платформа для швидких ігор: пошук, mobile, кілька тайтлів Chicken Road.",
        "Почніть з demo і перевірте у своєму лобі.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road на 1xBet?", "Так, у лобі з іншими InOut."],
        ["Як знайти?", "Casino → пошук → Chicken Road."],
        ["Шукати InOut?", "Так."],
        ["Немає в лобі?", "Спробуйте InOut."],
        ["Є demo?", "Так."],
        ["Як працюють?", "Короткі рішення, ставка, множник, Cash Out."],
        ["Бонуси на crash?", "Не завжди."],
        ["Predictor безпечні?", "Ні."],
        ["Яку версію першою?", "Original Chicken Road."],
        ["Інакше в app?", "Трохи — компактніший екран."],
    ],
}

EXPORT = {"pl": PL, "ro": RO, "ua": UA}
