# -*- coding: utf-8 -*-
"""Overrides for casino_articles#25 — PL, RO, UA."""

PL = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "O Jack-Pot",
    "img_hero_alt": "Lobby kasyna online Jack-Pot i podgląd Chicken Road",
    "about_paras": [
        "Jack-Pot to platforma online, na której gry kasynowe i zakłady sportowe są dostępne z jednego konta. Strona ma przejrzyste sekcje: casino, live, sport, promos, płatności, turnieje i cashback. Użytkownikowi łatwo wybrać, dokąd iść. Platforma wydaje się wystarczająco prosta. Kasyno jest podzielone na kategorie. Możesz też użyć głównych sekcji, jeśli już wiesz, w co chcesz grać.",
        "Chicken Road dobrze pasuje do Jack-Pot, bo to dokładnie ten typ gry, który potrzebuje szybkiego dostępu. Nikt nie chce przeszukiwać ogromnego lobby, żeby znaleźć szybką grę arcade. Otwierasz ją, ustawiasz stawkę, wybierasz poziom ryzyka i runda startuje. Dla Chicken Road główną zaletą Jack-Pot jest prosta droga do gry: szybkie lobby, wyszukiwarka, dostęp mobilny i układ, który nie przeszkadza. To wystarczy dla gry opartej na krótkich rundach i szybkich decyzjach.",
        "Jack-Pot ma też bonusy i promocje, więc warto sprawdzić sekcję promocji przed grą. Nie aktywuj niczego na ślepo. Bonusy mogą być ograniczone czasowo lub zasadami.",
    ],
    "h2_where": "Gdzie znaleźć Chicken Road na Jack-Pot",
    "where_paras": [
        "Chicken Road łatwo znaleźć na Jack-Pot, jeśli wiesz, gdzie szukać. Otwórz sekcję casino i przejdź do Slots lub Crash Games. Większość szybkich gier arcade zwykle leży w tych kategoriach.",
        "Najszybsza droga to wyszukiwarka. Wpisz Chicken Road, poczekaj na baner gry i otwórz ją. Gra powinna uruchomić się w osobnym oknie.",
        "Możesz też szukać po dostawcy. Wpisz InOut — Jack-Pot powinien pokazać gry tego studia. To pomaga znaleźć nie tylko Chicken Road, ale też inne tytuły InOut.",
        "Czasem gra pojawia się też w Crash Games, gdzie platformy często umieszczają instant games, crash games i tytuły poza klasycznymi slotami.",
    ],
    "short_path_title": "Krótka ścieżka jest prosta:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Jeśli gra nie pojawia się po nazwie, spróbuj wyszukać InOut."],
    "h2_play": "Jak grać w Chicken Road na Jack-Pot",
    "play_paras": [
        "Chicken Road na Jack-Pot łatwo uruchomić. Jeśli jesteś nowy, zacznij od Easy. Daje więcej miejsca na zrozumienie gry. Medium już jest ostrzejsze. Hard i Hardcore lepiej dla graczy, którzy wiedzą, jak szybko może zniknąć saldo w tym typie gry. Przed Play sprawdź stawkę jeszcze raz. Zwłaszcza na telefonie. Jeden pośpieszny tap może rozpocząć rundę z złą kwotą.",
        "Główny przycisk to Cash Out. Naciśnij, gdy aktualny mnożnik wystarcza i chcesz się zatrzymać. Jeśli poczekasz za długo i runda pójdzie źle, stawka przepada.",
        "Jeśli to oryginalny Chicken Road od InOut Games, podstawowe zasady na Jack-Pot są takie same jak na innych platformach: iść do przodu, rosnąć mnożnik, Cash Out zanim przegrasz rundę.",
    ],
    "h2_demo": "Demo i gra na prawdziwe pieniądze na Jack-Pot",
    "demo_paras": [
        "Demo Chicken Road jest dostępne na Jack-Pot i od tego bym zaczął. Nie dlatego, że demo uczy wygrywać — nie uczy. Ale pozwala zobaczyć grę bez presji.",
        "W trybie demo grasz na wirtualne saldo. Możesz zmieniać trudność, testować różne stawki, przesuwać kurczaka po drodze i próbować Cash Out w różnych punktach. Jeśli runda idzie źle, prawdziwe pieniądze nie ucierpią. Gra na prawdziwe pieniądze czuje się inaczej. Gra może wyglądać tak samo, przyciski te same, mnożnik rośnie tak samo. Ale gdy w grę wchodzi twoje saldo, każdy krok waży więcej.",
        "W demo ludzie zwykle grają dużo swobodniej. Saldo jest wirtualne, więc nie boli testowanie trudniejszych trybów ani pójście krok dalej.",
        "Na prawdziwe pieniądze ten sam ruch czuje się inaczej. Ten sam przycisk, ten sam mnożnik, ta sama droga — ale stawka jest twoja. Niektórzy robią Cash Out za wcześnie ze strachu przed stratą. Inni idą za daleko, by odrobić poprzednią rundę. Tu zaczyna się presja. Najpierw użyj demo na Jack-Pot. Naucz się gry tam. Gra na prawdziwe pieniądze ma sens dopiero, gdy rozumiesz mechanikę i akceptujesz ryzyko.",
    ],
    "h2_mobile": "Chicken Road na mobile przez Jack-Pot",
    "mobile_paras": [
        "Chicken Road dobrze działa na telefonie. Otwórz Jack-Pot, znajdź grę, ustaw stawkę i zacznij rundę bez ciężkiego interfejsu. Na mobile układ jest ciaśniejszy. Pole stawki, Play i Cash Out nadal są łatwo dostępne, co w tej grze ma znaczenie. Nie chcesz szukać przycisku wyjścia, gdy mnożnik już się rusza.",
        "Rundy są krótkie, więc mobile pasuje. Normalna sesja to kilka tapnięć. Otwórz rundę, rusz kurczakiem, pilnuj mnożnika i wyjdź, gdy następny krok zaczyna wydawać się zbyt ryzykowny.",
        "Szybkość zależy głównie od urządzenia i połączenia. Świeży telefon ze stabilnym internetem będzie płynniejszy. Stara przeglądarka lub słaby sygnał mogą spowolnić ekran. A bo wyświetlacz jest mały, zawsze sprawdź stawkę przed Play — jedno nieostrożne tapnięcie wystarczy, by zacząć z złą kwotą. Graj przez przeglądarkę. Unikaj losowych APK z nieznanych stron, zwłaszcza z obietnicą predictorów, hacków lub «specjalnej» wersji Chicken Road.",
    ],
    "h2_final": "Podsumowanie",
    "final_paras": [
        "Chicken Road dobrze pasuje do Jack-Pot, bo gra nie wymaga skomplikowanej konfiguracji. Otwórz casino, znajdź tytuł, wybierz tryb, ustaw stawkę — runda startuje. Dla tego typu szybkiej gry to dokładnie to, czego potrzebujesz.",
        "Główny urok jest prosty: krótkie rundy, czytelne przyciski, rosnący mnożnik i ciągły wybór — wziąć aktualny wynik czy zaryzykować jeszcze jeden krok. Łatwo zrozumieć, ale gra może szybko wciągnąć.",
        "Jack-Pot daje Chicken Road czyste miejsce do gry, zwłaszcza z mobile. Wyszukiwarka działa, lobby nie jest zbyt ciężkie, a demo jest przydatne, jeśli chcesz najpierw sprawdzić mechanikę.",
        "Chicken Road to nie narzędzie do zarabiania. To gra kasynowa z realnym ryzykiem. Najpierw demo, potem prawdziwe pieniądze; ustaw limity, nie gonić strat i traktuj każdą rundę jako rozrywkę, nie dochód.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Czym jest Jack-Pot?", "Jack-Pot to platforma kasyna online i zakładów sportowych. Możesz grać w sloty, live casino, instant games, crash games i obstawiać sport."],
        ["Czy Jack-Pot to tylko kasyno?", "Nie. Kasyno to tylko część platformy."],
        ["Jak szybka jest rejestracja?", "Rejestracja trwa mniej niż minutę. Potem strona może pokazać wybór bonusu lub otworzyć okno depozytu."],
        ["Czy Jack-Pot oferuje bonusy?", "Tak, ale sprawdź aktualne bonusy na oficjalnej stronie."],
        ["Czy znajdę Chicken Road na Jack-Pot?", "Tak, jeśli Chicken Road jest dostępny w lobby Jack-Pot. Najpierw szukaj po nazwie gry. Jeśli nic nie ma, spróbuj dostawcy InOut."],
        ["Czy Jack-Pot działa na mobile?", "Tak, Jack-Pot otwiera się w przeglądarce mobilnej. Lobby kasyna, sport, kasa i konto są dostępne z telefonu. Szybkość zależy od urządzenia i połączenia. Słaby sygnał lub stara przeglądarka mogą spowolnić ładowanie gier."],
        ["Czy Jack-Pot jest bezpieczny?", "Tak, ale upewnij się, że jesteś na prawdziwej domenie Jack-Pot. Fałszywe kopie kasyna mogą wyglądać bardzo podobnie do oryginału."],
        ["Jaką licencję ma Jack-Pot?", "Z informacji, które wcześniej sprawdziliśmy, Jack-Pot działa na licencji offshore Anjouan. To legalna licencja, często u nowszych marek kasyn. Nie daje jednak takiego poziomu ochrony gracza jak surowsi regulatorzy. Liczy się więc reputacja, historia wypłat i jakość supportu."],
        ["Czy Jack-Pot poprosi o dokumenty?", "Prawdopodobnie tak, przed wypłatą. Wysyłaj dokumenty tylko przez oficjalną stronę Jack-Pot."],
        ["Czy wypłaty są natychmiastowe?", "Nie zawsze. Małe wypłaty mogą być szybsze. Większe mogą trwać dłużej przez weryfikację, limity operatora płatności lub ręczne kontrole."],
        ["Czy gra na Jack-Pot jest ryzykowna?", "Tak. Sloty, crash games, live casino i zakłady sportowe niosą ryzyko. Możesz stracić pieniądze. Ustaw limity, nie gonić strat i nie traktuj Jack-Pot jako sposobu na zarobek. To rozrywka hazardowa, nie dochód."],
    ],
}

RO = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Despre Jack-Pot",
    "img_hero_alt": "Lobby-ul cazinoului online Jack-Pot și prezentarea Chicken Road",
    "about_paras": [
        "Jack-Pot este o platformă online unde jocurile de cazino și pariurile sportive sunt disponibile dintr-un singur cont. Site-ul are secțiuni clare: casino, live, sport, promos, plăți, turnee și cashback. Pentru utilizator e ușor să aleagă unde să meargă. Platforma pare destul de simplă. Cazinoul este împărțit în categorii. Poți folosi și secțiunile principale dacă știi deja ce vrei să joci.",
        "Chicken Road se potrivește bine cu Jack-Pot pentru că este exact tipul de joc care are nevoie de acces rapid. Nimeni nu vrea să caute într-un lobby uriaș pentru un joc arcade rapid. Îl deschizi, setezi miza, alegi nivelul de risc și runda începe. Pentru Chicken Road, principalul avantaj al Jack-Pot este calea clară către joc: lobby rapid, bară de căutare, acces mobil și un layout care nu deranjează. E suficient pentru un joc cu runde scurte și decizii rapide.",
        "Jack-Pot are și bonusuri și promoții, deci merită să verifici secțiunea de promoții înainte de joc. Nu activa nimic pe nevăzute. Bonusurile pot fi limitate în timp sau prin reguli.",
    ],
    "h2_where": "Unde găsești Chicken Road pe Jack-Pot",
    "where_paras": [
        "Chicken Road e ușor de găsit pe Jack-Pot dacă știi unde să cauți. Deschide secțiunea casino și mergi la Slots sau Crash Games. Majoritatea jocurilor arcade rapide sunt de obicei în aceste categorii.",
        "Cea mai rapidă cale este căutarea. Tastează Chicken Road în bară, așteaptă bannerul jocului și deschide-l. Jocul ar trebui să pornească într-o fereastră separată.",
        "Poți căuta și după furnizor. Introdu InOut și Jack-Pot ar trebui să arate jocurile acestui studio. Ajută dacă vrei să găsești nu doar Chicken Road, ci și alte titluri InOut.",
        "Uneori jocul apare și în Crash Games, unde platformele pun adesea instant games, crash games și titluri care nu încap în categoriile clasice de sloturi.",
    ],
    "short_path_title": "Calea scurtă e simplă:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Dacă jocul nu apare după nume, încearcă să cauți InOut."],
    "h2_play": "Cum joci Chicken Road pe Jack-Pot",
    "play_paras": [
        "Chicken Road pe Jack-Pot e ușor de pornit. Dacă ești nou, începe cu Easy. Îți dă mai mult spațiu să înțelegi jocul. Medium deja se simte mai ascuțit. Hard și Hardcore sunt mai bune pentru jucătorii care știu cât de repede poate dispărea soldul în acest tip de joc. Înainte de Play, verifică din nou miza. Mai ales pe telefon. Un tap grăbit poate porni runda cu suma greșită.",
        "Butonul principal este Cash Out. Apasă când multiplicatorul actual e suficient și vrei să te oprești. Dacă aștepți prea mult și runda merge prost, miza se pierde.",
        "Dacă este Chicken Road original de la InOut Games, regulile de bază pe Jack-Pot sunt aceleași ca pe alte platforme: mergi înainte, crește multiplicatorul, Cash Out înainte să pierzi runda.",
    ],
    "h2_demo": "Demo și joc pe bani reali pe Jack-Pot",
    "demo_paras": [
        "Demo-ul Chicken Road este disponibil pe Jack-Pot, și de acolo aș începe. Nu pentru că demo-ul învață cum să câștigi — nu o face. Dar îți permite să vezi jocul fără presiune.",
        "În modul demo joci cu sold virtual. Poți schimba dificultatea, testa mize diferite, mișca găina pe drum și încerca Cash Out în puncte diferite. Dacă runda merge prost, banii reali nu sunt afectați. Modul pe bani reali se simte diferit. Jocul poate arăta la fel, butoanele la fel, multiplicatorul crește la fel. Dar odată ce intră soldul tău, fiecare pas se simte mai greu.",
        "În demo oamenii joacă de obicei mult mai lejer. Soldul e virtual, deci nu doare să testezi moduri mai grele sau să mergi puțin mai departe.",
        "Cu bani reali, aceeași mișcare se simte diferit. Același buton, același multiplicator, același drum — dar miza e a ta. Unii fac Cash Out prea devreme de frica pierderii. Alții merg prea departe ca să recupereze runda anterioară. Acolo începe presiunea. Folosește mai întâi demo pe Jack-Pot. Învață jocul acolo. Jocul pe bani reali are sens doar când înțelegi mecanica și accepți riscul.",
    ],
    "h2_mobile": "Chicken Road pe mobil prin Jack-Pot",
    "mobile_paras": [
        "Chicken Road merge bine pe telefon. Deschide Jack-Pot, găsește jocul, setează miza și pornește runda fără interfață grea. Pe mobil layout-ul devine mai strâns. Câmpul de miză, Play și Cash Out rămân ușor de atins, ceea ce contează în acest joc. Nu vrei să cauți butonul de ieșire când multiplicatorul se mișcă deja.",
        "Rundele sunt scurte, deci mobilul se potrivește. O sesiune normală e doar câteva tap-uri. Deschide runda, mișcă găina, urmărește multiplicatorul și pleacă când următorul pas pare prea riscant.",
        "Viteza depinde în principal de dispozitiv și conexiune. Un telefon nou cu internet stabil va fi mai fluid. Un browser vechi sau semnal slab poate face ecranul să reacționeze mai lent. Și pentru că display-ul e mic, verifică mereu miza înainte de Play — un tap neatenționat e suficient să pornești cu suma greșită. Joacă prin browser. Evită APK-uri aleatoare de pe site-uri necunoscute, mai ales cele cu predictori, hack-uri sau o versiune «specială» de Chicken Road.",
    ],
    "h2_final": "Concluzie",
    "final_paras": [
        "Chicken Road se potrivește bine cu Jack-Pot pentru că jocul nu are nevoie de o configurare complicată. Deschizi casino, găsești titlul, alegi modul, setezi miza și runda pornește. Pentru acest tip de joc rapid, exact asta vrei.",
        "Atracția principală e simplă: runde scurte, butoane clare, multiplicator în creștere și alegerea constantă — iei rezultatul actual sau riști încă un pas. Ușor de înțeles, dar jocul te poate prinde repede.",
        "Jack-Pot oferă Chicken Road un loc curat de joc, mai ales de pe mobil. Căutarea funcționează, lobby-ul nu e prea greu, iar demo e util dacă vrei să testezi mecanica mai întâi.",
        "Chicken Road nu e unealtă de făcut bani. E un joc de cazino cu risc real. Folosește demo înainte de bani reali, setează limite, nu urmări pierderile și tratează fiecare rundă ca divertisment, nu ca venit.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Ce este Jack-Pot?", "Jack-Pot este o platformă de cazino online și pariuri sportive. Poți juca sloturi, live casino, instant games, crash games și pariuri sportive."],
        ["Jack-Pot e doar pentru cazino?", "Nu. Cazinoul e doar o parte a platformei."],
        ["Cât de rapidă e înregistrarea?", "Înregistrarea durează mai puțin de un minut. Apoi site-ul poate arăta alegerea unui bonus sau deschide fereastra de depunere."],
        ["Jack-Pot oferă bonusuri?", "Da, dar mergi pe site-ul oficial pentru bonusurile actuale disponibile."],
        ["Pot găsi Chicken Road pe Jack-Pot?", "Da, dacă Chicken Road e disponibil în lobby-ul Jack-Pot. Caută mai întâi după numele jocului. Dacă nu apare nimic, încearcă furnizorul InOut."],
        ["Jack-Pot funcționează pe mobil?", "Da, Jack-Pot se deschide pe mobil prin browser. Lobby cazino, sport, casierie și cont sunt utilizabile de pe telefon. Viteza depinde de dispozitiv și conexiune. Semnal slab sau browser vechi poate încetini unele jocuri."],
        ["Jack-Pot e sigur?", "Da, dar asigură-te că ești pe domeniul real Jack-Pot. Copiile false de cazino pot arăta foarte asemănător cu site-ul original."],
        ["Ce licență are Jack-Pot?", "Din informațiile pe care le-am verificat anterior, Jack-Pot operează cu licență offshore Anjouan. E o licență legală, folosită adesea de branduri de cazino mai noi. Totuși nu oferă același nivel de protecție ca regulatorii mai stricți. De aceea contează reputația, istoricul plăților și calitatea suportului."],
        ["Jack-Pot va cere documente?", "Cel mai probabil da, înainte de retragere. Încarcă documente doar prin site-ul oficial Jack-Pot."],
        ["Retragerile sunt instant?", "Nu întotdeauna. Retragerile mici pot fi mai rapide. Plățile mari pot dura mai mult din cauza verificării, limitelor furnizorului sau verificărilor manuale."],
        ["E riscant să joci pe Jack-Pot?", "Da. Sloturi, crash games, live casino și pariuri sportive implică risc. Poți pierde bani. Folosește limite, nu urmări pierderile și nu trata Jack-Pot ca pe o modalitate de câștig. E divertisment de jocuri de noroc, nu venit."],
    ],
}

UA = {
    "h1": "Jack-Pot — Chicken Road",
    "h2_about": "Про Jack-Pot",
    "img_hero_alt": "Лобі онлайн-казино Jack-Pot та огляд Chicken Road",
    "about_paras": [
        "Jack-Pot — онлайн-платформа, де казино та ставки на спорт доступні з одного акаунта. На сайті зрозумілі розділи: casino, live, sport, promos, payments, tournaments і cashback. Користувачу легко обрати, куди йти. Платформа виглядає досить простою. Казино поділене на категорії. Можна одразу відкрити потрібний розділ, якщо ви вже знаєте, у що хочете грати.",
        "Chicken Road добре підходить Jack-Pot, бо це саме той тип гри, якому потрібен швидкий доступ. Ніхто не хоче копатися у величезному лобі заради швидкої аркадної гри. Відкриваєте її, ставите ставку, обираєте рівень ризику — і раунд починається. Для Chicken Road головна перевага Jack-Pot — прямий шлях до гри: швидке лобі, пошук, мобільний доступ і інтерфейс, який не заважає. Цього достатньо для гри з короткими раундами та швидкими рішеннями.",
        "На Jack-Pot є бонуси та промо, тому перед грою варто заглянути в розділ акцій. Не активуйте нічого навмання. Бонуси можуть бути обмежені в часі або правилами.",
    ],
    "h2_where": "Де знайти Chicken Road на Jack-Pot",
    "where_paras": [
        "Chicken Road легко знайти на Jack-Pot, якщо знати, куди дивитися. Відкрийте розділ casino і перейдіть у Slots або Crash Games. Більшість швидких аркадних ігор зазвичай лежать у цих категоріях.",
        "Найшвидший спосіб — пошук. Введіть Chicken Road у рядок пошуку, дочекайтеся банера гри та відкрийте її. Гра має запуститися в окремому вікні.",
        "Можна шукати за провайдером. Введіть InOut — Jack-Pot покаже ігри цієї студії. Це допомагає знайти не лише Chicken Road, а й інші тайтли InOut.",
        "Іноді гра також з’являється в Crash Games, куди платформи часто ставлять instant games, crash games і тайтли поза класичними слотами.",
    ],
    "short_path_title": "Короткий шлях простий:",
    "short_path_item": "Casino → Crash Games / Slots → Chicken Road → Play Now",
    "short_path_outro": ["Якщо гра не з’являється за назвою, спробуйте пошук за InOut."],
    "h2_play": "Як грати в Chicken Road на Jack-Pot",
    "play_paras": [
        "Chicken Road на Jack-Pot легко запустити. Якщо ви новачок, почніть з Easy. Так простіше зрозуміти гру. Medium уже відчувається різкіше. Hard і Hardcore краще для тих, хто знає, як швидко може зникнути баланс у таких іграх. Перед Play ще раз перевірте ставку. Особливо на телефоні. Один поспішний тап — і раунд стартує з невірною сумою.",
        "Головна кнопка — Cash Out. Натискайте, коли поточний множник вас влаштовує і ви хочете зупинитися. Якщо чекати занадто довго і раунд піде не так, ставка згорає.",
        "Якщо це оригінальний Chicken Road від InOut Games, базові правила на Jack-Pot ті самі, що й на інших платформах: рухатися вперед, ростити множник, Cash Out до програшу раунду.",
    ],
    "h2_demo": "Демо та гра на реальні гроші на Jack-Pot",
    "demo_paras": [
        "Демо Chicken Road доступне на Jack-Pot, і я б почав саме з нього. Не тому, що демо вчить вигравати — ні. Але воно дозволяє подивитися гру без тиску.",
        "У демо ви граєте на віртуальний баланс. Можна міняти складність, пробувати різні ставки, рухати курку по дорозі та тестувати Cash Out у різних точках. Якщо раунд пройшов погано, реальні гроші не постраждають. Режим на гроші відчувається інакше. Гра може виглядати так само, кнопки ті самі, множник росте так само. Але коли в грі ваш баланс, кожен крок відчувається важче.",
        "У демо люди зазвичай грають набагато вільніше. Баланс віртуальний, тому не боляче тестувати складніші режими або йти трохи далі.",
        "На реальні гроші той самий хід відчувається інакше. Та сама кнопка, той самий множник, та сама дорога — але ставка вже ваша. Хтось робить Cash Out занадто рано зі страху програти. Хтось іде занадто далеко, щоб відіграти попередній раунд. Тут і починається тиск. Спочатку використайте демо на Jack-Pot. Вивчіть гру там. Гра на гроші має сенс лише коли ви розумієте механіку та приймаєте ризик.",
    ],
    "h2_mobile": "Chicken Road на мобільному через Jack-Pot",
    "mobile_paras": [
        "Chicken Road нормально працює на телефоні. Відкрийте Jack-Pot, знайдіть гру, поставте ставку і запускайте раунд без важкого інтерфейсу. На мобільному верстка компактніша. Поле ставки, Play і Cash Out залишаються під рукою — у цій грі це важливо. Не хочеться шукати кнопку виходу, коли множник уже рухається.",
        "Раунди короткі, тому мобільна гра підходить. Звичайна сесія — кілька тапів. Відкрили раунд, рухаєте курку, стежите за множником і виходите, коли наступний крок здається занадто ризикованим.",
        "Швидкість здебільшого залежить від пристрою та зв’язку. Свіжий телефон зі стабільним інтернетом буде плавнішим. Старий браузер або слабкий сигнал можуть уповільнити екран. А через маленький дисплей завжди перевіряйте ставку перед Play — одного неуважного тапу вистачить, щоб стартувати з невірною сумою. Грайте через браузер. Уникайте випадкових APK з невідомих сайтів, особливо з «предикторами», зломами чи «особливою» версією Chicken Road.",
    ],
    "h2_final": "Підсумок",
    "final_paras": [
        "Chicken Road добре підходить Jack-Pot, бо грі не потрібне складне налаштування. Відкрили casino, знайшли тайтл, обрали режим, поставили ставку — раунд почався. Для такого швидкого формату це саме те, що потрібно.",
        "Головна привабливість проста: короткі раунди, зрозумілі кнопки, множник що росте і постійний вибір — забрати поточний результат чи ризикнути ще кроком. Зрозуміти легко, але гра може швидко затягнути.",
        "Jack-Pot дає Chicken Road зручне місце для гри, особливо з мобільного. Пошук працює, лобі не перевантажене, демо корисне, якщо хочете спочатку перевірити механіку.",
        "Chicken Road — не інструмент заробітку. Це казино-гра з реальним ризиком. Спочатку демо, потім гроші; ставте ліміти, не гоніться за програшами і ставтеся до кожного раунду як до розваги, а не доходу.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Що таке Jack-Pot?", "Jack-Pot — онлайн-платформа казино та ставок на спорт. Можна грати в слоти, live casino, instant games, crash games і робити спортивні ставки."],
        ["Jack-Pot лише для казино?", "Ні. Казино — лише частина платформи."],
        ["Наскільки швидка реєстрація?", "Реєстрація займає менше хвилини. Після цього сайт може запропонувати вибір бонусу або відкрити вікно депозиту."],
        ["Чи є бонуси на Jack-Pot?", "Так, але дивіться актуальні пропозиції на офіційному сайті."],
        ["Чи можна знайти Chicken Road на Jack-Pot?", "Так, якщо Chicken Road є в лобі Jack-Pot. Спочатку шукайте за назвою гри. Якщо нічого немає — спробуйте провайдера InOut."],
        ["Чи працює Jack-Pot на мобільному?", "Так, Jack-Pot відкривається в мобільному браузері. Лобі казино, спорт, каса та акаунт доступні з телефону. Швидкість залежить від пристрою та зв’язку. Слабкий сигнал або старий браузер можуть уповільнити завантаження ігор."],
        ["Чи безпечний Jack-Pot?", "Так, але переконайтеся, що ви на справжньому домені Jack-Pot. Підроблені копії казино можуть бути дуже схожі на оригінал."],
        ["Яка ліцензія у Jack-Pot?", "За інформацією, яку ми раніше перевіряли, Jack-Pot працює за офшорною ліцензією Anjouan. Це легальна ліцензія, часто у нових брендів казино. Але рівень захисту гравця нижчий, ніж у суворіших регуляторів. Тому важливі репутація, історія виплат і якість підтримки."],
        ["Чи попросить Jack-Pot документи?", "Ймовірно так, перед виведенням. Завантажуйте документи лише через офіційний сайт Jack-Pot."],
        ["Чи миттєві виведення?", "Не завжди. Дрібні виведення можуть бути швидшими. Великі виплати довше через верифікацію, ліміти платіжки або ручні перевірки."],
        ["Чи ризиковано грати на Jack-Pot?", "Так. Слоти, crash games, live casino і ставки на спорт — усе з ризиком. Можна втратити гроші. Ставте ліміти, не гоніться за програшами і не вважайте Jack-Pot способом заробітку. Це розвага, а не дохід."],
    ],
}

EXPORT = {"pl": PL, "ro": RO, "ua": UA}
