# -*- coding: utf-8 -*-
"""Native-quality overrides for casino_articles#11 — FR, DE, ES, RU."""

FR = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road sur 1xBet — ce que les joueurs cherchent",
    "img_hero_alt": "Titres Chicken Road dans le lobby casino 1xBet",
    "intro_paras": [
        "Les joueurs cherchent Chicken Road sur 1xBet parce que le jeu est devenu l'un de ces titres casino rapides dont tout le monde parle. Les règles se comprennent vite : une poule avance, le multiplicateur monte, et il faut quitter le tour avant qu'il casse.",
        "C'est tout l'attrait. Pas de longue config de slot, pas d'écran bonus compliqué, pas besoin d'apprendre vingt symboles avant le premier tour. Vous ouvrez le jeu et comprenez presque tout de suite la pression de base : prendre le résultat actuel ou tenter un pas de plus.",
        "Chicken Road correspond au type de jeux que beaucoup de joueurs cherchent sur 1xBet — lancement rapide, tours courts, commandes simples et décisions de Cash Out. C'est un format qui convient à ceux qui ne veulent pas de gameplay lent.",
        "Mais la disponibilité peut dépendre de la région et du lobby casino. Sur certains comptes, le Chicken Road original d'InOut Games apparaît par son nom. Sur d'autres, il peut être absent, ou des jeux instant/crash similaires s'affichent à la place.",
        "La première chose à faire est simple : vérifiez la recherche casino 1xBet. Tapez Chicken Road ou InOut et voyez ce que le lobby affiche réellement pour votre région.",
    ],
    "h2_about": "À propos de 1xBet",
    "img_about_alt": "Page d'accueil paris sportifs et casino 1xBet",
    "about_paras": [
        "1xBet est une grande plateforme de paris et casino où tout est regroupé dans un seul compte. Les paris sportifs sont surtout ce que les gens connaissent, mais le site a aussi une grosse section casino.",
        "Sur la plateforme, on trouve slots, live casino, crash games, instant games, eSports, sports virtuels et paris en direct. Ce n'est plus seulement un bookmaker. C'est plutôt un lobby complet avec différents formats.",
        "Pour les jeux rapides, cette structure est utile. Vous ouvrez le casino, utilisez la recherche, parcourez les catégories et passez entre slots, live ou crash sans quitter le compte.",
        "Chicken Road ou des jeux similaires conviennent bien à ce type de plateforme : pas de longue préparation. Tours courts, boutons simples et accès rapide — exactement ce qu'attendent beaucoup de joueurs de la section instant games.",
    ],
    "h2_available": "Chicken Road est-il disponible sur 1xBet ?",
    "img_search_alt": "Résultats de recherche Chicken Road sur 1xBet",
    "available_paras": [
        "Oui, Chicken Road est sur 1xBet, avec d'autres titres de la même gamme InOut Games. Vous trouvez le Chicken Road original et Chicken Road 2. Ici la situation est meilleure que sur certaines plateformes : vous ne cherchez pas une copie — 1xBet affiche vraiment la série Chicken Road dans le lobby.",
        "Le moyen le plus simple de vérifier est la barre de recherche. Tapez Chicken Road et attendez les cartes de jeu. Si le lobby fonctionne comme sur la capture, vous devriez voir une rangée de titres Chicken Road dans la catégorie slots. Vous pouvez aussi chercher par fournisseur — InOut. Utile si vous voulez voir d'autres jeux du même studio. Point important : le mode Demo est aussi disponible. Vous pouvez ouvrir le jeu, tester la mécanique avec un solde virtuel, essayer différentes versions et comprendre multiplicateur et Cash Out avant l'argent réel.",
    ],
    "short_path_title": "Le chemin court :",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Vérifier Chicken Road dans le lobby 1xBet",
    "img_filter_alt": "Filtre et recherche fournisseur InOut sur 1xBet",
    "lobby_paras": [
        "La façon la plus propre de vérifier Chicken Road sur 1xBet, ce n'est pas les catégories, c'est la recherche du lobby. Ouvrez le casino et tapez Chicken Road. Vous pouvez aussi chercher InOut — pratique pour voir tout le catalogue du fournisseur, pas un seul titre.",
        "Si Chicken Road n'apparaît pas sur votre compte, vérifiez deux choses avant de conclure que le jeu est retiré. D'abord, essayez Slots, Crash Games, Instant Games ou Other. Ensuite, rappelez-vous que les lobbies changent selon le pays, la devise et la région du compte.",
    ],
    "quick_check_title": "La vérification rapide ressemble à ceci :",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": [
        "Je ne ferais pas défiler tout le lobby manuellement. Il y a trop de jeux, et la recherche est plus rapide.",
    ],
    "h2_play": "Comment fonctionnent les jeux Chicken Road sur 1xBet",
    "img_play_alt": "Gameplay Chicken Road avec multiplicateur et Cash Out sur 1xBet",
    "play_paras": [
        "Sur 1xBet, Chicken Road n'est pas un seul titre dans les résultats. Le lobby peut afficher plusieurs versions : le jeu original, 2.0, Bonus, Gold, Vegas, Race et d'autres sorties à thème poulet. Elles ont l'air différentes, mais l'idée de base se comprend vite.",
        "Vous commencez avec une mise modeste. Ensuite vous décidez du niveau de risque. Les modes plus sûrs avancent plus lentement, les modes agressifs poussent le multiplicateur plus fort.",
        "Une fois le tour lancé, la même boucle de décision revient. La poule avance, le multiplicateur monte, et le résultat actuel devient plus tentant. À un moment vous encaissez ou continuez.",
        "C'est là que ces jeux créent la pression. Pas besoin de règles compliquées. Tout repose sur une petite décision répétée : assez pour maintenant, ou un pas de plus ?",
        "Cash Out est le bouton le plus important. Si vous l'utilisez à temps, le tour se termine avec le résultat actuel. Si vous attendez trop, la mise peut disparaître en un mauvais pas. Le jeu est simple à ouvrir, pas toujours simple à maîtriser.",
    ],
    "h2_why": "Pourquoi Chicken Road convient au lobby 1xBet",
    "img_versions_alt": "Différentes versions Chicken Road dans le lobby 1xBet",
    "why_paras": [
        "1xBet est une plateforme où les jeux rapides ne détonnent pas. Le lobby a déjà slots, crash, instant games, live casino et paris sportifs — Chicken Road entre naturellement dans cette catégorie.",
        "Ce qui se démarque sur 1xBet, ce n'est pas seulement le jeu original, mais le nombre de versions liées dans le lobby. Un joueur peut ouvrir Chicken Road, puis comparer avec Chicken Road 2.0, Gold, Vegas, Race ou Bonus sans quitter la plateforme.",
        "La vraie question pour les utilisateurs 1xBet n'est pas seulement comment Chicken Road fonctionne, mais quelle version ouvrir en premier.",
        "L'original convient mieux pour comprendre le format. Chicken Road 2.0 paraît plus abouti. Gold et Vegas sont plus thématiques. Race est plus rapide et dynamique. Les versions Bonus visent ceux qui veulent plus de features.",
        "Sur 1xBet, Chicken Road n'est pas un jeu isolé. C'est plutôt une petite catégorie à part entière.",
    ],
    "h2_mobile": "Jeu mobile via 1xBet",
    "img_mobile_alt": "Chicken Road sur l'application mobile 1xBet",
    "mobile_paras": [
        "1xBet convient assez bien à ce type de jeu sur mobile. Vous ouvrez le casino depuis l'app ou le navigateur, cherchez Chicken Road, choisissez la version et lancez sans parcourir tout le lobby.",
        "Sur téléphone, ces jeux ont du sens. Sessions courtes, écran non surchargé, boutons principaux à portée. Pas besoin d'un grand setup desktop pour tester quelques tours ou comparer les versions.",
        "Surveillez surtout le champ de mise. Sur mobile, un tap rapide peut lancer le tour avec le mauvais montant, surtout en passant du Demo au réel.",
        "Utilisez l'app officielle 1xBet ou la version navigateur. Évitez les APK aléatoires, apps « predictor » et tout ce qui promet un build Chicken Road spécial. Si le jeu est dans le lobby 1xBet, inutile de le télécharger ailleurs.",
    ],
    "h2_bonuses": "Bonus et promos sur 1xBet",
    "img_bonus_alt": "Section bonus et promos casino 1xBet",
    "bonus_paras": [
        "Les bonus autour de Chicken Road sur 1xBet ne viennent généralement pas du jeu lui-même. Ils viennent de la plateforme. Le jeu peut être la raison de votre visite, mais les règles promo sont écrites par 1xBet.",
        "Le détail principal est l'éligibilité. Certains bonus ne valent que pour les slots. D'autres pour le sport. D'autres excluent totalement crash et instant games. Chicken Road est exactement dans cette zone où il ne faut rien supposer.",
        "Avant d'activer un bonus, ouvrez les conditions. Pour Chicken Road, vérifiez si crash ou instant games comptent pour le wager. Si le jeu ne compte pas, le bonus peut sembler intéressant mais ne servira pas pour ce titre.",
        "Vérifiez aussi l'effet sur votre solde. Certaines promos bloquent les fonds bonus jusqu'au wager, limitent le cashout max ou restreignent la mise pendant le bonus. Avec des jeux rapides, les tours vont vite et il est facile de casser une règle sans le voir. Approche sûre : ouvrir la promo, lire la liste de jeux, puis décider. Si Chicken Road ou les instant games InOut ne sont pas mentionnés, ne devinez pas.",
    ],
    "h2_safety": "Sécurité et confiance sur 1xBet",
    "safety_paras": [
        "Les sites copies peuvent paraître convaincants. Mêmes couleurs, même layout, boutons familiers. Puis quelque chose cloche : SMS trop tôt, APK imposé, ou demande de paiement avant la caisse normale.",
        "Évitez aussi les apps predictor. Chicken Road n'a pas besoin de « signaux », bots ou tables secrètes. Si quelqu'un promet le prochain pas sûr, il vend surtout de la confiance, pas un vrai outil.",
        "Gardez le jeu dans la bonne catégorie : divertissement rapide, pas plan de revenu. Avec de l'argent réel, le résultat peut aller dans les deux sens — ne construisez pas une session autour de récupérer des pertes ou d'un tour parfait.",
    ],
    "h2_final": "Avis final",
    "final_paras": [
        "1xBet est un bon endroit pour les jeux casino rapides : recherche, catégories, mobile et plusieurs titres Chicken Road au même endroit. Vous pouvez ouvrir l'original, comparer avec 2.0, Gold, Vegas, Race ou Bonus et tester celui qui vous convient.",
        "Le meilleur move : commencer par Demo. Pas comme « méthode d'entraînement », mais pour voir quelle version vous plaît vraiment. Certains Chicken Road sont plus calmes, d'autres plus dynamiques. Oui, 1xBet peut être pratique pour les joueurs Chicken Road. Vérifiez le jeu dans votre propre lobby, utilisez Demo d'abord, et ne laissez pas un tour rapide devenir une longue session sans plan.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Chicken Road est-il disponible sur 1xBet ?", "Oui. Sur 1xBet, Chicken Road apparaît dans le lobby casino avec d'autres jeux InOut. Vous pouvez voir l'original, Chicken Road 2.0, Gold, Vegas, Race, Bonus et d'autres titres liés."],
        ["Comment trouver Chicken Road sur 1xBet ?", "Ouvrez le casino et utilisez la recherche. Tapez Chicken Road et vérifiez les cartes affichées. C'est plus rapide que de faire défiler tout le lobby."],
        ["Puis-je chercher par fournisseur InOut ?", "Oui. Chercher InOut est une bonne option pour voir toute la liste du fournisseur. Parfois le lobby montre plus de jeux ainsi que par un seul titre."],
        ["Et si Chicken Road n'est pas dans le lobby ?", "Vérifiez l'orthographe et essayez InOut. Si rien n'apparaît, le jeu peut être masqué pour votre région, devise ou version du lobby. Regardez crash, instant, slots ou autres catégories rapides."],
        ["Puis-je jouer en Demo sur 1xBet ?", "Oui, le mode Demo est disponible pour les titres Chicken Road sur 1xBet. Utile pour comparer les versions sans utiliser le solde réel."],
        ["Comment fonctionnent les jeux style Chicken Road ?", "Le jeu repose sur des décisions courtes. Vous fixez une mise, la poule avance, le multiplicateur monte, et vous décidez quand Cash Out. Attendre trop longtemps peut faire perdre la mise."],
        ["Les bonus fonctionnent-ils avec les crash games ?", "Pas toujours. Certains bonus 1xBet ne comptent que slots ou sport. Avant d'activer une promo, vérifiez si crash ou instant games entrent dans le wager."],
        ["Les apps predictor sont-elles sûres ?", "Non, je les éviterais. Predictors, bots, APK et signaux Telegram promettent souvent plus qu'ils ne peuvent. Certains sont inutiles, d'autres risqués pour le compte ou l'appareil."],
        ["Quelle version Chicken Road ouvrir en premier sur 1xBet ?", "Commencez par le Chicken Road original pour comprendre le format de base. C'est la version la plus claire de la série."],
        ["Chicken Road est-il différent dans l'app 1xBet ?", "Un peu, surtout à cause de l'écran. Dans l'app, tout est plus proche : cartes, mise, boutons et Cash Out. Pratique, mais ralentissez avant de lancer un tour."],
    ],
}

DE = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road auf 1xBet — wonach Spieler suchen",
    "img_hero_alt": "Chicken-Road-Titel im 1xBet-Casino-Lobby",
    "intro_paras": [
        "Spieler suchen Chicken Road auf 1xBet, weil das Spiel zu den schnellen Casino-Titeln gehört, über die überall gesprochen wird. Die Regeln sind leicht zu verstehen: Das Huhn geht vorwärts, der Multiplikator steigt, und man muss die Runde verlassen, bevor sie bricht.",
        "Das ist der ganze Reiz. Kein langes Slot-Setup, kein komplizierter Bonus-Bildschirm, keine zwanzig Symbole vor der ersten Runde. Man öffnet das Spiel und versteht fast sofort den Druck: aktuelles Ergebnis nehmen oder noch einen Schritt wagen.",
        "Chicken Road passt zum Typ Spiel, den viele auf 1xBet suchen — schneller Start, kurze Runden, einfache Steuerung und Cash-Out-Entscheidungen. Gut für alle, die kein langsames Gameplay wollen.",
        "Die Verfügbarkeit kann aber von Region und Casino-Lobby abhängen. Manchmal erscheint das originale Chicken Road von InOut Games namentlich. Manchmal fehlt es oder ähnliche Instant/Crash-Spiele werden gezeigt.",
        "Der erste Schritt ist einfach: 1xBet-Casino-Suche prüfen. Chicken Road oder InOut eingeben und sehen, was Ihr Lobby für Ihre Region zeigt.",
    ],
    "h2_about": "Über 1xBet",
    "img_about_alt": "1xBet Sportwetten- und Casino-Startseite",
    "about_paras": [
        "1xBet ist eine große Wett- und Casino-Plattform mit allem in einem Konto. Sportwetten kennt man am ehesten, aber die Seite hat auch einen großen Casino-Bereich.",
        "Auf der Plattform finden Spieler Slots, Live Casino, Crash Games, Instant Games, eSports, Virtual Sports und Live-Wetten. Es ist nicht mehr nur ein Sportsbook, sondern ein volles Glücksspiel-Lobby.",
        "Für schnelle Spiele ist diese Struktur nützlich. Casino öffnen, suchen, Kategorien prüfen und zwischen Slots, Live oder Crash wechseln — alles im gleichen Konto.",
        "Chicken Road oder ähnliche Spiele passen gut: kein langes Setup. Kurze Runden, einfache Buttons und schneller Zugang — genau das, was viele von Instant Games erwarten.",
    ],
    "h2_available": "Ist Chicken Road auf 1xBet verfügbar?",
    "img_search_alt": "Suchergebnisse für Chicken Road auf 1xBet",
    "available_paras": [
        "Ja, Chicken Road ist auf 1xBet, zusammen mit anderen Titeln der InOut-Games-Reihe. Man findet das originale Chicken Road und Chicken Road 2. Hier ist die Lage besser als auf manchen Plattformen — 1xBet zeigt die Chicken-Road-Serie wirklich im Lobby.",
        "Am einfachsten prüft man es über die Suche. Chicken Road eingeben und auf die Spielkarten warten. Wenn das Lobby wie im Screenshot funktioniert, sollte eine Reihe Chicken-Road-Titel unter Slots erscheinen. Auch nach Anbieter — InOut — suchen. Wichtig: Demo ist verfügbar. Spiel öffnen, Mechanik mit virtuellem Guthaben testen, Versionen vergleichen und Multiplikator sowie Cash Out verstehen, bevor echtes Geld im Spiel ist.",
    ],
    "short_path_title": "Der kurze Weg:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Chicken Road im 1xBet-Lobby prüfen",
    "img_filter_alt": "Filter und Anbietersuche für InOut-Spiele auf 1xBet",
    "lobby_paras": [
        "Am saubersten prüft man Chicken Road auf 1xBet über die Lobby-Suche, nicht über Kategorien. Casino öffnen und Chicken Road eingeben. Oder InOut — besser, wenn man den ganzen Anbieterkatalog sehen will.",
        "Wenn Chicken Road in Ihrem Konto nicht erscheint, zwei Dinge prüfen, bevor man annimmt, das Spiel sei weg. Erst Kategorien wie Slots, Crash Games, Instant Games oder Other. Zweitens: Lobbies ändern sich je nach Land, Währung und Kontoregion.",
    ],
    "quick_check_title": "Die schnelle Prüfung sieht so aus:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": [
        "Ich würde das ganze Lobby nicht manuell scrollen. Zu viele Spiele — Suche ist einfach schneller.",
    ],
    "h2_play": "Wie Chicken-Road-Spiele auf 1xBet funktionieren",
    "img_play_alt": "Chicken-Road-Gameplay mit Multiplikator und Cash Out auf 1xBet",
    "play_paras": [
        "Auf 1xBet ist Chicken Road nicht nur ein Titel in den Suchergebnissen. Das Lobby kann mehrere Versionen zeigen: Original, 2.0, Bonus, Gold, Vegas, Race und andere Huhn-Themen. Sie sehen unterschiedlich aus, aber die Grundidee ist leicht zu erfassen.",
        "Man startet mit einem einfachen Einsatz. Dann entscheidet man über das Risiko. Sicherere Modi gehen langsamer, aggressive Modi treiben den Multiplikator stärker.",
        "Nach Start folgt dieselbe Entscheidungsschleife. Das Huhn bewegt sich, der Multiplikator steigt, das aktuelle Ergebnis wird verlockender. Irgendwann nimmt man die Auszahlung oder geht weiter.",
        "Hier entsteht der Druck. Keine komplizierten Regeln nötig. Alles dreht sich um eine kleine wiederholte Entscheidung: reicht es jetzt, oder noch ein Schritt?",
        "Cash Out ist der wichtigste Button. Rechtzeitig genutzt endet die Runde mit dem aktuellen Ergebnis. Zu langes Warten kann den Einsatz in einem schlechten Schritt kosten. Einfach zu öffnen, nicht immer einfach zu kontrollieren.",
    ],
    "h2_why": "Warum Chicken Road zum 1xBet-Lobby passt",
    "img_versions_alt": "Verschiedene Chicken-Road-Versionen im 1xBet-Lobby",
    "why_paras": [
        "1xBet ist eine Plattform, auf der schnelle Spiele nicht fehl am Platz wirken. Slots, Crash, Instant Games, Live Casino und Sportwetten sind schon da — Chicken Road passt natürlich in die Quick-Play-Kategorie.",
        "Auffällig auf 1xBet ist nicht nur das Original, sondern die Anzahl verwandter Versionen im Lobby. Man kann Chicken Road öffnen und mit 2.0, Gold, Vegas, Race oder Bonus vergleichen, ohne die Plattform zu wechseln.",
        "Die echte Frage für 1xBet-Nutzer ist nicht nur, wie Chicken Road funktioniert, sondern welche Version man zuerst öffnen soll.",
        "Das Original eignet sich am besten zum Verstehen des Formats. Chicken Road 2.0 wirkt ausgereifter. Gold und Vegas sind stärker thematisch. Race ist schneller und dynamischer. Bonus-Versionen für feature-lastigeres Gameplay.",
        "Auf 1xBet ist Chicken Road keine versteckte Einzelspielerei. Es wirkt eher wie eine kleine eigene Kategorie.",
    ],
    "h2_mobile": "Mobiles Spiel über 1xBet",
    "img_mobile_alt": "Chicken Road in der 1xBet-Mobile-App",
    "mobile_paras": [
        "1xBet eignet sich gut für diesen Spieltyp mobil. Casino in App oder Browser öffnen, Chicken Road suchen, Version wählen und starten, ohne das ganze Lobby zu durchsuchen.",
        "Am Handy machen diese Spiele Sinn. Kurze Sessions, nicht überladener Bildschirm, Hauptbuttons in Reichweite. Kein großes Desktop-Setup nötig, um ein paar Runden zu testen oder Versionen zu vergleichen.",
        "Achten Sie besonders auf das Einsatzfeld. Am Handy kann ein schneller Tap die Runde mit falschem Betrag starten, besonders beim Wechsel zwischen Demo und Echtgeld.",
        "Offizielle 1xBet-App oder Browserversion nutzen. Zufällige APKs, Predictor-Apps und spezielle Chicken-Road-Builds meiden. Wenn das Spiel im 1xBet-Lobby ist, gibt es keinen Grund, es woanders herunterzuladen.",
    ],
    "h2_bonuses": "Boni und Promos auf 1xBet",
    "img_bonus_alt": "1xBet-Casino-Boni und Promobereich",
    "bonus_paras": [
        "Boni rund um Chicken Road auf 1xBet kommen meist nicht vom Spiel selbst, sondern von der Plattform. Das Spiel kann der Grund für den Besuch sein, aber die Promo-Regeln schreibt 1xBet.",
        "Entscheidend ist die Berechtigung. Manche Boni gelten nur für Slots, manche für Sport, manche schließen Crash und Instant Games komplett aus. Chicken Road liegt genau in der Zone, wo man nichts annehmen sollte.",
        "Vor Aktivierung die AGB lesen. Für Chicken Road prüfen, ob Crash oder Instant Games zum Wagering zählen. Zählt das Spiel nicht, sieht der Bonus gut aus, hilft aber nicht für dieses Spiel.",
        "Prüfen Sie auch die Wirkung auf Ihr Guthaben. Manche Promos sperren Bonusgeld bis zum Wagering, begrenzen Max-Cashout oder die Einsatzhöhe. Bei schnellen Spielen gehen Runden schnell — leicht, eine Bonusregel zu brechen. Sicher: Promo öffnen, Spieleliste lesen, dann entscheiden. Wenn Chicken Road oder InOut Instant Games nicht erwähnt werden, nicht raten.",
    ],
    "h2_safety": "Sicherheit und Vertrauen auf 1xBet",
    "safety_paras": [
        "Kopien können überzeugend wirken. Gleiche Farben, Layout, bekannte Buttons. Dann stimmt etwas nicht: SMS zu früh, APK-Druck oder Zahlungsdaten vor der normalen Kasse.",
        "Predictor-Apps meiden. Chicken Road braucht keine Signale, Bots oder Geheimtabellen. Wer den nächsten sicheren Schritt verspricht, verkauft meist Selbstvertrauen, kein echtes Tool.",
        "Das Spiel richtig einordnen: schnelle Unterhaltung, kein Einkommensplan. Mit echtem Geld kann es in beide Richtungen gehen — keine Session um Verluste zurückholen oder eine perfekte Runde jagen.",
    ],
    "h2_final": "Fazit",
    "final_paras": [
        "1xBet ist stark für schnelle Casino-Spiele: Suche, Kategorien, Mobile und mehrere Chicken-Road-Titel an einem Ort. Original öffnen, mit 2.0, Gold, Vegas, Race oder Bonus vergleichen und testen, was zum Stil passt.",
        "Am besten mit Demo starten — nicht als Trainingsmethode, sondern um zu sehen, welche Version gefällt. Manche Chicken-Road-Spiele wirken ruhiger, manche dynamischer. Ja, 1xBet kann praktisch für Chicken-Road-Spieler sein. Spiel im eigenen Lobby prüfen, zuerst Demo, und nicht aus einer schnellen Runde eine lange Session ohne Plan machen.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Ist Chicken Road auf 1xBet verfügbar?", "Ja. Auf 1xBet erscheint Chicken Road im Casino-Lobby mit anderen InOut-Spielen. Original, Chicken Road 2.0, Gold, Vegas, Race, Bonus und verwandte Titel sind möglich."],
        ["Wie finde ich Chicken Road auf 1xBet?", "Casino öffnen und die Suche nutzen. Chicken Road eingeben und die Spielkarten prüfen. Schneller als das ganze Lobby scrollen."],
        ["Kann ich nach Anbieter InOut suchen?", "Ja. InOut-Suche zeigt oft die volle Anbieterliste. Manchmal mehr Spiele als bei nur einem Titel."],
        ["Was, wenn Chicken Road nicht im Lobby ist?", "Rechtschreibung prüfen und InOut versuchen. Wenn nichts erscheint, kann das Spiel für Region, Währung oder Lobby-Version verborgen sein. Crash, Instant, Slots oder andere schnelle Kategorien prüfen."],
        ["Kann ich Demo auf 1xBet spielen?", "Ja, Demo ist für Chicken-Road-Titel auf 1xBet verfügbar. Nützlich, um Versionen ohne echtes Guthaben zu vergleichen."],
        ["Wie funktionieren Chicken-Road-Spiele?", "Kurze Entscheidungen. Einsatz setzen, Huhn bewegen, Multiplikator steigen lassen, Cash-Out-Zeitpunkt wählen. Zu langes Warten kann den Einsatz kosten."],
        ["Funktionieren Boni mit Crash Games?", "Nicht immer. Manche 1xBet-Boni zählen nur Slots oder Sport. Vor Aktivierung prüfen, ob Crash oder Instant Games im Wagering enthalten sind."],
        ["Sind Predictor-Apps sicher?", "Nein, ich würde sie meiden. Predictors, Bots, APKs und Telegram-Signale versprechen oft zu viel. Manche nutzlos, andere riskant für Konto oder Gerät."],
        ["Welche Chicken-Road-Version zuerst auf 1xBet?", "Mit dem originalen Chicken Road starten, um das Basisformat zu verstehen. Das ist die klarste Version der Serie."],
        ["Fühlt sich Chicken Road in der 1xBet-App anders an?", "Ein wenig, vor allem wegen des Bildschirms. In der App ist alles näher: Karten, Einsatz, Buttons und Cash Out. Praktisch, aber vor dem Start einer Runde langsamer werden."],
    ],
}

ES = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road en 1xBet — qué buscan los jugadores",
    "img_hero_alt": "Títulos Chicken Road en el lobby casino de 1xBet",
    "intro_paras": [
        "Los jugadores buscan Chicken Road en 1xBet porque el juego se ha convertido en uno de esos títulos casino rápidos de los que todo el mundo habla. Las reglas se entienden al momento: la gallina avanza, el multiplicador crece y hay que salir de la ronda antes de que se rompa.",
        "Ese es todo el atractivo. Sin larga configuración de slot, sin pantalla de bonus complicada, sin aprender veinte símbolos antes de la primera ronda. Abres el juego y entiendes casi al instante la presión básica: tomar el resultado actual o probar un paso más.",
        "Chicken Road encaja con el estilo de juegos que muchos buscan en 1xBet: lanzamiento rápido, rondas cortas, controles simples y decisiones de Cash Out. Un formato ideal para quien no quiere gameplay lento.",
        "Pero la disponibilidad puede depender de la región y del lobby casino. En algunas cuentas aparece el Chicken Road original de InOut Games por nombre. En otras puede no estar, o mostrarse juegos instant/crash similares.",
        "Lo primero es simple: revisa la búsqueda casino de 1xBet. Escribe Chicken Road o InOut y mira qué muestra el lobby en tu región.",
    ],
    "h2_about": "Sobre 1xBet",
    "img_about_alt": "Página principal de apuestas y casino de 1xBet",
    "about_paras": [
        "1xBet es una gran plataforma de apuestas y casino con todo en una cuenta. Las apuestas deportivas son lo que más conoce la gente, pero el sitio también tiene una gran sección casino.",
        "En la plataforma hay slots, live casino, crash games, instant games, eSports, deportes virtuales y apuestas en vivo. Ya no es solo un sportsbook, sino un lobby completo con distintos formatos.",
        "Para juegos rápidos, esta estructura ayuda. Abres casino, usas búsqueda, revisas categorías y cambias entre slots, live o crash sin salir de la cuenta.",
        "Chicken Road o juegos similares encajan bien: sin setup largo. Rondas cortas, botones simples y acceso rápido — lo que muchos esperan de instant games.",
    ],
    "h2_available": "¿Está Chicken Road disponible en 1xBet?",
    "img_search_alt": "Resultados de búsqueda de Chicken Road en 1xBet",
    "available_paras": [
        "Sí, Chicken Road está en 1xBet, con otros títulos de la misma línea InOut Games. Puedes encontrar el Chicken Road original y Chicken Road 2. Aquí la situación es mejor que en otras plataformas: 1xBet muestra la serie Chicken Road en el lobby.",
        "La forma más fácil de comprobarlo es la barra de búsqueda. Escribe Chicken Road y espera las tarjetas del juego. Si el lobby funciona como en la captura, deberías ver una fila de títulos Chicken Road en slots. También puedes buscar por proveedor — InOut. Importante: el modo Demo también está disponible para probar mecánica, versiones, multiplicador y Cash Out antes del dinero real.",
    ],
    "short_path_title": "El camino corto:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Comprobar Chicken Road en el lobby de 1xBet",
    "img_filter_alt": "Filtro y búsqueda de proveedor InOut en 1xBet",
    "lobby_paras": [
        "La forma más limpia de comprobar Chicken Road en 1xBet no son las categorías, sino la búsqueda del lobby. Abre casino y escribe Chicken Road. También InOut — mejor si quieres ver todo el catálogo del proveedor.",
        "Si Chicken Road no aparece en tu cuenta, revisa dos cosas antes de asumir que el juego fue retirado. Primero categorías como Slots, Crash Games, Instant Games u Other. Segundo: los lobbies cambian por país, moneda y región de cuenta.",
    ],
    "quick_check_title": "La comprobación rápida es así:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["No haría scroll manual por todo el lobby. Hay demasiados juegos; la búsqueda es más rápida."],
    "h2_play": "Cómo funcionan los juegos Chicken Road en 1xBet",
    "img_play_alt": "Gameplay de Chicken Road con multiplicador y Cash Out en 1xBet",
    "play_paras": [
        "En 1xBet, Chicken Road no es un solo título en los resultados. El lobby puede mostrar varias versiones: original, 2.0, Bonus, Gold, Vegas, Race y otros temas de gallina. Se ven distintas, pero la idea base se capta rápido.",
        "Empiezas con una apuesta sencilla. Luego decides cuánto riesgo tomar. Modos más seguros avanzan más lento; modos agresivos empujan más el multiplicador.",
        "Tras iniciar la ronda, repites el mismo bucle de decisión. La gallina avanza, el multiplicador crece y el resultado actual se vuelve más tentador. En algún momento cobras o sigues.",
        "Ahí está la presión. No hacen falta reglas complicadas. Todo gira en una pequeña decisión repetida: ¿basta por ahora o un paso más?",
        "Cash Out es el botón clave. Si lo usas a tiempo, la ronda termina con el resultado actual. Si esperas demasiado, la apuesta puede desaparecer en un mal paso.",
    ],
    "h2_why": "Por qué Chicken Road encaja en el lobby de 1xBet",
    "img_versions_alt": "Distintas versiones Chicken Road en el lobby de 1xBet",
    "why_paras": [
        "1xBet es una plataforma donde los juegos rápidos no desentonan. Ya hay slots, crash, instant games, live casino y deportes — Chicken Road encaja naturalmente.",
        "Lo que destaca en 1xBet no es solo el original, sino cuántas versiones relacionadas muestra el lobby. Puedes abrir Chicken Road y comparar con 2.0, Gold, Vegas, Race o Bonus sin cambiar de plataforma.",
        "La pregunta real para usuarios de 1xBet no es solo cómo funciona Chicken Road, sino qué versión abrir primero.",
        "El original ayuda a entender el formato. Chicken Road 2.0 se siente más pulido. Gold y Vegas son más temáticos. Race es más rápido y dinámico. Las versiones Bonus son para quien quiere más features.",
        "En 1xBet, Chicken Road no es un juego enterrado. Parece más una pequeña categoría propia.",
    ],
    "h2_mobile": "Juego móvil a través de 1xBet",
    "img_mobile_alt": "Chicken Road en la app móvil de 1xBet",
    "mobile_paras": [
        "1xBet funciona bien para este tipo de juego en móvil. Abres casino desde app o navegador, buscas Chicken Road, eliges versión y lanzas sin recorrer todo el lobby.",
        "En el teléfono estos juegos tienen sentido. Sesiones cortas, pantalla no sobrecargada, botones principales cerca. No necesitas desktop para probar rondas o comparar versiones.",
        "Cuidado con el campo de apuesta. En móvil, un toque rápido puede iniciar la ronda con monto equivocado, sobre todo al cambiar entre Demo y dinero real.",
        "Usa la app oficial de 1xBet o la versión navegador. Evita APK aleatorios, apps predictor y builds «especiales» de Chicken Road. Si está en el lobby de 1xBet, no hace falta descargarlo de otro sitio.",
    ],
    "h2_bonuses": "Bonos y promos en 1xBet",
    "img_bonus_alt": "Sección de bonos y promos casino de 1xBet",
    "bonus_paras": [
        "Los bonos alrededor de Chicken Road en 1xBet normalmente no vienen del juego, sino de la plataforma. El juego puede ser tu motivo, pero las reglas las escribe 1xBet.",
        "Lo clave es la elegibilidad. Algunos bonos solo valen para slots, otros para deportes, otros excluyen crash e instant games por completo. Chicken Road está en esa zona donde no debes suponer nada.",
        "Antes de activar un bono, lee términos y condiciones. Para Chicken Road, comprueba si crash o instant games cuentan para el wagering. Si el juego no cuenta, el bono puede verse bien pero no servir para este título.",
        "Revisa también cómo afecta al saldo. Algunas promos bloquean fondos bonus hasta completar wagering, limitan cashout máximo o restringen apuesta. Con juegos rápidos, las rondas van veloz y es fácil romper una regla sin notarlo.",
    ],
    "h2_safety": "Seguridad y confianza en 1xBet",
    "safety_paras": [
        "Los sitios copia pueden parecer convincentes. Mismos colores, layout, botones familiares. Luego algo falla: SMS demasiado pronto, APK forzado o datos de pago antes de la caja normal.",
        "Evita apps predictor. Chicken Road no necesita señales, bots ni tablas secretas. Quien promete el siguiente paso seguro suele vender confianza, no una herramienta real.",
        "Mantén el juego en su sitio: entretenimiento rápido, no plan de ingresos. Con dinero real el resultado puede ir en cualquier dirección — no bases la sesión en recuperar pérdidas o cazar una ronda perfecta.",
    ],
    "h2_final": "Opinión final",
    "final_paras": [
        "1xBet es un buen sitio para juegos casino rápidos: búsqueda, categorías, móvil y varios títulos Chicken Road en un lugar. Puedes abrir el original, comparar con 2.0, Gold, Vegas, Race o Bonus y probar el que encaje con tu estilo.",
        "Lo mejor: empezar con Demo. No como método de entrenamiento, sino para ver qué versión te gusta. Sí, 1xBet puede ser cómodo para jugadores de Chicken Road. Comprueba el juego en tu propio lobby, usa Demo primero y no dejes que una ronda rápida se convierta en sesión larga sin plan.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["¿Está Chicken Road disponible en 1xBet?", "Sí. En 1xBet, Chicken Road aparece en el lobby casino con otros juegos InOut. Puedes ver el original, Chicken Road 2.0, Gold, Vegas, Race, Bonus y títulos relacionados."],
        ["¿Cómo encuentro Chicken Road en 1xBet?", "Abre casino y usa la búsqueda. Escribe Chicken Road y revisa las tarjetas. Más rápido que scroll por todo el lobby."],
        ["¿Puedo buscar por proveedor InOut?", "Sí. Buscar InOut muestra la lista completa del proveedor. A veces más juegos que con un solo título."],
        ["¿Y si Chicken Road no está en el lobby?", "Revisa ortografía y prueba InOut. Si no aparece nada, puede estar oculto por región, moneda o versión del lobby. Mira crash, instant, slots u otras categorías rápidas."],
        ["¿Puedo jugar Demo en 1xBet?", "Sí, el modo Demo está disponible para títulos Chicken Road en 1xBet. Útil para comparar versiones sin saldo real."],
        ["¿Cómo funcionan los juegos tipo Chicken Road?", "Decisiones cortas. Pones apuesta, la gallina avanza, el multiplicador crece y decides cuándo Cash Out. Esperar demasiado puede costar la apuesta."],
        ["¿Los bonos funcionan con crash games?", "No siempre. Algunos bonos 1xBet solo cuentan slots o deportes. Antes de activar, comprueba si crash o instant games entran en wagering."],
        ["¿Son seguras las apps predictor?", "No, las evitaría. Predictors, bots, APK y señales Telegram suelen prometer más de lo que dan. Algunas inútiles, otras riesgosas para cuenta o dispositivo."],
        ["¿Qué versión Chicken Road abrir primero en 1xBet?", "Empieza con el Chicken Road original para entender el formato base. Es la versión más clara de la serie."],
        ["¿Chicken Road se siente distinto en la app 1xBet?", "Un poco, sobre todo por la pantalla. En la app todo está más cerca: tarjetas, apuesta, botones y Cash Out. Conveniente, pero ve más despacio antes de iniciar una ronda."],
    ],
}

RU = {
    "h1": "1xBet - Chicken Road",
    "h2_intro": "Chicken Road на 1xBet — что ищут игроки",
    "img_hero_alt": "Тайтлы Chicken Road в лобби казино 1xBet",
    "intro_paras": [
        "Игроки ищут Chicken Road на 1xBet, потому что игра стала одним из тех быстрых casino-тайтлов, о которых говорят повсюду. Правила понятны сразу: курица идёт вперёд, множитель растёт, и нужно выйти из раунда до «поломки».",
        "В этом весь прикол. Без долгой настройки слота, без сложного bonus-экрана, без двадцати символов до первого раунда. Открываете игру и почти сразу чувствуете давление: забрать текущий результат или рискнуть ещё шагом.",
        "Chicken Road подходит под стиль игр, которые многие ищут на 1xBet — быстрый запуск, короткие раунды, простое управление и решения Cash Out. Формат для тех, кто не хочет медленный геймплей.",
        "Но доступность зависит от региона и лобби казино. На одних аккаунтах оригинальный Chicken Road от InOut Games виден по названию. На других его может не быть, или показываются похожие instant/crash игры.",
        "Первый шаг простой: проверьте поиск казино 1xBet. Введите Chicken Road или InOut и посмотрите, что лобби показывает в вашем регионе.",
    ],
    "h2_about": "О 1xBet",
    "img_about_alt": "Главная страница ставок и казино 1xBet",
    "about_paras": [
        "1xBet — крупная платформа ставок и казино, где всё собрано в одном аккаунте. Больше всего её знают по спортивным ставкам, но на сайте также большой раздел casino.",
        "На платформе есть slots, live casino, crash games, instant games, eSports, virtual sports и live betting. Это уже не только sportsbook, а полноценное gambling-лобби с разными форматами.",
        "Для быстрых игр такая структура удобна. Открываете casino, используете поиск, смотрите категории и переключаетесь между slots, live или crash, не выходя из аккаунта.",
        "Chicken Road и похожие игры хорошо ложатся на такую платформу: без долгой настройки. Короткие раунды, простые кнопки и быстрый доступ — то, что многие ждут от instant games.",
    ],
    "h2_available": "Доступен ли Chicken Road на 1xBet?",
    "img_search_alt": "Результаты поиска Chicken Road на 1xBet",
    "available_paras": [
        "Да, Chicken Road есть на 1xBet вместе с другими тайтлами линейки InOut Games. Можно найти оригинальный Chicken Road и Chicken Road 2. Здесь ситуация лучше, чем на некоторых платформах: 1xBet реально показывает серию Chicken Road в лобби.",
        "Проще всего проверить через поиск. Введите Chicken Road и дождитесь карточек игры. Если лобби работает как на скриншоте, должна быть строка тайтлов Chicken Road в категории slots. Можно искать по провайдеру — InOut. Важно: доступен и режим Demo — открыть игру, протестировать механику на виртуальном балансе, сравнить версии и понять множитель и Cash Out до игры на деньги.",
    ],
    "short_path_title": "Короткий путь:",
    "short_path_item": "Casino → Search → Chicken Road → Choose version → Demo or Play",
    "h2_lobby": "Проверка Chicken Road в лобби 1xBet",
    "img_filter_alt": "Фильтр и поиск провайдера InOut на 1xBet",
    "lobby_paras": [
        "Самый чистый способ проверить Chicken Road на 1xBet — не категории, а поиск в лобби. Откройте casino и введите Chicken Road. Или InOut — удобно, если нужен весь каталог провайдера, а не один тайтл.",
        "Если Chicken Road не виден в вашем аккаунте, проверьте две вещи, прежде чем решить, что игра удалена. Сначала категории Slots, Crash Games, Instant Games или Other. Второе: лобби меняется по стране, валюте и региону аккаунта.",
    ],
    "quick_check_title": "Быстрая проверка выглядит так:",
    "quick_check_item": "Casino → Search → Chicken Road or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Я бы не листал всё лобби вручную. Игр слишком много — поиск быстрее."],
    "h2_play": "Как работают игры Chicken Road на 1xBet",
    "img_play_alt": "Геймплей Chicken Road с множителем и Cash Out на 1xBet",
    "play_paras": [
        "На 1xBet Chicken Road — не один тайтл в результатах поиска. Лобби может показать несколько версий сразу: оригинал, 2.0, Bonus, Gold, Vegas, Race и другие chicken-тайтлы. Они выглядят по-разному, но базовая идея обычно понятна.",
        "Начинаете с простой ставки. Потом решаете, сколько риска брать. Более безопасные режимы идут медленнее, агрессивные сильнее давят на множитель.",
        "После старта раунда — тот же цикл решений. Курица движется, множитель растёт, текущий результат соблазнительнее. В какой-то момент забираете выплату или идёте дальше.",
        "Здесь и появляется давление. Сложные правила не нужны. Всё строится вокруг одного маленького решения снова и снова: хватит сейчас или ещё шаг?",
        "Cash Out — главная кнопка. Вовремя нажали — раунд заканчивается с текущим результатом. Слишком долго ждали — ставка может исчезнуть за один плохой шаг.",
    ],
    "h2_why": "Почему Chicken Road подходит лобби 1xBet",
    "img_versions_alt": "Разные версии Chicken Road в лобби 1xBet",
    "why_paras": [
        "1xBet — платформа, где быстрые игры не выглядят чужеродно. В лобби уже есть slots, crash, instant games, live casino и спорт — Chicken Road естественно попадает в quick-play категорию.",
        "На 1xBet выделяется не только оригинал, но и число связанных версий в лобби. Можно открыть Chicken Road и сравнить с 2.0, Gold, Vegas, Race или Bonus, не уходя с платформы.",
        "Для пользователей 1xBet главный вопрос не только «как работает Chicken Road», но и какую версию открыть первой.",
        "Оригинал лучше для понимания формата. Chicken Road 2.0 выглядит более отполированным. Gold и Vegas — более тематические. Race быстрее и динамичнее. Bonus-версии — для feature-heavy геймплея.",
        "На 1xBet Chicken Road — не один спрятанный тайтл. Скорее небольшая категория сама по себе.",
    ],
    "h2_mobile": "Мобильная игра через 1xBet",
    "img_mobile_alt": "Chicken Road в мобильном приложении 1xBet",
    "mobile_paras": [
        "1xBet достаточно удобен для такого типа игр на мобильном. Открываете casino из приложения или браузера, ищете Chicken Road, выбираете версию и запускаете без прокрутки всего лобби.",
        "На телефоне эти игры логичны. Короткие сессии, экран не перегружен, основные кнопки под рукой. Не нужен большой desktop, чтобы протестировать раунды или сравнить версии.",
        "Следите за полем ставки. На мобильном один быстрый тап может запустить раунд с неверной суммой, особенно при переключении Demo и real play.",
        "Используйте официальное приложение 1xBet или браузер. Избегайте случайных APK, predictor-приложений и «специальных» сборок Chicken Road. Если игра есть в лобби 1xBet, скачивать её откуда-то ещё нет смысла.",
    ],
    "h2_bonuses": "Бонусы и промо на 1xBet",
    "img_bonus_alt": "Раздел бонусов и промо казино 1xBet",
    "bonus_paras": [
        "Бонусы вокруг Chicken Road на 1xBet обычно не часть самой игры. Они от платформы. Игра может быть причиной визита, но правила promo пишет 1xBet.",
        "Главное — eligibility. Некоторые бонусы только для slots, некоторые для спорта, некоторые полностью исключают crash и instant games. Chicken Road как раз в зоне, где нельзя ничего предполагать.",
        "Перед активацией бонуса откройте terms and conditions. Для Chicken Road проверьте, считаются ли crash или instant games в wagering. Если игра не считается, бонус может выглядеть хорошо, но не поможет для этого тайтла.",
        "Также смотрите, как бонус влияет на баланс. Некоторые promos блокируют bonus funds до wagering, ограничивают max cashout или размер ставки. В быстрых играх раунды идут быстро — легко нарушить правило бонуса незаметно.",
    ],
    "h2_safety": "Безопасность и доверие на 1xBet",
    "safety_paras": [
        "Копии сайтов могут выглядеть убедительно. Те же цвета, layout, знакомые кнопки. Потом что-то не так: SMS слишком рано, навязанный APK или оплата до нормальной кассы.",
        "Избегайте predictor-приложений. Chicken Road не нуждается в «сигналах», ботах или секретных таблицах. Обещание «следующего безопасного шага» обычно продаёт уверенность, а не инструмент.",
        "Игра — быстрое развлечение, не план дохода. На реальные деньги результат может быть любым — не стройте сессию вокруг отыгрыша или «идеального раунда».",
    ],
    "h2_final": "Итоговое мнение",
    "final_paras": [
        "1xBet — сильная площадка для быстрых casino-игр: поиск, категории, mobile и несколько тайтлов Chicken Road в одном месте. Можно открыть оригинал, сравнить с 2.0, Gold, Vegas, Race или Bonus и протестировать подходящую версию.",
        "Лучший ход — начать с Demo. Не как «метод тренировки», а чтобы понять, какая версия нравится. Да, 1xBet может быть удобен для игроков Chicken Road. Проверьте игру в своём лобби, сначала Demo, и не превращайте быстрый раунд в длинную сессию без плана.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Доступен ли Chicken Road на 1xBet?", "Да. На 1xBet Chicken Road появляется в лобби казино вместе с другими играми InOut. Можно увидеть оригинал, Chicken Road 2.0, Gold, Vegas, Race, Bonus и связанные тайтлы."],
        ["Как найти Chicken Road на 1xBet?", "Откройте casino и используйте поиск. Введите Chicken Road и проверьте карточки. Быстрее, чем листать всё лобби."],
        ["Можно ли искать по провайдеру InOut?", "Да. Поиск InOut показывает полный список провайдера. Иногда больше игр, чем по одному названию."],
        ["Что если Chicken Road нет в лобби?", "Проверьте написание и попробуйте InOut. Если ничего нет, игра может быть скрыта для региона, валюты или версии лобби. Смотрите crash, instant, slots или другие быстрые категории."],
        ["Можно ли играть в Demo на 1xBet?", "Да, Demo доступен для тайтлов Chicken Road на 1xBet. Полезно сравнивать версии без реального баланса."],
        ["Как работают игры в стиле Chicken Road?", "Короткие решения. Ставка, движение курицы, рост множителя и момент Cash Out. Слишком долгое ожидание может стоить ставки."],
        ["Работают ли бонусы с crash games?", "Не всегда. Некоторые бонусы 1xBet считают только slots или спорт. Перед активацией проверьте, входят ли crash или instant games в wagering."],
        ["Безопасны ли predictor-приложения?", "Нет, я бы избегал. Predictors, боты, APK и Telegram-сигналы обычно обещают больше, чем дают. Одни бесполезны, другие опасны для аккаунта или устройства."],
        ["Какую версию Chicken Road открыть первой на 1xBet?", "Начните с оригинального Chicken Road, чтобы понять базовый формат. Это самая чистая версия серии."],
        ["Chicken Road ощущается иначе в приложении 1xBet?", "Немного, в основном из-за экрана. В приложении всё ближе: карточки, ставка, кнопки и Cash Out. Удобно, но перед раундом лучше не торопиться."],
    ],
}

EXPORT = {"fr": FR, "de": DE, "es": ES, "ru": RU}
