#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Shared Lingala polish replacements — remove French calques, keep Latin game terms."""

from __future__ import annotations

# Order matters: longer phrases first.
LN_REPLACEMENTS: list[tuple[str, str]] = [
    ("Guide na biso ya Cash Out", "Mwongozo na biso ya Cash Out"),
    ("Guide na biso ya APK Chicken Road", "Mwongozo na biso ya APK Chicken Road"),
    ("guide na biso ya stratégie", "mwongozo na biso ya strategy"),
    ("guide na biso ya APK Chicken Road", "mwongozo na biso ya APK Chicken Road"),
    ("Guide na biso ya", "Mwongozo na biso ya"),
    ("guide na biso ya", "mwongozo na biso ya"),
    ("Guide na biso", "Mwongozo na biso"),
    ("guide na biso", "mwongozo na biso"),
    ("Ba Stratégie Chicken Road", "Ba Strategy Chicken Road"),
    ("ba stratégie ya Chicken Road", "ba strategy ya Chicken Road"),
    ("Ba stratégie Chicken Road", "Ba Strategy Chicken Road"),
    ("ba stratégie na demo", "ba strategy na demo"),
    ("ba stratégie", "ba strategy"),
    ("Ba stratégie", "Ba Strategy"),
    ("Ezali stratégie", "Ezali strategy"),
    ("ezali stratégie", "ezali strategy"),
    ("Nakoki komeka ba stratégie", "Nakoki komeka ba strategy"),
    ("Nakoki kolonga na stratégie", "Nakoki kolonga na strategy"),
    ("Stratégie ya malamu", "Strategy ya malamu"),
    ("Style ya stratégie", "Style ya strategy"),
    ("Ndenge stratégie esalaka", "Ndenge strategy esalaka"),
    ("stratégie ya Chicken Road", "strategy ya Chicken Road"),
    ("Stratégie ya Chicken Road", "Strategy ya Chicken Road"),
    ("Stratégie ya solo", "Strategy ya solo"),
    ("stratégie ya solo", "strategy ya solo"),
    ("stratégie moko", "strategy moko"),
    ("Stratégie moko", "Strategy moko"),
    ("stratégie nionso", "strategy nionso"),
    ("Stratégie nionso", "Strategy nionso"),
    ("stratégie.", "strategy."),
    ("Stratégie.", "Strategy."),
    ("stratégie,", "strategy,"),
    ("Stratégie,", "Strategy,"),
    ("stratégie ", "strategy "),
    ("Stratégie ", "Strategy "),
    ("stratégie", "strategy"),
    ("Stratégie", "Strategy"),
    ("Ko-télécharger Demo Chicken Road", "Kozua Demo Chicken Road"),
    ("ko-télécharger Demo Chicken Road", "kozua Demo Chicken Road"),
    ("Ko-télécharger Chicken Road", "Kozua Chicken Road"),
    ("ko-télécharger Chicken Road", "kozua Chicken Road"),
    ("Ko-télécharger", "Kozua"),
    ("ko-télécharger", "kozua"),
    ("Osengeli Ko-télécharger", "Osengeli kozua"),
    ("Osengeli ko-télécharger", "Osengeli kozua"),
    ("problème ya ko-télécharger", "mokakatano ya kozua"),
    ("Télécharger Lisano Chicken Road", "Kozua Lisano Chicken Road"),
    ("Télécharger Chicken Road", "Kozua Chicken Road"),
    ("Télécharger", "Kozua"),
    ("télécharger", "kozua"),
    ("ba joueurs expérimentés", "basali oyo bazali koyeba"),
    ("Ba joueurs expérimentés", "Basali oyo bazali koyeba"),
    ("Ba joueurs réguliers", "Basali ya minene"),
    ("ba joueurs ebele", "basali ebele"),
    ("Ba joueurs mosusu", "Basali mosusu"),
    ("ba joueurs mosusu", "basali mosusu"),
    ("ba joueurs mingi", "basali mingi"),
    ("Ba joueurs mingi", "Basali mingi"),
    ("ba joueurs", "basali"),
    ("Ba joueurs", "Basali"),
    ("ba joueur", "mosali"),
    ("joueurs", "basali"),
    ("joueur", "mosali"),
    ("Joueur", "Mosali"),
    ("ba règles ya kosukisa", "mibeko ya kosukisa"),
    ("ba règles ya style", "mibeko ya style"),
    ("ba règles simples", "mibeko ya pépé"),
    ("ba règles", "mibeko"),
    ("Ba règles", "Mibeko"),
    ("Politique ya confidentialité", "Bosembo ya bomani"),
    ("politique ya confidentialité", "bosembo ya bomani"),
    ("Politique oyo ya confidentialité", "Bosembo oyo ya bomani"),
    ("Politique oyo", "Bosembo oyo"),
    ("Politique na biso", "Bosembo na biso"),
    ("Politique ", "Bosembo "),
    ("politique ", "bosembo "),
    ("Politique", "Bosembo"),
    ("politique", "bosembo"),
    ("Limitation ya responsabilité", "Mokumba ya libateli te"),
    ("responsabilité na yo", "mokumba na yo"),
    ("responsabilité", "mokumba"),
    ("Responsabilité", "Mokumba"),
    ("responsable te", "mokumba te"),
    ("Tozali responsable te", "Tozali mokumba te"),
    ("kopesa contenu", "kopesa makambo"),
    ("kobongisa contenu", "kobongisa makambo"),
    ("kotala contenu", "kotala makambo"),
    ("kotalela contenu", "kotalela makambo"),
    ("contenu oyo", "makambo oyo"),
    ("contenu sans erreur", "makambo na libunga te"),
    ("contenu,", "makambo,"),
    ("contenu.", "makambo."),
    ("contenu ", "makambo "),
    ("contenu", "makambo"),
    ("Contenu ", "Makambo "),
    ("Contenu", "Makambo"),
    ("écran d'accueil", "ecran ya liboso"),
    ("Écran d'accueil", "Ecran ya liboso"),
    ("écran monene", "ecran monene"),
    ("na écran", "na ecran"),
    ("Écran", "Ecran"),
    ("écran", "ecran"),
    ("sans installation ya risque", "na botia ya riski te"),
    ("sans installation", "na botia te"),
    ("sans risque", "na riski te"),
    ("sans app store", "na app store te"),
    ("sans yango", "na yango te"),
    ("Installation App", "Botia App"),
    ("installation esili", "botia esili"),
    ("installation", "botia"),
    ("Installation", "Botia"),
    ("permets notifications", "pesa ndingisa ya ba sango"),
    ("notifications", "ba sango"),
    ("ba bonus mpe promotions", "ba bonus mpe ba promotion"),
    ("promotions", "ba promotion"),
    ("fichier oyo e téléchargé", "fisyé oyo ozwi"),
    ("fichier", "fisyé"),
    ("tiroir ya apps", "esika ya ba app"),
    ("tiroir", "esika"),
    ("comportement na yo", "ndenge ya kosala na yo"),
    ("comportement", "ndenge ya kosala"),
    ("expérience", "ndenge ya kosalela"),
    ("compliqué", "mpimba"),
    ("ezali te compliqué", "ezali mpimba te"),
    ("confiance", "kondima"),
    ("pétillant", "pépé"),
    ("expliqué", "elimbolami"),
    ("Aperçu ya App Ofele", "Tala App Ofele"),
    ("Aperçu", "Tala"),
    ("facilité na yo", "pépé na yo"),
    ("facilité", "pépé"),
    ("étonnement", "esengo"),
    ("problèmes ya moke", "mikakatano mike"),
    ("problème", "mokakatano"),
    ("ba problèmes", "ba mokakatano"),
    ("ba raisons ebele", "ba ntina ebele"),
    ("raisons", "ntina"),
    ("approche na bango", "ndenge na bango"),
    ("approche éditoriale", "ndenge ya kosa"),
    ("approche", "ndenge"),
    ("Approche", "Ndenge"),
    ("décision ya kopona", "likambo ya kopona"),
    ("ba décision na yo", "ba likambo ya kopona na yo"),
    ("ba décision", "ba likambo ya kopona"),
    ("décision", "likambo ya kopona"),
    ("Décision", "Likambo ya kopona"),
    ("Gestion ya bankroll", "Kobatela bankroll"),
    ("Gestion ya", "Kobatela"),
    ("gestion ya", "kobatela"),
    ("ba pertes", "ba pété"),
    ("perte,", "pété,"),
    ("perte ", "pété "),
    ("perte", "pété"),
    ("bravade", "mpiko"),
    ("conservatrice", "ya riski moke"),
    ("équilibrée", "ya kati"),
    ("agressive", "ya riski monene"),
    ("réguliers", "ya minene"),
    ("expérimentés", "oyo bazali koyeba"),
    ("garantir profit", "kondima mbongo"),
    ("garanti profit", "mbongo ya surete"),
    ("garantir", "kondima"),
    ("garanti", "ya surete"),
    ("aléatoire", "ya hasard"),
    ("e préféré mingi", "olingi mingi"),
    ("e préféré", "olingi"),
    ("e vutaka", "ezali kobenda"),
    ("partie ya kobɔngisa", "eteni ya kobɔngisa"),
    ("ko-mise à jour", "kobongisa"),
    ("ba changements", "ba bongwana"),
    ("changements", "bongwana"),
    ("intérêts légitimes", "ba ntina ya solo"),
    ("kocher contenu", "kobomba makambo"),
    ("komeka trafic", "kotala ba visiteur"),
    ("disponibilité", "ezali"),
    ("pratiques ya", "ba ndenge ya"),
    ("ba résultats précis", "ba resultat ya solo"),
    ("résultats précis", "resultat ya solo"),
    ("Jeu Responsable", "Kobeta na Libateli"),
    ("jeu responsable", "kobeta na libateli"),
    ("contrôle ya jeu", "libateli ya lisano"),
    ("sentiment ya stratégie", "ndenge ya strategy"),
    ("guide ya stratégie", "mwongozo ya strategy"),
    ("Catalogue Mobimba", "Lisi Mobimba"),
    ("catalogue mobimba", "lisi mobimba"),
    ("Catalogue", "Lisi"),
    ("catalogue", "lisi"),
    ("Analyse Chicken Road", "Tala Chicken Road"),
    ("analyse ya Chicken Road", "tala ya Chicken Road"),
    ("Analyse", "Tala"),
    ("analyse", "tala"),
    ("monde ya Chicken Road", "mokili ya Chicken Road"),
    ("monde ya", "mokili ya"),
    ("monde", "mokili"),
    ("ba conseil ya bonus", "ba likanisi ya bonus"),
    ("ba conseil ya strategy", "ba likanisi ya strategy"),
    ("ba conseil ya solo", "ba likanisi ya solo"),
    ("Ba Conseil", "Ba Likanisi"),
    ("ba conseil", "ba likanisi"),
    ("conseil", "likanisi"),
    ("Conseil", "Likanisi"),
    ("ba signaux", "ba elembo"),
    ("Signaux", "Elembo"),
    ("signaux", "elembo"),
    ("ba décision", "ba kopona"),
    ("condition ya wagering", "mibeko ya wagering"),
    ("Ba Condition", "Mibeko"),
    ("ba condition", "ba mibeko"),
    ("condition", "mibeko"),
    ("Condition", "Mibeko"),
    ("Ba Providers", "Ba Provider"),
    ("ba providers", "ba provider"),
    ("Providers", "Provider"),
    ("providers", "provider"),
    ("Ba Signaux", "Ba Elembo"),
    ("Ba Mwongozo", "Ba Mwongozo"),
    ("mwongozo ya signaux", "mwongozo ya elembo"),
    ("elimbolami na ndenge ya pépé", "elimbolami na ndenge ya pépé"),
    ("Ba Offre Elimbolami", "Ba Offre Elimbolami"),
    ("icône PWA", "icone PWA"),
    ("icône", "icone"),
    ("Minimal,", "Moke,"),
    ("Minimal", "Moke"),
    ("pourquoi basali", "mpo na nini basali"),
    ("pourquoi ", "mpo na nini "),
    ("Pourquoi ", "Mpo na nini "),
    ("Pourquoi", "Mpo na nini"),
    ("bouton Cash Out", "buton Cash Out"),
    ("bouton Play", "buton Play"),
    ("bouton ", "buton "),
    ("Bouton ", "Buton "),
    ("Bouton", "Buton"),
    ("bouton", "buton"),
    ("décide ", "pona "),
    ("décide", "pona"),
    ("Choix ", "Kopona "),
    ("choix ", "kopona "),
    ("Choix", "Kopona"),
    ("choix", "kopona"),
    ("panique ", "nkanga "),
    ("panique", "nkanga"),
    ("souci ", "mwasi "),
    ("souci", "mwasi"),
    ("habitude ", "ndenge "),
    ("habitude", "ndenge"),
    ("réagit ", "eyano "),
    ("réagit", "eyano"),
    ("esongo ", "liboso "),
    ("esongo", "liboso"),
    ("mécanique ", "ndenge "),
    ("mécanique", "ndenge"),
    ("Mécanique", "Ndenge"),
    ("contrôle ", "libateli "),
    ("contrôle", "libateli"),
    ("Contrôle", "Libateli"),
    ("funny ", "ya esengo "),
    ("funny", "ya esengo"),
    ("lourde ", "mpimba "),
    ("lourde", "mpimba"),
    ("pétó ", "pete "),
    ("pétó", "pete"),
    ("couleurs ", "langi "),
    ("couleurs", "langi"),
    ("sérieux ", "makasi "),
    ("sérieux", "makasi"),
    ("tricky ", "pépé te "),
    ("tricky", "pépé te"),
    ("divertissant ", "ya esengo "),
    ("divertissant", "ya esengo"),
    ("discipline ", "libateli "),
    ("discipline", "libateli"),
    ("courage ", "mpiko "),
    ("courage", "mpiko"),
    ("smooth ", "malamu "),
    ("smooth", "malamu"),
    ("sans retard", "na retard te"),
    ("avantage ", "litite "),
    ("avantage", "litite"),
    ("pression ", "ngombi "),
    ("pression", "ngombi"),
    ("intentional", "ya ntina"),
    ("feeling ", "ndenge "),
    ("Feeling ", "Ndenge "),
    ("feeling", "ndenge"),
    ("boring ", "pépé "),
    ("boring", "pépé"),
    ("timing ya", "tango ya"),
    ("ko-review", "kotala"),
    (" téléphone", " telefone"),
    ("téléphone", "telefone"),
    ("Téléphone", "Telefone"),
    ("sécurité", "libateli"),
    ("Sécurité", "Libateli"),
    ("Installer ", "Botia "),
    ("installer ", "botia "),
    ("Installer,", "Botia,"),
    ("fungola ", "fungola "),
    (" jeu ", " lisano "),
    ("Jeu ", "Lisano "),
    (" ba jeux ", " ba lisano "),
    ("ba jeux", "ba lisano"),
]


def polish_ln(text: str) -> str:
    for old, new in LN_REPLACEMENTS:
        text = text.replace(old, new)
    return text
