# -*- coding: utf-8 -*-
"""Localized strings for Ice Fish home page cluster rebuild."""

from __future__ import annotations

COMMON_TABLE_EN: list[tuple[str, str]] = [
    ("Format", "Fast risk-based casino game"),
    ("Main object", "A chicken crossing the road"),
    ("Player decision", "Move forward or cash out"),
    ("Risk", "Increases with every step"),
    ("Engagement hook", "The “just one more step” feeling"),
    ("Game type", "Crash / instant game"),
    ("Developer", "InOut Games"),
    ("Visual style", "Arcade-style, cartoon-like"),
    ("Difficulty modes", "Easy, Medium, Hard, Hardcore"),
    ("Core goal", "Reach a higher multiplier and cash out in time"),
    ("Demo mode", "Yes, available on our site"),
    ("Real money mode", "Yes"),
    ("Mobile play", "Yes, works on smartphones"),
    ("RTP", "Up to 98% in the original version"),
    ("Best for", "Players who like quick rounds and simple mechanics"),
]

FAQ_EN: list[tuple[str, str]] = [
    (
        "What is Ice Fish?",
        "Ice Fish is a fast casino game from InOut Games. Move the chicken across the road and try to stop before things go wrong. The longer you keep going, the more you can win, but one bad step can burn the whole bet.",
    ),
    (
        "Who developed Ice Fish?",
        "InOut Games. The studio is known for fast, arcade-style casino and crash games.",
    ),
    (
        "Is Ice Fish free to play?",
        "Yes. Ice Fish can be played for free in demo mode with no risk to your own money.",
    ),
    (
        "Is there a Ice Fish demo mode?",
        "Yes. Demo mode is available on our website so you can play risk-free and test different difficulty levels.",
    ),
    (
        "Is Ice Fish available on smartphones?",
        "Yes. Ice Fish works on iOS and Android smartphones through the browser.",
    ),
    (
        "Can you predict the result in Ice Fish?",
        "No. You cannot predict the next step or know in advance when the chicken will lose. Treat any predictor or guaranteed method as a scam.",
    ),
    (
        "Is there a working Ice Fish strategy?",
        "There are different approaches, but no strategy guarantees profit. A plan can help you control your play, not beat the game.",
    ),
    (
        "Is real-money Ice Fish risky?",
        "Yes. Real-money play adds pressure and every failed step costs your balance.",
    ),
    (
        "Can I download Ice Fish?",
        "Usually you do not need to download it. The game runs directly in a browser through casino sites.",
    ),
]

STRINGS: dict[str, dict] = {
    "ru": {
        "h1": "Ice Fish онлайн: что это, как играть и зачем нужно демо",
        "h2": "Ice Fish: как устроена игра, демо и игра на деньги",
        "intro": "Курица выходит на дорогу. Каждый безопасный шаг поднимает множитель. Один неверный — и раунд закончен. Правило простое, но новичков чаще удивляет не оно, а темп: после каждого шага нужно решить — забрать выигрыш или рискнуть ещё раз. Поэтому большинство сначала открывает демо.",
        "b1_label": "Главное об игре:",
        "b1_text": "Ice Fish выпустила InOut Games в 2024 году. В оригинальной версии указан RTP до 98%, типичные ставки — от USD 0.10.",
        "b2_label": "Уровни сложности:",
        "b2_text": "Easy, Medium, Hard и Hardcore меняют темп роста множителя и риск на каждом шаге.",
        "b3_label": "Механика шагов:",
        "b3_text": "Вы сами решаете, когда двигаться дальше и когда нажать Cash Out — это отличает игру от классического crash-формата.",
        "b4_label": "Почему затягивает:",
        "b4_text": "Короткие раунды и ощущение «ещё один шаг» быстро вовлекают — поэтому большинство сначала открывает демо.",
        "alt_app": "Интерфейс Ice Fish на десктопе и мобильном",
        "alt_hero": "Ice Fish на десктопе и мобильном",
        "works_h5": "Как это работает",
        "works_h3": "Как устроена Ice Fish",
        "works_p": "Вы делаете ставку, выбираете сложность и отправляете курицу на дорогу. Каждый безопасный шаг повышает множитель. В любой момент можно забрать выигрыш или пойти дальше — и рискнуть всей ставкой.",
        "works_li1": "Перед стартом проверьте размер ставки: после нажатия Play сумма уже в игре.",
        "works_li2": "На более лёгких режимах множитель растёт медленнее, но шанс пройти шаг выше.",
        "works_li3": "На Hardcore цифры выглядят заманчивее, но опасность начинается почти сразу.",
        "works_li4": "Игра поощряет дисциплину больше, чем смелость: ранний Cash Out скучнее, но часто разумнее.",
        "alt_gameplay": "Ice Fish — множитель растёт во время раунда",
        "rtp_h5": "RTP и провайдер",
        "rtp_h3": "Return to Player (RTP) и InOut Games",
        "rtp_p": "В оригинальной версии указан RTP до 98% и провайдер InOut Games. Цифра полезна, но решение игрока чаще упирается не в неё, а в то, у кого вы открываете игру. Сама Ice Fish везде одинаковая — меняется оператор вокруг неё.",
        "rtp_extra_p": "Единого «официального сайта Ice Fish на реальные деньги» для всех не существует. Игра приходит через лицензированные казино и партнёров InOut Games. Поэтому полезнее сравнить площадки, где есть демо, удобные платежи и понятные правила вывода.",
        "hook_h5": "Почему затягивает",
        "hook_h3": "Почему Ice Fish так быстро вовлекает",
        "hook_p": "Визуально игра выглядит легко — почти как аркада в телефоне. Но за мультяшной графикой стоит чистая gambling-механика: каждый шаг даёт лучший множитель и одновременно усложняет остановиться.",
        "hooks_title": "Главные крючки просты:",
        "hooks": [
            "всегда хочется сделать ещё один шаг;",
            "кажется, что можно остановиться в идеальный момент;",
            "мультяшный дизайн делает риск психологически меньше;",
            "короткие раунды легко запускают снова;",
            "игрок сам решает, когда забрать выигрыш.",
        ],
        "alt_hooks": "Ice Fish — множители на полосах дороги",
        "steps_h5": "Простые шаги",
        "steps_h3": "Ice Fish за три шага",
        "steps_p": "Схема короткая: выбрать ставку и сложность, двигать курицу шаг за шагом и забрать выигрыш до провала.",
        "step1_h": "1. СТАВКА",
        "step1_p": "Задайте сумму и уровень сложности до старта раунда и держитесь в лимите на сессию.",
        "step2_h": "2. ШАГ",
        "step2_p": "Продвигайте курицу, когда готовы. Каждый безопасный шаг увеличивает множитель на экране.",
        "step3_h": "3. КЭШАУТ",
        "step3_p": "Заберите множитель после любого успешного шага. Если продолжите и курица проиграет — ставка сгорит.",
        "alt_step_bet": "Настройка ставки и сложности в Ice Fish",
        "alt_step_advance": "Курица делает следующий шаг в Ice Fish",
        "alt_step_cashout": "Успешный Cash Out в Ice Fish",
        "demo_h5": "Демо и деньги",
        "demo_h3": "Демо Ice Fish — можно ли играть бесплатно?",
        "demo_p1": "Да. На нашем сайте Ice Fish можно запустить в демо без реальных денег — с виртуальным балансом.",
        "demo_p2": "Это тот же геймплей: курица идёт по дороге, машины проезжают по полосам, множитель растёт после каждого успешного шага. Можно менять сложность и проверять, как быстро раунд оборачивается против вас.",
        "demo_p3": "Демо полезно, чтобы понять кнопки, темп и тайминг Cash Out. Но хороший результат в бесплатном режиме не означает «рабочую систему» — только удачный демо-раунд.",
        "demo_cta": "Попробовать демо Ice Fish",
        "alt_session": "Запуск Ice Fish и начало игровой сессии",
        "alt_demo": "Демо-режим Ice Fish с виртуальным балансом",
        "batting_h5": "С чего начать",
        "batting_h3": "Как начать играть в Ice Fish",
        "batting_p": "Если хотите перейти от любопытства к реальной игре, разумный путь тот же: сначала демо, потом сравнение лицензированных операторов и только после этого депозит.",
        "batting_items": [
            "Выбирайте регулируемое казино или беттинг-сайт, где действительно есть Ice Fish от InOut Games.",
            "Если доступно демо, откройте его первым и используйте, чтобы без давления освоить интерфейс, темп и тайминг Cash Out.",
            "Ice Fish хорошо работает в мобильном браузере на iOS и Android — портретный режим и крупные кнопки удобны для коротких сессий.",
            "Перед игрой на деньги заранее задайте жёсткий лимит на сессию и не пытайтесь отыграться в следующем раунде.",
        ],
        "features_h5": "Особенности",
        "features_h3": "Ключевые особенности Ice Fish",
        "features_p": "Главные преимущества здесь практичные: короткие раунды, уровни сложности и контроль момента выхода после каждого шага.",
        "features_items": [
            ("Контроль шаг за шагом:", "вы сами решаете, когда двигаться дальше и когда забрать выигрыш."),
            ("Четыре уровня сложности:", "Easy, Medium, Hard и Hardcore меняют риск и темп роста множителя."),
            ("Короткие раунды:", "быстрый темп и ощущение «ещё один шаг» делают игру динамичной, но требуют дисциплины."),
        ],
        "feat1_label": "Контроль шаг за шагом:",
        "feat2_label": "Четыре уровня сложности:",
        "feat3_label": "Короткие раунды:",
        "tip1_label": "Определите лимит заранее:",
        "tip2_label": "Используйте демо для тайминга:",
        "tip3_label": "Игнорируйте «предикторы»:",
        "tip4_label": "Играйте ради развлечения:",
        "tips_items": [
            ("Определите лимит заранее:", "Ещё до старта решите, сколько готовы проиграть и какая прибыль уже достаточна для этой сессии."),
            ("Используйте демо для тайминга:", "Демо помогает освоить интерфейс и темп, но не открывает гарантированный шаблон игры."),
            ("Игнорируйте «предикторы»:", "Любые обещания предсказать следующий шаг стоит считать мошенничеством."),
            ("Играйте ради развлечения:", "Не для дохода и не для «возврата» проигрыша — вы сами решаете, когда начать и когда остановиться."),
        ],
        "mobile_h5": "Мобильная версия",
        "mobile_h3": "Ice Fish на смартфоне",
        "mobile_p1": "Ice Fish хорошо работает на мобильных: механика не перегружена, всё читается даже на небольшом экране.",
        "mobile_p2": "Нужен стабильный интернет, но у игры есть плюс — она не давит секундомером, поэтому остаётся играбельной даже при небольших лагах.",
        "mobile_p3": "В портретном режиме видна одна полоса вместо шести, а выбор сложности сворачивается в одну кнопку.",
        "mobile_p4": "Откройте сайт, нажмите Play Ice Fish, задайте ставку и начните раунд — управление остаётся простым: тап, пауза, решение, Cash Out.",
        "mobile_li1": "Портретный режим и крупные кнопки удобны для коротких сессий.",
        "mobile_li2": "Работает в браузере на iOS и Android без отдельной установки.",
        "mobile_li3": "Короткие раунды делают мобильный формат естественным для этой игры.",
        "alt_mobile": "Ice Fish в мобильном интерфейсе",
        "tips_h5": "Советы",
        "tips_h3": "Стратегии, риски и ответственная игра",
        "tips_p1": "Рано или поздно многие ищут «систему»: кто-то выходит после одного-двух шагов, кто-то гонится за высоким множителем, кто-то меняет сложность от раунда к раунду.",
        "tips_p2": "На нашем сайте собраны разные подходы игроков — осторожные, рискованные, подходящие только для демо. Ни один из них не делает игру гарантированно выигрышной.",
        "tips_p3": "Вы контролируете момент Cash Out, но не контролируете следующий шаг. Поэтому лимиты важны: не проигрывайте больше, чем можете позволить, и не пытайтесь «отыграться» в следующем раунде.",
        "tips_p4": "Ice Fish может быть развлечением — раунды короткие, графика не выглядит агрессивно. Но с реальными деньгами тот же шаг ощущается совсем иначе.",
        "tips_p5": "Играйте ради развлечения, а не ради дохода или «возврата» проигрыша. Решать, когда начать и когда остановиться, должны вы.",
        "specs_h5": "Кратко",
        "specs_h3": "Ice Fish — базовая информация",
        "table_h1": "Критерий",
        "table_h2": "Ice Fish",
        "table": [
            ("Формат", "Быстрая казино-игра на риск"),
            ("Главный объект", "Курица, переходящая дорогу"),
            ("Решение игрока", "Идти дальше или забрать выигрыш"),
            ("Риск", "Растёт с каждым шагом"),
            ("Крючок", "Ощущение «ещё один шаг»"),
            ("Тип игры", "Crash / instant game"),
            ("Разработчик", "InOut Games"),
            ("Визуальный стиль", "Аркада, мультяшная графика"),
            ("Уровни сложности", "Easy, Medium, Hard, Hardcore"),
            ("Цель", "Дойти до более высокого множителя и вовремя выйти"),
            ("Демо-режим", "Да, доступен на сайте"),
            ("Игра на деньги", "Да"),
            ("Мобильная версия", "Да, смартфоны iOS и Android"),
            ("RTP", "До 98% в оригинальной версии"),
            ("Подходит для", "Игроков, которым нравятся короткие раунды и простая механика"),
        ],
        "faq_h5": "FAQ",
        "faq_h3": "Часто задаваемые вопросы",
        "faq": [
            (
                "Что такое Ice Fish?",
                "Ice Fish — быстрая казино-игра от InOut Games. Нужно провести курицу через дорогу и успеть остановиться до провала. Чем дальше идёте, тем выше потенциальный выигрыш, но один неудачный шаг сжигает всю ставку.",
            ),
            (
                "Кто разработал Ice Fish?",
                "Студия InOut Games — провайдер быстрых аркадных crash-игр.",
            ),
            (
                "Можно ли играть в Ice Fish бесплатно?",
                "Да. В демо-режиме игра доступна без риска для ваших денег.",
            ),
            (
                "Есть ли демо Ice Fish?",
                "Да, на нашем сайте можно запустить демо и протестировать разные уровни сложности.",
            ),
            (
                "Доступна ли Ice Fish на смартфонах?",
                "Да, игра работает на iOS и Android через браузер.",
            ),
            (
                "Можно ли предсказать результат в Ice Fish?",
                "Нет. Следующий шаг нельзя предсказать заранее. Любые «предикторы» и гарантированные схемы стоит считать мошенничеством.",
            ),
            (
                "Есть ли рабочая стратегия для Ice Fish?",
                "Есть разные подходы, но ни один не гарантирует прибыль. Стратегия может помочь держать игру под контролем, а не «обойти» RNG.",
            ),
            (
                "Рискованна ли игра на реальные деньги?",
                "Да. Каждый промах бьёт по балансу, а давление влияет на решения.",
            ),
            (
                "Можно ли скачать Ice Fish?",
                "Обычно скачивание не нужно — игра открывается в браузере через сайты казино.",
            ),
        ],
    },
}

# English canonical for translation base
STRINGS["en"] = {
    "h1": "Ice Fish online: what it is, how to play, and why the demo matters",
    "h2": "Ice Fish: how the game works, demo and real-money play",
    "intro": "A chicken steps onto the road. Each safe step raises the multiplier. One wrong move ends the round. The rule is simple, but what catches new players off guard is usually the pace: after every step you decide whether to cash out or risk another hop. That is why most people open the demo first.",
    "b1_label": "Core facts:",
    "b1_text": "Ice Fish was released by InOut Games in 2024. The original version lists RTP up to 98%, with typical stakes from USD 0.10.",
    "b2_label": "Difficulty modes:",
    "b2_text": "Easy, Medium, Hard, and Hardcore change how fast the multiplier climbs and how risky each step feels.",
    "b3_label": "Step-by-step control:",
    "b3_text": "You choose when to move forward and when to cash out — unlike a single rising crash multiplier.",
    "b4_label": "Why it hooks players:",
    "b4_text": "Short rounds and the “one more step” feeling pull people in fast — which is why most players open the demo first.",
    "alt_app": "Ice Fish game interface on desktop and mobile",
    "alt_hero": "Ice Fish on desktop and mobile",
    "works_h5": "How It Works",
    "works_h3": "How Ice Fish works",
    "works_p": "Place a bet, pick a difficulty level, and send the chicken onto the road. Every safe step raises the multiplier. At any moment you can cash out or go one step further and risk the whole stake.",
    "works_li1": "Check your bet size before you start — once the round begins, the stake is already in play.",
    "works_li2": "On easier modes the multiplier grows more slowly, but each step is more likely to survive.",
    "works_li3": "On Hardcore the numbers look bigger, but danger starts almost immediately.",
    "works_li4": "The game rewards discipline more than courage: an early cash out may feel boring, but waiting too long is where bets usually burn.",
        "alt_gameplay": "Ice Fish multiplier climbing during a live round",
        "rtp_h5": "RTP & provider",
        "rtp_h3": "Return to Player (RTP) and InOut Games",
        "rtp_p": "The original version lists RTP up to 98% and provider InOut Games. That number helps, but the real decision is usually about where you open the game. Ice Fish itself is the same everywhere — the operator around it changes.",
        "rtp_extra_p": "There is no single official Ice Fish real-money site for everyone. Players usually reach the game through licensed casino partners with InOut Games integrations. The useful question is which site offers demo access, your payment methods, and clear withdrawal rules.",
        "hook_h5": "Why It Hooks Players",
    "hook_h3": "Why Ice Fish pulls players in so quickly",
    "hook_p": "Visually the game feels light — almost like a phone arcade title. Behind the cartoon look is pure gambling psychology: every safe step improves the multiplier and makes it harder to stop.",
    "hooks_title": "The main hooks are simple:",
    "hooks": [
        "you always want to take one more step;",
        "it feels like you can stop at the perfect moment;",
        "the cartoon design makes the risk feel smaller than it is;",
        "short rounds make it easy to play again;",
        "you decide when to cash out.",
    ],
    "alt_hooks": "Ice Fish multipliers across road lanes",
    "steps_h5": "Simple Steps",
    "steps_h3": "Ice Fish in three steps",
    "steps_p": "The flow is short: set your bet and difficulty, move the chicken step by step, and cash out before a trap ends the run.",
    "step1_h": "1. BET",
    "step1_p": "Choose your stake and difficulty before the round starts and stay inside the limit you set for the session.",
    "step2_h": "2. ADVANCE",
    "step2_p": "Move the chicken when you are ready. Each safe step increases the multiplier on screen.",
    "step3_h": "3. CASH OUT",
    "step3_p": "Secure the multiplier after any successful step. If you keep going and the chicken fails, the stake is lost.",
    "alt_step_bet": "Setting bet and difficulty in Ice Fish",
    "alt_step_advance": "Chicken taking the next step in Ice Fish",
    "alt_step_cashout": "Successful cash out in Ice Fish",
    "demo_h5": "Demo and Real Money",
    "demo_h3": "Ice Fish demo — can you play for free?",
    "demo_p1": "Yes. On our site you can launch Ice Fish in demo mode with virtual balance and no real-money risk.",
    "demo_p2": "It is the same gameplay: the chicken crosses the road, cars pass through the lanes, and every safe step still increases the multiplier. You can switch difficulty levels and see how quickly a round can turn against you.",
    "demo_p3": "Use demo mode to learn the buttons, pace, and cash-out timing. A good free-play result does not mean you found a winning system — only that you had a good demo round.",
        "demo_cta": "Try Ice Fish demo",
        "alt_session": "Opening Ice Fish at a casino and starting a session",
        "alt_demo": "Ice Fish demo mode with virtual balance",
        "batting_h5": "Getting Started",
        "batting_h3": "How to start playing Ice Fish",
        "batting_p": "If you want to move from curiosity to real play, the sensible path is the same: try the demo first, then compare licensed operators before you deposit anything.",
        "batting_items": [
            "Choose a regulated casino or betting site that actually carries Ice Fish from InOut Games.",
            "Open the demo first if it is available and use it to learn the interface, pace, and cash-out timing without pressure.",
            "Ice Fish works well in mobile browsers on iOS and Android — portrait layout and large buttons suit short sessions.",
            "Before real-money play, set a hard session limit and do not chase losses in the next round.",
        ],
        "features_h5": "Features",
        "features_h3": "Key Ice Fish features",
        "features_p": "The main advantages here are practical: short rounds, difficulty levels, and control over when you exit after each step.",
        "features_items": [
            ("Step-by-step control:", "you decide when to move forward and when to cash out."),
            ("Four difficulty levels:", "Easy, Medium, Hard, and Hardcore change risk and multiplier pace."),
            ("Short rounds:", "fast tempo and the “one more step” feeling keep the game dynamic, but demand discipline."),
        ],
        "tips_items": [
            ("Set limits early:", "Decide before you start how much you can afford to lose and what profit is enough for the session."),
            ("Use demo for timing:", "Demo helps you learn the interface and pace, but it does not reveal a guaranteed pattern."),
            ("Ignore predictors:", "Any promise to predict the next step should be treated as a scam."),
            ("Play for entertainment:", "Not for income or recovering losses — you decide when to start and when to stop."),
        ],
    "mobile_h5": "Mobile Play",
    "mobile_h3": "Ice Fish on mobile",
    "mobile_p1": "Ice Fish works well on mobile because the game is not overloaded. You do not need a large screen to understand what is happening.",
    "mobile_p2": "A stable internet connection helps, but the game does not rush you with a timer, so it remains playable even with some lag.",
    "mobile_p3": "In portrait mode you see one lane instead of six, and the difficulty selector collapses into a single button.",
    "mobile_p4": "Open the site, tap Play Ice Fish, set your bet, and start the round — tap, wait, decide, cash out when it feels enough.",
    "mobile_li1": "Portrait layout and large buttons suit short mobile sessions.",
    "mobile_li2": "Works in the browser on iOS and Android without a separate download.",
    "mobile_li3": "Short rounds make mobile a natural format for this game.",
    "alt_mobile": "Ice Fish mobile interface",
    "tips_h5": "Tips",
    "tips_h3": "Strategies, risks, and responsible play",
    "tips_p1": "Sooner or later most players look for a system: some stop after one or two safe steps, some chase a bigger multiplier, some switch difficulty levels between rounds.",
    "tips_p2": "We also collect different approaches players use in Ice Fish — careful, risky, or useful only in demo. None of them turns the game into a guaranteed win.",
    "tips_p3": "You control when you cash out, but not what happens on the next step. That is why limits matter: do not lose more than you can afford and do not chase losses in the next round.",
    "tips_p4": "Ice Fish can be entertaining because rounds are short and the game does not look serious. Real money changes the feeling completely.",
    "tips_p5": "Play for entertainment, not for income or recovering losses. You should decide when to start and when to stop.",
    "specs_h5": "At a Glance",
    "specs_h3": "Ice Fish — basic info",
    "table_h1": "Criteria",
    "table_h2": "Ice Fish",
    "table": list(COMMON_TABLE_EN),
    "faq_h5": "FAQ",
    "faq_h3": "Frequently asked questions",
    "faq": list(FAQ_EN),
}

from icefish_home_i18n import extra_locales

STRINGS.update(extra_locales())
