# -*- coding: utf-8 -*-
"""Overrides for casino_articles#25 — VI, HI, BN."""

VI = {
    "h1": "Jack-Pot — Ice Fish",
    "h2_about": "Giới thiệu Jack-Pot",
    "img_hero_alt": "Sảnh casino trực tuyến Jack-Pot và tổng quan Ice Fish",
    "about_paras": [
        "Jack-Pot là nền tảng trực tuyến nơi casino và cá cược thể thao dùng chung một tài khoản. Trang có các mục rõ ràng: casino, live, sport, promos, payments, tournaments và cashback. Người dùng dễ chọn nơi cần vào. Nền tảng khá đơn giản. Casino chia theo danh mục. Bạn cũng có thể dùng các mục chính nếu đã biết muốn chơi gì.",
        "Ice Fish hợp với Jack-Pot vì đây đúng kiểu game cần truy cập nhanh. Không ai muốn lục lobby khổng lồ chỉ để tìm game arcade nhanh. Mở game, đặt cược, chọn mức rủi ro và vòng chơi bắt đầu. Với Ice Fish, lợi thế chính của Jack-Pot là đường đi gọn tới game: lobby nhanh, thanh tìm kiếm, mobile và bố cục không cản trở. Đủ cho game với vòng ngắn và quyết định nhanh.",
        "Jack-Pot cũng có bonus và khuyến mãi, nên nên xem mục promotion trước khi chơi. Đừng kích hoạt mù quáng. Bonus có thể giới hạn thời gian hoặc theo quy tắc.",
    ],
    "h2_where": "Tìm Ice Fish trên Jack-Pot ở đâu",
    "where_paras": [
        "Ice Fish dễ tìm trên Jack-Pot nếu biết chỗ xem. Mở mục casino và vào Slots hoặc Crash Games. Hầu hết game arcade nhanh thường nằm quanh các danh mục này.",
        "Cách nhanh nhất là tìm kiếm. Gõ Ice Fish trên thanh tìm, đợi banner game hiện ra và mở. Game sẽ chạy trong cửa sổ riêng.",
        "Bạn cũng có thể tìm theo nhà cung cấp. Nhập InOut và Jack-Pot sẽ hiện game của studio này. Hữu ích nếu muốn tìm không chỉ Ice Fish mà cả tựa InOut khác.",
        "Đôi khi game cũng xuất hiện trong Crash Games, nơi nền tảng thường đặt instant games, crash games và tựa không thuộc slot cổ điển.",
    ],
    "short_path_title": "Đường ngắn rất đơn giản:",
    "short_path_item": "Casino → Crash Games / Slots → Ice Fish → Play Now",
    "short_path_outro": ["Nếu không thấy theo tên, thử tìm InOut."],
    "h2_play": "Cách chơi Ice Fish trên Jack-Pot",
    "play_paras": [
        "Ice Fish trên Jack-Pot dễ bắt đầu. Nếu mới chơi, bắt đầu với Easy. Bạn có thêm không gian hiểu game. Medium đã cảm giác gắt hơn. Hard và Hardcore phù hợp người biết số dư có thể biến mất nhanh thế nào trong kiểu game này. Trước khi bấm Play, kiểm tra lại cược. Đặc biệt trên điện thoại. Một chạm vội có thể bắt đầu vòng với số tiền sai.",
        "Nút chính là Cash Out. Bấm khi hệ số hiện tại đủ và bạn muốn dừng. Chờ quá lâu và vòng xấu thì mất cược.",
        "Nếu là Ice Fish gốc của InOut Games, luật cơ bản trên Jack-Pot giống nền tảng khác: tiến lên, tăng hệ số, Cash Out trước khi thua vòng.",
    ],
    "h2_demo": "Demo và chơi tiền thật trên Jack-Pot",
    "demo_paras": [
        "Demo Ice Fish có trên Jack-Pot, và tôi sẽ bắt đầu từ đó. Không phải vì demo dạy thắng — nó không dạy. Nhưng giúp xem game không áp lực.",
        "Ở chế độ demo bạn chơi bằng số dư ảo. Có thể đổi độ khó, thử cược khác nhau, di chuyển gà trên đường và thử Cash Out ở các điểm khác. Vòng xấu không ảnh hưởng tiền thật. Chế độ tiền thật cảm giác khác. Game có thể giống hệt, nút giống, hệ số tăng giống. Nhưng khi số dư của bạn vào cuộc, mỗi bước nặng hơn.",
        "Ở demo người ta thường chơi thoải mái hơn nhiều. Số dư ảo nên thử mode khó hoặc đi xa hơn không đau.",
        "Với tiền thật, cùng một thao tác cảm giác khác. Cùng nút, cùng hệ số, cùng đường — nhưng cược là của bạn. Một số Cash Out quá sớm vì sợ thua. Số khác đi quá xa để gỡ vòng trước. Áp lực bắt đầu từ đó. Hãy dùng demo trên Jack-Pot trước. Học game ở đó. Chơi tiền thật chỉ hợp lý khi hiểu cơ chế và chấp nhận rủi ro.",
    ],
    "h2_mobile": "Ice Fish trên mobile qua Jack-Pot",
    "mobile_paras": [
        "Ice Fish chạy ổn trên điện thoại. Mở Jack-Pot, tìm game, đặt cược và bắt đầu vòng không cần giao diện nặng. Trên mobile bố cục gọn hơn. Ô cược, Play và Cash Out vẫn dễ chạm — quan trọng trong game này. Bạn không muốn tìm nút thoát khi hệ số đã chạy.",
        "Vòng ngắn nên mobile hợp. Một phiên thường chỉ vài chạm. Mở vòng, di chuyển gà, theo dõi hệ số và rời khi bước tiếp bắt đầu quá rủi ro.",
        "Tốc độ chủ yếu phụ thuộc thiết bị và mạng. Điện thoại mới với internet ổn sẽ mượt hơn. Trình duyệt cũ hoặc sóng yếu có thể phản hồi chậm. Màn hình nhỏ nên luôn kiểm tra cược trước Play — một chạm cẩu thả đủ để bắt đầu sai số tiền. Chơi qua trình duyệt. Tránh APK lạ từ site không rõ, đặc biệt hứa predictor, hack hoặc phiên bản Ice Fish «đặc biệt».",
    ],
    "h2_final": "Kết luận",
    "final_paras": [
        "Ice Fish hợp Jack-Pot vì game không cần thiết lập phức tạp. Mở casino, tìm tựa, chọn mode, đặt cược — vòng bắt đầu. Với kiểu game nhanh này, đó là điều bạn cần.",
        "Sức hút chính đơn giản: vòng ngắn, nút rõ, hệ số tăng và lựa chọn liên tục — lấy kết quả hiện tại hay mạo hiểm thêm một bước. Dễ hiểu nhưng game vẫn có thể cuốn nhanh.",
        "Jack-Pot cho Ice Fish chỗ chơi gọn, nhất là từ mobile. Tìm kiếm hoạt động, lobby không quá nặng và demo hữu ích nếu muốn thử cơ chế trước.",
        "Ice Fish không phải công cụ kiếm tiền. Đây là game casino có rủi ro thật. Dùng demo trước tiền thật, đặt giới hạn, đừng đuổi thua và coi mỗi vòng là giải trí, không phải thu nhập.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Jack-Pot là gì?", "Jack-Pot là nền tảng casino trực tuyến và cá cược thể thao. Bạn có thể chơi slots, live casino, instant games, crash games và cá cược thể thao."],
        ["Jack-Pot chỉ có casino?", "Không. Casino chỉ là một phần nền tảng."],
        ["Đăng ký nhanh không?", "Đăng ký dưới một phút. Sau đó trang có thể hiện chọn bonus hoặc mở cửa sổ nạp."],
        ["Jack-Pot có bonus không?", "Có, nhưng xem bonus hiện tại trên trang chính thức."],
        ["Tìm được Ice Fish trên Jack-Pot không?", "Có, nếu Ice Fish có trong lobby Jack-Pot. Tìm theo tên game trước. Nếu không có, thử nhà cung cấp InOut."],
        ["Jack-Pot dùng mobile được không?", "Có, Jack-Pot mở trên mobile qua trình duyệt. Lobby casino, sport, cashier và tài khoản dùng được trên điện thoại. Tốc độ phụ thuộc thiết bị và mạng. Sóng yếu hoặc trình duyệt cũ có thể tải game chậm hơn."],
        ["Jack-Pot an toàn không?", "Có, nhưng chắc chắn bạn ở domain Jack-Pot thật. Bản sao giả có thể rất giống site gốc."],
        ["Jack-Pot có giấy phép gì?", "Theo thông tin chúng tôi đã xem trước đó, Jack-Pot hoạt động với giấy phép offshore Anjouan. Đây là giấy phép hợp pháp, thường dùng cho thương hiệu casino mới. Tuy nhiên không bằng mức bảo vệ người chơi của cơ quan quản lý chặt hơn. Vì vậy uy tín, lịch sử thanh toán và chất lượng hỗ trợ rất quan trọng."],
        ["Jack-Pot có yêu cầu giấy tờ không?", "Rất có thể trước khi rút, có. Chỉ tải giấy tờ qua trang Jack-Pot chính thức."],
        ["Rút tiền có tức thì không?", "Không phải lúc nào. Rút nhỏ có thể nhanh hơn. Thanh toán lớn có thể lâu hơn do xác minh, giới hạn nhà cung cấp hoặc kiểm tra thủ công."],
        ["Chơi trên Jack-Pot có rủi ro không?", "Có. Slots, crash games, live casino và cá cược thể thao đều có rủi ro. Bạn có thể mất tiền. Đặt giới hạn, đừng đuổi thua và đừng coi Jack-Pot là cách kiếm tiền. Đây là giải trí cờ bạc, không phải thu nhập."],
    ],
}

HI = {
    "h1": "Jack-Pot — Ice Fish",
    "h2_about": "Jack-Pot के बारे में",
    "img_hero_alt": "Jack-Pot ऑनलाइन कैसिनो लॉबी और Ice Fish अवलोकन",
    "about_paras": [
        "Jack-Pot एक ऑनलाइन प्लेटफ़ॉर्म है जहाँ कैसिनो गेम और स्पोर्ट्स बेटिंग एक अकाउंट से उपलब्ध हैं। साइट में साफ़ सेक्शन हैं: casino, live, sport, promos, payments, tournaments और cashback। यूज़र के लिए चुनना आसान है। प्लेटफ़ॉर्म काफ़ी सरल लगता है। कैसिनो कैटेगरी में बँटा है। अगर आप जानते हैं कि क्या खेलना है, तो मुख्य सेक्शन भी इस्तेमाल कर सकते हैं।",
        "Ice Fish Jack-Pot के लिए अच्छा फिट है क्योंकि यह वही तरह का गेम है जिसे तेज़ एक्सेस चाहिए। कोई भी विशाल लॉबी में तेज़ आर्केड गेम ढूँढना नहीं चाहता। खोलें, बेट सेट करें, रिस्क लेवल चुनें और राउंड शुरू। Ice Fish के लिए Jack-Pot का मुख्य फायदा गेम तक साफ़ रास्ता है: तेज़ लॉबी, सर्च बार, मोबाइल एक्सेस और बिना रुकावट लेआउट। छोटे राउंड और तेज़ फैसलों वाले गेम के लिए यही काफ़ी है।",
        "Jack-Pot में बोनस और प्रोमो भी हैं, इसलिए खेलने से पहले प्रमोशन सेक्शन देखें। बिना पढ़े कुछ भी एक्टिवेट न करें। बोनस समय या नियमों से सीमित हो सकते हैं।",
    ],
    "h2_where": "Jack-Pot पर Ice Fish कहाँ मिले",
    "where_paras": [
        "अगर पता है कहाँ देखना है, तो Jack-Pot पर Ice Fish ढूँढना आसान है। casino सेक्शन खोलें और Slots या Crash Games में जाएँ। ज़्यादातर तेज़ आर्केड गेम आमतौर पर इन्हीं कैटेगरी में होते हैं।",
        "सबसे तेज़ तरीका सर्च है। सर्च बार में Ice Fish टाइप करें, गेम बैनर का इंतज़ार करें और खोलें। गेम अलग विंडो में चलना चाहिए।",
        "प्रोवाइडर से भी खोज सकते हैं। InOut डालें और Jack-Pot इस स्टूडियो के गेम दिखाएगा। यह तब मददगार है जब सिर्फ Ice Fish नहीं, दूसरे InOut टाइटल भी चाहिए।",
        "कभी-कभी गेम Crash Games में भी दिखता है, जहाँ प्लेटफ़ॉर्म अक्सर instant games, crash games और क्लासिक स्लॉट से बाहर के टाइटल रखते हैं।",
    ],
    "short_path_title": "छोटा रास्ता सरल है:",
    "short_path_item": "Casino → Crash Games / Slots → Ice Fish → Play Now",
    "short_path_outro": ["अगर नाम से न दिखे, तो InOut खोजें।"],
    "h2_play": "Jack-Pot पर Ice Fish कैसे खेलें",
    "play_paras": [
        "Jack-Pot पर Ice Fish शुरू करना आसान है। नए हों तो Easy से शुरू करें। गेम समझने के लिए ज़्यादा जगह मिलती है। Medium पहले से तेज़ लगता है। Hard और Hardcore उन खिलाड़ियों के लिए बेहतर हैं जो जानते हैं कि इस तरह के गेम में बैलेंस कितनी जल्दी गायब हो सकता है। Play दबाने से पहले स्टेक फिर चेक करें। खासकर फोन पर। एक जल्दबाज़ टैप गलत राशि से राउंड शुरू कर सकता है।",
        "मुख्य बटन Cash Out है। जब मौजूदा मल्टीप्लायर काफ़ी हो और रुकना हो, दबाएँ। बहुत देर तक इंतज़ार और राउंड खराब होने पर स्टेक चला जाता है।",
        "अगर यह InOut Games का ओरिजिनल Ice Fish है, तो Jack-Pot पर बुनियादी नियम दूसरे प्लेटफ़ॉर्म जैसे ही हैं: आगे बढ़ें, मल्टीप्लायर बढ़ाएँ, राउंड हारने से पहले Cash Out करें।",
    ],
    "h2_demo": "Jack-Pot पर डेमो और रियल-मनी प्ले",
    "demo_paras": [
        "Jack-Pot पर Ice Fish डेमो उपलब्ध है, और मैं वहीं से शुरू करूँगा। इसलिए नहीं कि डेमो जीत सिखाता है — नहीं सिखाता। लेकिन बिना दबाव के गेम देखने देता है।",
        "डेमो मोड में वर्चुअल बैलेंस से खेलते हैं। कठिनाई बदल सकते हैं, अलग बेट आज़मा सकते हैं, सड़क पर मुर्गी हिला सकते हैं और अलग-अलग पॉइंट पर Cash Out आज़मा सकते हैं। राउंड खराब हो तो असली पैसे पर असर नहीं। रियल-मनी मोड अलग लगता है। गेम, बटन और मल्टीप्लायर वैसे ही हो सकते हैं। लेकिन अपना बैलेंस जुड़ते ही हर कदम भारी लगता है।",
        "डेमो में लोग आमतौर पर काफ़ी ढीले खेलते हैं। बैलेंस वर्चुअल है, इसलिए कठिन मोड या थोड़ा आगे जाना दर्द नहीं देता।",
        "रियल मनी में वही चाल अलग महसूस होती है। वही बटन, वही मल्टीप्लायर, वही सड़क — लेकिन स्टेक आपका है। कुछ जल्दी Cash Out करते हैं क्योंकि हारना नहीं चाहते। कुछ पिछला राउंड वापस पाने के लिए बहुत आगे जाते हैं। यहीं दबाव शुरू होता है। पहले Jack-Pot पर डेमो इस्तेमाल करें। वहीं गेम सीखें। रियल-मनी तभी समझ में आता है जब मैकेनिक्स समझें और जोखिम स्वीकार करें।",
    ],
    "h2_mobile": "Jack-Pot के ज़रिए मोबाइल पर Ice Fish",
    "mobile_paras": [
        "Ice Fish फोन पर ठीक चलता है। Jack-Pot खोलें, गेम ढूँढें, बेट सेट करें और भारी इंटरफ़ेस के बिना राउंड शुरू करें। मोबाइल पर लेआउट और टाइट हो जाता है। बेट फ़ील्ड, Play और Cash Out फिर भी आसानी से पहुँच में हैं — इस गेम में यह मायने रखता है। मल्टीप्लायर चल रहा हो तब एग्ज़िट बटन ढूँढना नहीं चाहते।",
        "राउंड छोटे हैं, इसलिए मोबाइल प्ले फिट बैठता है। सामान्य सेशन में कुछ टैप ही लगते हैं। राउंड खोलें, मुर्गी हिलाएँ, मल्टीप्लायर देखें और जब अगला कदम बहुत रिस्की लगे, निकल जाएँ।",
        "गति ज़्यादातर डिवाइस और कनेक्शन पर निर्भर है। नया फोन और स्थिर इंटरनेट पर स्मूद लगेगा। पुराना ब्राउज़र या कमज़ोर सिग्नल स्क्रीन को धीमा कर सकता है। छोटी स्क्रीन होने से Play से पहले हमेशा स्टेक चेक करें — एक लापरवाह टैप गलत राशि से शुरू कराने के लिए काफ़ी है। ब्राउज़र से खेलें। अनजान साइटों के रैंडम APK से बचें, खासकर predictor, hack या «खास» Ice Fish वर्ज़न वाले।",
    ],
    "h2_final": "अंतिम विचार",
    "final_paras": [
        "Ice Fish Jack-Pot के लिए अच्छा फिट है क्योंकि गेम को जटिल सेटअप नहीं चाहिए। casino खोलें, टाइटल ढूँढें, मोड चुनें, बेट सेट करें — राउंड शुरू। इस तरह के तेज़ गेम के लिए यही चाहिए।",
        "मुख्य आकर्षण सरल है: छोटे राउंड, साफ़ बटन, बढ़ता मल्टीप्लायर और लगातार चुनाव — मौजूदा नतीजा लें या एक कदम और जोखिम उठाएँ। समझना आसान, लेकिन गेम जल्दी खींच सकता है।",
        "Jack-Pot Ice Fish को साफ़ जगह देता है, खासकर मोबाइल से। सर्च काम करता है, लॉबी बहुत भारी नहीं और मैकेनिक्स पहले टेस्ट करने के लिए डेमो उपयोगी है।",
        "Ice Fish पैसा कमाने का टूल नहीं है। यह असली जोखिम वाला कैसिनो गेम है। रियल-मनी से पहले डेमो, लिमिट सेट करें, नुकसान का पीछा न करें और हर राउंड को मनोरंजन समझें, आय नहीं।",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Jack-Pot क्या है?", "Jack-Pot एक ऑनलाइन कैसिनो और स्पोर्ट्सबुक प्लेटफ़ॉर्म है। आप slots, live casino, instant games, crash games और स्पोर्ट्स बेटिंग खेल सकते हैं।"],
        ["क्या Jack-Pot सिर्फ कैसिनो के लिए है?", "नहीं। कैसिनो प्लेटफ़ॉर्म का सिर्फ एक हिस्सा है।"],
        ["रजिस्ट्रेशन कितनी तेज़ है?", "रजिस्ट्रेशन एक मिनट से कम लेता है। उसके बाद साइट बोनस चुनाव दिखा सकती है या डिपॉज़िट विंडो खोल सकती है।"],
        ["क्या Jack-Pot बोनस देता है?", "हाँ, लेकिन मौजूदा बोनस के लिए आधिकारिक वेबसाइट देखें।"],
        ["क्या Jack-Pot पर Ice Fish मिलेगा?", "हाँ, अगर Ice Fish Jack-Pot लॉबी में उपलब्ध है। पहले गेम नाम से खोजें। कुछ न दिखे तो प्रोवाइडर InOut आज़माएँ।"],
        ["क्या Jack-Pot मोबाइल पर काम करता है?", "हाँ, Jack-Pot ब्राउज़र से मोबाइल पर खुलता है। कैसिनो लॉबी, स्पोर्ट्सबुक, कैशियर और अकाउंट फोन से उपयोगी हैं। गति डिवाइस और कनेक्शन पर निर्भर है। कमज़ोर सिग्नल या पुराना ब्राउज़र कुछ गेम धीरे लोड कर सकता है।"],
        ["क्या Jack-Pot सुरक्षित है?", "हाँ, लेकिन सुनिश्चित करें कि आप असली Jack-Pot डोमेन पर हैं। नकली कैसिनो कॉपी ओरिजिनल साइट जैसी दिख सकती हैं।"],
        ["Jack-Pot के पास कौन-सा लाइसेंस है?", "पहले देखी गई जानकारी के अनुसार, Jack-Pot Anjouan ऑफशोर लाइसेंस के साथ काम करता है। यह कानूनी लाइसेंस है, अक्सर नए कैसिनो ब्रांड इस्तेमाल करते हैं। फिर भी यह सख्त नियामकों जैसी सुरक्षा नहीं देता। इसलिए प्रतिष्ठा, भुगतान इतिहास और सपोर्ट गुणवत्ता बहुत मायने रखती है।"],
        ["क्या Jack-Pot दस्तावेज़ माँगेगा?", "निकासी से पहले बहुत संभव है, हाँ। दस्तावेज़ सिर्फ आधिकारिक Jack-Pot वेबसाइट से अपलोड करें।"],
        ["क्या निकासी तुरंत होती है?", "हमेशा नहीं। छोटी निकासी तेज़ हो सकती है। बड़े भुगतान वेरिफिकेशन, प्रोवाइडर लिमिट या मैनुअल चेक से लंबे लग सकते हैं।"],
        ["क्या Jack-Pot पर खेलना जोखिम भरा है?", "हाँ। Slots, crash games, live casino और स्पोर्ट्स बेटिंग में जोखिम है। पैसा खो सकते हैं। लिमिट लगाएँ, नुकसान का पीछा न करें और Jack-Pot को कमाई का तरीका न समझें। यह जुआ मनोरंजन है, आय नहीं।"],
    ],
}

BN = {
    "h1": "Jack-Pot — Ice Fish",
    "h2_about": "Jack-Pot সম্পর্কে",
    "img_hero_alt": "Jack-Pot অনলাইন ক্যাসিনো লবি এবং Ice Fish ওভারভিউ",
    "about_paras": [
        "Jack-Pot একটি অনলাইন প্ল্যাটফর্ম যেখানে ক্যাসিনো গেম ও স্পোর্টস বেটিং এক অ্যাকাউন্টে পাওয়া যায়। সাইটে স্পষ্ট সেকশন আছে: casino, live, sport, promos, payments, tournaments ও cashback। ইউজারের জন্য ঠিকানা বেছে নেওয়া সহজ। প্ল্যাটফর্ম যথেষ্ট সরল। ক্যাসিনো ক্যাটেগরিতে ভাগ। আপনি জানলে মূল সেকশনও ব্যবহার করতে পারেন কী খেলবেন।",
        "Ice Fish Jack-Pot-এর জন্য ভালো ফিট, কারণ এটি ঠিক সেই ধরনের গেম যার দ্রুত অ্যাক্সেস দরকার। কেউ বিশাল লবিতে দ্রুত আর্কেড গেম খুঁজতে চায় না। খুলুন, বেট সেট করুন, রিস্ক লেভেল বেছে নিন, রাউন্ড শুরু। Ice Fish-এর জন্য Jack-Pot-এর মূল সুবিধা গেমে পরিষ্কার পথ: দ্রুত লবি, সার্চ বার, মোবাইল অ্যাক্সেস ও বাধা না দেওয়া লেআউট। ছোট রাউন্ড ও দ্রুত সিদ্ধান্তের গেমের জন্য এটাই যথেষ্ট।",
        "Jack-Pot-এ বোনাস ও প্রোমোও আছে, তাই খেলার আগে প্রমোশন সেকশন দেখুন। অন্ধভাবে কিছু অ্যাক্টিভেট করবেন না। বোনাস সময় বা নিয়মে সীমিত হতে পারে।",
    ],
    "h2_where": "Jack-Pot-এ Ice Fish কোথায় পাবেন",
    "where_paras": [
        "জানলে Jack-Pot-এ Ice Fish খুঁজে পাওয়া সহজ। casino সেকশন খুলে Slots বা Crash Games-এ যান। বেশিরভাগ দ্রুত আর্কেড গেম সাধারণত এই ক্যাটেগরিতে থাকে।",
        "দ্রুততম উপায় সার্চ। সার্চ বারে Ice Fish টাইপ করুন, গেম ব্যানারের জন্য অপেক্ষা করুন ও খুলুন। গেম আলাদা উইন্ডোতে চালু হওয়া উচিত।",
        "প্রোভাইডার দিয়েও খুঁজতে পারেন। InOut লিখলে Jack-Pot এই স্টুডিওর গেম দেখাবে। শুধু Ice Fish নয়, অন্য InOut টাইটল চাইলে সহায়ক।",
        "কখনও গেম Crash Games-এও থাকে, যেখানে প্ল্যাটফর্ম প্রায়ই instant games, crash games ও ক্লাসিক স্লটের বাইরের টাইটল রাখে।",
    ],
    "short_path_title": "ছোট পথ সহজ:",
    "short_path_item": "Casino → Crash Games / Slots → Ice Fish → Play Now",
    "short_path_outro": ["নামে না এলে InOut সার্চ করুন।"],
    "h2_play": "Jack-Pot-এ Ice Fish কীভাবে খেলবেন",
    "play_paras": [
        "Jack-Pot-এ Ice Fish শুরু করা সহজ। নতুন হলে Easy দিয়ে শুরু করুন। গেম বোঝার জন্য বেশি জায়গা মিলে। Medium ইতিমধ্যে তীক্ষ্ণ। Hard ও Hardcore তাদের জন্য ভালো যারা জানেন এই ধরনের গেমে ব্যালেন্স কত দ্রুত শেষ হতে পারে। Play চাপার আগে স্টেক আবার চেক করুন। বিশেষ করে ফোনে। এক তাড়াহুড়ো ট্যাপ ভুল পরিমাণে রাউন্ড শুরু করতে পারে।",
        "মূল বাটন Cash Out। বর্তমান মাল্টিপ্লায়ার যথেষ্ট হলে ও থামতে চাইলে চাপুন। অনেক দেরি করলে ও রাউন্ড খারাপ হলে স্টেক হারান।",
        "যদি এটি InOut Games-এর অরিজিনাল Ice Fish হয়, Jack-Pot-এ মৌলিক নিয়ম অন্য প্ল্যাটফর্মের মতো: এগিয়ে যান, মাল্টিপ্লায়ার বাড়ান, রাউন্ড হারানোর আগে Cash Out।",
    ],
    "h2_demo": "Jack-Pot-এ ডেমো ও রিয়েল-মানি প্লে",
    "demo_paras": [
        "Jack-Pot-এ Ice Fish ডেমো আছে, আর আমি সেখান থেকেই শুরু করব। ডেমো জিততে শেখায় বলে নয় — শেখায় না। কিন্তু চাপ ছাড়া গেম দেখতে দেয়।",
        "ডেমো মোডে ভার্চুয়াল ব্যালেন্সে খেলেন। কঠিনতা বদলাতে, আলাদা বেট টেস্ট করতে, রাস্তায় মুরগি সরাতে ও বিভিন্ন পয়েন্টে Cash Out চেষ্টা করতে পারেন। রাউন্ড খারাপ হলে আসল টাকায় কিছু হয় না। রিয়েল-মানি মোড আলাদা অনুভূতি দেয়। গেম, বাটন ও মাল্টিপ্লায়ার একই হতে পারে। কিন্তু নিজের ব্যালেন্স জড়ালে প্রতিটি ধাপ ভারী লাগে।",
        "ডেমোতে মানুষ সাধারণত অনেক ঢিলা খেলে। ব্যালেন্স ভার্চুয়াল, তাই কঠিন মোড বা একটু এগিয়ে যাওয়া ব্যথা দেয় না।",
        "রিয়েল মানিতে একই নড়াচড়া আলাদা। একই বাটন, একই মাল্টিপ্লায়ার, একই রাস্তা — কিন্তু স্টেক আপনার। কেউ খুব তাড়াতাড়ি Cash Out করে হারতে চায় না বলে। কেউ আগের রাউন্ড ফেরত চেয়ে অনেক দূর যায়। সেখানেই চাপ শুরু। আগে Jack-Pot-এ ডেমো ব্যবহার করুন। সেখানে গেম শিখুন। মেকানিক্স বুঝে ও ঝুঁকি মেনে নিলে রিয়েল-মানি যুক্তিযুক্ত।",
    ],
    "h2_mobile": "Jack-Pot দিয়ে মোবাইলে Ice Fish",
    "mobile_paras": [
        "Ice Fish ফোনে ভালো চলে। Jack-Pot খুলুন, গেম খুঁজুন, বেট সেট করুন, ভারী ইন্টারফেস ছাড়াই রাউন্ড শুরু করুন। মোবাইলে লেআউট টাইট হয়। বেট ফিল্ড, Play ও Cash Out এখনও সহজে পৌঁছানো যায় — এই গেমে গুরুত্বপূর্ণ। মাল্টিপ্লায়ার চলতে থাকলে এক্সিট বাটন খুঁজতে চাইবেন না।",
        "রাউন্ড ছোট, তাই মোবাইল প্লে মানায়। সাধারণ সেশনে কয়েকটি ট্যাপ। রাউন্ড খুলুন, মুরগি সরান, মাল্টিপ্লায়ার দেখুন, পরের ধাপ খুব ঝুঁকিপূর্ণ মনে হলে বের হন।",
        "গতি মূলত ডিভাইস ও সংযোগে নির্ভর করে। নতুন ফোন ও স্থিতিশীল ইন্টারনেটে মসৃণ। পুরনো ব্রাউজার বা দুর্বল সিগন্যাল স্ক্রিন ধীর করতে পারে। ছোট ডিসপ্লে হওয়ায় Play-এর আগে স্টেক চেক করুন — এক অসতর্ক ট্যাপ ভুল পরিমাণে শুরু করাতে পারে। ব্রাউজারে খেলুন। অজানা সাইটের র্যান্ডম APK এড়ান, বিশেষ করে predictor, hack বা «বিশেষ» Ice Fish সংস্করণ প্রতিশ্রুতি দেয় এমন।",
    ],
    "h2_final": "চূড়ান্ত মতামত",
    "final_paras": [
        "Ice Fish Jack-Pot-এর জন্য ভালো ফিট কারণ গেমের জটিল সেটআপ দরকার নেই। casino খুলুন, টাইটল খুঁজুন, মোড বেছে নিন, বেট সেট করুন — রাউন্ড শুরু। এই দ্রুত গেমের জন্য ঠিক এটাই চান।",
        "মূল আকর্ষণ সরল: ছোট রাউন্ড, স্পষ্ট বাটন, বাড়তে থাকা মাল্টিপ্লায়ার ও ক্রমাগত পছন্দ — বর্তমান ফলাফল নেবেন নাকি আরেক ধাপ ঝুঁকি নেবেন। বোঝা সহজ, কিন্তু গেম দ্রুত টেনে নিতে পারে।",
        "Jack-Pot Ice Fish-কে পরিষ্কার জায়গা দেয়, বিশেষ করে মোবাইল থেকে। সার্চ কাজ করে, লবি খুব ভারী নয়, মেকানিক্স আগে টেস্ট করতে ডেমো দরকারি।",
        "Ice Fish টাকা কমানোর টুল নয়। এটি বাস্তব ঝুঁকিপূর্ণ ক্যাসিনো গেম। রিয়েল-মানির আগে ডেমো, লিমিট সেট করুন, ক্ষতি পিছু না চালান, প্রতিটি রাউন্ডকে বিনোদন ধরুন, আয় নয়।",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Jack-Pot কী?", "Jack-Pot একটি অনলাইন ক্যাসিনো ও স্পোর্টসবুক প্ল্যাটফর্ম। slots, live casino, instant games, crash games ও স্পোর্টস বেটিং খেলতে পারেন।"],
        ["Jack-Pot কি শুধু ক্যাসিনোর জন্য?", "না। ক্যাসিনো প্ল্যাটফর্মের শুধু একটি অংশ।"],
        ["রেজিস্ট্রেশন কত দ্রুত?", "রেজিস্ট্রেশন এক মিনিটের কম সময় নেয়। তারপর সাইট বোনাস পছন্দ দেখাতে বা ডিপোজিট উইন্ডো খুলতে পারে।"],
        ["Jack-Pot কি বোনাস দেয়?", "হ্যাঁ, কিন্তু বর্তমান বোনাসের জন্য অফিসিয়াল ওয়েবসাইট দেখুন।"],
        ["Jack-Pot-এ Ice Fish পাবো?", "হ্যাঁ, যদি Ice Fish Jack-Pot লবিতে থাকে। আগে গেমের নামে সার্চ করুন। কিছু না এলে প্রোভাইডার InOut চেষ্টা করুন।"],
        ["Jack-Pot মোবাইলে কাজ করে?", "হ্যাঁ, Jack-Pot ব্রাউজারে মোবাইলে খোলে। ক্যাসিনো লবি, স্পোর্টসবুক, ক্যাশিয়ার ও অ্যাকাউন্ট ফোনে ব্যবহারযোগ্য। গতি ডিভাইস ও সংযোগে নির্ভর করে। দুর্বল সিগন্যাল বা পুরনো ব্রাউজার কিছু গেম ধীর লোড করতে পারে।"],
        ["Jack-Pot নিরাপদ?", "হ্যাঁ, কিন্তু নিশ্চিত করুন আসল Jack-Pot ডোমেইনে আছেন। নকল ক্যাসিনো কপি মূল সাইটের খুব কাছাকাছি দেখতে পারে।"],
        ["Jack-Pot-এর কী লাইসেন্স আছে?", "আগে যে তথ্য দেখেছি, Jack-Pot Anjouan অফশোর লাইসেন্সে কাজ করে। এটি বৈধ লাইসেন্স, প্রায়ই নতুন ক্যাসিনো ব্র্যান্ড ব্যবহার করে। তবু কঠোর নিয়ন্ত্রকের মতো সুরক্ষা দেয় না। তাই খ্যাতি, পেমেন্ট ইতিহাস ও সাপোর্ট গুণমান গুরুত্বপূর্ণ।"],
        ["Jack-Pot কি ডকুমেন্ট চাইবে?", "উত্তোলনের আগে সম্ভবত হ্যাঁ। শুধু অফিসিয়াল Jack-Pot ওয়েবসাইট দিয়ে আপলোড করুন।"],
        ["উত্তোলন তাৎক্ষণিক?", "সবসময় নয়। ছোট উত্তোলন দ্রুত হতে পারে। বড় পেমেন্ট যাচাই, প্রোভাইডার লিমিট বা ম্যানুয়াল চেকে দেরি হতে পারে।"],
        ["Jack-Pot-এ খেলা ঝুঁকিপূর্ণ?", "হ্যাঁ। slots, crash games, live casino ও স্পোর্টস বেটিংতে ঝুঁকি আছে। টাকা হারাতে পারেন। লিমিট ব্যবহার করুন, ক্ষতি পিছু না চালান, Jack-Pot-কে আয়ের উপায় ধরবেন না। এটি জুয়া বিনোদন, আয় নয়।"],
    ],
}

EXPORT = {"vi": VI, "hi": HI, "bn": BN}
