# -*- coding: utf-8 -*-
"""Overrides for casino_articles#11 — VI, HI, BN."""

VI = {
    "h2_intro": "Ice Fish trên 1xBet — người chơi đang tìm gì",
    "img_hero_alt": "Các tựa Ice Fish trong lobby casino 1xBet",
    "intro_paras": [
        "Người chơi tìm Ice Fish trên 1xBet vì đây là một trong những tựa casino nhanh được nhắc đến khắp nơi. Luật dễ hiểu: gà tiến, hệ số tăng, phải thoát trước khi vòng hỏng.",
        "Đó là sức hút. Không setup slot dài, không màn bonus phức tạp. Mở game là hiểu áp lực: lấy kết quả hiện tại hay thêm một bước.",
        "Ice Fish hợp phong cách game nhiều người tìm trên 1xBet — khởi động nhanh, vòng ngắn, Cash Out.",
        "Khả dụng có thể phụ thuộc khu vực và lobby.",
        "Bước đầu: kiểm tra tìm kiếm casino 1xBet — gõ Ice Fish hoặc InOut.",
    ],
    "h2_about": "Giới thiệu 1xBet",
    "img_about_alt": "Trang chủ cá cược và casino 1xBet",
    "about_paras": [
        "1xBet là nền tảng cá cược và casino lớn trong một tài khoản.",
        "Có slots, live casino, crash, instant, eSports — lobby đầy đủ.",
        "Với game nhanh: mở casino, tìm kiếm, chuyển danh mục trong cùng tài khoản.",
        "Ice Fish phù hợp: vòng ngắn, nút đơn giản, truy cập nhanh.",
    ],
    "h2_available": "Ice Fish có trên 1xBet không?",
    "img_search_alt": "Kết quả tìm Ice Fish trên 1xBet",
    "available_paras": [
        "Có, Ice Fish có trên 1xBet cùng các tựa InOut Games — bản gốc và Ice Fish 2.",
        "Cách dễ nhất: thanh tìm kiếm. Demo cũng có để thử cơ chế trước khi chơi tiền thật.",
    ],
    "short_path_title": "Đường ngắn:",
    "short_path_item": "Casino → Search → Ice Fish → Choose version → Demo or Play",
    "h2_lobby": "Kiểm tra Ice Fish trong lobby 1xBet",
    "img_filter_alt": "Bộ lọc và tìm nhà cung cấp InOut trên 1xBet",
    "lobby_paras": [
        "Cách sạch nhất là tìm trong lobby, không phải danh mục. Gõ Ice Fish hoặc InOut.",
        "Nếu không thấy, thử Slots, Crash Games, Instant Games. Lobby thay đổi theo quốc gia và tiền tệ.",
    ],
    "quick_check_title": "Kiểm tra nhanh:",
    "quick_check_item": "Casino → Search → Ice Fish or InOut → choose the version → open demo or real play",
    "lobby_outro": ["Đừng cuộn cả lobby — tìm kiếm nhanh hơn."],
    "h2_play": "Cách game Ice Fish hoạt động trên 1xBet",
    "img_play_alt": "Gameplay Ice Fish với hệ số và Cash Out trên 1xBet",
    "play_paras": [
        "Trên 1xBet không chỉ một tựa: original, 2.0, Bonus, Gold, Vegas, Race.",
        "Bắt đầu với cược nhỏ, sau chọn mức rủi ro.",
        "Vòng lặp quyết định: gà di chuyển, hệ số tăng.",
        "Áp lực từ một quyết định nhỏ lặp lại.",
        "Cash Out là nút quan trọng nhất.",
    ],
    "h2_why": "Vì sao Ice Fish hợp lobby 1xBet",
    "img_versions_alt": "Các phiên bản Ice Fish trong lobby 1xBet",
    "why_paras": [
        "1xBet đã có slots, crash, instant, live — Ice Fish tự nhiên phù hợp.",
        "Nhiều phiên bản liên quan trong cùng lobby.",
        "Câu hỏi: mở phiên bản nào trước.",
        "Original để hiểu format; 2.0 tinh chỉnh hơn.",
        "Trên 1xBet giống một danh mục nhỏ riêng.",
    ],
    "h2_mobile": "Chơi mobile qua 1xBet",
    "img_mobile_alt": "Ice Fish trên app mobile 1xBet",
    "mobile_paras": [
        "1xBet ổn trên mobile — app hoặc trình duyệt.",
        "Phiên ngắn, màn hình không quá tải.",
        "Cẩn thận ô cược — chạm nhanh có thể sai số tiền.",
        "Dùng app chính thức; tránh APK và predictor.",
    ],
    "h2_bonuses": "Bonus và khuyến mãi trên 1xBet",
    "img_bonus_alt": "Mục bonus casino 1xBet",
    "bonus_paras": [
        "Bonus từ nền tảng, không từ game.",
        "Một số chỉ cho slots/sport; một số loại crash/instant.",
        "Đọc điều khoản trước khi kích hoạt.",
        "Kiểm tra wagering và giới hạn cược.",
    ],
    "h2_safety": "An toàn trên 1xBet",
    "safety_paras": [
        "Site giả có thể rất giống thật.",
        "Tránh app predictor.",
        "Giải trí, không phải thu nhập.",
    ],
    "h2_final": "Kết luận",
    "final_paras": [
        "1xBet mạnh với game nhanh: tìm kiếm, mobile và nhiều tựa Ice Fish.",
        "Bắt đầu bằng Demo và kiểm tra trong lobby của bạn.",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Ice Fish có trên 1xBet?", "Có, trong lobby casino với InOut khác."],
        ["Tìm Ice Fish thế nào?", "Casino → tìm kiếm → Ice Fish."],
        ["Tìm theo InOut?", "Có."],
        ["Không thấy trong lobby?", "Thử InOut; có thể ẩn theo vùng."],
        ["Có Demo?", "Có."],
        ["Cơ chế?", "Quyết định ngắn, cược, hệ số, Cash Out."],
        ["Bonus cho crash?", "Không phải lúc nào."],
        ["Predictor an toàn?", "Không."],
        ["Phiên bản nào trước?", "Ice Fish original."],
        ["Khác trong app?", "Hơi khác — màn hình gọn hơn."],
    ],
}

HI = {
    "h1": "1xBet - Ice Fish",
    "h2_intro": "1xBet पर Ice Fish — खिलाड़ी क्या ढूँढते हैं",
    "img_hero_alt": "1xBet कैसिनो लॉबी में Ice Fish टाइटल",
    "intro_paras": [
        "खिलाड़ी 1xBet पर Ice Fish ढूँढते हैं क्योंकि यह उन तेज़ casino गेम में से एक है जिसकी चर्चा हर जगह है। नियम सरल: मुर्गी आगे, मल्टीप्लायर बढ़ता, राउंड टूटने से पहले निकलना।",
        "यही आकर्षण है। लंबा slot setup नहीं। गेम खोलते ही दबाव समझ आता है: मौजूदा नतीजा लें या एक कदम और।",
        "Ice Fish 1xBet पर कई खिलाड़ियों की पसंदीदा शैली से मेल खाता है — तेज़ लॉन्च, छोटे राउंड, Cash Out।",
        "उपलब्धता क्षेत्र और लॉबी पर निर्भर हो सकती है।",
        "पहला कदम: 1xBet casino सर्च — Ice Fish या InOut टाइप करें।",
    ],
    "h2_about": "1xBet के बारे में",
    "img_about_alt": "1xBet स्पोर्ट्सबुक और कैसिनो होमपेज",
    "about_paras": [
        "1xBet एक बड़ा बेटिंग और कैसिनो प्लेटफ़ॉर्म है — सब एक अकाउंट में।",
        "slots, live casino, crash, instant, eSports — पूरा लॉबी।",
        "तेज़ गेम के लिए: casino, सर्च, कैटेगरी एक ही अकाउंट में।",
        "Ice Fish फिट बैठता है: छोटे राउंड, सरल बटन।",
    ],
    "h2_available": "क्या Ice Fish 1xBet पर है?",
    "img_search_alt": "1xBet पर Ice Fish सर्च परिणाम",
    "available_paras": [
        "हाँ, Ice Fish 1xBet पर InOut Games की लाइन के साथ — original और Ice Fish 2।",
        "सबसे आसान: सर्च बार। Demo भी उपलब्ध है।",
    ],
    "short_path_title": "छोटा रास्ता:",
    "short_path_item": "Casino → Search → Ice Fish → Choose version → Demo or Play",
    "h2_lobby": "1xBet लॉबी में Ice Fish जाँच",
    "img_filter_alt": "1xBet पर InOut फ़िल्टर और सर्च",
    "lobby_paras": [
        "सबसे साफ़ तरीका: लॉबी सर्च। Ice Fish या InOut।",
        "न दिखे तो Slots, Crash Games, Instant Games देखें।",
    ],
    "quick_check_title": "त्वरित जाँच:",
    "quick_check_item": "Casino → Search → Ice Fish or InOut → choose the version → open demo or real play",
    "lobby_outro": ["पूरा लॉबी स्क्रॉल न करें — सर्च तेज़ है।"],
    "h2_play": "1xBet पर Ice Fish गेम कैसे चलते हैं",
    "img_play_alt": "1xBet पर मल्टीप्लायर और Cash Out के साथ Ice Fish गेमप्ले",
    "play_paras": [
        "1xBet पर एक टाइटल नहीं: original, 2.0, Bonus, Gold, Vegas, Race।",
        "सरल स्टेक से शुरू, फिर जोखिम चुनें।",
        "वही निर्णय लूप।",
        "छोटे दोहराए निर्णय से दबाव।",
        "Cash Out सबसे महत्वपूर्ण बटन।",
    ],
    "h2_why": "Ice Fish 1xBet लॉबी में क्यों फिट है",
    "img_versions_alt": "1xBet लॉबी में अलग Ice Fish वर्ज़न",
    "why_paras": [
        "1xBet में slots, crash, instant, live पहले से — Ice Fish स्वाभाविक रूप से फिट।",
        "लॉबी में कई संबंधित वर्ज़न।",
        "सवाल: पहले कौन सा वर्ज़न खोलें।",
        "फॉर्मेट समझने के लिए original।",
        "1xBet पर छोटी अपनी कैटेगरी जैसा।",
    ],
    "h2_mobile": "1xBet के ज़रिए मोबाइल प्ले",
    "img_mobile_alt": "1xBet मोबाइल ऐप पर Ice Fish",
    "mobile_paras": [
        "1xBet मोबाइल पर ठीक — ऐप या ब्राउज़र।",
        "छोटे सेशन, हल्का इंटरफ़ेस।",
        "स्टेक फ़ील्ड ध्यान से।",
        "ऑफिशियल ऐप; APK और predictor से बचें।",
    ],
    "h2_bonuses": "1xBet पर बोनस और प्रोमो",
    "img_bonus_alt": "1xBet कैसिनो बोनस सेक्शन",
    "bonus_paras": [
        "बोनस प्लेटफ़ॉर्म से, गेम से नहीं।",
        "कुछ केवल slots/स्पोर्ट; कुछ crash/instant बाहर।",
        "सक्रिय करने से पहले नियम पढ़ें।",
        "wagering और स्टेक लिमिट देखें।",
    ],
    "h2_safety": "1xBet पर सुरक्षा",
    "safety_paras": [
        "कॉपी साइटें असली जैसी लग सकती हैं।",
        "predictor ऐप से बचें।",
        "मनोरंजन, आय नहीं।",
    ],
    "h2_final": "अंतिम राय",
    "final_paras": [
        "1xBet तेज़ casino गेम के लिए मजबूत: सर्च, मोबाइल, कई Ice Fish टाइटल।",
        "Demo से शुरू करें, अपने लॉबी में जाँचें।",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["Ice Fish 1xBet पर?", "हाँ, InOut के साथ lobby में।"],
        ["कैसे ढूँढें?", "Casino → सर्च → Ice Fish।"],
        ["InOut सर्च?", "हाँ।"],
        ["लॉबी में नहीं?", "InOut आज़माएँ।"],
        ["Demo?", "हाँ।"],
        ["कैसे काम करता?", "छोटे फैसले, स्टेक, मल्टीप्लायर, Cash Out।"],
        ["crash पर बोनस?", "हमेशा नहीं।"],
        ["predictor सुरक्षित?", "नहीं।"],
        ["पहला वर्ज़न?", "original Ice Fish।"],
        ["ऐप में अलग?", "थोड़ा — स्क्रीन कॉम्पैक्ट।"],
    ],
}

BN = {
    "h1": "1xBet - Ice Fish",
    "h2_intro": "1xBet-এ Ice Fish — খেলোয়াড়রা কী খোঁজে",
    "img_hero_alt": "1xBet ক্যাসিনো লবিতে Ice Fish টাইটল",
    "intro_paras": [
        "খেলোয়াড়রা 1xBet-এ Ice Fish খোঁজে কারণ এটি সেই দ্রুত casino গেমগুলোর একটি যার কথা সর্বত্র। নিয়ম সহজ: মুরগি এগিয়ে, মাল্টিপ্লায়ার বাড়ে, রাউন্ড ভাঙার আগে বের হতে হয়।",
        "এটাই আকর্ষণ। দীর্ঘ slot setup নয়। গেম খুললেই চাপ বোঝা যায়।",
        "Ice Fish 1xBet-এ অনেকের পছন্দের ধরনের গেম — দ্রুত লঞ্চ, ছোট রাউন্ড, Cash Out।",
        "উপলব্ধতা অঞ্চল ও লবির উপর নির্ভর করতে পারে।",
        "প্রথম ধাপ: 1xBet casino সার্চ — Ice Fish বা InOut।",
    ],
    "h2_about": "1xBet সম্পর্কে",
    "img_about_alt": "1xBet স্পোর্টসবুক ও ক্যাসিনো হোমপেজ",
    "about_paras": [
        "1xBet একটি বড় বেটিং ও ক্যাসিনো প্ল্যাটফর্ম — সব এক অ্যাকাউন্টে।",
        "slots, live casino, crash, instant, eSports — পূর্ণ লবি।",
        "দ্রুত গেমের জন্য: casino, সার্চ, ক্যাটেগরি এক অ্যাকাউন্টে।",
        "Ice Fish মানায়: ছোট রাউন্ড, সহজ বাটন।",
    ],
    "h2_available": "1xBet-এ Ice Fish আছে?",
    "img_search_alt": "1xBet-এ Ice Fish সার্চ ফলাফল",
    "available_paras": [
        "হ্যাঁ, 1xBet-এ Ice Fish InOut Games লাইনের সঙ্গে — original ও Ice Fish 2।",
        "সবচেয়ে সহজ: সার্চ বার। Demo-ও আছে।",
    ],
    "short_path_title": "ছোট পথ:",
    "short_path_item": "Casino → Search → Ice Fish → Choose version → Demo or Play",
    "h2_lobby": "1xBet লবিতে Ice Fish যাচাই",
    "img_filter_alt": "1xBet-এ InOut ফিল্টার ও সার্চ",
    "lobby_paras": [
        "সবচেয়ে পরিষ্কার: লবি সার্চ। Ice Fish বা InOut।",
        "না থাকলে Slots, Crash Games, Instant Games দেখুন।",
    ],
    "quick_check_title": "দ্রুত যাচাই:",
    "quick_check_item": "Casino → Search → Ice Fish or InOut → choose the version → open demo or real play",
    "lobby_outro": ["পুরো লবি স্ক্রল করবেন না — সার্চ দ্রুত।"],
    "h2_play": "1xBet-এ Ice Fish গেম কীভাবে কাজ করে",
    "img_play_alt": "1xBet-এ মাল্টিপ্লায়ার ও Cash Out সহ Ice Fish গেমপ্লে",
    "play_paras": [
        "1xBet-এ একটিমাত্র টাইটল নয়: original, 2.0, Bonus, Gold, Vegas, Race।",
        "সহজ বেট দিয়ে শুরু, তারপর ঝুঁকি বেছে নিন।",
        "একই সিদ্ধান্তের লুপ।",
        "ছোট повтор সিদ্ধান্ত থেকে চাপ।",
        "Cash Out সবচেয়ে গুরুত্বপূর্ণ বাটন।",
    ],
    "h2_why": "কেন Ice Fish 1xBet লবিতে মানায়",
    "img_versions_alt": "1xBet লবিতে বিভিন্ন Ice Fish সংস্করণ",
    "why_paras": [
        "1xBet-এ slots, crash, instant, live আছে — Ice Fish স্বাভাবিকভাবে মানায়।",
        "লবিতে অনেক সম্পর্কিত সংস্করণ।",
        "প্রশ্ন: প্রথমে কোনটি খুলবেন।",
        "ফরম্যাট বোঝার জন্য original।",
        "1xBet-এ ছোট নিজস্ব ক্যাটেগরির মতো।",
    ],
    "h2_mobile": "1xBet দিয়ে মোবাইল প্লে",
    "img_mobile_alt": "1xBet মোবাইল অ্যাপে Ice Fish",
    "mobile_paras": [
        "1xBet মোবাইলে ভালো — অ্যাপ বা ব্রাউজার।",
        "ছোট সেশন, হালকা ইন্টারফেস।",
        "বেট ফিল্ড সতর্ক।",
        "অফিসিয়াল অ্যাপ; APK ও predictor এড়ান।",
    ],
    "h2_bonuses": "1xBet-এ বোনাস ও প্রোমো",
    "img_bonus_alt": "1xBet ক্যাসিনো বোনাস সেকশন",
    "bonus_paras": [
        "বোনাস প্ল্যাটফর্ম থেকে, গেম থেকে নয়।",
        "কিছু শুধু slots/স্পোর্ট; কিছু crash/instant বাদ।",
        "সক্রিয় করার আগে শর্ত পড়ুন।",
        "wagering ও বেট লিমিট দেখুন।",
    ],
    "h2_safety": "1xBet-এ নিরাপত্তা",
    "safety_paras": [
        "কপি সাইট আসলের মতো দেখতে পারে।",
        "predictor এড়ান।",
        "বিনোদন, আয় নয়।",
    ],
    "h2_final": "চূড়ান্ত মতামত",
    "final_paras": [
        "1xBet দ্রুত casino গেমের জন্য শক্তিশালী: সার্চ, মোবাইল, একাধিক Ice Fish।",
        "Demo দিয়ে শুরু করুন, নিজের লবিতে যাচাই করুন।",
    ],
    "h2_faq": "FAQ",
    "faq": [
        ["1xBet-এ Ice Fish?", "হ্যাঁ, InOut-এর সঙ্গে lobby-তে।"],
        ["কীভাবে খুঁজব?", "Casino → সার্চ → Ice Fish।"],
        ["InOut সার্চ?", "হ্যাঁ।"],
        ["লবিতে নেই?", "InOut চেষ্টা করুন।"],
        ["Demo?", "হ্যাঁ।"],
        ["কীভাবে কাজ করে?", "ছোট সিদ্ধান্ত, বেট, মাল্টিপ্লায়ার, Cash Out।"],
        ["crash-এ বোনাস?", "সবসময় নয়।"],
        ["predictor নিরাপদ?", "না।"],
        ["প্রথম সংস্করণ?", "original Ice Fish।"],
        ["অ্যাপে আলাদা?", "সামান্য — কমপ্যাক্ট স্ক্রিন।"],
    ],
}

EXPORT = {"vi": VI, "hi": HI, "bn": BN}
