#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate pages_1.json and pages_4.json sw/ln editorial clusters."""

from __future__ import annotations

import json
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "pages_sw_ln_data"
SEG_ROOT = Path.home() / "Downloads/02/aviator-pages"

P1_SW = [
    "Mchezo wa Aviator: jinsi unavyofanya kazi, wapi kucheza, na kwa nini demo ni muhimu",
    "Jinsi Mchezo wa Aviator Unavyofanya Kazi",
    "Return to Player (RTP) na Kuhusu Spribe",
    "Kuweka Dau kwenye Aviator kwa Hatua Tatu",
    "1. DAU",
    "2. ANGALIA",
    "3. CASH OUT",
    "Jinsi ya Kuanza Kucheza Aviator",
    "Vipengele vya Mchezo wa Aviator",
    "Vidokezo vya Aviator na Uchezaji Wenye Uwajibikaji",
    "Maelezo ya mchezo wa Aviator",
    "Ninaweza kucheza Aviator wapi?",
    "Jinsi ya kuchagua kasino kwa Aviator",
    "Aviator demo dhidi ya pesa halisi",
    "Maswali yanayoulizwa mara kwa mara",
    "Wachezaji kwa kawaida hugundua nini kwenye Aviator",
    "Multiplier ya Aviator inapanda wakati wa raundi ya moja kwa moja",
    "Weka dau lako kabla raundi ya Aviator haijaanza",
    "Angalia multiplier ya Aviator ikikua wakati wa raundi",
    "Fanya Cash Out kabla ndege ya Aviator kutoweka",
    "Kufungua Aviator kwenye kasino na kuanza kikao",
    "Hisia ya mchezaji kuhusu kasi ya mchezo wa Aviator",
    "Hisia ya mchezaji kuhusu zana za haki za Aviator",
    "Hisia ya mchezaji kuhusu kutumia Aviator kwenye simu",
    "Hisia ya mchezaji kuhusu kuanza na demo ya Aviator",
    "Ndege inachomoza. Nambari inaanza kupanda. Mahali kati ya 1.00x na wakati unapoondoka, ama unafanya Cash Out au unapoteza dau. Hiyo ndiyo mchezo mzima. Mshangao kwa wachezaji wengi wapya si sheria, ni kasi. Raundi ni fupi, dirisha la uamuzi linaonekana fupi zaidi, na ndio maana watu wengi hufungua demo kabla ya kufikiria kucheza kwa pesa halisi.",
    "Ukweli wa msingi: Aviator ilitolewa na Spribe mwaka 2019. Data ya sasa ya ukurasa inaonyesha RTP ya 97%, na dau kutoka USD 0.10 hadi USD 100.",
    "Dau mbili: Nafasi mbili zinaweza kukimbia pamoja katika raundi moja, hivyo wachezaji mara nyingi hutumia moja kama kutoka mapema na kuacha nyingine wazi kwa muda mrefu.",
    "Mantiki ya Provably Fair: Huwezi kutabiri matokeo, lakini jinsi yanavyotolewa ni wazi kwa uthibitisho kupitia mfumo wa seed unaonyeshwa ndani ya mchezo.",
    "Hali ya moja kwa moja: Gumzo, ushindi unaonekana, na mzunguko wa haraka huipa Aviator hisia ya kijamii zaidi kuliko kikao cha kawaida cha slot.",
    "Raundi huanza karibu 1.00x. Multiplier inapanda. Kwa hatua fulani ya nasibu, ndege hutoweka. Fanya Cash Out kabla ya wakati huo na multiplier kwenye skrini inakuwa malipo yako. Kaa ndani kwa muda mrefu sana na dau linaenda. Kwenye karatasi ni sheria ya sentensi moja. Wakati halisi, sehemu inayowagonga watu ni timing.",
    "Raundi inaisha wakati mantiki ya matokeo ya mchezo inapoamua, ambayo inamaanisha hakuna njia ya kuaminika ya kukisia pointi ya crash mapema.",
    "Baadhi ya wachezaji wanapendelea kutoka mapema na ushindi mdogo; wengine husubiri zaidi na wanakubali kwamba raundi nyingi zitaisha kabla ya kufika huko.",
    "Uthibitisho wa seed uko pale ikiwa haki ni muhimu kwako, lakini haufanyi raundi inayofuata iweze kusomeka.",
    "Ukiwa mpya, raundi chache zilizotazamwa upande na jaribio fupi la demo kwa kawaida hutosha kuzoea mwendo.",
    "Data ya ukurasa inaonyesha RTP ya 97% na Spribe kama mtoa huduma. Ni vizuri kujua, lakini uamuzi halisi wa mchezaji mara chache ni kuhusu nambari ya RTP. Ni kuhusu unayefungua naye mchezo. Aviator ni mchezo ule ule kwenye tovuti zote; mtoa huduma unaouzunguka ndiyo anayobadilika.",
    "Matokeo ya utafutaji hufanya hili kuchanganyikiwa kwa makusudi. Hakuna tovuti ya «rasmi ya Aviator» ya pesa halisi kwa kila mtu. Mchezo unawafikia wachezaji kupitia kasino na vitabu vya michezo vinavyofanya kazi na Spribe. Kwa hivyo swali lenye thamani ni rahisi: ni tovuti gani yenye leseni ina Aviator, inaunga mkono malipo yako, na inakuacha uijaribu kabla ya kuamua chochote?",
    "Mtiririko ni mfupi: weka dau, angalia multiplier, kisha uamue lini kuondoka kwenye raundi.",
    "Chagua dau moja au mbili kabla hesabu ya nyuma haijaisha na uweke kiasi ndani ya kikomo ulichoweka kwa kikao.",
    "Fuata multiplier ya moja kwa moja na uamue kama raundi inafaa kutoka mapema au uko tayari kukaa ndani kwa muda mrefu.",
    "Chukua multiplier kabla ndege kuondoka. Ukikosa wakati huo, nafasi hiyo imekwisha.",
    "Ukitaka kuhamia kutoka udadisi hadi kucheza kweli, njia salama zaidi ni wazi: jaribu demo kwanza, kisha linganisha waendeshaji wenye leseni kabla ya kuweka chochote.",
    "Chagua kasino au tovuti ya kamari iliyodhibitiwa ambayo kweli ina Aviator kutoka Spribe.",
    "Fungua demo kwanza ikiwa inapatikana na uitumie kujifunza mpangilio, kasi, na timing ya Cash Out bila shinikizo.",
    "Ukihamia kwenye mchezo halisi, jaza akaunti kwa njia ya malipo unayoamini na uamue kikomo cha kikao kabla ya dau la kwanza.",
    "Weka akilini uondoaji, uthibitisho, na ubora wa msaada, kwa sababu mtoa huduma anaweza kuunda uzoefu mzima kama vile mchezo.",
    "Vipengele vya nguvu zaidi vya Aviator ni vya vitendo: raundi fupi, zana za haki zinazoonekana, na njia kadhaa za kudhibiti jinsi unavyotoka.",
    "Dau mbili hai: Inafaa ikiwa unataka kutoka salama moja na nafasi ya ujasiri zaidi ndani ya raundi ile ile.",
    "Auto cash-out na autoplay: Inasaidia wachezaji wanaopendelea sheria thabiti badala ya kubuni kila sekunde chache.",
    "Gumzo na mlisho wa moja kwa moja: Hizi hufanya chumba lihisi hai, ingawa pia zinaweza kuwatawanya wachezaji wanaotamani kufuatilia multipliers.",
    "Aviator inaonekana rahisi juu ya uso, ndio maana nidhamu ya benki ina umuhimu. Raundi za haraka zinaweza kufanya jaribio moja la ziada lionekane lisilo na madhara hata wakati kikao tayari kinaenda vibaya.",
    "Weka hatua ya kusimama kabla ya kuanza: Amua hasara gani inahisi inakubalika na faida gani tayari ingekutosha kwa kikao hicho.",
    "Tumia demo kujifunza mwendo, si kuthibitisha mfumo: Demo ni muhimu kwa kasi na mpangilio, si kugundua muundo unaohakikishwa.",
    "Puuzia vitabiri na hacks: Chochote kinachodai kutabiri ndege au kushinda mantiki ya matokeo kinapaswa kuchukuliwa kama ulaghai, si faida.",
    "Chukua mtoa huduma kwa uzito: Zana za haki ndani ya mchezo hazibadilishi haja ya tovuti yenye leseni, masharti wazi ya uondoaji, na msaada wa kuaminika.",
    "USD 0.10",
    "Iliotolewa",
    "Mifumo",
    "Desktop, iOS, Android",
    "Mtoa huduma",
    "Unaweza kufikia Aviator kupitia waendeshaji wanaobeba mchezo wa Spribe, si kupitia ukurasa mmoja wa pesa halisi. Hii inafanya iwe na manufaa zaidi kulinganisha kasino zinazopatikana kuliko kufuatilia kurasa zinazofanana na «rasmi» kwenye matokeo ya utafutaji. Angalia ukurasa wetu wa kasino kwa waendeshaji wanaotoa mchezo.",
    "Leseni na sifa: Pendelea waendeshaji waliodhibitiwa vizuri na rahisi kuthibitisha.",
    "Malipo na uondoaji: Angalia njia za amana, kasi ya uondoaji, na kama masharti ni wazi kabla ya kujiandikisha.",
    "Ufikiaji wa demo: Tovuti inayokuacha ujaribu Aviator kwanza mara nyingi ni muhimu zaidi kuliko ile inayokusukuma moja kwa moja kuweka amana.",
    "Matumizi ya simu: Kwa sababu raundi ni za haraka, kuchelewa, vitufe visivyorahisisha, au mpangilio uliojaa vitu ni muhimu zaidi kuliko wachezaji wengi wanavyotarajia mwanzoni.",
    "Demo ndipo unapojifunza kiolesura, kasi ya raundi, na tabia zako za Cash Out bila shinikizo la kifedha. Mchezo wa pesa halisi unatumia mchezo ule ule wa msingi, lakini unahisi tofauti mara tu kila kutoka kukosa kugusa salio lako. Ukiwa mpya kwenye Aviator, demo ndiyo mahali pa busara zaidi pa kuanza.",
    "Je, Aviator ni mchezo halisi kutoka Spribe? Ndiyo. Aviator ni crash game halisi kutoka Spribe, lakini wachezaji kwa kawaida huufikia kupitia waendeshaji washirika badala ya tovuti moja ya kamari.",
    "Je, ninaweza kucheza Aviator bure? Ndiyo. Waendeshaji wengi hutoa hali ya demo na salio la kawaida, na hiyo kwa kawaida ndiyo mahali sahihi pa kuanza ukiwa bado unajifunza mchezo.",
    "Je, kuna tovuti rasmi ya Aviator kwa mchezo wa pesa halisi? Si kwa njia rahisi ambayo matokeo mengi ya utafutaji yanaonyesha. Wachezaji wengi hufikia Aviator kupitia washirika wa kasino au vitabu vya michezo wenye leseni.",
    "Je, ninaweza kutabiri ndege itaondoka lini? Hapana. Unaweza kujifunza mwendo na kuthibitisha haki, lakini hakuna kitabiri cha kuaminika kinachokuambia lini ufanye Cash Out.",
    "Je, Aviator inapatikana kwenye simu? Ndiyo. Aviator huchezwa sana kwenye vivinjari vya simu, na kwa watumiaji wengi hiyo ndiyo njia rahisi zaidi ya kuifikia.",
    "Wachezaji wengi wa mara ya kwanza hugundua kitu kimoja mara moja: sheria ni rahisi, lakini shinikizo linaonekana haraka kuliko walivyotarajia.",
    "Wachezaji wanaojali haki kwa kawaida huangalia zaidi ya uhuishaji wa ndege na kuzingatia zaidi ukaguzi wa Provably Fair na mtoa huduma nyuma yake.",
    "Kwa kuwa watu wengi huchezwa kwenye simu, mpangilio na nafasi ya vitufe ni muhimu hapa zaidi kuliko katika michezo ya kasino ya polepole.",
    "Wachezaji wengi huhisi vizuri zaidi baada ya kujaribu demo kwanza na kisha kuamua tu kama mchezo halisi unawafaa.",
]

P1_LN = [
    "Aviator : ndenge ya kosala, esika ya kobeta mpe mpo nini démo ezali important",
    "Ndenge lisano Aviator esalaka",
    "Retour au joueur (RTP) mpe na tina na Spribe",
    "Kobeta na Aviator na mitano misato",
    "1. MISE",
    "2. KOLANDA",
    "3. CASH OUT",
    "Ndenge ya kobanda kobeta Aviator",
    "Ba fonctionnalité ya lisano Aviator",
    "Ba conseil Aviator mpe kobeta na responsabilité",
    "Ba caractéristique ya lisano Aviator",
    "Nakoki kobeta Aviator wapi ?",
    "Ndenge ya kopona casino mpo na Aviator",
    "Démo Aviator vs mbongo ya solo",
    "Ba question oyo batunaka mingi",
    "Oyo ba joueur remarquent mingi na Aviator",
    "Aviator game multiplier climbing during a live round",
    "Set your stake before an Aviator round starts",
    "Watch the Aviator multiplier rise during the round",
    "Cash out before the Aviator plane disappears",
    "Opening Aviator at a casino and starting a session",
    "Player impression about Aviator game speed",
    "Player impression about Aviator fairness tools",
    "Player impression about using Aviator on mobile",
    "Player impression about starting with Aviator demo",
    "Ekipi ebandi kopumbwa. Motá ebandi kokita. Na kati ya 1.00x mpe tango epumbwaka, ozali kosala cash out to olembi mise. Yango nde lisano mobimba. Oyo esilisaka ba joueur ya sika, ezali mibeko te, ezali tempo. Ba manche ezali mokuse, esika ya décision ezali lokola mokuse mingi, mpe yango nde ntina mingi bato babongisi démo liboso ya kokanisa kobeta na mbongo ya solo.",
    "L’essentiel : Aviator ebandi na Spribe na 2019. Ba donnée ya page ya lelo emonisi RTP ya 97%, na ba mise kobanda na USD 0.10 tii na USD 100.",
    "Double mise : Positions mibale ekoki kosala elongo na manche moko ; ba joueur mingi basalaka moko lokola sortie ya mbangu mpe batikaka ya mibale koleka ntango.",
    "Logique Provably Fair : Okoki te koyebisa resultat, kasi ndenge ezali produite ekoki kotalama na système ya seeds oyo emonisami na lisano.",
    "Ambiance live : Chat, ba gain oyo emonisami mpe ba rotation ya mbangu epesaka Aviator ndenge ya sociali oyo session ya slot ya classique ezali na yango te.",
    "Manche moko ebandi pene na 1.00x. Multiplicateur ekomi. Na moment ya hasard, ekipi epumbwaka. Soki osala cash out liboso, multiplicateur oyo emonisami ezali gain na yo. Soki ozali kozela mingi, mise elembi. Na papier, mibeko ezali na phrase moko. Na lisano, timing nde ebebisaka bato mingi.",
    "Manche esukaka tango logique ya resultat ya lisano esengi : ezali na ndenge ya kotya confiance te ya kokanisa point ya crash liboso.",
    "Ba joueur mosusu balingaka ba sortie mokuse mpe ba gain moke ; basusu bazela mingi mpe bakokani ete ba manche mingi ekosukaka liboso ete bato basala.",
    "Vérification ya seeds ezali soki équité ezali important mpo na yo, kasi esalaka te manche elandi ezala ya polele.",
    "Soki ozali kobanda, ba manche moke oyo otalaki mpe test ya démo ya mokuse ekoki kopesa yo tempo.",
    "Ba donnée ya page emonisaka RTP ya 97% mpe Spribe lokola fournisseur. Malamu koyeba, kasi décision ya solo ya joueur ezali moke mpenza na chiffre ya RTP. Ezali plutôt na ndako oyo ofungolaka lisano. Aviator ezali lisano moko na ba site nionso ; opérateur oyo ezali zungu na yango nde ebongwanaka.",
    "Ba résultat ya recherche ebongisaka biloko na ntina. Ezali na « site officiel Aviator » ya mbongo ya solo mpo na bato nionso te. Lisano ekomi na ba joueur na ba casino mpe bookmaker partenaire ya Spribe. Question ya kolobela ezali simple : site oyo ezali na licence, oyo epesaka Aviator, oyo endimaka ba paiement na yo mpe oyo etikaka yo komeka liboso ya kokanga yo ?",
    "Principe ezali simple : kotia mise, kolanda multiplicateur mpe koyebisa tango ya kobatela resultat.",
    "Pona mise moko to mibale liboso ya fin ya compte à rebours mpe talá ete montant ezali na budget ya session na yo.",
    "Landá multiplicateur na direct mpe yebisa soki manche esengeli sortie ya mbangu to soki ozali na confiance kozela mingi.",
    "Zua multiplicateur liboso ete ekipi epumbwaka. Soki ofi moment wana, position wana elembi.",
    "Soki olingi kobanda na curiosité tii na jeu réel, nzela ya malamu ezali simple : meka démo liboso, sima comparer ba opérateur oyo ezali na licence liboso ya kotia eloko moko.",
    "Pona casino to site ya pari oyo ezali régulé mpe oyo epesaka Aviator ya Spribe.",
    "Fungola démo liboso soki ezali mpe basalela yango mpo na koyeba interface, tempo mpe moment ya cash out.",
    "Soki obongisi na jeu réel, tia mbongo na compte na moyen ya paiement oyo ozali na confiance mpe botia limite ya session liboso ya mise ya liboso.",
    "Kanisa mpe ba retrait, vérification mpe qualité ya support, mpo opérateur ekoki kobongisa expérience mobimba lokola lisano.",
    "Ba atout ya malamu ya Aviator ezali ya solo : ba manche mokuse, ba outil ya transparence oyo emonisami mpe ba ndenge mingi ya kozala na contrôle ya sortie na yo.",
    "Deux mises actives :Pratique soki olingi sortie ya sécurité mpe position ya aggressif mingi na tour moko.",
    "Encaissement automatique et lecture auto :Pratique mpo na ba joueur oyo balingaka ba règle fixes na kobimisa ba seconde nionso.",
    "Chat et fil en direct :Ces éléments esalisaka salle vivante, ata soki ekoki pe kotela ba joueur oyo bandelaki kolanda ba multiplicateur.",
    "Aviator ezali lokola simple na liboso, mpe yango wana discipline ya bankroll ezali important. Ba manche ya mbangu ekoki kosala ete tentative moko ya lisusu ezala lokola eloko ya moke ata soki session esili kozala mabe.",
    "Botia limite liboso ya kobanda :Yebisa perte oyo okoki kondima mpe gain oyo ekosala déjà mpo na session oyo.",
    "Basalela démo mpo na timing, mpe te mpo na kopesa preuve ya méthode :Démo esalisaka koyeba interface mpe tempo, mpe te kozua schéma garanti.",
    "Boya ba « predictors » mpe ba hacks :Nyonso oyo elobi koyebisa départ ya ekipi to kobunda logique ya resultat ezali arnaque, mpe te avantage.",
    "Benda opérateur na sérieux :Ba outil ya équité na lisano ebandi site na licence, ba règle ya retrait ya polele mpe support ya confiance te.",
    "Caractéristique",
    "Mise min.",
    "USD 0.10",
    "Mise max.",
    "Plateformes",
    "Ordinateur, iOS, Android",
    "Fournisseur",
    "Ozali kofikisa Aviator na ba opérateur oyo epesaka lisano ya Spribe, mpe te na page moko ya mbongo ya solo. Ezali malamu mingi kokokanisa ba casino oyo ezali pene na koluka ba page « officielles » na ba résultat ya recherche. Talá page na biso ya casinos mpo na ba opérateur oyo epesaka lisano.",
    "Licence et réputation :Privilégiez des opérateurs correctement régulés et faciles à vérifier.",
    "Paiements et retraits :Vérifiez les méthodes de dépôt, la vitesse des retraits et la clarté des conditions avant de vous inscrire.",
    "Accès à la démo :Un site qui permet de tester Aviator d'abord est souvent plus utile qu'un site qui pousse directement au dépôt.",
    "Confort mobile :Comme les manches sont rapides, le lag, des boutons maladroits ou une interface surchargée posent plus de problèmes que beaucoup de joueurs ne l'imaginent au début.",
    "Démo ezali esika oyo oyekaka interface, vitesse ya ba manche mpe ba habitude na yo ya cash out sans pression financière. Jeu na mbongo ya solo ezali lisano moko, kasi ezali différent soki sortie oyo ofi ekotya solde na yo. Soki obandi na Aviator, démo ezali liboso ya malamu.",
    "Aviator est-il un vrai jeu de Spribe ?Oui. Aviator ezali vrai crash game ya Spribe, kasi bato bakofikisa yango mingi na ba opérateur partenaire na site ya pari central moko te.",
    "Puis-je jouer à Aviator gratuitement ?Oui. Ba opérateur mingi epesaka mode démo na solde virtuel, mpe yango nde esika malamu soki ozali naba koyekola lisano.",
    "Existe-t-il un site officiel Aviator pour jouer en argent réel ?Pas de la manière simple que laissent entendre beaucoup de résultats de recherche. Na pratique, ba joueur bakofikisa Aviator na ba partenaires casino to paris sportifs oyo ezali na licence.",
    "Puis-je prévoir quand l'avion va partir ?Non. Okoki koyekola tempo mpe kotya équité, kasi ezali na indicateur ya confiance te oyo ekobisa yo tango ya cash out.",
    "Aviator est-il disponible sur mobile ?Oui. Aviator esalelami mingi na navigateur mobile mpe, mpo na ba joueur mingi, yango nde nzela ya pete.",
    "Ba joueur ya sika remarquent mbala moko eloko moko : ba règle ezali simple, kasi pression ekomi nokinoki koleka ndenge basalaki kanisa.",
    "Ba joueur oyo balingi équité batalaka mingi vérification Provably Fair mpe opérateur oyo ezali na nsima.",
    "Mpo bato mingi babetaka na mobile, disposition ya écran mpe espacement ya ba bouton ezali important awa koleka na ba jeux ya casino ya polele.",
    "Ba joueur mingi bazali na confiance mingi sima ya komeka démo liboso mpe bakamaka kaka sima soki jeu réel esili kopasana na bango.",
]

P4_SW = [
    "Aviator demo — cheza bila usajili au amana",
    "Hali ya demo inamaanisha nini",
    "Je, unahitaji usajili?",
    "Jinsi demo inavyotofautiana na mchezo halisi",
    "Kwa nini Aviator huwavutia wachezaji haraka",
    "Jinsi ya kufungua demo ya Aviator kwenye simu",
    "Makosa ya kawaida ya kufungua demo",
    "Jinsi ya kutambua tovuti bandia ya demo",
    "RTP na sheria za Aviator: kinachohitaji kuwa muhimu",
    "Kamari yenye uwajibikaji: cheza kwa ufahamu",
    "FAQ",
    "Hitimisho",
    "Skrini ya kukaribisha demo ya Aviator na salio la kawaida na vidhibiti",
    "Multiplier ya demo ya Aviator inapanda wakati wa raundi",
    "Cash Out uliofanikiwa katika demo ya Aviator",
    "Mfano wa multiplier ya juu katika Aviator",
    "Paneli ya My Bets katika demo ya Aviator",
    "Paneli ya dau za Aviator",
    "Gumzo la Aviator karibu na mchezo",
    "Mlisho wa ushindi wa Aviator",
    "Demo ya Aviator kwenye simu, kibao, na desktop",
    "Demo ya Aviator na salio la mazoezi",
    "Demo ya Aviator ni hali ambapo unaweza kuangalia ndani ya mchezo bila usajili, amana, au hatari kwa pesa yako. Unapata salio la kawaida, unaweka dau za mazoezi, unaangalia multiplier, na unajaribu kufanya Cash Out kabla ndege kuondoka.",
    "Aviator ni miongoni mwa michezo ya crash: raundi ni fupi, matokeo yanaonekana karibu mara moja, na uamuzi mkuu daima ni ule ule — chukua sasa au subiri kidogo zaidi. Ndio maana mchezo unaweza kuwavutia watu hata wakati mikopo kwenye skrini ni ya kubuni tu.",
    "Demo si njia ya kupata mkakati wa siri. Itumie kuelewa mechanics: kiolesura, dau mbili, auto bet, auto cash-out, na mchezo wa simu kabla hata ya kufikiria salio halisi.",
    "Demo ni toleo la bure la mchezo ambapo mikopo ya kawaida inachukua nafasi ya pesa halisi. Unachagua dau, unaangalia multiplier ikikua, na unaamua lini kuchukua ushindi wa mazoezi. Ukikosa ndege, dau la demo tu ndilo linalotoweka.",
    "Hali ya demo ni muhimu ikiwa unataka:",
    "kujifunza sheria za Aviator bila kuhatarisha pesa;",
    "kujaribu kiolesura na vitufe mwenyewe;",
    "kuelewa jinsi Cash Out inavyofanya kazi;",
    "kujifunza auto bet na auto cash-out;",
    "kujaribu dau mbili kwa wakati mmoja;",
    "kuangalia kama mchezo wa simu unahisi raha;",
    "kuona kwa nini michezo ya crash inakuwa ya kuvutia haraka.",
    "Toleo la demo halihakikishii mafanikio katika mchezo halisi. Linaonyesha mechanics na linakusaidia kuelewa mtiririko, lakini halikupi njia ya kushinda mfumo. Tofauti kuu na mchezo wa pesa ni kutokuwepo kwa hatari ya kifedha halisi.",
    "Aviator ni mchezo wa kamari. Hali ya pesa halisi daima ina hatari ya kifedha. Cheza tu ikiwa una miaka 18 au zaidi na kwa pesa unayoweza kumudu kupoteza.",
    "Kwa kawaida, demo ya Aviator haihitaji usajili. Ukichagua kwenda kwa mtoa huduma wa kasino na kucheza kwa pesa halisi, ndipo jukwaa linaweza kuomba akaunti, uthibitisho, na amana.",
    "Demo haipaswi kuomba:",
    "maelezo ya pasipoti;",
    "nambari ya kadi ya benki;",
    "msimbo wa CVV;",
    "nenosiri la huduma ya malipo;",
    "msimbo wa SMS;",
    "ufikiaji wa barua pepe au messengers;",
    "amana ya lazima;",
    "usakinishaji wa programu isiyojulikana.",
    "Ikiwa tovuti inaomba hivyo kabla ya kufungua demo, ichukulie kama ishara ya onyo. Toleo la bure limekusudiwa kujifunza mchezo, si kukusanya data ya kibinafsi au malipo.",
    "Demo ya Aviator inahisi karibu na mchezo wa kawaida: ndege ile ile, multiplier ule ule, vitufe vile vile vya Cash Out, na historia ile ile ya raundi. Lakini pesa halisi inapoingia, tabia ya mchezaji hubadilika: hofu ya hasara, hamu ya kujirejeshea, na kuongezeka kwa dau kwa hisia huwa sehemu ya kikao.",
    "Kigezo",
    "Aviator demo",
    "Mchezo halisi",
    "Kawaida, hakuna ongezeko",
    "Salio halisi la mchezo",
    "Dau za mazoezi",
    "Dau za pesa halisi",
    "Hatari ya kupoteza pesa",
    "Usajili",
    "Kwa kawaida haihitajiki",
    "Kwa kawaida inahitajika na mtoa huduma",
    "Uondoaji",
    "Haupatikani",
    "Inawezekana chini ya sheria za mtoa huduma",
    "Lengo kuu",
    "Kujifunza mechanics za mchezo",
    "Kucheza na matokeo ya kifedha",
    "Shinikizo la kihisia",
    "Chini kwa sababu hakuna pesa inayotumika",
    "Juu kwa sababu hasara ni halisi",
    "Dau mbili",
    "Unaweza kujaribu mechanic",
    "Unaweza kuitumia katika mchezo halisi",
    "Cash Out",
    "Inafanya kazi kwa mafunzo",
    "Inaathiri matokeo halisi",
    "Auto bet na auto cash-out",
    "Inaweza kujifunzwa bila hatari",
    "Inahitaji matumizi ya makini",
    "Aviator imeundwa kwa urahisi kwa makusudi: ndege inachomoza, coefficient inakua, ushindi unaowezekana unakua, na mchezaji anaamua lini kubonyeza Cash Out. Kadri unavyosubiri, ndivyo matokeo yanavyoweza kuwa juu, lakini pia ndivyo nafasi ya raundi kuisha kwanza inavyokua.",
    "Raundi za haraka, visuals rahisi, uhuishaji wazi wa ndege, sauti, jedwali la wachezaji wa moja kwa moja, ushindi unaonekana kutoka kwa wachezaji wengine, dau mbili kwa wakati mmoja, auto bet, na auto cash-out vyote huongeza mvuto huo.",
    "Unaweza kufungua demo ya Aviator moja kwa moja kwenye kivinjari cha simu. Programu tofauti haihitajiki: fungua ukurasa wa demo, gusa «Fungua demo», chagua dau la kawaida, liweke kabla raundi haijaanza, na fanya Cash Out kabla ndege kuondoka.",
    "Tumia kikao kujaribu auto bet, auto cash-out, na dau mbili. Ukihitaji njia ya kusakinisha, nenda kwenye sehemu ya download na uchague chaguo la simu kwa kifaa chako.",
    "Wakati mwingine demo ya Aviator inaweza kutofunguka au kukimbia kwa utulivu. Kawaida tatizo si mchezo wenyewe, bali kivinjari, muunganisho, au mipangilio ya kifaa.",
    "Aviator inagandaa kwenye simu: funga programu na vichupo vya ziada, zima hali ya kuokoa nishati, na sasisha kivinjari chako.",
    "Fremu inabaki tupu: angalia vizuizi vya matangazo, hali ya faragha, na mipangilio ya ulinzi wa iframe.",
    "Mchezo unachelewa: badilisha kwenye Wi-Fi thabiti au anzisha upya data ya simu.",
    "Demo inaomba data nyingi sana: usiweke kadi ya benki, CVV, misimbo ya SMS, au nenosiri za huduma za malipo.",
    "Tovuti bandia mara nyingi hutumia jina la Aviator, muundo unaofanana, rangi zinazojulikana, na ahadi za ushindi rahisi. Hali ya kawaida ya demo haiombi taarifa za siri na haiahidi matokeo yaliyohakikishwa.",
    "Tovuti ya shaka mara nyingi inatangaza «utabiri halisi,» «algorithm ya siri,» predictor, amana kufungua demo, APK isiyojulikana, nambari ya kadi, au msimbo wa SMS. Ukurasa wa taarifa wa kuaminika unasema wazi kwamba Aviator ni kamari na kwamba matokeo ya raundi hayawezi kutabiriwa.",
    "RTP ni kiwango cha nadharia cha kurudi kwa mchezaji kwa umbali mrefu. Si ahadi ya ushindi kwa mtu fulani, na haimaanishi kwamba kikao kimoja kifupi kitarudisha sehemu ya pesa yako.",
    "Katika hali ya demo, RTP na sheria husaidia kuelewa mechanics, lakini husaidii kutabiri raundi inayofuata. Historia ya multiplier inaweza kuwa ya kuvutia kutazama, lakini si utabiri wa kuaminika.",
    "Demo ya Aviator ni muundo wa kujaribu na kujifunza. Hata mchezo wa bure unaweza kuunda hamu ya kuhamia kwenye dau za pesa halisi, hivyo ni bora kutathmini hatari mapema.",
    "cheza tu ikiwa una miaka 18 au zaidi;",
    "weka mipaka ya muda na bajeti mapema;",
    "usicheze kwa pesa iliyokopwa au pesa ya mwisho;",
    "usifuate hasara;",
    "usiongeze dau kwa hisia;",
    "usichukulie mchezo kama kipato;",
    "jitenge ikiwa mchezo unaleta hisia hasi.",
    "Ukigundua dalili za uraibu, wasiliana na wataalamu au huduma za msaada wa kamari yenye uwajibikaji.",
    "Je, unaweza kucheza demo ya Aviator bure? Ndiyo. Demo hutumia salio la kawaida. Huhitaji amana au pesa halisi kuifungua.",
    "Je, unahitaji kujiandikisha kwa demo ya Aviator? Kwa kawaida hapana. Demo inaweza kufunguliwa bila akaunti. Ikiwa tovuti inahitaji usajili, angalia masharti na usiweke data isiyo ya lazima.",
    "Je, unaweza kutoa ushindi kutoka demo ya Aviator? Hapana. Demo hutumia fedha za mazoezi. Ushindi huo hauwezi kutolewa kwenye kadi, pochi, au akaunti ya mchezo.",
    "Je, toleo la demo linatofautiana na mchezo halisi? Mechanics ni sawa, lakini tofauti kuu ni kutokuwepo kwa dau na malipo halisi. Mchezo wa pesa halisi unaongeza hatari ya kifedha.",
    "Je, unaweza kucheza demo ya Aviator kwenye simu? Ndiyo. Demo kwa kawaida hufanya kazi kwenye kivinjari cha simu. Kusakinisha programu kwa kawaida si lazima.",
    "Je, unahitaji kupakua demo ya Aviator? Hapana. Ni salama zaidi kufungua demo mtandaoni kwenye kivinjari. Kupakua faili za APK zisizojulikana kunaweza kuwa hatari.",
    "Je, kuna mkakati unaofanya kazi kwa demo ya Aviator? Katika demo, unaweza kujaribu mbinu tofauti za dau na Cash Out. Lakini hakuna mkakati unaohakikisha matokeo katika mchezo halisi.",
    "Je, unaweza kutabiri multiplier ya Aviator? Hapana. Hakuna njia ya kuaminika ya kujua multiplier halisi ya raundi inayofuata mapema. Chukulia huduma zenye «ishara halisi» kwa ukaribu.",
    "Kwa nini Aviator inavutia sana? Kwa sababu mchezo unachanganya matokeo ya haraka, multiplier inayopanda, mechanics rahisi, matarajio ya kuona, na hisia ya udhibiti. Mchezaji daima anafanya uamuzi mfupi: chukua sasa au subiri zaidi.",
    "Je, hii ni tovuti rasmi ya Spribe? Hapana. Tovuti hii si tovuti rasmi ya Spribe na haawakilishi msanidi wa mchezo. Ukurasa umeundwa kama utambulisho wa taarifa wa demo ya Aviator.",
    "Demo ya Aviator ni njia rahisi ya kujifunza mchezo bure bila usajili au amana. Unaweza kujaribu dau, Cash Out, vipengele vya kiotomatiki, dau mbili kwa wakati mmoja, na mchezo wa simu bila kuhatarisha pesa yako.",
    "Tumia demo kama utambulisho. Usiweke data ya kibinafsi au malipo kwenye tovuti za shaka, usipakue faili zisizojulikana, na kumbuka: kamari ya pesa halisi daima ina hatari ya hasara ya kifedha.",
]

P4_LN = [
    "Aviator demo — kobeta sans inscription to pe dépôt",
    "Oyo mode démo elobaka",
    "Esengeli kokoma na site ?",
    "Ndenge démo ezali différente na jeu réel",
    "Mpo nini Aviator ebandi kobenda ba joueur nokinoki",
    "Ndenge ya kofungola Aviator demo na téléphone",
    "Ba erreur ya mbala na mbala na kofungola démo",
    "Ndenge ya koyeba site ya démo ya faux",
    "RTP mpe ba règle ya Aviator : oyo ezali important",
    "Jeu responsable : kobeta na conscience",
    "FAQ",
    "Na mokuse",
    "Écran d'accueil Aviator demo avec solde virtuel et commandes",
    "Multiplicateur Aviator demo en hausse pendant une manche",
    "Cash-out réussi dans la démo Aviator",
    "Exemple de multiplicateur élevé dans Aviator",
    "Panneau Mes mises dans Aviator demo",
    "Panneau des mises Aviator",
    "Chat Aviator à côté du jeu",
    "Fil des gains Aviator",
    "Aviator demo sur téléphone, tablette et ordinateur",
    "Aviator demo avec un solde d'entraînement",
    "Aviator demo ezali mode oyo epesaka yo kotala lisano na kati sans inscription, sans dépôt mpe sans riski mpo na mbongo na yo. Ozali na solde virtuel, otia ba mise ya formation, olanda multiplicateur mpe oeseyi cash out liboso ete ekipi epumbwaka.",
    "Aviator ezali na ba jeux crash : ba manche ezali mokuse, resultat emonisami nokinoki, mpe décision ya liboso ezali ntango nyonso moko — cash out sikoyo to zela moke.",
    "Démo esalaka te mpo na kozua stratégie ya secret. Basalela yango mpo na koyeba mécanique : interface, ba double mise, mise automatique, cash-out automatique mpe mobile liboso ya kokanisa solde ya solo.",
    "Demo ezali version ya ofele ya lisano, epai wapi ba crédit virtuel ebongisaka mbongo ya solo. Oponi mise, otala multiplicateur ekoma mpe oyebisa tango ya kozua gain ya formation. Soki ofi ekipi, kaka mise ya démo epumbwaka.",
    "Mode démo ezali malamu soki olingi :",
    "koyekola ba règle ya Aviator sans kotiya mbongo na riski ;",
    "komeka yo moko interface mpe ba bouton ;",
    "koyeba ndenge cash out esalaka ;",
    "koyekola mise automatique mpe cash-out automatique ;",
    "komeka ba mise mibale na tango moko ;",
    "kotya soki kobeta na mobile ezali confortable ;",
    "komona mpo nini ba jeux crash ebandi kozala captivants nokinoki.",
    "Version démo egaranti te succès na jeu réel. Emonisaka mécanique mpe esalisaka yo koyeba flow, kasi epesi yo ndenge te ya kobunda système. Différence ya solo na jeu na mbongo ezali absence ya riski financier ya solo.",
    "Aviator ezali jeu d'argent. Mode mbongo ya solo ezali ntango nyonso na riski financier. Beta kaka soki ozali na mbula 18 to koleka mpe na mbongo oyo okoki kolimwisa.",
    "Na ndenge ya général, Aviator demo esengeli inscription te. Soki opona kokende na opérateur ya casino mpe kobeta na mbongo ya solo, platforme ekoki kosenga compte, vérification mpe dépôt.",
    "Demo esengeli te :",
    "ba information ya passeport ;",
    "numéro ya carte bancaire ;",
    "code CVV ;",
    "mot de passe ya service ya paiement ;",
    "code SMS ;",
    "accès na email to messagerie ;",
    "dépôt obligatoire ;",
    "installation ya application oyo oyebi te.",
    "Soki site esengi yango liboso ya kofungola démo, benga yango lokola signal ya alerte. Version ya ofele ezali mpo na koyekola lisano, mpe te mpo na kokanga ba donnée ya solo to ya paiement.",
    "Aviator demo ezali pene na jeu ya habituel : ekipi moko, multiplicateur moko, ba bouton cash out moko mpe historique ya ba manche moko. Kasi tango mbongo ya solo ekoti, comportement ya joueur ebongwanaka : libota ya kozua, envie ya kozongisa mpe ba mise na émotion ekoki kobima.",
    "Aviator demo",
    "Jeu réel",
    "Virtuel, sans recharge",
    "Solde de jeu réel",
    "Mises d'entraînement",
    "Mises en argent réel",
    "Risque de perdre de l'argent",
    "Inscription",
    "Généralement non requise",
    "Généralement requise par l'opérateur",
    "Retraits",
    "Non disponibles",
    "Possibles selon les règles de l'opérateur",
    "Objectif principal",
    "Apprendre les mécaniques du jeu",
    "Jouer avec un résultat financier",
    "Pression émotionnelle",
    "Plus faible, car aucun argent n'est utilisé",
    "Plus forte, car les pertes sont réelles",
    "Deux mises",
    "Vous pouvez tester la mécanique",
    "Vous pouvez l'utiliser en jeu réel",
    "Cash out",
    "Fonctionne pour l'entraînement",
    "Influe sur le résultat réel",
    "Mise automatique et cash-out automatique",
    "Peuvent être étudiés sans risque",
    "Nécessitent une utilisation prudente",
    "Aviator ezali simple na ntina : ekipi epumbwaka, coefficient ekoma, gain possible ekomaka monene mpe joueur ayebisi tango ya cash out. Koleka ozela, resultat ekoki kozala monene, kasi riski ete manche esukaka liboso ekomaka monene.",
    "Ba manche ya mbangu, ba visuel simple, animation ya ekipi, son, tableau ya ba joueur na direct, ba gain ya bato mosusu, ba mise mibale na tango moko, mise automatique mpe cash-out automatique nyonso ebakisi attraction.",
    "Okoki kofungola Aviator demo na navigateur mobile. Application ya kobongola esengeli te : fungola page démo, fina « Ouvrir la démo », pona mise virtuelle, tia yango liboso ya manche mpe cash out liboso ete ekipi epumbwaka.",
    "Basalela session mpo na komeka mise automatique, cash-out automatique mpe ba mise mibale. Soki ozali na besoin ya installation, kende na section téléchargement mpe pona option mobile mpo na appareil na yo.",
    "Ntango mosusu Aviator demo ekofungola te to esalaka malamu te. Problème ebandi mingi na navigateur, connexion to paramètre ya appareil.",
    "Aviator eko bloquer na téléphone : funga ba application mpe onglet oyo esengeli te, boma mode économie d'énergie mpe metà navigateur na yo à jour.",
    "Cadre etikaka mpamba : talá ba bloqueur ya publicité, mode privé mpe ba paramètre ya protection contre ba iframe.",
    "Lisano esalaka malamu te : kende na Wi-Fi stable to restart ba données mobiles.",
    "Démo esengi ba donnée mingi : kotia carte bancaire, CVV, ba code SMS to mot de passe ya service ya paiement te.",
    "Ba site ya faux basalaka mingi nkombo Aviator, design ya ndenge moko, ba couleur oyo oyebi mpe ba promesse ya gain ya pete. Mode démo ya normal esengi ba information confidentielle te mpe epromise resultat garanti te.",
    "Site ya doutou ebandi mingi koloba « prédiction exacte », « algorithme secret », predictor, dépôt mpo na débloquer démo, APK oyo oyebi te, numéro ya carte to code SMS. Page ya information ya confiance elobaka polele ete Aviator ezali jeu d'argent mpe resultat ya manche ekoki koyebisama liboso te.",
    "RTP ezali taux théorique ya retour au joueur na distance molai. Ezali promesse ya gain mpo na moto moko te mpe elobaka te ete session mokuse ekozongisa yo part ya mbongo.",
    "Na mode démo, RTP mpe ba règle esalisaka koyeba mécanique, kasi esalisaka te koyebisa manche elandi. Historique ya multiplicateur ekoki kozala ya kotala, kasi ezali prévision ya confiance te.",
    "Aviator demo ezali format ya test mpe ya koyekola. Ata jeu ya ofele ekoki kopesa envie ya kokende na ba mise na mbongo ya solo, yango wana malamu kotya ba riski liboso.",
    "beta kaka soki ozali na mbula 18 to koleka ;",
    "botia ba limite ya temps mpe budget liboso ;",
    "kobeta te na mbongo ya kobola to ya suka ;",
    "kolanda ba perte te ;",
    "kobakisa ba mise na émotion te ;",
    "koyebisa jeu lokola revenu te ;",
    "tika soki jeu epesaka ba émotion négative.",
    "Soki omoni ba signe ya addiction, benga ba spécialiste to ba service ya aide au jeu responsable.",
    "Peut-on jouer gratuitement à Aviator demo ?Oui. Démo esalela solde virtuel. Ozali na dépôt to mbongo ya solo te mpo na kofungola yango.",
    "Faut-il s'inscrire pour Aviator demo ?Généralement non. Démo ekoki kofungola sans compte. Soki site esengi inscription, talá ba condition mpe kotia ba donnée oyo esengeli te te.",
    "Peut-on retirer les gains d'Aviator demo ?Non. Démo esalela ba fonds ya formation. Ba gain wana ekoki kobimisama na carte, portefeuille to compte ya jeu te.",
    "Version démo ezali différente na jeu réel ?Mécanique ezali pene, kasi différence ya liboso ezali absence ya ba mise mpe ba paiement ya solo. Jeu na mbongo ya solo ebakisi riski financier.",
    "Peut-on jouer à Aviator demo sur un téléphone ?Oui. Démo esalelami mingi na navigateur mobile. Installation ya application esengeli mingi te.",
    "Faut-il télécharger Aviator demo ?Non. Ezali malamu mingi kofungola démo na navigateur. Ko télécharger ba APK oyo oyebi te ekoki kozala danger.",
    "Existe-t-il une stratégie efficace pour Aviator demo ?Dans la démo, okoki komeka ba approche ya mise mpe cash out. Kasu stratégie moko egaranti resultat na jeu réel te.",
    "Peut-on prédire le multiplicateur Aviator ?Non. Ezali na ndenge ya confiance te ya koyeba multiplicateur exact ya manche elandi liboso. Banda ba service ya « signaux exacts » na prudence.",
    "Pourquoi Aviator est-il si captivant ?Parce que jeu ecombines resultat ya mbangu, multiplicateur oyo ekomi, mécanique simple, attente visuelle mpe sensation ya contrôle. Joueur azali ntango nyonso na décision mokuse : cash out sikoyo to zela lisusu.",
    "Est-ce le site officiel de Spribe ?Non. Site oyo ezali site officiel ya Spribe te mpe erepresente développeur ya jeu te. Page ezali présentation informative ya Aviator demo.",
    "Aviator demo ezali ndenge ya pete ya koyekola lisano ofele sans inscription to dépôt. Okoki komeka ba mise, cash out, ba fonction automatique, ba mise mibale na tango moko mpe mobile sans kotiya mbongo na yo na riski.",
    "Basalela démo lokola introduction. Kotia ba donnée ya solo to ya paiement na ba site ya doutou te, ko télécharger ba fichier oyo oyebi te te mpe kanisa : jeu na mbongo ya solo ezali ntango nyonso na riski ya perte financière.",
]


def build_page(entity_id: int, sw_targets: list[str], ln_targets: list[str], meta: dict) -> dict:
    en_path = SEG_ROOT / f"pages-{entity_id}-en-segments.json"
    fr_path = SEG_ROOT / f"pages-{entity_id}-fr-segments.json"
    en_segs = json.loads(en_path.read_text(encoding="utf-8"))
    fr_segs = json.loads(fr_path.read_text(encoding="utf-8"))
    if len(en_segs) != len(sw_targets):
        raise SystemExit(f"pages_{entity_id}: sw count {len(sw_targets)} != en {len(en_segs)}")
    if len(fr_segs) != len(ln_targets):
        raise SystemExit(f"pages_{entity_id}: ln count {len(ln_targets)} != fr {len(fr_segs)}")
    return {
        "ln_from_fr": True,
        "meta": meta,
        "pairs": {
            "sw": [[a, b] for a, b in zip(en_segs, sw_targets, strict=True)],
            "fr_ln": [[a, b] for a, b in zip(fr_segs, ln_targets, strict=True)],
        },
    }


META = {
    1: {
        "sw": {
            "name": "Nyumbani",
            "title": "Aviator Mtandaoni: Jinsi Inavyofanya Kazi, Demo na Pesa Halisi",
            "description": "Jifunze jinsi Aviator inavyofanya kazi, kwa nini demo ni muhimu, na jinsi ya kuchagua tovuti yenye leseni kwa pesa halisi bila kurudia kurasa bandia za «rasmi».",
        },
        "ln": {
            "name": "Liboso",
            "title": "Aviator na Internet: Ndenge, Démo mpe Mbongo ya Solo",
            "description": "Yebisa ndenge Aviator esalaka, mpo nini démo ezali important mpe ndenge ya kopona site na licence mpo na kobeta na mbongo ya solo.",
        },
    },
    4: {
        "sw": {
            "name": "Demo",
            "title": "Aviator Demo Bure | Bila Usajili au Amana",
            "description": "Cheza Aviator demo kwa mikopo ya kawaida, jaribu Cash Out, dau mbili, vipengele vya auto na kufungua kwenye simu kabla ya kuhatarisha pesa halisi.",
        },
        "ln": {
            "name": "Démo",
            "title": "Aviator Demo ya Ofele | Sans Inscription to Dépôt",
            "description": "Betta Aviator demo na crédit virtuel, teste cash out, ba mise mibale, auto mpe mobile liboso ya kotiya mbongo ya solo na riski.",
        },
    },
}


def main() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    pages = {
        1: (P1_SW, P1_LN),
        4: (P4_SW, P4_LN),
    }
    for eid, (sw, ln) in pages.items():
        out = DATA_DIR / f"pages_{eid}.json"
        payload = build_page(eid, sw, ln, META[eid])
        out.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        print(f"Wrote {out} sw={len(sw)} fr_ln={len(ln)}")
        for lang in ("sw", "ln"):
            m = META[eid][lang]
            print(f"  {lang} title={len(m['title'])} desc={len(m['description'])}")


if __name__ == "__main__":
    main()
